### ISSUE TITLE
New build-dependency xxd

### ISSUE THREAD

**Issue by stefanhusmann** [BestImageViewer/geeqie#1002]
After the switch from autotools to meson a new build-dependency was introduced: xxd. Is this really needed? Under Arch Linux, xdd comes with the vim packages, And I would like to avoid to install vim just to compile geeqie.

**Comment by eli-schwartz** [comment]
https://github.com/BestImageViewer/geeqie/blob/e68b6b1bf98f6d03a88f05326e02c060364f5768/src/meson.build#L259-L265

This looks odd. I'd normally expect a built file to be a custom_target, not a run_command, because you'd want this to be generated at build time rather than configure time.

As far as xxd goes, this was always kinda-sorta needed, the Makefile had a rule to run xxd but the dist already had that pre-built so it might not actually run.

**Comment by caclark** [comment]
xxd has been a dependency since geeqie v1.0 (but see another message in this list).
Arch has a package xxd-standalone - does this provide xxd without vim?

**Comment by caclark** [comment]
> This looks odd. I'd normally expect a built file to be a custom_target, not a run_command, because you'd want this to be generated at build time rather than configure time.

Thanks

> As far as xxd goes, this was always kinda-sorta needed, the Makefile had a rule to run xxd but the dist already had that pre-built so it might not actually run.

I had not realised that ClayRGB1998_icc.h was distributed. It is a generated file (along with ui_icons.h and icons_inline.h), so I think it a mistake for it to be in the repo.

**Comment by stefanhusmann** [comment]
> Arch has a package xxd-standalone - does this provide xxd without vim?
No, it has not - at least neither in the official repos nor in AUR. Where did you see it?

**Comment by eli-schwartz** [comment]
https://repology.org/project/xxd-standalone/versions
https://repology.org/project/xxd/versions

Weird naming split, but the AUR definitely seems to have the one with the "-standalone" suffix if you look at packages for the first link.

And if you follow that link, you'll notice the AUR has a "geeqie-git" package with a make dependency on xxd, which links to "xxd-standalone" as a satisfier (in addition to "vim"), so it appears that someone already noticed the issue and arranged for it to not be an issue anymore.

What's the actual issue?

**Comment by eli-schwartz** [comment]
> I had not realised that ClayRGB1998_icc.h was distributed. It is a generated file (along with ui_icons.h and icons_inline.h), so I think it a mistake for it to be in the repo.

autotools can be configured with an out of source build, but often isn't. So it's possible that those files were accidentally checked into git as a group. Meson mandates that all builds must be out of source, in part to prevent that from happening -- although that does require you use custom_target to generate the file, not run_command!!!

**Comment by caclark** [comment]
Fixed in commit ef70ba51

**Comment by tomaszg7** [comment]
There's still something wrong with generation of the file. 

- First of all, meson doesn't check for the presence if xxd/xxdi, it is only checked during compile phase. 
- Secondly, even if it is present, build still fails for me:

```
[1/3] Generating src/ClayRGB1998 with a custom command
unsigned char ClayRGB1998_icc[] = {
	0x00, 0x00, 0x02, 0x44, 0x61, 0x72, 0x67, 0x6c, 0x02, 0x20, 0x00, 0x00, 
	0x6d, 0x6e, 0x74, 0x72, 0x52, 0x47, 0x42, 0x20, 0x58, 0x59, 0x5a, 0x20, 
	0x07, 0xd6, 0x00, 0x07, 0x00, 0x08, 0x00, 0x03, 0x00, 0x1c, 0x00, 0x2f, 
	0x61, 0x63, 0x73, 0x70, 0x4d, 0x53, 0x46, 0x54, 0x00, 0x00, 0x00, 0x00, 
	0x6e, 0x6f, 0x6e, 0x65, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf6, 0xd6, 
	0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0xd3, 0x2d, 0x61, 0x72, 0x67, 0x6c, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 
	0x64, 0x65, 0x73, 0x63, 0x00, 0x00, 0x00, 0xfc, 0x00, 0x00, 0x00, 0x7b, 
	0x63, 0x70, 0x72, 0x74, 0x00, 0x00, 0x01, 0x78, 0x00, 0x00, 0x00, 0x35, 
	0x77, 0x74, 0x70, 0x74, 0x00, 0x00, 0x01, 0xb0, 0x00, 0x00, 0x00, 0x14, 
	0x62, 0x6b, 0x70, 0x74, 0x00, 0x00, 0x01, 0xc4, 0x00, 0x00, 0x00, 0x14, 
	0x72, 0x58, 0x59, 0x5a, 0x00, 0x00, 0x01, 0xd8, 0x00, 0x00, 0x00, 0x14, 
	0x67, 0x58, 0x59, 0x5a, 0x00, 0x00, 0x01, 0xec, 0x00, 0x00, 0x00, 0x14, 
	0x62, 0x58, 0x59, 0x5a, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x14, 
	0x72, 0x54, 0x52, 0x43, 0x00, 0x00, 0x02, 0x14, 0x00, 0x00, 0x00, 0x0e, 
	0x67, 0x54, 0x52, 0x43, 0x00, 0x00, 0x02, 0x24, 0x00, 0x00, 0x00, 0x0e, 
	0x62, 0x54, 0x52, 0x43, 0x00, 0x00, 0x02, 0x34, 0x00, 0x00, 0x00, 0x0e, 
	0x64, 0x65, 0x73, 0x63, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x21, 
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x20, 0x77, 
	0x69, 0x74, 0x68, 0x20, 0x41, 0x64, 0x6f, 0x62, 0x65, 0x20, 0x52, 0x47, 
	0x42, 0x20, 0x28, 0x31, 0x39, 0x39, 0x38, 0x29, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 0x74, 0x65, 0x78, 0x74, 0x00, 0x00, 0x00, 0x00, 
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x20, 0x44, 0x6f, 0x6d, 0x61, 0x69, 
	0x6e, 0x2e, 0x20, 0x4e, 0x6f, 0x20, 0x57, 0x61, 0x72, 0x72, 0x61, 0x6e, 
	0x74, 0x79, 0x2c, 0x20, 0x55, 0x73, 0x65, 0x20, 0x61, 0x74, 0x20, 0x6f, 
	0x77, 0x6e, 0x20, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x00, 0x00, 0x00, 0x00, 
	0x58, 0x59, 0x5a, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf3, 0x51, 
	0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x16, 0xcc, 0x58, 0x59, 0x5a, 0x20, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 0x58, 0x59, 0x5a, 0x20, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x9c, 0x18, 0x00, 0x00, 0x4f, 0xa5, 0x00, 0x00, 0x04, 0xfc, 
	0x58, 0x59, 0x5a, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x34, 0x8d, 
	0x00, 0x00, 0xa0, 0x2c, 0x00, 0x00, 0x0f, 0x95, 0x58, 0x59, 0x5a, 0x20, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x26, 0x31, 0x00, 0x00, 0x10, 0x2f, 
	0x00, 0x00, 0xbe, 0x9c, 0x63, 0x75, 0x72, 0x76, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x01, 0x02, 0x33, 0x00, 0x00, 0x63, 0x75, 0x72, 0x76, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x02, 0x33, 0x00, 0x00, 
	0x63, 0x75, 0x72, 0x76, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 
	0x02, 0x33, 0x00, 0x00, 
};
unsigned int ClayRGB1998_icc_len = 580;
[2/3] Compiling C++ object src/geeqie.p/color-man.cc.o
FAILED: src/geeqie.p/color-man.cc.o 
c++ -Isrc/geeqie.p -Isrc -I../src -I. -I.. -Isrc/icons -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gspell-1 -I/usr/include/enchant-2 -I/usr/include/openjpeg-2.5 -I/usr/include/poppler/glib -I/usr/include/poppler -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -O3 -fpermissive -Wno-error=deprecated-declarations -Wno-error=sign-compare -Wno-error=return-type -Wno-error=literal-suffix -Wno-error=write-strings -O2 -march=native -pipe -pthread -MD -MQ src/geeqie.p/color-man.cc.o -MF src/geeqie.p/color-man.cc.o.d -o src/geeqie.p/color-man.cc.o -c ../src/color-man.cc
../src/color-man.cc:75:10: fatal error: ClayRGB1998_icc.h: No such file or directory
   75 | #include "ClayRGB1998_icc.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```

**Comment by tomaszg7** [comment]
Apparently it was never tested with `xxdi.pl` and commit https://github.com/BestImageViewer/geeqie/commit/ef70ba51932269f4579472abaaa8ffe4c3a23705 is broken. `xxdi.pl` doesn't accept output file as a second parameter and needs a redirect `>`. Since vim xxd in case of no second parameter uses stdout by default, it is safe to add a redirect in any case.

Trivial patch:
```
--- a/scripts/generate-ClayRGB1998-icc-h.sh
+++ b/scripts/generate-ClayRGB1998-icc-h.sh
@@ -20,4 +20,4 @@ build_dir="$PWD"
 
 cd "$(dirname "$1")" || return 1
 
-${XXD} "$(basename "$1")" "$build_dir/$2"
+${XXD} "$(basename "$1")" > "$build_dir/$2"
```

**Comment by caclark** [comment]
Should xxdi.pl be part of the Geeqie package?

[And perl is not part of the FreeBSD base system - but as no-one has complained, it cannot be a problem]

**Comment by tomaszg7** [comment]
Well, it is not a big file, but it depends on another Perl module (File::Slurp). In my case it was not installed so bundling this script would not help much. I suggest only to check for existence of either method (xxd or xxdi.pl) by meson on configure time, not on build time. 

Is there a reason the generated file cannot be simply included in the tree instead of binary one?

**Comment by eli-schwartz** [comment]
Generated files make no sense, as a general rule, to check into git.

Distributing them in a dist tarball might make sense.

**Comment by tomaszg7** [comment]
This last commit is only a partial solution. Regretfully, even if the detection fails and CMS get disabled, the meson still tries to generate the file and build still fails, just like before:
```
[1/129] Generating src... with a custom command
FAILED: src/ClayRGB1998_icc.h 
/home/tomaszg/src/geeqie/scripts/generate-ClayRGB1998-icc-h.sh ../src/ClayRGB1998.icc src/ClayRGB1998_icc.h
/home/tomaszg/src/geeqie/scripts/generate-ClayRGB1998-icc-h.sh: line 23: xxd: command not found
```
