### ISSUE TITLE
meson build system - fail gracefully when pandoc isn't installed

### ISSUE THREAD

**Issue by l8gravely** [BestImageViewer/geeqie#1003]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
master
```

```
gtk3
```

### OS / DISTRIBUTION
LinuxMint 20.3

### SUMMARY

If you don't have pandoc installed, 'meson setup build' bombs out with an error which doesn't even mention the tool requirement.   

### STEPS TO REPRODUCE

sudo apt-get purge pandoc
meson setup build

**Comment by caclark** [comment]
Fixed in commit db95a097
