### ISSUE TITLE
Square artifacts when viewing pictures using system color correction

### ISSUE THREAD

**Issue by sebathomas** [BestImageViewer/geeqie#1014]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.7.3 GTK3
```

### OS / DISTRIBUTION
Manjaro

### SUMMARY
When I open any pictures on my new laptop, I get strange square artifacts as seen on the screenshot below.

Geeqie screenshot:
![geeqie](https://user-images.githubusercontent.com/14236667/182021632-4a98e654-75b8-4d5e-9b41-6102b352954b.jpg)
Original:
![original](https://user-images.githubusercontent.com/14236667/182021635-8e7573ba-f5d4-45c0-a3cd-f6e5bb969fbb.jpg)

It happens for any picture that I open with geeqie (even if it's not always as obvious as in the example), independent of whether I use full-screen mode or not. I don't have any issues with other image viewers.

I use the same version of geeqie on other computers without any issues so I believe it has something to do with my laptop (XPS 13 9310 with an OLED screen).

### STEPS TO REPRODUCE
Open any picture on that laptop.

**Comment by mowgli** [comment]
That is really strange. Could you try to switch off the color correction? Does the artifacts still occur?

Do you have a special color profile for your laptop? What is with other image viewers that use color profile information? (I believe, at least firefox is able to use color correction.)

**Comment by sebathomas** [comment]
Thank you, that helped quite a bit. The issue gets a lot less noticeable if I change the color correction in the settings and then reload the image. It is still there for some images but a lot more subtle.

![colorprofilebad](https://user-images.githubusercontent.com/14236667/182024016-851b75d7-bdce-4b5f-b295-abdad4582a31.png)
![colorprofilegood](https://user-images.githubusercontent.com/14236667/182024018-1191c843-775d-4e5e-b817-edbec81f68a9.png)

**Comment by caclark** [comment]
I think this is the same as issue #971, which is now fixed.
If you do not wish to compile from sources, I will be uploading a new version in a few days' time.
[In the commit I noted that the screen scaling factor was involved.]

**Comment by sebathomas** [comment]
Thanks for the quick response. I just compiled from source and confirmed that the issue isn't there on the current master. 👍
