### ISSUE TITLE
Remote commands vaguely broken

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#102]
Commands that worked in gqview no longer work, and my attempts to
control a running geeqie process via the commandline often report
errors and don't always do what I expect from the documentation.

Some examples perhaps illustrate best.  I have a running geeqie process.

jeff@aragorn:California $ geeqie --remote file 20091023-093855-6366.jpg 20091023-142855-6367.jpg
Geeqie 1.0beta2, This is an alpha release.
Invalid or ignored remote options: file, 20091023-093855-6366.jpg, 20091023-142855-6367.jpg
Use --remote-help for valid remote options.
jeff@aragorn:California $ 

But, in fact, the remote session did the right thing (displayed those
two images as a selection of two things).  The error message appears
incorrect (and quite distracting!).  By selection, I mean "what does
repeated application of page-up and page-down indicate is the set of
images I am viewing?"

When viewing a single image (geeqie --remote file foo.jpg), the file
foo.jpg displays but I don't see a selection of one.  (That is, next
and back move to other images.)

jeff@aragorn:California $ geeqie --remote file  20091023-142855-6367.jpg
Geeqie 1.0beta2, This is an alpha release.
Invalid or ignored remote options: file, 20091023-142855-6367.jpg
Use --remote-help for valid remote options.
jeff@aragorn:California $ 

Some unrecognized commands cause the geeqie window to raise itself,
which is probably never the right thing to do unless the command has
as defined purpose to raise the geeqie window.  E.g.,

jeff@aragorn:California $ geeqie --remote -z
Geeqie 1.0beta2, This is an alpha release.
Invalid or ignored remote options: -z
Use --remote-help for valid remote options.
jeff@aragorn:California $ 

(The geeqie window raised after this call.)

In any case, remote commands should surely not print to stdout or
stderr if they do their thing successfully.

jeff@aragorn:California $ geeqie --remote -n
Geeqie 1.0beta2, This is an alpha release.
jeff@aragorn:California $ 

(The image advanced, but why did I have to be told geeqie's version?)

Forwarded from http://bugs.debian.org/562488

Reported by: nijel

**Comment by caclark** [comment]
I think these issues have been resolved
