### ISSUE TITLE
Unresponsive UI when Show Marks is enabled

### ISSUE THREAD

**Issue by Agilulfo** [BestImageViewer/geeqie#1023]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
both:
```
Geeqie 1.7.2 GTK3
2.0+git20220813-eb9d0e10 (appimage)
```

### OS / DISTRIBUTION
Ubunut 22.04

### SUMMARY
Show Marks feature (shortcut "M") appear to significantly slowdown the whole application. 

- Scrolling the image list is unresponsive
- Clicking on an image does not immediately show the image.
- selecting a range of pictures is extremely slow

On the same hardware I've never had similar issues with previous versions.
(I don't know which specific version I was running, probably the one coming  with previous Ubuntu LTS)

It looks very similar to what has been reported in (here)[https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=965339 ]

### STEPS TO REPRODUCE
- Open a folder containing images. 
- click select>Show Marks (or simply press M)
- click on a thumbnail to show that image or try to do any other basic operation described in the summary
- Disabling the Show Marks feature causes the app to become responsive

**Comment by caclark** [comment]
Could you try the `Images As List` display, with the `Show Thumbnails` option.
You might need to use the menu `View/Files And Folders/Images As List` to make the switch.

**Comment by Agilulfo** [comment]
Interesting results. Enabling the `Image As list` option

- On geeqie 1.7.2 simply produce an almost immediate crash.
- On 2.0 instead noticeably improves performance to the point I cannot notice any difference between `Show Marks` on or off

So it looks like the application slowdown only when both `Images as Icons` and `Show Marks` are both on at the same time.

Additionally it looks like the amount of columns displayed seems to matter. (If you reduce the area where the thumbnail are previewed so that only one column is displayed things start improving but still the application remains less responsive than when the `Images As List` is used.
