### ISSUE TITLE
Bug: scanning for keywords produces duplicates (a lot of duplicates)

### ISSUE THREAD

**Issue by kha84** [BestImageViewer/geeqie#1033]
Go to Preferences -> keywords -> search  
Select some folder where you have photos with keywords.
Give it a time and you'll see it fills the list with lot of duplicates.

Looks like the algorithm used there just walks through all files and whatever keywords it finds, it just adds them to the list.
Thus if you had the same keyword in multiple files you'll get duplicates.

If you want to fix it in easy way, what needs to be done here:
- when you're traversing image files, you collect keywords from them to some buffer, while keeping only unique values
- then, upon merging what you have collected with what user might be having already in hist keywords list, you merge while leaving only unique records again

**Comment by caclark** [comment]
When the list is saved, it is first sorted and then duplicates are removed. If you re-open that page there should be no duplicates.
If that is not so with your setup, please re-open this issue.

**Comment by kha84** [comment]
Sure, I get that you eventually sort and dedupe that list. But filling it with a lot of duplicates as a result of scanning is very confusing from the UX perspective. Because when you hit "save" button while having a lot of garbage above that button, you're kind of accepting all that garbage
