### ISSUE TITLE
small display of raw image for olympus e-500

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#104]
Hi

When you try to open a raw image of a olympus e-500 camera (*.orf) you are getting a small thumbnail sized 160x120.
Opening a orf file taken with a e-510 shows a 1600x1200 thumb

Using dcraw -e serves a 1600x1200 thumbnail in both cases

Thanks in advance

Reported by: *anonymous

**Comment by caclark** [comment]
Works with images downloaded from rawsamples.ch
