### ISSUE TITLE
Simplify the UI.

### ISSUE THREAD

**Issue by lidgnulinux** [BestImageViewer/geeqie#1041]
### ISSUE TYPE

* Feature Request

### GEEQIE VERSION

```
Creating Geeqie dir:/home/ahmad/.cache/geeqie/thumbnails

Geeqie 2.0+git20220927-4905c95a GTK3
```

```
I use gtk3.
```

### OS / DISTRIBUTION

CRUX version 3.7

### SUMMARY

I need a simple image viewer like imv, but imv breaks on wayland, then I found geeqie, it run well on wayland (I'm using dwl compositor). I get annoyed by directory tree and file listing on the left. How do I get rid of them ? I have a quite small screen.

### STEPS TO REPRODUCE

- Trying to find a setting or preference to hide directory tree and file listing (I don't find it yet).

**Comment by caclark** [comment]
There is a feature which might be suitable - go to `View\Hide Bars`.
This action is also toggled by the back-tick key (top left on a British keyboard). This key can be remapped.
The state is remembered on restart.

Please close this issue if this fixes the problem.

**Comment by lidgnulinux** [comment]
hello @caclark , it works. Thanks. 
Forgive me for the rude language. Have a nice day.
