### ISSUE TITLE
Can't open CR3 images

### ISSUE THREAD

**Issue by serhiykobyakov** [BestImageViewer/geeqie#1054]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION

```
Geeqie 2.0.1 GTK3
```
Installed directly from ubuntu repository

### OS / DISTRIBUTION
Ubuntu 22.10

### SUMMARY
Geeqie does not open CR3 images.
I can open CR3 images using Darktable, libraw binaries on my machine but not Geeqie...
Tried to pass --debug=9 (```geeqie --debug=9 <CR3 image file name>```, tried to pass other numbers into debug option) in bash, but I see no output in command line, log window is empty, Geeqie opens empty window each time.
At the same time Geeqie have no problems with CR2 or dng images.
Tried few appimages from https://www.geeqie.org/AppImage/index.html, same result.
Exiv2 extracts previews from CR3 images, exiftool and libraw binaries also have no problems with CR3.
Grabbed few CR3 images from Dpreview (other cameras than my EOS R) - Geeqie refuses to open all CR3 images...

On my other PC with Ubuntu 22.04 and Geeqie 1.7.2 installed I see CR3 images, there is no problem there.

Is there any other ways to debug Geeqie? Or should I debug Ubuntu? What can I do to find what is wrong here?

### STEPS TO REPRODUCE
```geeqie <CR3 image file name>``` in bash: Geeqie opens empty window each time - see screenshot attached:
![image](https://user-images.githubusercontent.com/15909653/209542531-e7021f3b-8208-4188-a163-e2950677944a.png)

**Comment by caclark** [comment]
There are .cr3 samples on the following link. Do they show ok?

https://www.imaging-resource.com/PRODS/canon-eos-r7/canon-eos-r7GALLERY.HTM

**Comment by serhiykobyakov** [comment]
> There are .cr3 samples on the following link. Do they show ok?
> 
> https://www.imaging-resource.com/PRODS/canon-eos-r7/canon-eos-r7GALLERY.HTM

No, still nothing...

**Comment by caclark** [comment]
Could you please create a temp directory e.g `mkdir /tmp/test-cr3`, and copy a single .cr3 file there.
Then run one of the Geeqie AppImages:
`<geeqie-appimage> --debug=4 --log-file:test-cr3.log /tmp/test-cr3/`
Exit geeqie
`gzip test-cr3.log`
Upload the debug file to here

**Comment by serhiykobyakov** [comment]
> Could you please create a temp directory e.g `mkdir /tmp/test-cr3`, and copy a single .cr3 file there. Then run one of the Geeqie AppImages: `<geeqie-appimage> --debug=4 --log-file:test-cr3.log /tmp/test-cr3/` Exit geeqie `gzip test-cr3.log` Upload the debug file to here

I've got empty test-cr3.log file when using Geeqie installed from repository.

I see you mentioned <geeqie-appimage> - do you mean some exact appimage version from https://www.geeqie.org/AppImage/index.html ?

**Comment by caclark** [comment]
The version of Geeqie in the Ubuntu repo. does not have debug output enabled. To see debug output it is necessary to use an AppImage or compile from sources.

There may be a problem with your config. file. To start with default settings try:

`mv $HOME/.config/geeqie/geeqierc.xml $HOME/.config/geeqie/geeqierc.xml.20221226`
and then run the Geeqie AppImage again.

**Comment by serhiykobyakov** [comment]
Appimage does not work, it created just $HOME/.config/geeqie directory and the $HOME/.config/geeqie/layouts directory

The geeqie from repository works, it created geequierc.xml file and open main window with CR3 preview!

Though it only shows 1620x1080 images which is not the full resolution previews, but at least I see something, which is much better than nothing!

@caclark, thank you for helping me with this!

**Comment by caclark** [comment]
> Though it only shows 1620x1080 images which is not the full resolution previews, but at least I see something, which is much better than nothing!

There is already a bug report for this - #990 - but I had forgotten about it.

That issue report shows a workaround if you are compiling from sources (which you are not).
I will fix #990 somehow.
