### ISSUE TITLE
AppImage exit silently on missing system dependency

### ISSUE THREAD

**Issue by romain-dartigues** [BestImageViewer/geeqie#1060]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
Geeqie 2.0+git20230103-c45c933d GTK3
```

### OS / DISTRIBUTION

Distributor ID: Linuxmint
Description:    Linux Mint 21.1
Release:        21.1
Codename:       vera
Based on Ubuntu Jammy Jellyfish 22.04

### SUMMARY

Running `Geeqie-v2.0+20230103-x86_64.AppImage` result in "nothing" being displayed with an exit code of 1.
Running `strace` showed:
```
openat(AT_FDCWD, "/usr/share/uim/lib/sigscheme-init.scm", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, "Error: ", 7)                  = 7
write(2, "in load: file \"/usr/share/uim/li"..., 63) = 63
write(2, "\n", 1)                       = 1
```

I solved the issue by installing the package `uim`.

I expected to see the errors messages without having to rely on strace, and `uim` is not installed by default.

**Comment by allefeld** [comment]
I had the same problem on Debian 12. There is a message when the appimage is started from a terminal,
```
Error: in load: file "/usr/share/uim/lib/sigscheme-init.scm" not found
```
I solved it by installing the `uim` package.

However, I then noticed that UIM disables the compose key in KDE applications, which is a no-go for me.

So I would appreciate if the dependency of Geeqie on UIM could be removed or circumvented.
