### ISSUE TITLE
How to set the background/board color?

### ISSUE THREAD

**Issue by LogWell** [BestImageViewer/geeqie#1065]
The configuration is the same as: https://github.com/BestImageViewer/geeqie/issues/1063#issue-1597849914

How to set the board color to distinguish it from the picture boundary:

Geeqie
![20230309_123802](https://user-images.githubusercontent.com/34391447/223918545-0dea1d74-f0ea-4b7d-9a97-c7c396aa2b66.png)

tev
![image](https://user-images.githubusercontent.com/34391447/223918938-cfec27bd-b874-4018-9e85-cb1fd86832bc.png)

**Comment by caclark** [comment]
The setting is on `Edit/Preferences/Image` . The checker-board colors are set by the two Alpha channel colors.

If you are looking at black/white images, this comment on the mailing list might be interesting:

https://www.freelists.org/post/geeqie/Display-images-with-a-white-background
