### ISSUE TITLE
Meson and webp-pixbuf-loader

### ISSUE THREAD

**Issue by caclark** [BestImageViewer/geeqie#1066]
@eli-schwartz
Thanks for your previous help with meson.

Currently Geeqie uses libwebp directly for webp files, but now gdk-pixbuf also supports webp, so that is an easier solution (and also supports animation).

So `sudo apt install webp-pixbuf-loader` gets the loader, but the only way I can get meson to see it is:

` libwebp_dep = cc.find_library('libpixbufloader-webp', dirs : '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/', required : get_option('webp'))`

That cannot be right. Do you have a suggestion?

**Comment by eli-schwartz** [comment]
Hmm. I thought that gdk-pixbuf loaders were plugins that are supposed to be used by the gdk-pixbuf API rather than directly using the loader itself.

Are you doing this in order to link to the loader or just to assert that as a runtime dependency, it is installed? In the latter case it may be sufficient simply to document in the README that it should be installed.

You can get the gdk-pixbuf loader directory with:

```meson
dependency('gdk-pixbuf-2.0', method: 'pkg-config').get_variable('gdk_pixbuf_moduledir')
```

**Comment by caclark** [comment]
As far as I see, loading libgtk-pixbuf also loads standard loaders like png, ico etc., but not the webp loader.
I do not know why, but maybe that will change in the future.

I just want the meson user to be informed that the webp loader is not installed.

I will hack something using the gdk-pixbuf-loader directory as you have detailed in order that the user is informed that the webp loader is or is not installed.

Thanks for the information.

**Comment by Safari77** [comment]
geeqie produces only black images for every webp image, but they load ok with the following test program for gtk3 and pixbuf. geeqie loads JPEG images just fine.
geeqie does not produce any useful logs when using --debug , it is as if everything goes fine.
I have webp-pixbuf-loader 0.2.4 gtk-3.24.37 on Fedora 37.

```
gcc -Og -o gtkshow gtkshow.c `pkg-config --cflags --libs gtk+-3.0 gdk-pixbuf-2.0`
```
```
#include <gtk/gtk.h>

int main(int argc, char *argv[]) {
    GtkWidget *window;
    GtkWidget *image;

    if (argc != 2) {
        fprintf(stderr, "give image as command line option\n");
        exit(1);
    }
    // Initialize gtk
    gtk_init(&argc, &argv);

    // Create the main window
    window = gtk_window_new(GTK_WINDOW_TOPLEVEL);
    gtk_window_set_title(GTK_WINDOW(window), "Image Viewer");
    gtk_window_set_default_size(GTK_WINDOW(window), 800, 600);
    gtk_container_set_border_width(GTK_CONTAINER(window), 10);

    // Load the image
    GdkPixbuf *pixbuf = gdk_pixbuf_new_from_file(argv[1], NULL);

    // Create the image widget
    image = gtk_image_new_from_pixbuf(pixbuf);

    // Add the image widget to the main window
    gtk_container_add(GTK_CONTAINER(window), image);

    // Show the widgets
    gtk_widget_show(image);
    gtk_widget_show(window);

    // Start the main loop
    gtk_main();

    return 0;
}
```
