### ISSUE TITLE
Delete a keyboard shortcut

### ISSUE THREAD

**Issue by hugh-m** [BestImageViewer/geeqie#1079]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
"Geeqie 2.0.1 GTK3"
`
### OS / DISTRIBUTION
Debian Unstable

### SUMMARY
I would like to delete some preconfigured keyboard shortcuts to use them for my own scripts. I can't see a way to delete shortcuts via Edit → Preferences → Keyboard. Is it possible?

**Comment by caclark** [comment]
In the Help file, Reference/Keyboard And Mouse Shortcuts, lists the keys which can be reprogrammed and those which cannot.

**Comment by hugh-m** [comment]
Yes. I would like to unset some of the programmable actions to use the shortcuts for different actions. Say I wanted to use <primary>1 to trigger a script plugin of my own, can I delete that shortcut from its current action "Select mark 1"?

**Comment by caclark** [comment]
You just need to allocate "1" to whichever action you require.

**Comment by hugh-m** [comment]
Ah. In my previous comment, the word primary in angle brackets was swallowed by the system, I meant primary-1. Anyway I can't allocate 1 to an action, it is already allocated to return zoom to 1:1. All the digits 0-9 are currently allocated. This is my point. I think it would be useful to have a way to unset the shortcut of an action, so the shortcut can be assigned to a new action created by the user.

If the same shortcut is allocated to two different actions, the first one takes precedent, the second is ignored. That has been my experience.

**Comment by caclark** [comment]
It is not possible to allocate the same shortcut to two actions.

If "1" is allocated to "Toggle Mark 1", and you then allocate "1" to "First Page", "Toggle Mark 1" will no longer have a shortcut.

[There is no warning that you are re-allocating a shortcut - that is perhaps a deficiency]

**Comment by hugh-m** [comment]
You seem determined to misunderstand my point. I have been using gqview/geeqie daily for 18 years. I am very familiar with the application.

This is the behaviour I expected and would like to encourage the developers to adopt: for an editable shortcut: after double-click on the shortcut for an action: pressing some key, say, Backspace, deletes the shortcut from that action so that shortcut can be assigned to a different action. In my case, that different action would be a plugin script written by me.

**Comment by caclark** [comment]
I continue to misunderstand.
However, I see that there might be a need to unset an accelerator shortcut for some reason or another.
I might implement that, at some time or other.

A right now, immediate, solution to that is to close Geeqie and open $HOME/.config/geeqie/accels in an editor.
Find the accel in question, delete the semi-colon and space characters at the start of the line and insert "" as the shortcut.

**Comment by hugh-m** [comment]
That works fine. Thanks.
