### ISSUE TITLE
External editor fails with diacritics in filename

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#108]
I'm using Geeqie 1.0beta2, I've got directory names with diacritics (in French), like "événement". When I try to apply a custom external editor to files in this directory, I get an error message saying that the external command cannot be executed. The external command is basically Exec=myscript %f. Note that myscript is not even launched (log commands at the beginning of that script are not executed).

Renaming the directory in something without diacritics (like "evenement") works perfectly, so it is really caused by this "é". The diacritics are displayed correctly everywhere in geeqie, including in the popup error message, but the command is not launched. No message in the terminal window, and setting the debug log level to 4 does produce a lot of messages, but none seem related to this and I get the same messages with a directory name that works (i.e. without é).

I believe my file system is in ISO8859-15 (not UTF-8), although I'm definitely not an expert about this... My locale is fr_FR@euro.

Launching "LANG=C geeqie" from a terminal gives me a lot of messages "Unable to convert filename to UTF-8:" (followed by a filename with a diacritic), as well as "(geeqie:6168): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()", and then the diacritics are *not* displayed correctly in the geeqie window *but* the external command works fine on files in this directory!

No other idea of what to test...

Reported by: *anonymous

**Comment by caclark** [comment]
Seems to be fixed
