### ISSUE TITLE
Buggy scrolling when image overlay is enabled.

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#109]
Geeqie scrolls the zoomed picture so that the rectangle of overlay \"moves\"\' with the scrolled picture. See the attached picture. (The full screenshot doesn't fit to the upload limit.) This occurs in both windowed and fullscreen modes. I noticed the following: When geeqie has to reload the "buggy" area (because I am moving an other window in front of geeqie), the "white noise" disappears.

I am using version 1.0beta2.

Reported by: ngaba

**Comment by caclark** [comment]
Fixed in v1.1
