### ISSUE TITLE
Orientation  functions not working in 2.01

### ISSUE THREAD

**Issue by stephenboston** [BestImageViewer/geeqie#1092]
* Bug Report

### GEEQIE VERSION
Geeqie 2.0.1 GTK3

None of the orientation functions are working. Not through the menu or through the assigned keys.

### OS / DISTRIBUTION
6.3.2-arch1-1

### SUMMARY

None of the orientation functions are working. Not through the menu or through the assigned keys.

### STEPS TO REPRODUCE
1. Open an image using geeqie
2. Right click 
3. Orientation
4. Pick any of the orientation functions
5. Observe result

alternatively 
1. Open an image using geeqie
2. Press any of the orientation-assigned keys as shown in Edit/Preferences/Keyboard
3. Observe Result

Note : Journal shows no entries for geeqie.

**Comment by caclark** [comment]
Is Edit/Orientation/Exif Rotate set?

**Comment by stephenboston** [comment]
Ah! Silly me. So sorry. 

I've been using geeqie for years and never had to set that before. I must have knocked it off accidentally.

Thank you.
