### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [BestImageViewer/geeqie#1095]
It would be a good to cut a new release after:
- https://github.com/BestImageViewer/geeqie/issues/1090
- I also need the new release for removing the build patch of [this commit](https://github.com/BestImageViewer/geeqie/commit/87042fa51da7c14a7600bbf842010)

Thanks!

**Comment by caclark** [comment]
There is a new release.

**Comment by chenrui333** [comment]
Thanks @caclark!
