### ISSUE TITLE
Libdir is hardlinked, should take system one

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#110]
The dir for libs is hard-linked in configure script, so on some systems, like Mandriva Linux 64bit it makes problems (the libdir is /usr/lib64). Attached patch to fix it, where the libs dir si taken the system one

Reported by: *anonymous

**Comment by qarkai** [comment]
@caclark @mowgli Is this issue still relevant after moving to Meson?

**Comment by caclark** [comment]
https://mesonbuild.com/Builtin-options.html

> libdir is automatically detected based on your platform,
