### ISSUE TITLE
Portrait mode pictures are shown in landscape mode

### ISSUE THREAD

**Issue by MarkusHB1** [BestImageViewer/geeqie#1102]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
Geeqie 2.0+git20230512-254b0fcb GTK3 but also with 1.7.2

```

```
I don't compile myself
```

### OS / DISTRIBUTION

Ubuntu 22.04
### SUMMARY

Pictures taken in portrait mode are shown in landscape mode.

**Comment by MarkusHB1** [comment]
Again, reproducing instructions got lost. Just open the attached jpg
![DSC00077](https://github.com/BestImageViewer/geeqie/assets/135862210/f4386211-bdea-4309-b651-2910db32cfc0)

**Comment by caclark** [comment]
On the status bar at the bottom of the Geeqie window, on the right-hand side is an icon which has the tooltip "Toggle Exif rotate". If you click this, is there any change?

**Comment by MarkusHB1** [comment]
Yes, after clicking this icon the picture is shown in portrait mode. So I leave it in this state? Did I set it accidentally in a wrong mode?

**Comment by caclark** [comment]
Typically one would leave it set so that images are auto-rotated. 

This option may be useful for a user who has manipulated images to be rotated and needs to know how the original image was.

**Comment by MarkusHB1** [comment]
Thank You so much for helping me, Colin.

Seems again the problem is sitting in front of the screen. So it seems, my problem is solved after toggling the option. Then we can close the issue, I guess.
