### ISSUE TITLE
NetBSD: missing link against libexecinfo

### ISSUE THREAD

**Issue by 0-wiz-0** [BestImageViewer/geeqie#1111]
When building geeqie-2.1 on NetBSD, linking fails with:
```
ld: src/geeqie.p/main.cc.o: undefined reference to symbol 'backtrace'
ld: /usr/lib/libexecinfo.so.0: error adding symbols: DSO missing from command line
```
On NetBSD, `backtrace()` is provided in libexecinfo, and since `main.cc` uses this (when the `execinfo.h` header is found, which NetBSD provides), it needs to link against `-lexecinfo` on NetBSD.

I don't speak meson well, can you please add this?

**Comment by caclark** [comment]
Unfortunately I do not use NetBSD and my understanding of meson is not too good. Perhaps you could try the attached .diif and make the necessary changes?
[1111.diff.gz](https://github.com/BestImageViewer/geeqie/files/11781214/1111.diff.gz)

**Comment by 0-wiz-0** [comment]
Thanks for the patch!
Sadly, it doesn't work, since meson tries to find libexecinfo via pkg-config and NetBSD's base system libraries do not provide pkg-config files.
libexecinfo is part of NetBSD since 2012, so I think you could unconditionally depend on it on NetBSD.
However, it pointed me in the right direction. What do you think of #1114?

**Comment by 0-wiz-0** [comment]
#1114 was merged so this is fixed, thanks!
