### ISSUE TITLE
Can't re-add items to collection after accidentally removing them

### ISSUE THREAD

**Issue by ssokolow** [BestImageViewer/geeqie#1151]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 2.1 GTK3
```

### OS / DISTRIBUTION
```
ssokolow@monolith ~ % lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
ssokolow@monolith ~ % flatpak --version
Flatpak 1.14.4
```

### SUMMARY

Since at least somewhere in the Geeqie 1.x series, if I've accidentally removed the wrong image from a collection, Geeqie would refuse to let me drag-and-drop it back in unless I saved, closed, and then re-opened the collection.

I think this bug might have arrived around the same time Geeqie started refusing to allow a collection to contain the same image more than once without actually duplicating it on the hard drive. (Which you might want to do if your goal is to construct quick-and-dirty predefined slideshows using collections or create even quicker-and-dirtier weighted randomization in random slideshows.)

### STEPS TO REPRODUCE

1. Open a new collection.
2. Drop some images in.
3. Remove one (i.e. select and press Delete)
4. Attempt to re-add it using drag-and-drop

**Comment by caclark** [comment]
> (Which you might want to do if your goal is to construct quick-and-dirty predefined slideshows using collections or create even quicker-and-dirtier weighted randomization in random slideshows.)

Do you want multiple entries of the same image in a Collection, or would you simply like (in some way or other) to be able to modify a Slideshow set to include an image more than once?

[For example, a Collection is simply a list of images in a text file. Slideshows could be constructed also by lists in text files - which might lead to additional options such as variable time delays and links to audio files.

 However, there may already be specialized slideshow programs which do this better than Geeqie could.

Using an external program via a plugin would be the preferable option - for me.]

**Comment by caclark** [comment]
@ssokolow 

Having duplicates in collections is a problem because for each file Geeqie creates a unique hash from the filepath. This speeds up various operations, but having duplicate values is not possible.

For duplicate entries could you create a symlink in the same directory with some random name?

**Comment by ssokolow** [comment]
> @ssokolow
> 
> Having duplicates in collections is a problem because for each file Geeqie creates a unique hash from the filepath. This speeds up various operations, but having duplicate values is not possible.
> 
> For duplicate entries could you create a symlink in the same directory with some random name?

Nahh. That'd be such a mess to manage that it'd be easier to just move forward with my plans to write a replica of the relevant bits of Geeqie's UI in PyQt and slap it on top of an SQLite database full of `path → file_hash → pixmap_hash → cached_similarity_hash → metadata` narrowings.

Either way, all I know is that GQView used to allow it, and that silently refusing to re-add stuff after deleting it unless you close and re-open the collection must be a bug.

**Comment by caclark** [comment]
@ssokolow 
It looks like I was wrong - there is now an option in Preferences/Behavior to permit duplicates in Collections.
It also solves the re-insert problem (actually I think the problem is still there, just hidden, but if it works....).
