### ISSUE TITLE
Unable to apply metadata on multiple files

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#116]
I enabled the option that say that metadata can be saved on gouped sidebar files. I select multiple files, right-click and group them, then set a keyword. Save button on bottom right say it will be saved in only latest selected file. When I change dir or file, metadatas are only saved on latest selected file.

Tested on 1.0 and trunk  r1915

Reported by: elacour

**Comment by caclark** [comment]
Fixed in v1.1
