### ISSUE TITLE
Put main menu items into one hamburger menu

### ISSUE THREAD

**Issue by Stalinist1** [BestImageViewer/geeqie#1184]
Now I have horizontal scroll bar to see all main menu items.

1. It's unconvenient.
2. Main menu item are rarely used. Mostly in order to configurate application only once. So put them all into one hamburger menu.
 
![изображение](https://github.com/BestImageViewer/geeqie/assets/33825590/6e24817d-34ce-4cea-a7a6-17ef69c3e2de)

**Comment by caclark** [comment]
Open `Edit/Preferences/General` , select `Expand menu and toolbar` and restart Geeqie. That will solve part of the problem (but take some vertical space from another box).

A "hamburger menu" button could be implemented, probably as an icon on the left of the box containing the words `/home/sergei` in the above image.

**Comment by Stalinist1** [comment]
Yes, I see. The height of the main box with thumbnails is little smaller. Not so good. I think there must be is much vertical space as possible, because main scrolling in any application is vertical.

And by the way, you THICK status bar at bottom that eats vertical space as well. It's 45px high!

Why do you need it?

![изображение](https://github.com/BestImageViewer/geeqie/assets/33825590/c84ec8ce-fb9d-4583-91cf-a069fd3e736e)

**Comment by caclark** [comment]
> Why do you need it?

Do you want an option to hide the status bar, or do you want its size to be reduced?

**Comment by Stalinist1** [comment]
Well, you definitely you can make it half its size

**Comment by caclark** [comment]
The gtk function used to display icons has a very limited range of values for size.

In the latest Geeqie version, the icon size is no longer explicitly set, but it is left to default to whatever the system uses.
On one computer the icon size is reduced by a few pixels, and on another, there is no change (although both computers are running the same OS).

The latest version is Geeqie-latest-x86_64.AppImage in Continuous Build at:
https://github.com/BestImageViewer/geeqie/releases

The issue is still open.

**Comment by caclark** [comment]
Commit fbbea4f8bc does not reduce the size of the status bar, but makes it possible to show or hide it.

**Comment by caclark** [comment]
Commit f1c1ccb94 reduces the height of the toolbars

**Comment by caclark** [comment]
The attached images show a mock-up of a "hamburger" menu style. I don't feel terribly enthusiastic - especially if it ends up with yet another user option.

![Screenshot_2024-01-19_20-47-53](https://github.com/BestImageViewer/geeqie/assets/574981/6d52fc0f-960e-43c8-9c55-9da87a4dc13b)
![Screenshot_2024-01-19_20-47-27](https://github.com/BestImageViewer/geeqie/assets/574981/46915dc0-c04e-44e4-b21d-5ad7785a7612)

**Comment by Stalinist1** [comment]
Ok. I just installed new version of geeqie from official repo. I enabled hamburger menu from Preferences. How can I hide toolbar?

**Comment by Stalinist1** [comment]
> The state of the toggle is not preserved over restarts of Geeqie.

Why?
Before update toolbar was always hidden. Now I can only hide it for current session. Next time I launch app I see it again.

**Comment by Stalinist1** [comment]
I want it simple like this every time I launch the app
![image](https://github.com/BestImageViewer/geeqie/assets/33825590/b713974d-e3cc-44b7-a7af-9aa35e202c61)

**Comment by caclark** [comment]
I will make the state of the toggle remembered.

**Comment by Stalinist1** [comment]
Ok, I enabled hamburger menu and expand toolbar, tgen restarted the app.
Now I see narrow panel with directory tree (like on the screenshot above) but I have some vertical space taken by wide toolbar expanded on my wide monitor.

When toolbar is not expanded no vertical space is taken BUT I have wide panel for directory tree because of toolbar that doesn't want to shrinked.

Please make the ability to make toolbar hidden forever.

**Comment by Stalinist1** [comment]
Font for OSD can be set for current session only. After I restart for app font is reset!

**Comment by caclark** [comment]
> When toolbar is not expanded no vertical space is taken BUT I have wide panel for directory tree because toolbar doesn't want to shrinked.

I think this problem is solved in the latest sources.

> Font for OSD can be set for current session only. After I restart for app font is reset!

I do not see this problem. You can see the setting that is saved by:
`grep "image_overlay.font"  $HOME/.config/geeqie/geeqierc.xml`

**Comment by Stalinist1** [comment]
Ok, my turn.

1. Toolbar expanded. Directory tree is ok

![изображение](https://github.com/BestImageViewer/geeqie/assets/33825590/b830c468-0158-48f4-b363-f94b9985b55b)

2. Toolbar not expanded. Width of panel is the same, but directory tree began somewhere in negative X coordinates.

![изображение](https://github.com/BestImageViewer/geeqie/assets/33825590/23ab0159-e346-48de-93e8-5517619d4faf)

**Comment by caclark** [comment]
>  I just installed new version of geeqie from official repo.

Do you mean a distribution such as Debian? If so, you have version 2.2 which does not have the latest sources.

If you do not wish to compile from sources, you could try an AppImage from the Continuous Build section of the GitHub Geeqie project page:
https://github.com/BestImageViewer/geeqie/releases/tag/continuous

**Comment by Stalinist1** [comment]
> Do you mean a distribution such as Debian?

Manjaro Linux

**Comment by caclark** [comment]
Commit d0fb54619 gives the option to remove window decorations.

**Comment by Stalinist1** [comment]
I can't hide upper toolbar. 
Well, it doesn't bother me a lot, but it would be better to hide it because I don't need it.

![image](https://github.com/BestImageViewer/geeqie/assets/33825590/09333b21-968d-4977-ba9d-6f14a13ee2fb)

**Comment by caclark** [comment]
The comment above on Feb 22 is a way of doing this.

Also the latest sources have a feature:
`Edit/Preferences/Windows/Hide Window Decorations`
that result in a very minimalist view.

**Comment by Stalinist1** [comment]
I select Toolbar to hide

![image](https://github.com/BestImageViewer/geeqie/assets/33825590/7b66db7d-679d-450e-9a4b-baaf6700fb1d)

Then I press `Ctrl+`` (backtick). It hides toolbar. But after restart I see toolbar again.
