### ISSUE TITLE
Multiple instances of geeqie not working as expected

### ISSUE THREAD

**Issue by pd3** [BestImageViewer/geeqie#1186]
### ISSUE TYPE
* Bug Report and Feature Request in one

### GEEQIE VERSION
```
Geeqie 1.7.2 GTK3
```

### OS / DISTRIBUTION
Ubuntu 22.04.3 LTS

### SUMMARY
I love geeqie but the way it handles multiple windows drives me crazy. Please see below.

### STEPS TO REPRODUCE
1) run `geeqie ~/path/to/directory` from the command line
2) run another instance `geeqie ~/path/to/different/directory` from the command line
What I get is a new window pointing to the home directory. 

A workaround is to run `geeqie -n  ~/path/to/different/directory`.  However, it is a bit annoying that the `-n` option is needed and don't understand the benefits of opening the home directory instead of the directory given on the command line.

Added to this problem, the `geeqie -r --id` stops being useful with `-n` because the new instance gets assigned the same window id. It would be useful if the program accepted PID as the id argument, or if it could start with an id provided by the user, since the instance naming is not reliable anyway.

Other than that, I am really happy `gqview` got resurrected and is maintained again, thank you for the fantastic work!

**Comment by caclark** [comment]
If I run `geeqie ~/data` I get a window opened pointing to `~/data`.
If I then, from another terminal, run `geeqie ~/Desktop` I get a new window opened pointing to `~/Desktop`.
Maybe the problem you see has been fixed at some time.

There are still problems with window IDs, but you are the first person to say that feature is being used....

**Comment by pd3** [comment]
> If I run `geeqie ~/data` I get a window opened pointing to `~/data`. If I then, from another terminal, run `geeqie ~/Desktop` I get a new window opened pointing to `~/Desktop`. Maybe the problem you see has been fixed at some time.

I'll see if I'd be able to compile from source, 1.7.2 is what I get on ubuntu, unfortunately.

> There are still problems with window IDs, but you are the first person to say that feature is being used....

I can imagine it's a very niche usage. From an outsider view looks like something easy to improve I hope, best if the user was allowed to assign the id from command line on start up.

**Comment by pd3** [comment]
I was able to compile from the latest source and happy to confirm that the windows now work as expected. Thank you for your help and wonderful work!

**Comment by caclark** [comment]
@pd3 
Some LayoutWindow ID problems have been solved in commit 436753cf4
