### ISSUE TITLE
Geeqie keeps forgetting marks 

### ISSUE THREAD

**Issue by pd3** [BestImageViewer/geeqie#1188]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 2.1+git20230913-c7f18408 GTK3
```

### SUMMARY
I spent a considerable amount of time marking a photo collection. Before I started, I made sure the marks would be remembered by marking several photos, quitting geeqie, then starting it again, all seemed good. However, a few days later when wanted to get back to the photo processing, I found out that all my markings are gone, and inexplicably, only one of the photos is marked. I again tried to mark a few photos, restarted the program, now they are remembered.

I am concerned that if I spend significant amount of time marking the photos again, the marks will disappear again. 
Where are the marks stored? How can one make sure they exist somewhere physically? How can I make a backup of this data?

Note that I typically have multiple geeqie windows opened, although not in the same directory, I am wondering if that could somehow confuse the program.

**Comment by pd3** [comment]
I noticed that geeqie was not compiled with exif support. Recompiled and will test if it changes anything...

**Comment by caclark** [comment]
The marks settings are contained in a text file:
`$HOME/.config/geeqie/marks`

There is a setting: `Edit/Preferences/Behavior/Save Marks On Exit`, but this must have been set for the marks to have been saved initially.

I do not think that Exif is involved.

**Comment by pd3** [comment]
The setting was set in preferences. The location of marks file is very helpful, now I can verify manually and make a backup if necessary, thanks! I'll mark this as resolved
