### ISSUE TITLE
Export/Import of Keyword tree.

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#120]
I'm accessing my image collection from several computers.
I would like to be able to export my Keyword tree at one machine and import it at another.

Reported by: rylleman

**Comment by caclark** [comment]
The repo. at geeqie.org contains a script which enables the keyword tree of two config. files to be merged.
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=015500a02c9e57cb1f59be6b5ae347cf96c49614
