### ISSUE TITLE
Sort by Number missing from Sort method menu

### ISSUE THREAD

**Issue by jankazemier** [BestImageViewer/geeqie#1212]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 2.1 GTK3
```

### OS / DISTRIBUTION
Running the latest `geeqie 2.1-3` from the `extra` repository from Arch Linux

### SUMMARY
I have a lot of folders with images named e.g. 1.jpg thru 200.jpg. When sorted by name, 10.jpg and 100.jpg come before 2.jpg. 
The docs do mention [sort by number](https://www.geeqie.org/help/GuideMainWindowStatusBar.html) (which would be 1.jpg, 2.jpgs, ... 200.jpg), however, it seems to be missing from the sort menu in the status bar:

![image](https://github.com/BestImageViewer/geeqie/assets/355155/564883a3-11fc-4722-8c6d-2422acb75bba)

### STEPS TO REPRODUCE
Open Geeqie, click on sthe Sort menu in the status bar, see sort by numbers missing.

**Comment by caclark** [comment]
This was implemented on 2023-08-04.

For v2.1, if you go to Edit/Preferences/File Filter, there is a checkbox for Natural Sort Order.
You need to restart Geeqie for it to take effect.

**Comment by jankazemier** [comment]
Ah, that indeed works, but then the docs should be updated, as there is no "Sort by number" anymore. 

I'll close this issue for now.

**Comment by RWL-69** [comment]
I know this is closed but the documentation still doesn't explain this.  The only reason I came to the bug reports is to get sort by number back.

**Comment by caclark** [comment]
For v2.1, got to `Edit/Preferences/File Filters`. There is an option for `Natural Sort Order`.

Later sources have a `Sort By Number` option on the status line `Sort` box or by right click popup menu.
