### ISSUE TITLE
New window behavior 

### ISSUE THREAD

**Issue by pd3** [BestImageViewer/geeqie#1216]
### ISSUE TYPE
* Bug Report combined with Feature Request

### GEEQIE VERSION
```
Geeqie 2.1+git20231203-022e9b12 GTK3
```

### OS / DISTRIBUTION
Ubuntu 22.04.3 LTS

### SUMMARY
I am not sure whether to classify this as a bug or a feature request, but the behavior in opening new geeqie windows is rather unfortunate.

What I want:
- pressing CTRL+n to open a new geeqie window positioned in the same directory, the same image and with the same settings

What I get when pressing ctrl+n:
- opens a new default window with a different sort order (not my desired sort by date + descending)
- positions the window in my home directory rather than in the directory where I currently am

Using the menu windows -> new window -> from current gives me:
- opens a new window with my desired sort order (this is great!)
- but positions the window in my home directory rather than in the directory where I currently am
- in addition, there is no keyboard shortcut

Is there a possibility to configure:
1) if ctrl+n opens a new window or the window derived from the current?
2) have the new window opened at the same image where I currently at?
Surely this would make me love geeqie more! :)

**Comment by caclark** [comment]
On `Edit/Preferences/Windows` is an option `Use Current Layout For Default`.

Will that help with some problems?

**Comment by caclark** [comment]
> in addition, there is no keyboard shortcut

Go to `Edit/Preferences/Keyboard`.
Click on the Accelerators box and type "from".
Focus moves to the "from current" entry. You may set an accelarater there.

Menu `Help/Keyboard Map` will help you find a spare key setting.

**Comment by caclark** [comment]
And possibly another method which uses a recently added feature.

Create a new plugin which calls a script. Set a keyboard shortcut to the plugin.
Make the plugin `exec` line:
`Exec=/<somewhere>/script-name.sh %f`

In the script:
`#!/bin/sh`
`geeqie --remote --action:NewWindowDefault`
`geeqie --remote "$1"`

**Comment by pd3** [comment]
> On `Edit/Preferences/Windows` is an option `Use Current Layout For Default`.
> 
> Will that help with some problems?

It does, partially. The behavior is now as follows:
- [ ] `ctrl+n` opens a new window with the fixed preset defaults (e.g. the sort order)
- [ ] `windows/new window/from current` opens a new window with the current settings
- [ ] the path is not taken into account, the home directory is open with both `ctrl+n` and `windows/new window/from current`

**Comment by caclark** [comment]
The plugin must first be saved before it can be seen in `Edit/Preferences/Keyboard`.

The `Action` column will show the name you have given it.

The `Accel` column will show the desktop file name e.g. `<Actions>MenuActionsExternal/test.desktop`

**Comment by pd3** [comment]
Ah, excellent, this works. I only replaced with
```
geeqie --remote --action:NewWindowFromCurrent
```
Thank you for your help and for maintaining this wonderful software!!
