### ISSUE TITLE
Fullscreen is not actually full

### ISSUE THREAD

**Issue by Stalinist1** [BestImageViewer/geeqie#1218]
When I open some photo in fullscreen mode (by double clicking or pressing `V` button) I can see my DE's panel (XFCE4 panel on the left side in my case). In this situation I can't quit «fullscreen» mode by pressing `Escape` button. As if it's disabled.

Example

![image](https://github.com/BestImageViewer/geeqie/assets/33825590/1c1cf2f0-a687-43cd-b084-a9851295df9f)

After I go to next/previous photo being in «fullscreen» mode panel is seen anymore and it became really fullscreen. In this situation I can use all hotkeys to control the view (zoom in/out, escape, so on)

Example

![image](https://github.com/BestImageViewer/geeqie/assets/33825590/bec8f871-bfac-4c4e-ace4-1e6cdb9d3a38)

Why?

Please fix this bug.

**Comment by caclark** [comment]
There are settings on `Edit/Preferences/Windows/Full Screen`

Do they all show the same problem?

**Comment by Stalinist1** [comment]
![image](https://github.com/BestImageViewer/geeqie/assets/33825590/70f4b27d-5ca0-43c0-aad7-c7d85a020fe6)

**Comment by Stalinist1** [comment]
I changed Location to `Active screen`. 
The problem seems to be solved.
