### ISSUE TITLE
Narrow sidebars are clipped on left edge with "Expand menu and toolbar" unchecked

### ISSUE THREAD

**Issue by ssokolow** [BestImageViewer/geeqie#1237]
**Setup (please complete the following information):**
 - Distribution: Kubuntu
 - Distribution release: 22.04 LTS
 - Geeqie version [geeqie --version]: Geeqie 2.2 GTK3
 (Flatpak commit `ba1e53e0d0a6aaf6e8034081d3bf9d6bb139f74d7713872d2806ab869e4d00f4`)

**Describe the bug**

The transition from Flatpak commit `202f48969f49311420efd557bb64ae4dc69e7d77e0b83e93427658a444714ebb` (Update to runtime 45 (#31)) to Flatpak commit `ba1e53e0d0a6aaf6e8034081d3bf9d6bb139f74d7713872d2806ab869e4d00f4` (Update geeqie-2.1.tar.xz to 2.2 (#32)) broke the scrollbar-ization of the menu bar and the auto-overflow-arrow-ization of the toolbar, causing the entire sidebar to have its left edge cropped away if the menu bar is too narrow to fit.

(I have "Expand menu/toolbar" unchecked to replicate the layout I've been using since the GQView days for maximizing usable space for both portrait and landscape images and I tested checking "≡ style menu button" would fix it, but all it did was turn the toolbar into the marker for when the sidebar starts to left-clip, while rendering the menus completely inaccessible in KDE.)

**To reproduce**

1. Uncheck "Expand menu/toolbar" and restart Geeqie
2. Resize the sidebar to be too narrow to fit the menu bar

**Expected behavior**

The menu should either automatically gain a ⋮-style overflow menu (ideal) or just clip away the right end of the menu bar without clipping away any other widgets in the sidebar.

The toolbar, if the menu bar isn't present, should automatically gain a ▼ overflow menu (old behaviour). 

**Screenshots**

**Geeqie 2.1:**
![Screenshot_20240130_074052](https://github.com/BestImageViewer/geeqie/assets/46915/001aacef-9958-458b-8b95-b43c9a121e60)

**Geeqie 2.2:**
![Screenshot_20240130_073939](https://github.com/BestImageViewer/geeqie/assets/46915/35a9c258-2309-41c9-8fac-ecbdbfceff96)

**Additional context**

I'm happy to help further, as long as it doesn't take too much of my time, but I need my tooling to be functional, so I've rolled back to Flathub commit `202f48969f49311420efd557bb64ae4dc69e7d77e0b83e93427658a444714ebb` and run `flatpak mask org.geeqie.Geeqie` to pin it there until this problem is fixed.

(Thank goodness for Flathub. This is so much more convenient than when I had to grab the Geeqie 1.0 `.deb` from... Lubuntu 12.04, I think? ...to downgrade what would be Lubuntu 14.04 if the other one was 12.04, because loading my collections would crash the included Geeqie 1.1.)

**Comment by caclark** [comment]
I think this is the same problem as #1236.
It should not be difficult to fix.

> The toolbar, if the menu bar isn't present, should automatically gain a ▼ overflow menu (old behaviour).

That functionality was in the GtkToolbar widget, which is now deprecated and gone in GTK4 (although I know that Geeqie is not GTK4. but part of the migration process was to eliminate the toolbar widget...)
I suspect that will not be easy to implement. A scrollbar is possible but might increase the height of that box, which I was trying to avoid,

**Comment by ssokolow** [comment]
> That functionality was in the GtkToolbar widget, which is now deprecated and gone in GTK4 (although I know that Geeqie is not GTK4. but part of the migration process was to eliminate the toolbar widget...) I suspect that will not be easy to implement. A scrollbar is possible but might increase the height of that box, which I was trying to avoid,

The GNOME people keep making me more thankful that, since forced GNOME-isms started leaking into non-GNOME GTK apps, I've been in the middle of a long-running effort to replace all GTK apps on my desktop.

(In Geeqie's case, I'm literally just reimplementing the bits of Geeqie that I use, bit-by-bit, in PyQt, so I can transplant the UI I know onto an SQL-based image databasing tool I want to write.)

**Comment by ssokolow** [comment]
...and yeah. #1236 looks like the same bug. I just didn't think to try the right keywords when looking for existing reports.
