### ISSUE TITLE
Regression: Option to open new full-function window directly is missing

### ISSUE THREAD

**Issue by ssokolow** [BestImageViewer/geeqie#1240]
**Setup (please complete the following information):**
 - Distribution: Kubuntu
 - Distribution release: 22.04
 - Geeqie version [geeqie --version]: Geeqie 2.1 GTK3 (Flatpak commit `202f48969f49311420efd557bb64ae4dc69e7d77e0b83e93427658a444714ebb`)

**Describe the bug**

As of... Geeqie 2.0, I think... the option in the File menu to open a window that's not constrained to a specific image, selected set of images, or collection is missing and "Go to directory view" in a "View in new window" window just closes the window if the main window is pointed at the same parent directory.

As someone with three monitors, that was a feature I made a fair bit of use of.

I'm forced to do a "File > Open Recent > [anything]", "Right-click an image which isn't in the same folder and choose 'View in new window'", "Right-click and choose 'Go to directory view'" dance whenever I want a new window.

**To reproduce**

1. Open the File menu
2. See that the needed option is missing

**Expected behavior**

Case A:
1. Open the File menu
2. Click "New Window"

Case B:
1. Right-click a window with no sidebar
2. Choose "Go to directory view" or whatever it was called in Geeqie 1.x
3. Have the window *reliably* gain a sidebar instead of potentially vanishing

**Comment by caclark** [comment]
You can open a new window via `Windows/New Window/default`
