### ISSUE TITLE
Bug: 'Go to directory view' uses hard-coded default values

### ISSUE THREAD

**Issue by ssokolow** [BestImageViewer/geeqie#1241]
**Setup (please complete the following information):**
 - Geeqie version [geeqie --version]: Geeqie 2.1 GTK3 (Flatpak commit `202f48969f49311420efd557bb64ae4dc69e7d77e0b83e93427658a444714ebb`)

**Describe your feature request**

Whenever I open a new full-function window (using an indirect route since 2.0, see #1240), the sidebar layout is in an undesirable configuration and I have to manually turn thumbnail display on, drag the width of the places column down to nil, grow the folder browser a few dozen pixels so it's not pushing the menu bar half-way out of the viewport, and narrow the sidebar overall to fit my preferred balance.

It'd be very convienient if there were some way to either say "Save this window's current sidebar layout as the default for creating new ones" or say "Clone the main window's sidebar layout when creating new ones".

(I'd be more partial to the former, since it both solves the question of "how do you make it visibly clear which window is the first/main one?" and allows me to pin a layout I like, temporarily diverge from it, and then reset to it just by restarting Geeqie.)

...maybe paired with either a means of resetting all per-window settings to "use default" or some kind of rework to address how I steer clear of per-window customizations because I have no idea how Geeqie decides which per-window profile in my `git diff` output of my Geeqie config file corresponds to which visible window, how to invoke a specific one, or even how to list, edit, or clear them without editing the raw configuration file.

**UPDATE:** The problem is that 'Go to directory view' ignores the "Use current layout for default" button when opening a new window.

**Comment by ssokolow** [comment]
> There are some options under the main menu `Windows` entry.

Ahh. The menu I forget exists and have to get at via scrollbar or the arrow keys because the menu bar is too wide for my preferred sidebar width when I configure it to free up more vertical space for portrait-oriented images.

Good to see there's a keyboard shortcut to skip all the extra steps that 2.0 introduced to get that effect. It appears to do what I want so far, so I suppose, on that facet, it's a discoverability issue more than a functionality issue.

> Window layouts can be given a name by the `Rename` option.

OK, but it's still unclear how "Go to directory view" chooses one.

> 
> You can track where you are by selecting `/Edit/Preferences/Windows/Show Window IDs` (this information is not displayed unless an image is being shown)

OK, but I don't understand how that fits into things. I see the resulting names nowhere else, and certainly not under the Windows menu. Does it gain new "Windows > New Window" entries or some kind of "manage saved window settings" option if I use "Configure this window..."?

(I don't want to just find out myself, if it doesn't, then I'm potentially stuck digging through the config file to delete the test profile.)

> You can set the `default` layout at `Edit/Preferences/Use Current Layout For Default`

OK. I just tried that, but it has no effect on the layout "Go to directory view" produces.

> I think there are problems with what layout is saved - it seems that `Sort` sidebar is not remembered - maybe no one uses this feature.

I don't know the dynamics of it in "multiple saved window profiles" situations, but I certainly rely on Sort being remembered between runs so, within the scope of how I use it, it works. (Usually Sort by date but sometimes Sort by name.)

**Comment by caclark** [comment]
> OK, but it's still unclear how "Go to directory view" chooses one

I think the only place that the menu `Go To Directory` is used is  from `View In New Window`. The layout window the image came from should be used (but I have not checked that this works).

>  I see the resulting names nowhere else, and certainly not under the Windows menu. 

The window names should appear in the `Windows/New Window` menu.

> but I certainly rely on Sort being remembered between runs so,

I was referring to the `Sort` sidebar - the image sort order should be remembered.

**Comment by ssokolow** [comment]
> > OK, but it's still unclear how "Go to directory view" chooses one
> 
> I think the only place that the menu `Go To Directory` is used is from `View In New Window`. The layout window the image came from should be used (but I have not checked that this works).

It very much does not work. It appears to always produce the layout I'd get if I deleted my Geeqie dotdir and started fresh.

That's what prompted me to open this big report.

> The window names should appear in the `Windows/New Window` menu.

They don't, even after a restart, so I'm going to assume that un-customized/auto-generated names are exempted.

> I was referring to the `Sort` sidebar - the image sort order should be remembered.

"Sort Manager" on the opposite side?

**Comment by caclark** [comment]
> OK, but it's still unclear how "Go to directory view" chooses one.


The open layout windows are searched - if one is displaying that image, that is the layout window used (but that layput window is not brought to the top).

If the image is not displayed in a layout window, a new layout window is created using hard-coded default values.

**Comment by ssokolow** [comment]
> If the image is not displayed in a layout window, a new layout window is created using hard-coded default values.

Would it be OK to rename this issue thread to "Bug: 'Go to directory view' uses hard-coded default values" then?

**Comment by caclark** [comment]
Yes, that is OK
