### ISSUE TITLE
Crash when hiding file list

### ISSUE THREAD

**Issue by yourealwaysbe** [BestImageViewer/geeqie#1248]
**Setup (please complete the following information):**
 - Distribution: Arch Linux
 - Distribution release: Updated 2024/02/10
 - Geeqie version [geeqie --version]: Geeqie 2.2 GTK3

**Describe the bug**
Starting with a clean config, i am able to open Geeqie. When selecting View -> Files and Folders -> Hide File List or pressing ctrl-H a null pointer error occurs. This is even when Geeqie is opened in a directory with no images (or with images).

**To reproduce**
Open Geeqie, press ctrl-H.

**Error logs or seg. fault files**
[crash.log.gz](https://github.com/BestImageViewer/geeqie/files/14313972/crash.log.gz)

**Additional Context**
Tried with the Arch Linux community version of Geeqie, the geeqie-git AUR package, and the Flatpak/Flathub version of Geeqie.

**Comment by caclark** [comment]
@gusnan 
What is your opinion about how to handle this kind of bug, where the user is seriously affected?
After a patch has been committed:
1. Do nothing
2. Create v2.2.1 bug fix release, containing only the fix
3. Create v2.3 containing all available changes

Thanks....

**Comment by gusnan** [comment]
@caclark Thanks for the hilight!

Either is fine - What I can do with the Debian package depends on where in the Debian release cycle we are - Currently (Debian unstable is in standard development mode) I can absolutely get a new 2.3 in to Debian (or at least relatively soon).

On the other hand, if we would be in a stage of Debian freeze for a coming release, then the Debian release team only accepts targeted fixes for serious bugs in, and most likely wouldn't accept a completely new upstream release of geeqie. (the freeze for Debian 13 isn't until somewhere around beginning of 2025).

But for a more non-specific reply to your question, the old rule "Release early, release often" is good in these cases. And I always appreciate fixes that are easy to get or cherry-pick (single-commit fixes, or at least fixes that are easy to determine what is required to get only the fix and nothing additional).

But, in this case I wouldn't mind a 2.3 at all.

**Comment by micha-bee** [comment]
Hello,

as an addition, my observations for geeqie 2.2-1.2 from the system repository of openSUSE Tumbleweed:

Environment:  
Fresh installation from openSUSE-Tumbleweed-DVD-x86_64-Snapshot20240214-Media.iso , package update just a few minutes before testing.

Package data:
Name        : geeqie
Version     : 2.2
Release     : 1.2
Architecture: x86_64
Install Date: Fr 16 Feb 2024 11:59:45 CET

no ~/.config/geeqie directory initially 
no images to load initially 
crashes occur regardless of DE (Mate, Plasma) or WM (ivewm, fvwm2), or X11 redirection over ssh

geeqie, when started for the first time, crashes, when I try to configure it:

 * right click on thumbnail pane, click 'Images as Icons'
    or 
 * right click in directory listing pane, click 'View as Tree'
    or 
 * right click in image pane, click 'Hide file list'

 Maybe crashes occur on other right clicks too, but not all. For example
 deselecting 'Show Filename Text' in thumbnail pane is working without crashing.

To set "Images as Icons", the hotkey Ctrl-I is working. For testing, I then use a directory with ~2000 JPG images. As long as thumbnails are shown with file names, geeqie seems to work now. But then

 * right click on thumbnail pane, deselect 'Show Filename Text', filenames disappear
 * clicking on thumbnails then crashes geeqie after some (1..3) successful clicks
    or
 * single click on a thumbnail, the moving the mouse pointer to image pane,  crashes geeqie

This is the link to the openSUSE bug report:
    https://bugzilla.opensuse.org/show_bug.cgi?id=1220031

Kind Regards
Michael

(This is my first comment in Github, so please forgive me if I did somehing unusual - instead tell me what I should change :)
