### ISSUE TITLE
Does not honor LC_PAPER settings

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#125]
LC_PAPER environment variable should be used as default in printing dialog, currently there seems to be hardcoded default to US Letter.

This has been originally reported in Ubuntu bug tracker:
https://bugs.launchpad.net/ubuntu/+source/geeqie/+bug/40127

Reported by: nijel

**Comment by caclark** [comment]
No longer relevant - the standard print dialog is used.
