### ISSUE TITLE
annoying chown after copy

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#126]
I was trying to copy images from my camera which is mounted as a USB
mass storage device.  The files on the mount are owned by root, and
geeqie tries to chown (and chgrp) the copy, fails, and displays an
error message.  This is only mildly annoying when copying a single
file, but when I want to copy multiple files the failure stops the
operation after the first file.

Forwarded from http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=574853

Reported by: nijel

**Comment by caclark** [comment]
Fixed in commit 138e31f32
