### ISSUE TITLE
Resize dialog too small, hiding elements

### ISSUE THREAD

**Issue by Massimo-B** [BestImageViewer/geeqie#1261]
**Setup (please complete the following information):**
 - Distribution: Gentoo
 - Distribution release:  default/linux/amd64/17.1/desktop (stable) *
 - Geeqie version: Geeqie 2.2 GTK3

**Describe the bug**
The rename dialog (F2) is always sized too small. It does not show all the buttons and always needs to be resized manually:

![image](https://github.com/BestImageViewer/geeqie/assets/3286728/b7c36566-b9e5-4b61-bea7-fcbb5a4a841b)

**Comment by caclark** [comment]
If you go to `Edit/Preferences/Windows` and select `Remember Dialog Window Positions`, that should solve the problem.

**Comment by Massimo-B** [comment]
Yes, thanks.

**Comment by Massimo-B** [comment]
Anyway, the default sizing should already fit to show all elements.
