### ISSUE TITLE
Crush for printoxx.desktop

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#127]
I have /usr/share/applications/printoxx.desktop file in my system (Arch Linux x86_64) with contents:

[Desktop Entry]
Name=printoxx
Categories=Graphics
Type=Application
Terminal=false
GenericName=Image Layout and Print
Comment=Arrange images and text on a page, save or print
# Exec=/usr/bin/printoxx
# Icon=/usr/share/printoxx/icons/printoxx.png

Geeqie crush immediately after start.
If I remove this file Geeqie stats correctly.

I try with 1.0 and svn rev 1917 (2010-05-11) with same results.
In attachment gnome-style bug report generated by geeqie svn rev1917.

Reported by: zuf

**Comment by caclark** [comment]
Fault not repoducible
