### ISSUE TITLE
Geeqie cuts part of the folder view, navigation almost impossible.

### ISSUE THREAD

**Issue by lruzicka** [BestImageViewer/geeqie#1279]
**Setup (please complete the following information):**
 - Distribution: Fedora 
 - Distribution release: 40 Beta
 - Geeqie version [geeqie --version]: Geeqie 2.2 GTK3

**Describe the bug**
The application cuts the left part of the folder view (see attachment), so navigation is extremely difficult if not impossible. Resizing the application window does not affect the situation anyhow, the view just gets bigger, but only shows the ends of folders and file names. 
I use geeqie quite often and I have only seen this behaviour for the first time.

**To reproduce**
Nothing needed, just run the application.

**Expected behavior**
The folder and file view (left side of the app) should show the whole names, or at least be scrollable so that one does not see just the endings or a completely empty widget.

**Screenshots**
![Screenshot from 2024-03-10 10-18-26](https://github.com/BestImageViewer/geeqie/assets/24384878/31113229-e847-4e1e-8bb6-d275794c9ebb)

**Image sources**
Images do not affect this, it seems.

**Error logs or seg. fault files**
No crash experienced, except of the described problem, the application seems to be working normally.

**Comment by gusnan** [comment]
This is fixed in Geeqie 2.3 - see https://github.com/BestImageViewer/geeqie/issues/1236 and the fix in https://github.com/BestImageViewer/geeqie/commit/148f003f5b23bd38feacb263189e1646a1da193a.
