### ISSUE TITLE
No overwrite resolving dialog when moving files between dirs

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#128]
In 1.0beta2 (ubuntu lucid package)  and 1.0, from documentation 
"If a file with the same name exists in the selected destination a dialog will appear to notify the user and ask how to resolve the conflict. The dialog will also display the source and destination images..."
instead a dialog with no images preview and no conflict resolving options but one message: "Really continue? destination already exists and will be overwritten : cancel/continue"
Same issue mentioned here: http://ubuntuforums.org/showthread.php?t=1451957

Best regards

Reported by: *anonymous

**Comment by caclark** [comment]
Fixed in commit 2dd2516887b
