### ISSUE TITLE
2.3 release failed to build on macos

### ISSUE THREAD

**Issue by chenrui333** [BestImageViewer/geeqie#1282]
👋 looks like 2.3 release contains[ some linux-only changes](https://github.com/Homebrew/homebrew-core/pull/165346#issuecomment-1983563095) which broke the macos buillds. 

- https://github.com/Homebrew/homebrew-core/pull/165346

**Comment by qarkai** [comment]
@chenrui333 Could you check if #1283 fixes build?

**Comment by chenrui333** [comment]
yeah, totally, let me test out that PR.

**Comment by chenrui333** [comment]
the patch works for me. closing the issue now. Thanks @qarkai!
