### ISSUE TITLE
Stuck on Metadata writing fail

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#129]
If Geeqie fails while writing metadata to some image, can be because of write permissions of image, it gives an error message.
There you're given two options, cancel or continue.
Cancel just cancel the whole write operation, discarding any images it has not yet written to.
Continue functions as a retry. Geeqie retries to write to the failing image again, giving a new error message etc.
There is no way to skip the failing image and continue writing to remaining images.

Reported by: rylleman

**Comment by caclark** [comment]
The changes can be selectively discarded
