### ISSUE TITLE
Doubled path in thumbnail preferences

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#130]
Under Edit &gt; Preferences &gt; Thumbnail maintenance..., the home folder  path is shown doubled (/home/user/home/user/etc.). See: http://www.ubuntu-pics.de/bild/62893/manuten\_\_\_\_o\_do\_cache\_\_\_geeqie\_026\_2Pa2TS.png

Reported by: nijel

**Comment by caclark** [comment]
Fixed in commit acb881988 at geeqie.org
