### ISSUE TITLE
Automatically hide image overlay in fullscreen mode

### ISSUE THREAD

**Issue by andreas-mausch** [BestImageViewer/geeqie#1303]
- Geeqie version [geeqie --version]: Geeqie 2.2 GTK3

Would it be possible to add an option which automatically hides the image overlay in fullscreen mode?

I'd like to (always) see the image overlay in windowed mode, but prefer to not see it in fullscreen mode.

**Comment by andreas-mausch** [comment]
Thank you very much @mowgli, that was super quick.

**Comment by mowgli** [comment]
Am Do den 28. M�r 2024 um 17:57 schrieb Andreas Mausch:
> Thank you very much @mowgli, that was super quick.

The thanks goes to Colin ***@***.***) as he did the fix/commit. I am just
the proxy pushing the commits to github (from the main repository).

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen ***@***.***>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
