### ISSUE TITLE
geeqie --remote options not clear to me

### ISSUE THREAD

**Issue by stephenboston** [BestImageViewer/geeqie#1305]
**Setup (please complete the following information):**
 - Geeqie version [geeqie --version]:
Geeqie 2.2+git20240306-1b4752bb GTK3

**What is your question**
I want a remote command that will open an image in fullscreen at top. Preferably with navigation keys operative so I can browse that directory. 

The full screen options refer to the home screen, as far as I can tell.  

I have tried like this, and various similar configs

     geeqie --remote --fullscreen-start --slideshow-start --delay=24:0:0 --raise file:$1 

I always have to alt-tab to find the window and when I do find it is the home screen. 

I'm missing some magic . I've looked through the man page and have tried many things
for example not using some of them, using `view:` instead of `file:`, various things like that but -- nope.

**Comment by caclark** [comment]
This  rearrangement seems to work for me:

`geeqie --remote  --delay=0:0:2 --file:"$1" --fullscreen-start --slideshow-start`

**Comment by stephenboston** [comment]
Ah so it does! Thank you very much.
