### ISSUE TITLE
Remote --cache-maintenance causes out-of-memory

### ISSUE THREAD

**Issue by caclark** [BestImageViewer/geeqie#1307]
**Setup (please complete the following information):**
 - Distribution: Ubuntu
 - Distribution release: 23:10
 - Geeqie version: All
 
**Describe the bug**

Running `geeqie --cache-maintenance` on a directory of 135, mostly raw, files causes out-of-memory on  a computer with 4GB of memory.

**Comment by qarkai** [comment]
@caclark Could you check on your files after dd16d83?

**Comment by caclark** [comment]
@qarkai 
Thanks.

Fixed in commit dd16d83
