### ISSUE TITLE
Zoom with mouse wheel without Ctl

### ISSUE THREAD

**Issue by stephenboston** [BestImageViewer/geeqie#1309]
**Setup (please complete the following information):**
 - Geeqie version [geeqie --version]:
 -
Geeqie 2.2+git20240306-1b4752bb GTK3

**What is your question**
When in fullscreen, or any view,  I want to use the mouse wheel to zoom in/out without using the Ctl key.  'Next Image' , the current  wheel behavior, is already mouseable by simply clicking on the image.

**Additional context**
Add any other context or screenshots about the question here.

**Comment by caclark** [comment]
Go to `Edit/Preferences/Behavior` and ensure that `Navigation By Left Or Middle Click` is not selected.

Now mouse wheel click should toggle between zoom and next/previous image.

**Comment by stephenboston** [comment]
Ah well look at that. The click trick! Totally missed that. Thanks.
