### ISSUE TITLE
Crash when no privileges to read files

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#131]
When there is a directory with images, where none can be read by Geeqie it crashes, giving error on console:

ERROR:../../src/filecache.c:54:file_cache_get: assertion failed: (fc && fd)
Neúspěšně ukončen (SIGABRT)

Steps to reproduce:

mkdir test
cp SOME_IMAGE test/
chmod 000 test/*
geeqie test/

Reported by: nijel

**Comment by caclark** [comment]
Fixed at some time or other
