### ISSUE TITLE
remove subfolder

### ISSUE THREAD

**Issue by 532910** [BestImageViewer/geeqie#1314]
please add support to remove folders recursively with subfolders

**Comment by caclark** [comment]
You can override the built-in delete function with a plugin.
Go to `Edit/Configure Plugins` and create a new plugin with the name `geeqie-delete-command.desktop`

Edit the contents to include `exec=rm --recursive --force %f`

If you wish, instead create a script that is called from the plugin, and within that script call Zenity or Yad to provide a "Are you sure" message before carrying out the delete action.

[Other common actions can also be overridden - see https://www.geeqie.org/help/GuidePluginsConfig.html]
