### ISSUE TITLE
window opens, closes, reopens when geeqie is launched

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#132]
When the Windows -&gt; Fit Window To Image option is enabled, starting geeqie by double-clicking an image file causes geeqie's main window to appear, disappear, and finally reappear with the image displayed.

I'm using version 1.0 beta2 as packaged in Ubuntu Lucid.

Reported by: forest

**Comment by caclark** [comment]
Seems to have been fixed at some time or other.
