### ISSUE TITLE
"Copy path" problem (or may be feature)

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#137]
in the GDK there are 3 "clipboards"
GDK_SELECTION_PRIMARY
GDK_SELECTION_SECONDARY
GDK_SELECTION_CLIPBOARD

to paste contents of PRIMARY, user need to do middle-click
to paste contents of CLIPBOARD, user need to do Ctrl-V or Shift-Insert or right-click-&gt;Paste or menu Edit -&gt;Paste

i think that at the present the most used/known/common way is the second
but on "Copy path", the Geeqie uses PRIMARY and, imho, this seems unexpected that i have copied, but can not paste it in a "common way"

so i suggest
sed -i -e's/GDK_SELECTION_PRIMARY/GDK_SELECTION_CLIPBOARD/' ./src/utilops.c

Reported by: *anonymous

**Comment by archenemies** [comment]
I agree that this should be fixed. Maybe for backwards compatibility (people who expect PRIMARY) it would make sense to copy to both PRIMARY and CLIPBOARD. But if it says "copy" it should definitely copy to CLIPBOARD.

**Comment by Beep6581** [comment]
7 years to run a sed command which changes two lines of code, that's quite impressive ;)

I'm adding my +1 for CLIPBOARD.

```diff
diff --git a/src/utilops.c b/src/utilops.c
index 0bc9d0db..230dcf76 100644
--- a/src/utilops.c
+++ b/src/utilops.c
@@ -3038,7 +3038,7 @@ void file_util_copy_path_to_clipboard(FileData *fd)
 
 	if (!fd || !*fd->path) return;
 
-	clipboard = gtk_clipboard_get(GDK_SELECTION_PRIMARY);
+	clipboard = gtk_clipboard_get(GDK_SELECTION_CLIPBOARD);
 	gtk_clipboard_set_text(clipboard, g_shell_quote(fd->path), -1);
 }
 
@@ -3048,7 +3048,7 @@ void file_util_copy_path_list_to_clipboard(GList *list)
 	GList *work;
 	GString *new;
 
-	clipboard = gtk_clipboard_get(GDK_SELECTION_PRIMARY);
+	clipboard = gtk_clipboard_get(GDK_SELECTION_CLIPBOARD);
 
 	new = g_string_new("");
 	work = list;
```

**Comment by caclark** [comment]
Fixed in commit ea5503b10 at geeqie.org

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am Sa den  4. Nov 2017 um 14:04 schrieb Beep6581:
> 7 years to run a sed command which changes two lines of code, that's quite impressive ;)
> 
> I'm adding my +1 for CLIPBOARD.

I do not think, that this is a good solution.

I never ever use that ctrl-v-windows-keycrap stuff (sorry, I have no
other words for it). I always use middle mouse button to paste to other
tools. Don't mention that in xterm this is the only way to go as ctr-v
does not work there.

So, your solution breaks this stuff. It is not posible anymore to paste
image links to xterm.

If you want to have that in another clipboard, please make it
configurable.

I reverted that commit as it break to much usecases.

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAln+IdEACgkQpnwKsYAZ
9qzxcQwAvPCRdCUFO+S3dQYsLRqPw3wiin5cS+V9Gb+mGv6fcZS7zy1HR2L/dsfS
PFj2qZl71lweLcFifcoI/kYSDCTQI/qOzs6u29IeEBYcDK6XqcVecpVVt8ak6mN6
5VEu29ZGxER89GTEtiL6y7rTMtIpFJdxvzre/K44VeCbl+aKWM7/NVTNM5swFp+z
rQAjTlyRRKajfARrR2Lvo4I2n1nCxcX2b0qDoKHODr9CgRnNhGaxvefgyT9LRILf
8u0gRroZEKclxlS2hpJr7bobUVFhCwtQnCv2ehaGUetave4U2E2n41Mpj7KxrEX0
keixOhamFzFTQXpgKHhd/Jc+q18do/u+6hnoX/0u0XtD6q4AEzBzons1W2/fHMv8
owzrTug2iFFzE1zTp/Kcxy9TaCvtWApr9JtXJ4Po55pEBb4RZsmS2LJ5JqaAnJCW
z7ymaTmZOH+GwBCp1pEjdBD+Uedwa4+tD90flEyLVJWlaUUtnpsnsoSgVVrOshku
UcqshFch
=Akb2
-----END PGP SIGNATURE-----

**Comment by mowgli** [comment]
Let me add that I use that method quite often and to break it this way makes a important part of geeqie unusable for me.

I understand that this might be implemented with a way to choose but just replace a method (middle mouse button) that work everywhere with something (ctrl-v) that only work in some editors like word, is not the way to "fix" it.

**Comment by archenemies** [comment]
You can use ctrl-meta-c and ctrl-meta-v to copy and paste in urxvt. It's much easier to type than "shift-insert", which pastes the selection. Also when you select something, the clipboard isn't wiped out. Unlike PRIMARY. So I always prefer to use the clipboard. It may resemble Windows or Mac OS but let's face it, the designers of X just made a bad decision. Selecting should be separate from copying, and pasting shouldn't require the mouse or weird keystrokes.

Try putting `XTerm*selectToClipboard: true` in .Xdefaults. If you still want to use xterm.

**Comment by Beep6581** [comment]
> I never ever use that ctrl-v-windows-keycrap stuff (sorry, I have no
other words for it). I always use middle mouse button to paste to other
tools. Don't mention that in xterm this is the only way to go as ctr-v
does not work there.

I politely disagree and object to the "crap" reference.

It's 2017, there are standards, and most applications follow them, including xterm. I don't think Geeqie's target audience are only xterm users who refuse to set `XTerm*selectToClipboard: true` for some emotional reason (first result on google and duckduckgo).

Well explained here:
https://www.starnet.com/xwin32kb/copying-and-pasting-in-xterm/

Example of why PRIMARY is a bad choice:
Right-click on a thumb, copy path. Alt+tab to a web browser or file browser. Ctrl+L to focus the address field, paste. Fail, because pressing Ctrl+L selects the current path, so you can no longer paste the path from Geeqie if it uses PRIMARY.

Furthermore, I don't think Geeqie's "Copy path" should wrap the path in quotes. The command is called "Copy path", not "copy path and wrap it in quotes which only terminals handle, not file managers and not web browsers".

I think @archenemies proposed solution is ideal: copying a path will copy it to both PRIMARY and CLIPBOARD, and since it's clear that PRIMARY is used heavily by terminal users such as @mowgli , then the path in PRIMARY can be wrapped in quotes while the path in CLIPBOARD should not.

**Comment by mowgli** [comment]
archenemies, Just as the normal way of using middle mouse button does not fit your needs, doesn't mean they did a bad decision. I feel that it was a good and even the best decision that X designers could have done. And your "solution" für xterm would break many other use cases I use in my daily work. It would also not work for middle button (... to work in any application)

beep: Well it is your standard. Don't try to force your standard to everyone.

I do not object that there are other use cases around, Just don't break a standard usecase by only applying your needs. The current way of geeqie using PRIMARY fits the use case of many people (me included). Your patch did just destroy that.

Why not making that configurable and keeping the current way as default? That would be the clean way.

To your use cases:
The browser one is false. If you focus the address field, the selection is _not_ copied in tha PRIMARY buffer. (My oppinion about that select by single click or activate is bad think in current browsers. But that is another thing)

If you don't like that it is wrapped in quotes, how would you disting path with spaces?

That feature is original to use on command line. And there you usually paste with middle mouse button and you surelly want to have that stuff quoted as otherwise you open up for security implications. (And yes, if you only paste one name, you can manually quote them. With many files it is not practicable.)

The solution with both buffers would be a short term solution. I would prefer, if you want to change that, please come up with an configurable solution.

**Comment by caclark** [comment]
Attached is a diff that is a possible solution to the clipboard section of this issue - an additional option on Preferences/Behavior.

(At the moment I'm in a hotel, between flights, totally **** with airport
 security problems, and the laptop I'm using seems to have lost all write access to the repo. If someone wants to convert the diff to a pull request or whatever, that would be useful)

[clipboard.gz](https://github.com/BestImageViewer/geeqie/files/1447756/clipboard.gz)

**Comment by caclark** [comment]
Maybe fixed in commit 051b52178e at geeqie.org

**Comment by archenemies** [comment]
I still wonder if it wouldn't have been better to copy to *both* PRIMARY and CLIPBOARD by default. It took me a good while to find that Preferences option, I had to read through this whole bug report to even jog my memory that it exists... Anyway, thanks for improving my own user experience. I'm just a little skeptical that new users will figure out how to benefit :)

**Comment by caclark** [comment]
So possibly it would be best to add a third option - "Both clipboards". Current users will have whichever clipboard is already stored in geeqierc.xml.
For new users it will default to "Both".

**Comment by archenemies** [comment]
@caclark Yes, I think that would be great... If it is not below the threshold of importance for this project...

**Comment by caclark** [comment]
There is a commit to copy to both clipboards:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=23d54a6fa903a9522062e266a139b94e4f4b26d7

>  It took me a good while to find that Preferences option,

There is a menu option for on-line Help search. Unfortunately the on-line help files are a little out of date, but nevertheless can sometimes be useful. More work....

**Comment by archenemies** [comment]
Thank you that looks good.

It may just be a matter of taste, but instead of this

    if (options->clipboard_selection == CLIPBOARD_PRIMARY)
                   {
                   gtk_clipboard_set_text(gtk_clipboard_get(GDK_SELECTION_PRIMARY), quoted ? g_shell_quote(fd->path) :  fd->path , -1);
                   }
    else if (options->clipboard_selection == CLIPBOARD_CLIPBOARD)
               {
               gtk_clipboard_set_text(gtk_clipboard_get(GDK_SELECTION_PRIMARY), quoted ? g_shell_quote(fd->path) :  fd->path , -1);
               }
    else {...}
  
I would do something more concise:

    int sel = options->clipboard_selection;
    char *str = quoted ? g_shell_quote(fd->path) :  fd->path;
    if (sel == CLIPBOARD_PRIMARY || sel == CLIPBOARD_BOTH)
        gtk_clipboard_set_text(gtk_clipboard_get(GDK_SELECTION_PRIMARY), str, -1);
    if (sel == CLIPBOARD_CLIPBOARD || sel == CLIPBOARD_BOTH)
        gtk_clipboard_set_text(gtk_clipboard_get(GDK_SELECTION_CLIPBOARD), str, -1);

**Comment by tomaszg7** [comment]
Probably even more elegant solution would be to store separate bits to store selected clipboard by giving values of 1, 2 and 3. Then you could just do
```
if (sel & CLIPBOARD_PRIMARY) ...
if (sel & CLIPBOARD_CLIPBOARD) ...
```
