### ISSUE TITLE
[ and ] settings are applied to all following pictures

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#140]
In geeqie 1.0, when using the [ and ] key bindings for rotating the view of the current image, the according setting will be applied also to all *following* images. Although geeeqie seems to be aware which images were rotated (because it offers to write according metadata at the end of a session), it nevertheless displays the following, unaffected images with an incorrect rotation (i.e. as if they had been rotated as well). I am not sure whether this behavior, which differs from gqview's, is intentional, but it is annoying in the following workflow:

I would like to use geeqie to correct the orientation of all images in a directory. I would like to do so not merely by changing the EXIF orientation, but by actually rotating the pixel data and then resetting the EXIF orientation to 1. Because "physical" rotation of a single image takes quite a while, I would like to first correct the rotation of all images merely by view (i.e. use the [ and ] keys until they all display correctly), and eventually perform the "physical" rotation according to that view. However, this is only possible if the [ and ] keys are applied not globally but individually (per image).

If the display rotation was applied individually for each image, I could use [ and ] until all images display with the correct rotation, then write the according information to the EXIF orientation field at the end of the session (using the awesome tool which geeqie provides for this purpose) and eventually use "jhead -autorot" to perform the "physical" rotation and EXIF orientation reset. Right now this is impossible, because the [ and ] keys affect displayed rotation of images which I do not want to rotate at all.

Reported by: *anonymous

**Comment by hurzl** [comment]
If I select multiple images and do "[" the rotation is not applied to all following but only to the last image of my selection. It should be applied to all selected images.

**Comment by caclark** [comment]
Commit fa4df089 (at both geeqie.org and at github) is relevant to this.

**Comment by caclark** [comment]
I assume this is considered fixed
