### ISSUE TITLE
Huge Image Display Issue #772 happenes again

### ISSUE THREAD

**Issue by terrancewong** [BestImageViewer/geeqie#1400]
**Setup (please complete the following information):**
 - Distribution: Debian
 - Distribution release: testing+unstable
 - Geeqie version: Geeqie 2.4 GTK3

**Describe the bug**
see #772

**Screenshots**
![image](https://github.com/BestImageViewer/geeqie/assets/44456699/5a1ab308-ea6f-442b-961c-aa6a2bc0211b)

**Image sources**
It is too huge to upload. please generate or resize some image with width > 32767 to test.

**Comment by caclark** [comment]
Do you see the effect with this image?
https://upload.wikimedia.org/wikipedia/commons/8/86/Alongtheriver_QingMing.jpg

**Comment by terrancewong** [comment]
Negative. This one is fine.

Same image, in jpg, it's fine. in 16-bit tiff or 8-bit tiff, it's bad.
