### ISSUE TITLE
Where can I download a Geeqie Appimage 2.4 for Xubuntu

### ISSUE THREAD

**Issue by ralphldcm** [BestImageViewer/geeqie#1404]
**Setup (please complete the following information):**
 - Geeqie 2.4

**What is your question**
Where can I download a Geeqie Appimage 2.4 for Xubuntu

**Additional context**
Add any other context or screenshots about the question here.

**Comment by caclark** [comment]
The AppImages are under Releases/Continuous Build. They are automatically created each time the source code is updated, therefore they are v2.4 + latest changes. There is no AppImage for the point at which v2.4 was released.

https://github.com/BestImageViewer/geeqie/releases/tag/continuous
