### ISSUE TITLE
program crash if rename a file

### ISSUE THREAD

**Issue by BalazsNyiro** [BestImageViewer/geeqie#1406]
**Setup (please complete the following information):**
 - Distribution: Ubuntu
 - Distribution release: 24.04
 - Geeqie version [geeqie --version]: Geeqie 2.2 GTK3

**Describe the bug**
in the left file browser if you press right-click and Rename, you can type the new filename - but when you press Enter, the file is NOT renamed and Geeqie crashes

**To reproduce**
open Geeqie in a folder with lot of images
in the left file browser menu right click on an image name -> Rename
type a new name into the text field
press ENTER
Crash is the next 

**Expected behavior**
rename the file WITHOUT a crash

**Screenshots**
![err_rename_CRASH](https://github.com/BestImageViewer/geeqie/assets/1611185/ff61d9e4-4dad-4c7f-876e-872ea425a934)
hots to help explain your problem.

**Image sources**
If applicable, upload image files causing the bug. (Use gzip)

**Error logs or seg. fault files**
in the terminal I see these errors:

b@go1 ~ $ geeqie .

(geeqie:48184): GdkPixbuf-CRITICAL **: 10:51:26.569: gdk_pixbuf_composite: assertion 'dest_x >= 0 && dest_x + dest_width <= dest->width' failed

(geeqie:48184): GLib-GObject-CRITICAL **: 10:51:36.130: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed

(geeqie:48184): GLib-GObject-CRITICAL **: 10:51:36.130: instance with invalid (NULL) class pointer

(geeqie:48184): GLib-GObject-CRITICAL **: 10:51:36.130: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(geeqie:48184): GLib-GObject-CRITICAL **: 10:51:36.130: instance with invalid (NULL) class pointer

(geeqie:48184): GLib-GObject-CRITICAL **: 10:51:36.130: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Geeqie fatal error
Signal: Invalid memory reference
Code: Address not mapped
Address: 0x0000000000000030
geeqie(+0xe0c58)[0x647afb880c58]
/lib/x86_64-linux-gnu/libc.so.6(+0x45320)[0x70eb4c245320]
/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_unref+0x29a)[0x70eb4d94761a]
/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2033da)[0x70eb4e0033da]
/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main_do_event+0xa3a)[0x70eb4e003eaa]
/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x3a407)[0x70eb4dd3f407]
/lib/x86_64-linux-gnu/libgdk-3.so.0(+0x93c6e)[0x70eb4dd98c6e]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x5d5b5)[0x70eb4d8375b5]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xbc717)[0x70eb4d896717]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_loop_run+0x127)[0x70eb4d837f77]
/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_main+0x85)[0x70eb4dffeb45]
geeqie(+0x785de)[0x647afb8185de]
/lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca)[0x70eb4c22a1ca]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b)[0x70eb4c22a28b]
geeqie(+0x7a555)[0x647afb81a555]
b@go1 ~ $ 

**Additional context**

**Comment by caclark** [comment]
This was fixed in commit fef4012de7 (2024-02-07)

**Comment by BalazsNyiro** [comment]
Thank you.
