### ISSUE TITLE
Unused functions

### ISSUE THREAD

**Issue by qarkai** [BestImageViewer/geeqie#1407]
There are a lot of `*_unused` functions. Total count of `#pragma GCC diagnostic ignored "-Wunused-function"` is 62, some cover more than one function.
What are these for? Can they be removed? I'd prepare PR.

**Comment by caclark** [comment]
I am the kind of person who never throws anything away....

In some cases I thought there was a possibility that the function might have a use in the future, and that it would save someone effort in recreating the function.

Either way I am not concerned. If standard practice is to delete all unused code, then that is OK by me.
