### ISSUE TITLE
External commands wont function for read only media

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#141]
If I right click a file from a read only NFS share and chose to edit with any editor I get the message

"This operation cannot continue:

destination directory is not writable"

Geeqie should not refuse to continue if the file is sitting in a read only location. That should be up to the handler program, which was the GIMP in my case. I was able to open the file from GIMP's file dialog and Save As when I was done, so there certainly wasn't any need to prevent the operation. I would say that most handler programs won't care if the source directory is writable and this is not something that should be handled by geeqie.

The only option is "cancel" which brings up the "Editor" dialog with a prompt asking "Run editor?" but the note below says "This will copy the following files" and lists my file. Somehow, perhaps, it thinks "run the gimp" means "copy"? I don't know.

Geeqie version 1.0 (specifically debian package version 1:1.0-7)
Debian, mixed testing/sid, Enlightenment, other details by request.

Reported by: *anonymous

**Comment by nijel** [comment]
See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=625637

**Comment by xi2** [comment]
It appears that in the latest version of Geeqie this is fixed.

With version 1.0 I get "operation can't continue", as per the bug report.

With latest Geeqie I get "Really continue?". I select Continue and then all is well. Tested with ImageMagick.

**Comment by caclark** [comment]
Fixed in commit f4245483e5
