### ISSUE TITLE
Create an RAII `FileDataRef` object.

### ISSUE THREAD

**Issue by xsdg** [BestImageViewer/geeqie#1415]
[See here](https://stackoverflow.com/questions/2321511/what-is-meant-by-resource-acquisition-is-initialization-raii) for a quick explanation of RAII.

In short, this would make it easy to `::file_data_ref` an `fd` for the scope of a particular function, and to guarantee that `::file_data_unref` is called on the `fd` when the function is exited, without requiring a separate `::file_data_unref` call to be added to every potential exit point.

This works by creating a locally-scoped object that calls `::file_data_ref` in its constructor (so when the object is created, `::file_data_ref` is called), and then `::file_data_unref` in its destructor (so when the object is destroyed, `::file_data_unref` is called).  Because the object is declared on the stack, it will be created by the compiler IFF that line of code is run, and it will be destroyed IFF it goes out of scope.

**Comment by qarkai** [comment]
BTW GLib has macros for automatic cleanup of variables when they go out of scope https://docs.gtk.org/glib/auto-cleanup.html
These macros has limitations on compilers but already used in code, see 
```c++
g_autoptr(GFileEnumerator) enumerator = nullptr;
```
in https://github.com/BestImageViewer/geeqie/blob/master/src/ui-fileops.cc#L1107
`g_autofree` seems to me more convenient than `std::unique_ptr`, e.g.
```cpp
std::unique_ptr<gchar, decltype(&g_free)> file_name_watcher{g_strdup(file_name), g_free};
```
would be
```c++
g_autofree gchar *file_name_watcher = g_strdup(file_name);
```

@caclark @xsdg 
What do you think about using automatic cleanup macros more widely?

**Comment by qarkai** [comment]
> Does the default compiler on all systems that Geeqie is likely to be compiled on support these macros?

Since there were no complains about `g_autoptr(GFileEnumerator)` for over 3 years I guess it does.

> The `count1` example is the way I would have written the code....

Compiler generate warning if `g_autofree`/`g_autoptr` is not initialized. Also C++ recommends to not declare a variable until you have a value to initialize it with. And there are no `goto`s now.

> Is there any possibility that implementing changes (either individually or by bulk grep) to use these macros will result in a system that compiles and runs, but will fail when a user executes a particular sequence of commands?

`g_auto*` macros are used in GLib's internal code so I guess it's pretty safe to use them. Although bulk grep doesn't seem like good idea.

> Also note that there may be cases where the current code is wrong, but works by chance, and programmatically modifying the code may result in a system that is syntactically correct but does not run.

It would be great if these changes could help finding errors.
