### ISSUE TITLE
Wrong display selection for full-screen mode in dual-head

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#142]
In dual-head configuration geeqie in fullscreen mode ('f' key) use wrong display (in my case it always second head) and display image 'not fullscreen' (some of surrounding black area have non-filled area). I use two monitors with different resolution, and 'second head' is 1920x1050, first is 1680x1050; when geeqie draw black area on second head it is about 1680x1050 (like first head) not 1920x1080 (like second one). 

My X configuration:

Section "ServerLayout"
Identifier     "Default Layout"
Screen         0 "Samsung 215tw" 0 0
InputDevice    "Generic Keyboard"
InputDevice    "Configured Mouse"
EndSection

Section "InputDevice"
Identifier     "Generic Keyboard"
Driver         "kbd"
Option         "CoreKeyboard"
Option         "XkbRules" "xorg"
Option         "XkbModel" "pc104"
Option         "XkbLayout" "us"
EndSection

Section "InputDevice"
Identifier     "Configured Mouse"
Driver         "mouse"
Option         "CorePointer"
Option         "Device" "/dev/input/mice"
Option         "Protocol" "ImPS/2"
Option         "Emulate3Buttons" "true"
EndSection

Section "Monitor"
Identifier     "Samsung 215tw"
EndSection

Section "Device"
Identifier     "GeForce First Head"
Driver         "nvidia"
BusID          "PCI:1:0:0"
EndSection

Section "Screen"
Identifier     "Samsung 215tw"
Device         "GeForce First Head"
Monitor        "Samsung 215tw"
Option         "TwinView"
Option         "MetaModes" "1680x1050, 1920x1080"
Option         "TwinViewOrientation" "RightOf"
Option         "RandRRotation"
EndSection

This brokeness might be related to upgrade of some library or xserver as it did not happen before.

Debian bug report for this: http://bugs.debian.org/593839

Reported by: nijel

**Comment by caclark** [comment]
Fault not reproducible
