### ISSUE TITLE
make image overlay configurable

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#143]
Hello, 

I use image overlay much because i am semi professional and need for work. Can you allow overly configure ? Like, choose from the EXIF window (crosses).
For example i dont need see my digital camera i have only one. I would see 35mm focal and white balancce. How can i configure ?

EXIF window is not help because it is too much for page and i must scroll and does not work in fullscreen.

greetings yuseph

Reported by: yuseph

**Comment by vsiegel** [comment]
An useful configuration would be the overlay font; (Font,font size, backround width, background color)

Use cases can be very different - imagine a presentation where essential metadata is show as overlay,  
and another, where the overlay contains guiding hints for the speaker, looking closely.

**Comment by caclark** [comment]
On 12/05/16 19:14, vsiegel wrote:
>
> An useful configuration would be the overlay font; (Font,font size, 
> backround width, background color)
>
> Use cases can be very different - imagine a presentation where 
> essential metadata is show as overlay,
>
> and another, where the overlay contains guiding hints for the speaker, 
> looking closely.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/BestImageViewer/geeqie/issues/143#issuecomment-218840666>
>
The latest commit in the repository gives you the option to set the font.

The font button is at the bottom of the Preferences/Windows tab.

Maybe configurable font colour and background colour will arrive in a 
couple of weeks.


Colin Clark

**Comment by caclark** [comment]
Fixed in commits 215bb15c and 8b7898a
