### ISSUE TITLE
Problem with copy to NFS mounted FS

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#144]
When I try to copy one file to an NFS mounted folder I got a message "External editor returned error status Copy failed" but the file is copied.
When I try to copy multiple files the same message but with "Continue multiple operation?" question. Even if I click  "Continue" only the first image is copied.
For any other folder copy works like expected.

Reported by: artiom

**Comment by caclark** [comment]
Fixed in commit 138e31f
