### ISSUE TITLE
Rotate don't rotate the thumbnail

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#145]
When I rotate an image its thumbnail didn't rotate.

Reported by: artiom

**Comment by caclark** [comment]
If an image file (e.g jpeg) is rotated, the thumbnail is also rotated.
If a RAW file is auto-rotated via its exif setting, then the thumbnail is not rotated.
Maybe the question is, should the thumbnail also be auto-rotated in line with the exif value.

**Comment by caclark** [comment]
If a jpeg image file is rotated, the thumbnail is also rotated.
If an image has orientation set via exif, the generated thumbnail also respects that orientation - as specified in Thumbnail Managing Standard
