### ISSUE TITLE
Plugin .desktop shortcuts on toolbars don't work as expected

### ISSUE THREAD

**Issue by gusnan** [BestImageViewer/geeqie#1450]
**Setup (please complete the following information):**
 - Distribution: Debian
 - Distribution release: stable and unstable
 - Geeqie version: 2.4+git20240730-136d1ab6 (latest git)

**Describe the bug**
Adding a plugin to the toolbar doesn't show it's icon in the toolbar, but just the desktop filename (in my case with ristretto, it shows the button without any icon, and just the desktop filename org.xfce.ristretto.desktop). Also, nothing happens when trying to start the plugin from the toolbar, but it shows

```
(geeqie:34564): Gtk-CRITICAL **: 15:45:43.893: gtk_action_activate: assertion 'GTK_IS_ACTION (action)' failed
```

in the terminal running geeqie.

**To reproduce**
Simply add a custom plugin, and it acts just fine in the plugins menu and in the menu when right-clicking an image, but not in the toolbar.

**Expected behavior**
Showing icon, and reacting properly on clicking the toolbar button.

**Additional context**
Doing a git bisect, if I've done it properly it seems like the commit

f1c1ccb94e55253651cc2219ec8d63130d90203d

is the cause of the problem, and it seems related, so it seems worth investigating.

Reported on the debian bugtracker, here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1076665

**Comment by caclark** [comment]
@gusnan 

Thanks for the bisect.

That is the problem - not so easy to fix.

**Comment by gusnan** [comment]
> @gusnan
> 
> Thanks for the bisect.
> 
> That is the problem - not so easy to fix.

Yeah, as mentioned in the debian bug report, I understand that the changes in the commit is due to the migration to newer GTK which removes the toolbar - so, as you say, I see that it's not easy to fix.

**Comment by gusnan** [comment]
@miiichael - yeah, info from https://docs.gtk.org/gtk4/migrating-3to4.html

>GtkToolbar has been removed
>
>Toolbars were using outdated concepts such as requiring special toolitem widgets. Toolbars should be replaced by using a GtkBox with regular widgets instead and the “toolbar” style class.[/quote]
