### ISSUE TITLE
Toolbar looks fixed, but actions don't work before opening preferences once

### ISSUE THREAD

**Issue by gusnan** [BestImageViewer/geeqie#1462]
**Setup (please complete the following information):**
 - Distribution: Debian
 - Distribution release: stable
 - Geeqie version [geeqie --version]: latest git

**Describe the bug**
The fix for the bug #1450 seems to have fixed the looks of the buttons and part of the behavior, many thanks for that - BUT, now that it works I have discovered that it doesn't work correctly until I go to preferences (I don'ẗ even need to go to the toolbar preferences tab, just open the preferences window) and press OK to apply them before it works properly. Before I do this, pressing a plugin toolbar button just gives 

```
(geeqie:74135): Gtk-CRITICAL **: 18:32:37.349: gtk_action_activate: assertion 'GTK_IS_ACTION (action)' failed
```

in a terminal, but no action. After going to the preferences, pressing OK to apply them, the toolbar plugin button works just fine. Doing some research it looks like the function `config_window_apply()` in preferences.cc calls `toolbar_apply(TOOLBAR_MAIN)`, which isn't called before this, this might be related. This might be a config thing specific to my setup, but I kind of doubt it.

**To reproduce**
See above ^.

**Expected behavior**
Toolbar plugin buttons working without having to go to preferences first to make it work.

**Comment by gusnan** [comment]
And to make things clearer, the problem seems to be only for plugin buttons.

**Comment by caclark** [comment]
@gusnan 
Thanks. I see the problem, but did not yet find a solution.

**Comment by gusnan** [comment]
Excellent! Thank you so much - I will test the fix ASAP.

**Comment by gusnan** [comment]
And it works for me. Again, thank you very much!
