### ISSUE TITLE
Honor the .hidden file

### ISSUE THREAD

**Issue by ssokolow** [BestImageViewer/geeqie#1469]
**Setup (please complete the following information):**
 - Geeqie version [geeqie --version]: Geeqie 2.4 GTK3

**Describe your feature request**
Major file managers like Nautilus, Dolphin, etc. have a mechanism for letting users hide files or folders without renaming them and it'd be nice if Geeqie would also honor it.

The mechanism is simply that, if the folder contains a file named `.hidden`, it will be opened and parsed as a newline-delimited list of files to be treated as if their names began with a dot.

(It's useful for things like hiding the `Network Trash Folder`, `TheFindByContentFolder`, and `TheVolumeSettingsFolder` folders that get created in the root of network shares served up to vintage macs via Netatalk. The macs don't show them because they set the HFS Invisible flag, which is equivalent to the FAT/NTFS Hidden attribute... but nothing I'm aware of parses and honors Netatalk's means of storing HFS flags on non-mac filesystems. I'm not even sure how API-stable they consider it.)

**Additional context**

![Screenshot_20240808_222440](https://github.com/user-attachments/assets/561eaf16-4f83-4150-8563-88227d85d78f)

**Comment by caclark** [comment]
Implemented in commit 13dfe578e54773b5b367ff021a6a42f8513744ea

**Comment by ssokolow** [comment]
Wow. Thanks for the fast fix. :)
