### ISSUE TITLE
Feature Request: fit large image to desktop

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#148]
Years ago when I used Windows, I had an excellent image viewer/photo manager called ACDSee.  One of the best features of this viewer was "fit large images to desktop."  This allows smaller images to be viewed at actual size, and any images larger than the desktop are scaled to fit.  This is extremely useful when viewing mixed collections of images with widely differing resolutions.  Please add "Fit large images to desktop" as an option.

Reported by: sribarence

**Comment by caclark** [comment]
Implemented
