### ISSUE TITLE
Don't auto select images when app was started with files on CLI

### ISSUE THREAD

**Issue by smyru** [BestImageViewer/geeqie#1484]
**Setup:**
 - Distribution: FreeBSD
 - Distribution release: 13.3
 - Geeqie version: Geeqie 2.4 GTK3

**Describe the bug**
When geeqie is started from command line with a wide selection of images, all images are auto selected after startup. Even as one browses through them with PageUp or PageDown, still all images are focused in the file view. Now when using Delete action ie. via Shift+Delete, all selected files will be deleted. The confirmation dialog does not look much different from a single file deletion, as only one image preview will be shown. 

**To reproduce**
1. Start geeqie from command line in a folder full of images, ie.: `$ geeqie *.jpg`
2. Note that all JPEG images are selected in the file list
3. Browse through them
4. Hit Shift+Delete to delete seemingly the image you are viewing.

**Expected behavior**
Do not auto select all images from CLI arguments. When viewing images the action shall affect only the image being viewed.

**Comment by caclark** [comment]
There are some usability problems that will take a while to resolve.

I suggest the following as an immediate workaround:

Go to `Edit/Preferences/Windows` and select `Remember Dialog Window Positions`.
Open a `Delete` dialog and resize the window downwards. The left-hand pane will then clearly show when multiple files have been selected. Press `Cancel`. The window size will be remembered.

When deleting a single file, do not use a keyboard shortcut but instead right-click on the image pane and select `Delete`. The single image being viewed will then be the only one selected for deletion.

**Comment by smyru** [comment]
I just got a one of those "never forget lessons" as I have deleted all of vacation photos this way (I have got a backup though). So I will remember to be cautious since now on. Just making sure, others won't be affected as much :-)

**Comment by caclark** [comment]
I do not think that deselecting the files is a good idea.

There is now a commit that provides the following:
    - Where appropriate, change the menu text from "Delete" to "Delete  selected"
    - If multiple files are selected for deletion, include the file total  and a warning icon in the dialog message

The warning icon is necessarily in the same font as the rest of the text, which makes it rather small.

If you feel it is appropriate, please reopen this Issue.
