### ISSUE TITLE
Drag'n'drop functions with Mozilla apps

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#149]
I run Geeqie on Ubuntu 10.04. D'n'd function acts as follow:
- I can drag image from Geeqie to some folder in Nautils, it seems to work fine
- I can drag image from Geeqie to new letter in Mozilla Thunderbird, thumbnails appear in letter window, but no files are sent when I send letters.
- I can drag images from Geeqie to" upload" field  in Mozilla Firefox (with draganddrop extension installed), but no path appears in that field.

Offtopic: I'd like to help with Russian translation, what should I do? Do you have any online translation like one on launchpad? Or should I use something like QT Linguist?

Reported by: subeditor

**Comment by caclark** [comment]
DnD works ok
