### ISSUE TITLE
Add support of FITS file format

### ISSUE THREAD

**Issue by vladtcvs** [BestImageViewer/geeqie#1499]
**Setup (please complete the following information):**
 - Geeqie version [geeqie --version]: Geeqie 2.4 GTK3

**Describe your feature request**
FITS file format is often used in astrophotography and other scientific cases, and adding support to view FITS format would be great

**Comment by vladtcvs** [comment]
Example image
[M_92_Light_R_001.fits.gz](https://github.com/user-attachments/files/17693010/M_92_Light_R_001.fits.gz)

**Comment by caclark** [comment]
@vladtcvs 
I have created some code to display .fits files - 2D only.

The intensity range for a pixbuf is 0 to 255.
The range in your sample image is 0 to 450, with most of the data below 40.00

After the rescaling is made to show in a pixbuf, the image is just black.

How does other software cope with this extended range?
I see that QFitsView has a log scale option.

**Comment by vladtcvs** [comment]
kstars has viewer of FITS, it stretches values that lowest value is a black and highest - is a white.
![image](https://github.com/user-attachments/assets/9d879998-fbe0-478f-acf9-c45b8ead1537)

**Comment by vladtcvs** [comment]
Also there is tool called `fv`, it does the same

**Comment by vladtcvs** [comment]
> I see that QFitsView has a log scale option.

Yes, software which works with FITS usually have possibility to adjust gamma

**Comment by caclark** [comment]
@vladtcvs 

I doubt that this is adequate.

Please re-open this issue if you have comments.

[If you do not wish to compile from sources, the AppImages let you make a quick check]
