### ISSUE TITLE
compile issues

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#150]
make[1]: Entering directory `/usr/src/sourceforge/geeqie/trunk'
cd . && autoheader
make[1]: Leaving directory `/usr/src/sourceforge/geeqie/trunk'
cd . \
&& CONFIG_FILES= CONFIG_HEADERS=[config.h] \
/bin/sh ./config.status
config.status: error: cannot find input file: `[config.h].in'
make: *** [stamp-h] Error 1

I geuss this happens with newer autools. Can be fixed trivially, see attached patch 

Reported by: seegras

**Comment by mowgli** [comment]
@seegras, I think we can close this, right?

**Comment by Seegras** [comment]
Would guess, please close
