### ISSUE TITLE
Random image plugin hidden

### ISSUE THREAD

**Issue by mdpenguin** [BestImageViewer/geeqie#1503]
**Setup (please complete the following information):**
 - Distribution: Linux Mint
 - Distribution release: 22
 - Geeqie version [geeqie --version]: Geeqie 2.4+git20240829-39e929b2 GTK3

**Describe the bug**
The Random Image plugin is flagged as hidden

**To reproduce**
1. Browse to Edit > Configure Plugins
2. Note that `Random image` plugin is flagged as hidden

**Expected behavior**
Plugin should not be hidden and should be available to use

**Screenshots**
![image](https://github.com/user-attachments/assets/156c2e76-a5fc-4ef7-b37b-9f29056456be)

**Image sources**
N/A

**Error logs or seg. fault files**
N/A

**Additional context**
Confirmed issue occurs both in build using geeqie-install-debian.sh and also in AppImage

**Comment by caclark** [comment]
Immediate fix:
Edit `/usr/local/share/geeqie/applications/org.geeqie.random-image.desktop`
and change
`Categories=Graphics;`
to
`Categories=X-Geeqie;`
