### ISSUE TITLE
"Zoom to fit" toolbar icon doesn't work

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#151]
Hi there,

Just upgraded from Ubuntu 9.04 to 10.10, and noticed that GQview is now replaced by Geeqi (version 1.0). In GQview I set the preferences so taht all images are automatically shrunk or enlarged to fit the window.  But in Geeqi this option doesn't work. When I clik un the toolbar on the "Zomm to fit" icon, nothing happens at all. If I try to set it in the preferences dialog, where it is called "Fit image to window", it doesn't work either.

I hope you can fix it, in the meantime I will have to comile GQview on Ubuntu 10.10, to keep me going.

Thanks for this fork BTW, it's great to see life into GQview again, well, Geeqi now ! ;-)

Reported by: vincent77

**Comment by caclark** [comment]
Somewhere, sometime, this has been fixed.
