### ISSUE TITLE
Exif window is empty

### ISSUE THREAD

**Issue by philippludwig** [BestImageViewer/geeqie#1511]
**Setup (please complete the following information):**
 - Distribution: OpenSuse Tumbleweed
 - Distribution release: current
 - Geeqie version: 2.4 GTK3
 
**Describe the bug**
The exif window is empty and does not display any EXIF data.

**To reproduce**
Open any image with EXIF data. 

**Expected behavior**
Exif data should be displayed; at least the comment and the description:

```
Comment                         : Created with GIMP
Description                     : test_description
```

**Screenshots**
![image](https://github.com/user-attachments/assets/c4e61878-2cf8-4238-8966-733c0238823b)

**Image sources**
[exif.png.gz](https://github.com/user-attachments/files/16849295/exif.png.gz)

**Comment by caclark** [comment]
I do not think that image contains exif data.
Please try one of these files to check if any exif  data is displayed:
https://pixelpeeper.com/photos

**Comment by philippludwig** [comment]
It does. `exiftool` shows e.g. the comment and the description.

**Comment by philippludwig** [comment]
> I do not think that image contains exif data. Please try one of these files to check if any exif data is displayed: https://pixelpeeper.com/photos

With one of the sample images from that URL Ctrl+E works as intended. Why it's not working with my sample image I have no idea, but I guess the problem lays somewhere else.

**Comment by caclark** [comment]
I think exiftool is displaying the "jpeg comment", which is not the same as the "exif comment".
This has caused some confusion before:
#286 
#381
