### ISSUE TITLE
Sort Manager and sidecar grouping issues

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#152]
There are multiple issues in the "Sort Manager" when working with sidecar grouping:

1) When using the Sort Manager to Copy grouped files (e.g. a .JPG+.CR2 pair) to a folder, only the parent file is copied.

2) When unfolding a grouped pair in the sidecar, highlighting both files in the group, and then copying them from within the sort manager, only the second file is copied.

3) When highlighting multiple groups in the sidecar and copying them from within the sort manager, only the parent file from the last group is processed.

In the source code there is no comment about what the defined behaviour should be. In bar_sort.c, bar_sort_bookmark_select_folder(), the initial list of files contains only one file (the parent file for case 1). Later in the code, in filedata.c file_data_process_groups_in_selection() there's ungrouping of files, and because of that the sidecar files aren't considered.

Reported by: mschwendt

**Comment by caclark** [comment]
Fixed at some time or other
