### ISSUE TITLE
HTML documentation doesn't get installed as it has done in previous versions

### ISSUE THREAD

**Issue by gusnan** [BestImageViewer/geeqie#1523]
**Setup (please complete the following information):**
 - Distribution: Debian
 - Distribution release: latest unstable, as 20240922
 - Geeqie version [geeqie --version]: latest Git

**Describe the bug**
Build system doesn't seem to install html documentation.

**Expected behavior**
HTML documentation getting installed with the program.

**Additional context**
I guess e6c17943ab0e61d7a3f33d6edc6f0ac23383f137 is the cause of this, and the command just hasn't got replaced properly.

**Comment by caclark** [comment]
@gusnan 

When the local help is missing, Geeqie reverts to the help on geeqie.org.
There is also now help in pdf format locally.

Do you think it necessary for a 2.5.1 release for this?

(And no one reads the help anyway....)

**Comment by gusnan** [comment]
Nah, that's not necessary - (And neither for the other recent small bug I have posted) - It's just details, that I have solved in the Debian packaging. (Which I pretty much always can do).

Yeah, sadly I guess that it's true that very few people read documentation...
