### ISSUE TITLE
Runtime end-fo-life

### ISSUE THREAD

**Issue by nk8020** [BestImageViewer/geeqie#1537]
**Setup (please complete the following information):**
 - Linux Mint
 - 22
 - Geeqie version: 2.5

**Describe the bug**
Reported EoL for the gnome runtime  (gnome 45)

**To reproduce**
Install & get it automatically

**Expected behavior**
Opens up security update problems

**Screenshots**
![11](https://github.com/user-attachments/assets/658ff4d5-07f4-47d9-8188-d1fd974bab00)

**Image sources**
Flathub

URGENT !!
It Is my favorite photo viewer by far.

**Comment by caclark** [comment]
I think this may be a Flathub problem:

`https://github.com/flathub/org.geeqie.Geeqie`

**Comment by richardstevenhack** [comment]
Same problem on openSUSE Tumbleweed.

The GNOME 45 platform is no longer supported. Flatpak offers version 47. 
https://flathub.org/apps/org.gnome.Platform

**Comment by caclark** [comment]
I am confused as to what is happening here with .


If there is a problem with a FlatPak, I think that raising the issue on `https://github.com/flathub/org.geeqie.Geeqie` would be best.

**Comment by richardstevenhack** [comment]
It is NOT an issue with the flatpak. You developed Geeqie to run on Flatpak, did you not? Or did someone else do that? I'm not familiar on who does Flatpak development, either the original author or someone else. In any event, it's your program so I'm addressing the issue to you.

The GNOME Platform for which Geeqie was developed on Flatpak is version 45. That version has security issues and has been retired. Current version is 47. Therefore it is logical that the Flatpak version should be modified to use the correct platform. 

I don't know if that's you or someone else. I'm just pointing this out.

**Comment by qarkai** [comment]
> Same problem on openSUSE Tumbleweed.

It doesn't matter where Flatpak is running.

> It is NOT an issue with the flatpak.

It is. Not the whole Flatpak system, just one obsolete package. Hint: https://github.com/flathub/org.geeqie.Geeqie/blob/a79d54e5aa8ca696dd1a672d02693854a152c0db/org.geeqie.Geeqie.json#L4

> You developed Geeqie to run on Flatpak, did you not?

Nope.

> Or did someone else do that?

Yep. @caclark has already provided the link twice: https://github.com/flathub/org.geeqie.Geeqie

> In any event, it's your program so I'm addressing the issue to you.

Again, it's the packager's issue, usually called "downstream". Address it to https://github.com/flathub/org.geeqie.Geeqie

---

@caclark I'd close this issue.

**Comment by caclark** [comment]
The project `github.com/BestImageViewer/geeqie/` provides only source code (although in recent times I have additionally included code to auto-generate AppImages within this project). The source code is taken by various packagers e.g Debian, Flatpak etc., to create something for users.

As @qarkai  has commented, the Flatpak failure should be reported to the Geeqie/Flatpak project.

The near-simultaneous failure of Geeqie's Flatpaks and AppImages is just a coincidence.

At around the same time that the GNOME 45 platform was obsoleted, I updated the GitHub runner used to create the AppImages from Ubuntu 22.04 to 24.04, and that caused the AppImages to fail.

I used  `AppImageCrafters / appimage-builder`  to generate the AppImages, and that is where I think the problem lies. Rather than wait for that project to be updated, I will use another method - and that may take a little while.

**Comment by qarkai** [comment]
> Q: does the Geeqie code (flatpak or not) rely on a genome 45 runtime?

No, Geeqie depends on particular libraries GTK, GLib, etc. AFAIU GNOME platform/runtime is Flatpak-specific.

**Comment by qarkai** [comment]
GNOME 45 is not maintained https://release.gnome.org/calendar/, GTK3 is still maintained https://en.wikipedia.org/wiki/GTK#Releases:~:text=3%2B%20years%0A3.22.29-,3.24,-2018%2D09%2D03. So it's not a technical issue, rather manager's decision.

**Comment by qarkai** [comment]
> if I decide to dispense of the flatpak and install it as a native package, it should run fine

Note that flatpak application's cache-config-data files could be somewhere in flatpak's directories. When you run native package application it usually creates and searches for them in XDG-based directories, i.e. `~/.cache/<app>`,  `~/.config/<app>`,  `~/.local/share/<app>`, etc.

**Comment by richardstevenhack** [comment]
Thanks all for the clarifications. I have opened an issue with the flatpak maintainer.
