### ISSUE TITLE
Show particular exif fields on single key press

### ISSUE THREAD

**Issue by pevik** [BestImageViewer/geeqie#1542]
**Setup (please complete the following information):**
 - Geeqie version: Geeqie 2.5 GTK3

**Describe your feature request**
I saw recently on some image editor in windows (zooner?) feature to show on `i` key press few basic exif info (date, GPS, comment) as a text printed on the image top left corner . This is particularly handy when showing photos on presentation (full screen mode). Because geeqie shows exif info in separate window (with `ctrl + e`) but it has 1) many fields here 2) it's in separate window.

I suppose this should be doable via plugins, but it would be nice if user could select fields to display.

**Comment by caclark** [comment]
Could you use the Overlay Screen Display to show the data?
`https://www.geeqie.org/help/GuideOptionsOSD.html`

Keystroke letter "I" is used to cycle through the display modes.

The option `Edit/Preferences/Behavior/Hide OSD In Fullscreen` affects what is displayed.

If you have the Info Sidebar open, you can set the displayed items in the Exif group (which is not useful in full-screen mode).

**Comment by caclark** [comment]
If the OSD does what you wish, you will see that keystroke "I" cycles through the modes therefore there are multiple keystrokes to turn the display on and off.

If you do not want that, go to `Edit/Preferences/Keyboard`, click on the header of `Action` to sort, and find the entry for `Image Overlay`.
Set a new keystroke for the action - I think you can remap the character "I".

**Comment by pevik** [comment]
I'm sorry for long reply. Yes, Overlay Screen Display works for me well. The only thing I would appreciate is to disable overlay with the histogram on showed on the second `I` press. Atm 3x `I` is needed to be pressed to remove the overlay.

**Comment by caclark** [comment]
Go to `Edit/Preferences/Keyboard`
Click somewhere in the `Action` column of the table.
Type `image overlay` - the required action will be selected.
Set a key combination for this action - you may reallocate the keystroke `i` to this action.
