### ISSUE TITLE
Holding the delete key causes errors

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#157]
I couldn't find a way to comment on already closed bug or reopen it, so posting a new one.  For those who don't know the original report (ID: 2900032):

Holding the Delete key to unlink files in batch one after another, causes various error messages to appear. This worked flawlessly in GQView and as a matter of fact is a wonderful way to delete files if you control Geeqie with only Delete, Page Down and Page Up (which I very often do) and having to select is a pain since you have to hold Shift or some such.

So guys, instead of claiming this is not an issue how about thinking for a second how to solve it.  Here's a though: how about while Delete key is pressed all Delete key press events are ignored and instead files are deleted when deleting of the previous files has finishes. A pseudo code could look as follows:

bool delete_down = false

on Delete key down:
&gt; if !delete_down 
&gt; &gt; delete_down = true
&gt; &gt; delete(selected files)

on Delete key up:
&gt; delete_down = false

on files deleted:
&gt; update GUI
&gt; if delete_down
&gt; &gt; delete(selected files)

Reported by: mina86

**Comment by caclark** [comment]
If "confirm file delete" is not selected, the Delete key works as requested
