### ISSUE TITLE
Star Rating in Image Overlay only visible after refresh

### ISSUE THREAD

**Issue by lukadh** [BestImageViewer/geeqie#1571]
**Setup (please complete the following information):**
 - Distribution: Pop-OS
 - Distribution release: 22.04
 - Geeqie version [geeqie --version]: Geeqie 2.5+git20241221-a0d1c068 GTK3

**Describe the bug**
When rating an image using alt+1 I can see the rating being accepted in the Info Sidebar but not in the Image Overlay. It takes either going to the next image and back or clicking refresh to show the stars in Image Overlay. The Image Overlay is set to show %formatted.star_rating% and the star character was set to U+2605.

**To reproduce**
1. Open an image with Image Overlay activated
2. Change its rating using keyboard shortcuts
3. Take notice of the star rating in Image Overlay
4. Refresh view/ Navigate back and forth

**Comment by caclark** [comment]
A temporary fix is to select `Select/Show Marks`

**Comment by lukadh** [comment]
Thank you for the hint! The workaround is all I neeed. With having set the Files pane to Images as Icons it doesnt even affect the workspace much.

**Comment by lukadh** [comment]
Wow, awesome. Thank you for the fast fix. The OSD behaves properly now regarding the star rating.

One thing: After changing back to "not show marks" in the Files pane, I noticed it still needs the "back and forth" between images to update to the proper star rating. Let me know, if I should open a bug report for that.

**Comment by caclark** [comment]
> After changing back to "not show marks" in the Files pane, I noticed it still needs the "back and forth" between images to update to the proper star rating

I do not see this problem. Are you using the latest sources?

**Comment by lukadh** [comment]
I have only just updated to: _Geeqie 2.5+git20241221-a0d1c068 GTK3_ but the behaviour is still the same. Maybe my description was misleading. I am talking about the star rating in the Files Pane now (hence asking, wether to open a new issue)

This screenshot shows star rating at 1 with Select/Show Marks active
![Geeqie-show-marks-1-star](https://github.com/user-attachments/assets/90cd0d9b-b183-4433-8b68-b6aa7bd42000)

This screenshot shows updating the star rating 3 with Select/Show Marks active
![Geeqie-show-marks-3-star](https://github.com/user-attachments/assets/3aa9e390-4636-4ad7-b722-c65eb99e82ce)

This screenshot shows the problematic behaviour: Updating the star rating to 5 stars with Select/Show Marks deactivated results in both 3 stars (Files Pane) and 5 stars OSD
![Geeqie-hide-marks-3-and-5-star](https://github.com/user-attachments/assets/c04c936f-fddb-47b8-98d5-cfb298f780b1)

Thank you for taking the time to look into it. This issue is not hindering my work atm, but I thought to let you know.

**Comment by caclark** [comment]
Sorry - yes, it is a bug.
I had checked with OSD/sidebar only, and not when stars in the files pane are enabled.
Please log a bug.
