### ISSUE TITLE
Star rating doesn't update in info sidebar

### ISSUE THREAD

**Issue by arrhat** [BestImageViewer/geeqie#1577]
**Setup (please complete the following information):**
 - Distribution: Kubuntu
 - Distribution release: 24.10
 - Geeqie version [geeqie --version]: 2.4 GTK3

**Describe the bug**
When I use alt+[#] to change the star rating on an image, the rating change isn't displayed in the info sidebar until I move to another image and back. Clicking refresh does not update the info sidebar display. Similar to issue #1571, except the star rating in the info sidebar doesn't change and clicking refresh doesn't update it. (I tried the solution listed in #1571, and while it did cause the star rating in the image overlay to update correctly, the info sidebar still isn't updating.)

**To reproduce**

1. Open an image with the info sidebar visible.
2. Change the image rating using keyboard shortcut.
3. The displayed star rating in the info sidebar doesn't change.
4. Navigate forward and then backward to the rated image. The rating has been updated.

**Comment by arrhat** [comment]
Realized I didn't have the most recent version so installed 2.5 via flathub -- issue is present in this version as well.

**Comment by caclark** [comment]
This is fixed in commit eba438f3abbc8b772a8fed96be8f104010d33292 (#1571)

This is a workaround:

Add the `Exif` pane to the sidebar.
If it is not already included in the `Exif` pane, add an entry for `formatted.star_rating`
If required, delete the entries you do not need.
