### ISSUE TITLE
Replace print dialog by standard GTK dialog

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#160]
The print dialog of Geeqie is still of the old pre-CUPS print command line stile. It does not list the CUPS queues, does not get the printer's page geometry (available page sizes, unprintable margins), nor does it allow to select printer-specific options. The user has to enter page size and margin data manually and has to set the print queue defaults with the printer setup tool to make the printer do the desired printout. This is far away from today's usability standards.

Printing should work as in eog: GTK standard printing dialog with Page Size and Orientation setting in the print dialog (no Page Setup dialog, see https://bugzilla.gnome.org/show\_bug.cgi?id=614451\).

Reported by: tillkamppeter

**Comment by caclark** [comment]
Commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=c6dc44268599a322f91c4f0d8b86861526f57797

is first step to convert to standard gtk print dialog. Proof print not included.

**Comment by tomaszg7** [comment]
At the moment it is a serious regression, since it seems to be impossible to fit image to the window (I haven't tried to print, maybe scale 100% means just that?). Anyway, looks like a step in a good direction, I had a lot of problems printing in portrait mode with old dialog.

**Comment by caclark** [comment]
> since it seems to be impossible to fit image to the window

Could you please make a screen capture to show how the image doesn't fit?
If you are referring to the preview mode, there are + and - buttons to change the view.

**Comment by tomaszg7** [comment]
Sorry for being imprecise. I mean it is not evident without actually printing what "scale 100%" in page setup means. If the image is printed preserving set DPI? Fit to paper? Some other way? Also no way to centre image on the page in a specific way.

The preview button answers that question, but in a very inconvenient way. For example, you cannot return from preview dialog back to the print dialog, or see the result of changing the scale interactively.

Another caveat: you can choose what extra information to print, but not where to show it. Maybe it would be possible to borrow the code from overlay definition string and use something similar here for header and footer separately. On the other hand, it might be an overkill.

**Comment by caclark** [comment]
>  what "scale 100%" in page setup means

The image is down-scaled to the maximum print area as supplied by the printer widget, then the image and annotation centred vertically or horizontally as appropriate. The scaling is done at the highest resolution (GDK_INTERP_HYPER).
(If the image is smaller than the print area, it is up-scaled - that is a bug.)
(If the zoom setting is used, the placement goes to top-left - also a bug)

> you cannot return from preview dialog back to the print dialog,

That is the same for all other applications that use the standard dialog - it is a GTK "design feature".

> Also no way to centre image on the page in a specific way.

Both Gimp and Eog have a preview on the custom tab to enable interactive adjustments, as did Geeqie previously. Oh, well. Print.c got reduced from 3600 lines to 600 lines, but it looks like it's getting increased again :-(.

>  borrow the code from overlay definition string 

If copy-paste is easy, I intend to use the same code as in overlay screen display for the text annotations. That will permit the user to use data such as formatted.ShutterSpeed, but at the expense of a more complicated setup.

I will probably not bother with the proof print unless there are complaints.

**Comment by tomaszg7** [comment]
> Both Gimp and Eog have a preview on the custom tab to enable interactive adjustments, as did Geeqie previously. Oh, well. Print.c got reduced from 3600 lines to 600 lines, but it looks like it's getting increased again :-(.

Yeah, it seems that Gimp's solution is good (although I didn't check how `scale` works together with settings on this custom tab). I didn't check EoG.

> If copy-paste is easy, I intend to use the same code as in overlay screen display for the text annotations. That will permit the user to use data such as formatted.ShutterSpeed, but at the expense of a more complicated setup.

Yeah, complication of setup would be a bad thing. I don't know if anyone would care about this feature. I'm just thinking out loud. Maybe something like that: put two checkboxes next to each item for including the item in footer or header and a checkbox called e.g. `advanced setup` which switches to overlay-like setup.

**Comment by caclark** [comment]
Enhanced text options:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=0c352dfb884134ad426a14c854b79b73b7ecabc8

**Comment by tomaszg7** [comment]
Nice, although text contents is not self-explanatory yet :) In the sense that it is not obvious what is the difference between footer 1 and 2: I guess there is no intrinsic difference, it is just a way to specify which goes first. 

Another observation - seems that printing ignores exif orientation tags (and geeqie internal rotation).

Also, I don't know what I did, but one time while watching preview Geeqie's main window jumped to the preview file directory (e.g. `/tmp/evince-previewer-23683`).

**Comment by caclark** [comment]
> it is just a way to specify which goes first

Exactly so. There is an interlock to prevent both annotations being set to the same place. I will update the documentation some time. A context-sensitive Help button on the custom tab would be useful.

> seems that printing ignores exif orientation tags

Geeqie used to rotate on the proof page, but not on the single-image page. Eog rotates. It makes sense to rotate to the exif setting.

> main window jumped to the preview file directory

I have not experienced that. Geeqie doesn't handle the preview - that is done by the printer widget.

**Comment by tomaszg7** [comment]
> I have not experienced that. Geeqie doesn't handle the preview - that is done by the printer widget.

I think I know what I did. I dragged the preview image by mistake into main window. So I guess it is a feature, not a bug :)

**Comment by caclark** [comment]
Rotate to exif orientation:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=9341482f94420d22ec510da3f29b198a1ac0c460

**Comment by caclark** [comment]
Permit exif tags to be included in the image text annotations:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=40ee2ff3d50b2a9491837a037aea8004f12da4fe
