### ISSUE TITLE
Overwrite resolve dialog too long

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#161]
When moving lots of files between folders and if there are lots of duplicates that will be overwritten, Geeqie will generate a overwrite resolve dialog that's too long for my screen. I have to close the dialog because the buttons are unreachable. I'm using Ubuntu 10.10 and Geeqie 1.0. The screen fonts are larger than default because the computer is hooked to a 47" LCD-TV placed a couple of meters away.  The lines will wrap and if I increase the width of the dialog, it won't unwrap the text.

Reported by: smask

**Comment by caclark** [comment]
New dialog fixes this
