### ISSUE TITLE
Do not handle RAS images or handle all of them

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#163]
Geeqie boasts it can handle raster images (extension RAS) but it expects them to be Sun raster images.  It is unfair; there are other raster image formats that can use the same extension, such as CMU raster and CALS raster.  Geeqie does not support either.
So please either unregister RAS (this will stop KSuSEInstall from recommending Geeqie for CMU images) or, preferably, handle CMU and CALS as well.

Samples:
* http://www.fileformat.info/format/cals/sample/index.htm
* http://www.fileformat.info/format/cmu/sample/index.htm

Reported by: yecril71pl

**Comment by caclark** [comment]
Fixed in commit 258cd76c at geeqie.rog
