### ISSUE TITLE
Picture loading stops when accessing last picture

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#172]
If I have about 1000 or more pictures in a list, when I "arrow down" to the last one, picture loading stops and delays for several seconds like 10 or more, and then it beeps and loads the last pic. It seems like it refreshes the whole list and that's the delay but I can't confirm that. Ther eis no reason to refresh the list at all, so I don't know what the delay is. Just annoying.

Reported by: web11

**Comment by caclark** [comment]
I cannot replicate this fault
