### ISSUE TITLE
Sort by capture date (from EXIF)

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#174]
Please provide "Sort by capture date" which can be retrieved from EXIF data. Files that do not have EXIF capture date+time sort these at the beginning (when ascending has been chosen). Sort these on file date and perhaps also make some sort selection overlay (similar to as is selected) in the file list pane.

Reported by: pander

**Comment by nijel** [comment]
See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=729625

**Comment by caclark** [comment]
Fixed in commit 92c6523db9
