### ISSUE TITLE
Printing problem

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#175]
I wanted to print 2 images on one page. I choosed paper-orientation-landscape and than I set an appropriate proof size in preview. 

The result was that it printed in portrait orientation. 

Reported by: tankerjedi

**Comment by nijel** [comment]
See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=599589

**Comment by caclark** [comment]
No longer relevant - the standard print dialog is used.
