### ISSUE TITLE
Only a very simple duplicate resolve dialog appears on cp/mv

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#177]
I was used to a duplicate resolve dialog, that shows both conflicting images and some selections on how to proceed: rename / overwrite / skip / ...

My newly compiled geeqie 1.0 shows only a very simle dialog:

"Really continue?
destination already exists and will be overwritten
Continue - Cancel"

Neither a face to face comparison nor any choices on how to proceed!

moali

Reported by: m1523

**Comment by caclark** [comment]
Fixed in commit 2dd2516887
