### ISSUE TITLE
Moving up and down dir does not retain dir list position

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#178]
When traversing through a directory structure, if you descend down three levels A/B/C then ascend back up to the top level (A), the position in the directory list is not retained. 

For example, if you have an images directory formatted YYYY/MM/DD like the following:

1990/01/01/
.
.
.
2012/04/25/

And descend down 2012 -&gt; 4 -&gt; 25 and then ascend back up two levels, the directory '2012' is no longer visible and the directory list is reset back to the very top.  This is very annoying when working with large structures of images.

This worked correctly with gqview, but no longer works with geeqie.

Reported by: sfdcw

**Comment by caclark** [comment]
Fixed at some time
