### ISSUE TITLE
geeqie zeros out hardlinked files on metadata save

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#183]
If I have a file name1.jpg with a hardlink name2.jpg (perhaps in different albums) and change and save the keywords on name1.jpg, name2.jpg will be truncated to 0.

Since hardlinking is a fairly common way to keep photos in multiple directories, this is a pretty bad problem.

This is with geeqie 1.0 (package build 13) on Fedora.

Reported by: *anonymous

**Comment by caclark** [comment]
Fixed at sometime or other
