### ISSUE TITLE
Crash if Exec is missing from desktop file

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#185]
in editors.c, in editor_command_parse:
if (editor-&gt;exec[0] == '\0')
will segfault if in editor_read_desktop_file:
editor-&gt;exec = g_key_file_get_string(key_file, DESKTOP_GROUP, "Exec", NULL);
is not found

Reported by: weary001

**Comment by caclark** [comment]
Fixed in commit cf90f247
