### ISSUE TITLE
PNM, PGM, PBM not working

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#186]
Though I have seen the previous bug report - which says the problem is in gdk-pixbuf - I beliieve the problem might actually be in Geeqie. gdk-pixbuf is working well in GIMP, and also in PyGTK, and several other programs! It loads
PBM and PGM images perfectly in those apps.

I find it difficult to follow other people's programs, but I did find a call to gdk_pixbuf_loader_get_pixbuf which seems 
a little strange (image_loader_sync_pixbuf) as, according to the manual, this call should not normally be used. It 
seems to expect a pixbuf as result, but this is not garanteed.

Please look into this... 

Reported by: jcoppens

**Comment by caclark** [comment]
Works now.
