### ISSUE TITLE
Support preview of .svgz files

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#188]
Please render .svgz files. These are simply zipped .svg files.

Supporting this file format will enable geeqie users to easily preview zipped SVG files.

Reported by: pander

**Comment by caclark** [comment]
gdk-pixbuf-query-loaders shows that .svgz files are supported.
It doesn't work for me, though.

**Comment by tomaszg7** [comment]
It doesn't work for me either. (For the record, they are gzipped, not zipped)

Generally SVG rendering is a bit lacking. For example some layers/object are not rendered (even new file class icons in geeqie tree have this problem.

**Comment by caclark** [comment]
Using gdk_pixbuf_loader_new_with_mime_type() instead of gdk_pixbuf_loader_new() seems to work.
I don't know what the implications of changing the code would be.

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=4d6b98ab4e23ff830ddc3ba45bc1e06d9128172b
