### ISSUE TITLE
layout_set_path: file_data_new_group: assertion failed: (fd)

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#191]
In Geeqie folder view, use the combobox to open an old path that no longer exists. Those are maintained in $HOME/.config/geeqie/history in the "[path_list]" section. 
Geeqie crashes:

ERROR:filedata.c:1101:file_data_new_group: assertion failed: (fd)
Aborted (core dumped)

That is because first of all the S_ISDIR check fails for a non-existing path, and so it assumes that it knows the cached fd for the parent dir already, but if that dir has not been visited before (or doesn't exist either), it could return NULL rather than abort via g_assert().

Further, wherever the history path_list is maintained, when restoring it from disk, it might be possible to apply existance-checks there and eliminate non-existing paths.

Reported by: mschwendt

**Comment by caclark** [comment]
Commit 900e65e7e, I think fixes this
