### ISSUE TITLE
slow recognition of file move, delete, rename

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#193]
I'm running Debian Jessie w/geeqie 1.1.

In the past month or so, I see a weird slowdown. Geeqie is slow to recognize changes in the file system. Look at a picture. Use Geeqie to move it. The file moves right away (I'm monitoring Nautilus at same time), but Geeqie does not notice the file has moved and then display next image for 5 seconds or so.

I've been GQView/Geeqie user for 10 years, I'm not a notice.  But I don't know where to look for trouble. Is Geeqie using a "file alteration monitor" and should I debug that?

Oh, one more new problem. When I use Geeqie to rename a file, the new name NEVER registers in the titlebar. Name stay same until I move to next image, then shift back again.

thanks in advance.

Reported by: pauljohn32

**Comment by caclark** [comment]
Implemented in commit 8a2a3697
