### ISSUE TITLE
Geeqie crashes when renaming some images inside a collection

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#196]
Renaming some images from inside a collection is making Geeqie close unexpectedly:I've just seen this behavior in version 1.0beta2 (installed from Ubuntu repo) and version 1.1 as well (compiled from source).

The steps are:
-open an existing collection
-select an image for renaming
-start to type the new name
-Geeqie crashes

Apparently it's images with long filenames that cause this issue,however I've just noticed it so I can't be sure.

If running Geeqie from a terminal (or with some specific debugging options) can be useful,please let me know-thanks.

Reported by: klonator

**Comment by caclark** [comment]
There is also a crash if a file in a collection is renamed twice. Saving the collection before the second rename seems to work.

**Comment by caclark** [comment]
Commit bc543c3082 at geeqie.org possibly solves all these problems
