### ISSUE TITLE
case change makes file unviewable. 

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#198]
I have a script that copies a few photos from my camera, starts geequie and then cleans up: It renames the upper-case filenames from the camera to lowercase ones. 

The running geequie will then "lose" the ability to show the renamed files: It shows the uppercase filenames in the tools window, it will show "no read permission" when you select such a file, and a "refresh" from the context menu doesn't change anything. 

Workaround: "manual" refresh:  select another directory with the browser, and go back to the original directory. Now the lowercase filenames are shown. 

I think the "refresh" considers the upper/lowercase change as "no change", but trying to open the original (uppercase) filename results in "file not found" (not no read permission!).... 

Reported by: rewolff2

**Comment by caclark** [comment]
Fixed at some time or other
