### ISSUE TITLE
[pixbuf-renderer.c:1222]: (style) Same expression on both sides of '&&'

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#199]
Source code is

```
g_return_if_fail(tile_width >= 32 && tile_width >= 32);
```

Maybe

```
g_return_if_fail(tile_width >= 32 && tile_height >= 32);
```

would be better code.

I found this possible problem using cppcheck, a static analysis checker.

Reported by: dcb314

**Comment by caclark** [comment]
Is duplicated in #386. Fixed in  d78ae72
