### ISSUE TITLE
Geeqie to pop to top of current windows when open up with -r

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#201]
Whenever I double click on a an image via the desktop (Xfce) or a file browser (Thunar), the image opens up in Geeqie, but Geeqie does not come to the front or even jump to the primary desktop workspace. 

I figured that Geeqie is being stared with the -r (remote option), but could there be a configuration within Geeqie to force the application to come to the front of whatever  desktop workspace the user is currently on. As it is currently my options are to change Geeqie to not start with the remote option (new instance each time) or be confused as to where the window is located.

This took me a while to figure out and is very confusing. as I have Geeqie to be my default image viewer. However if Geeqie is already open there is no indication that a file has been opened up.

Reported by: sebon

**Comment by caclark** [comment]
Fixed in commit ecbdd1d6 at geeqie.org
