### ISSUE TITLE
Geeqie 1.1 forces "navigate existing window" when I double-click a file

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#203]
I just upgraded from Lubuntu 12.04 (includes Geeqie 1.0) to Lubuntu 14.04 (includes Geeqie 1.1) and, now, I've encountered three new bugs in Geeqie.

The first two (a temporary freeze and a crash) may be related to video driver bugs I haven't resolved yet but the third is that, whenever I double-click a bunch of files, the window navigates through them rather than opening several windows.

(And, given how Geeqie has no crash recovery and I often open multiple instances to protect one from being killed by others, if I can't get the old Geeqie 1.0 packages to install on my newer desktop, I'll probably have to work around the  dig out strace and then set an incron task to immediately delete whatever single instance lockfile Geeqie uses as soon as it appears.)

Reported by: ssokolow

**Comment by caclark** [comment]
The current design for for a only a single window to be opened.
