### ISSUE TITLE
Crash in 1.1 while attempting to open a specific collection

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#205]
After upgrading to Geeqie 1.1, I found that attempting to open a specific collection would crash Geeqie. Downgrading to 1.0 restored normal functionality.

I can't attach the collection since the paths contain sensitive information, but here's a backtrace with the sensitive portions of the paths redacted. (I've left the file extensions and path separators intact so it should be clear what you're looking at.

Reported by: ssokolow

**Comment by caclark** [comment]
The patch quoted by mschwendt has been included in the main branch.
