### ISSUE TITLE
Symlink doesn't show  in Sort Manager (Geeqie 1.0)

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#207]
In Geeqie 1.0 (Debian package geeqie 1:1.0-10.1 in Debian Wheezy) the **Symlink** entry doesn't show up in the Sort Manager below **Copy** and **Move**,but it becomes visible if I open a second Geeqie window from File-->New window.
I've also compiled Geeqie 1.1 from tarball (in another Ubuntu-based distro) and it's exactly the same,whilst in Geeqie 1.0 beta 2 (installed in Ubuntu) there was no such issue.

Reported by: klonator

**Comment by caclark** [comment]
Temporary fix in commit 30a7a60d at geeqie.org.
The user has to open the sort manager each time Geeqie is started.

An undocumented feature is if a desktop file contains "X-Geeqie-Filter=true", it will appear in the Folder actions of the Sort Manager.
Unfortunately, the corresponding Undo action gets confused.

**Comment by caclark** [comment]
Fixed in commit 81dc6bbc71 at geeqie.org
