### ISSUE TITLE
mouse pointer back end text entry field after each character metadata

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#210]
hi, 
I just go from 12.04 to 14.04, 
Geeqie in 1.1, if I want to enter text by inserting (for exp. Adding a word) 
the mouse pointer '| flashing' returns to the end of the text field after entering each character 
when I keyboarding in the side information bar, some'm the field (comment, Keywords, title). 
In Geeqie 1.0 (installed on 12.04 - testing dual-boot) 
it is always possible to insert more than one character in the fields: comment tags, as EXIF, IPTC and XMP without necessarily being returned at the end thereof. 
While in Geeqie 1.1 (installed on 14.04 - testing dual-boot) 
it is only possible to complete the metadata and not to correct or rewrite.
il est seulement possible de compléter les métadonnées à la fin du champ et non de les corriger ou de les réécrire. 

Reported by: benney

**Comment by caclark** [comment]
I can't replicate this fault
