### ISSUE TITLE
Title not saved to EXIF metadata

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#216]
When editing the metadata of an image, I can enter a title and comment. Both are saved to the XMP file, and are saved into the image in xmp.dc.title and xmp.dc.description. However, only the comment/description is written out to the exif tags, the title is not saved.

FWIW both are saved to the legacy IPTC tags.

I am using geeqie v1.2 on Gentoo Linux

Reported by: bruceguenter

**Comment by caclark** [comment]
It seems that Geeqie's implementation is correct
