### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#226]
Hey

When a user goes to http://www.geeqie.org/ (s)he is left still thinking that Geeqie is dead. I can't find a link in human language to report a bug or make a feature request. I guess that's maybe what "trac wiki" is for, but that's not something a user should know, and it points to SourceForge which received a shitstorm of bad rap recently and judging by your commit history you are moving away from it, so I don't even know if this report will be seen.

It would be good is you could add this very simple info to the website:
- Latest version and **date of release** (extremely important that there is a date!)
- Link to changelog.
- Link to report bugs.
- A full-sized screenshot of the latest version.

This should also be removed or updated:
"Geeqie is currently short before releasing stable release 1.0. All planned features are implemented, there are however issues that needs to be finished, like documentation or translations."

Kind regards

Reported by: beep6581

**Comment by caclark** [comment]
Commit 123f8337321 on geeqie.org refers to this.
README.md has a more complete list of features, and https://en.wikipedia.org/wiki/Geeqie has link to the file on github. Anyone clicking the link gets the file in html format.
The Geeqie wiki page has a Preview release date to show a more relevant date for the state of the source code.
The repository link would be to geeqie.org, but I had bit of a %3f%3d problem.

**Comment by caclark** [comment]
In topic #471 Néstor has proposed a much more artistic style of web page.
If we are to continue using a text-style in the meantime, my preference is for a very minimal style.
My suggestion is:
http://cclark.uk

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am So den 13. Aug 2017 um 14:43 schrieb Colin Clark:
> In topic #471 Néstor has proposed a much more artistic style of web page.
> If we are to continue using a text-style in the meantime, my preference is for a very minimal style.
> My suggestion is:
> http://cclark.uk

As I am no real good web designer. (Particularly, I am a very bad one.)
Just go ahead and update the web directory. I will sync it to the
website.

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAlmRUBoACgkQpnwKsYAZ
9qzXIwwAiTk2cOF/7yIeLLpUBRUTULjKSwysYkCQ1Qi+kHysJSOdTVaWkg3eOJ6i
HA/f6dFDEqUqwKvL5S9yfzPELwCZKk9L8c1sxgP/MmKwjQ2RTAEio3NSTzM/ZezX
oGdNTwe12+IFHJFKr2+PxkFOFwxqyNqNYzUoWgJKDEpUAqJxPCHVBgjrcM/s9b03
3wgfPeWrHjcoJHpmXyw1xjkMPisym/dMdfxEEDFn9+D1kcEH7JPly2TlBHJze6h5
NTZhHH7ojqnpyH+jfQQ/++4zKj/i215fTvna6qsGj5kxGsezWkQUyqG9ReaTx3kV
P+nsBiT5Zzm3zg/c/+HFE9kXwz2s0wbVMtVPP3Pp5UROg2j4wNHt7bVHkBNPdhMt
JtdhnzoLltkyRcm5aT55HSopJWJNmNh35B7IzTfdd5Cj+P50euG+3U89JFrOq9At
w0OcT8dJtBvd+a4azBwq1LQ5cfH/e2Kge9i6aocUsHtEYJaxN4Tnihzxgqscyf0S
JviZAdiw
=4LQE
-----END PGP SIGNATURE-----

**Comment by n3storm** [comment]
Sorry everyone I've been off participating.

I would like to point out that I am much more interested in content organization and highlighting Geeqie features than in artistic discussions (my favourite color is...).

My proposal can be seen here:
http://geeqie.estudionexos.com/

For example at http://cclark.uk paragraph "A few screenshots give an idea of the range of possibilities." I don't think 2017 potentiall users will find that paragraph plus a bunch of screenshots really informative (please do not take it personal).

My references:

- http://www.pixa-app.com/
- http://mylio.com/
- https://www.lynapp.com/
- https://lunarship.com/index.html (https://lunarship.com/features.html)

More minimalistic references and maybe in line with what @caclark has in mind:

- http://www.adobe.com/es/products/bridge.html
- https://theunarchiver.com/xee

I am open to make style more minimalist (smaller color palette, no gradients or shadows or background images)  anyway I would like to recommend not dropping features exposition.

Cheers.

P.S. I promise to read this thread moreoften :)

**Comment by n3storm** [comment]
@caclark sorry, my bad, I don't understand you at first when reading " If we are to continue using a text-style in the meantime, my preference is for a very minimal style. My suggestion is: http://cclark.uk"

I missed the "meantime" part :(

**Comment by mowgli** [comment]
I want to bring this up to discussion. As I am not the web designer, I want to bring all together.

- @patdavid, who I met on Libre Graphics meeting in Saarbrücken
- @n3storm, your Page is impressive.
- Others

Please keep in mind that we have some conditions (Some of them could be discussed):
- Page should be static to be uploaded onto the server
- Page could use javascript but should work without too
- The server has no PHP, see first point above

**Comment by patdavid** [comment]
Howdy!

I (and others in the PIXLS.US team) would be happy to help!

If you’d like a look at my previous work it’s at:
* https://www.gimp.org
* https://darktable.org
* https://pixls.us

Most of my work is meant for progressive enhancement (has to work with raw html and nothing else first, then you can get fancy with JavaScript and whatnot. ;) ). It’s also all done with static site generators these days for easy hosting. 

I am currently finishing up work on the new rawtherapee.com with mica (https://patdavid.gitlab.io/rawtherapee-web/) so any new work would have to happen after this (I’ve been putting it off for far too long and need to get it finished for the RawTherapee team). 

Is @n3storm ready to ship with that page? What build system is being used? We could setup something with a Travis CI for building and publishing to a host (or host directly on GitHub pages I’d you want).

**Comment by paperdigits** [comment]
Seems like geeqie.org can't be reached right now.

**Comment by alebcay** [comment]
Hi, I was considering opening another issue for this but seeing as this one is already opened, I'll mention it here. For the link for macOS on the page, it links to [BrewFormulas](http://brewformulas.org/Geeqie), a Homebrew package tracker which is not maintained by the Homebrew team. Instead, I would kindly advise that the link instead go to the official tracker maintained by the Homebrew team, which is at https://formulae.brew.sh/formula/geeqie.

**Comment by caclark** [comment]
> For the link for macOS

I have updated the web page source, but note bug #644 - Geeqie does not run on Mojave.

**Comment by mowgli** [comment]
Uploaded, thanks

**Comment by h1z1** [comment]
I can open a separate bug for this if needed buy fyi the SSL version returns a generic apache error page.

**Comment by caclark** [comment]
Four years ago @n3storm created a webpage for Geeqie. The webpage is at long last published on http://geeqie.org
You can submit changes at https://github.com/geeqie/geeqie.github.io

There is a sub-page for AppImages. The code for this is a real mess - but it works.
Some of the fixed text in the page should be generated at run-time from the appdata xml file. But to fix that I will have to read the idiot's guide to javascript, which isn't too likely to happen - a glass of beer seems a better alternative.

**Comment by n3storm** [comment]
Thank you so much! I thought I would never seen this happen!

@patdavid this is an static one page. I am open to any suggestions.

Cheers

**Comment by tomaszg7** [comment]
The page is very nice and clear improvement over the previous page. I have a few minor remarks/concerns to consider:
* list of features is in "Documentation" section, not "Features"
* it is also a link to a part of github readme file, it'd be better to incorporate it on the webpage.
* I could't find a link to GIT repository on this page. It is in "Resources" section, while I expected it rather to be in "Get Geeqie" section. Also there seem to be no link to source tarballs.
* "Resources" section only mentions reporting bugs on github. It should also mention submitting code contributions.
* Maybe it should say at some place that it is based on GTK. It might be obvious but why not state it explicitly somewhere.
* Maybe a list of supported image formats somewhere? It is in github readme, but again it is a kind of information people might want to see at first glance.
* Animated GIFs and video support is not mentioned.
* Some bigger screenshots would be nice. 
* Is the webpage really copyrighted by Geeqie? Seems harsh on open-source project. 
* Author of the page should probably include his name somewhere also.
* At least two photos (Smena and laptop ones) are hosted on outside server. It would make sense to host them all together with the webpage. Moreover, even though that service (pexels.com) doesn't require any attribution, it would be nice to include some note in a footer.
* In section "Get Geeqie" all that "Available for" on buttons seem redundant and makes it less readable.
* Maybe add icons for distributions in Linux part of the download section.
