### ISSUE TITLE
Scrolling / zooming big images with overlay display is slow

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#23]
Overlay display, especially with histogram, makes zooming and scrolling slow.
It seems this issue is there since a long time, but with histogram feature things are worse.
A comment in pixbuf-renderer.h:
/* OVL_HIDE_ON_SCROLL = 1 &lt;&lt; 1*/ /* hide temporarily when scrolling (not yet implemented) */
let me think John Ellis was about to fix it.

Reported by: zas_

**Comment by caclark** [comment]
Currently there is no lag when using overlay display
