### ISSUE TITLE
Geeqie no longer displays the large JPEG preview embedded in raw files

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#231]
Hello

As of a few months ago my Geeqie build stopped displaying the high resolution JPEG image embedded in each raw file. I have a collection of raw files which I've used for many years for testing various software and these files have not changed.

I'm currently on geeqie-1.2.2-r2 (Gentoo). I downgraded to 1.2-r1 but the same problem there, so the cause must lie elsewhere. I'm also currently using media-libs/tiff-4.0.6 and media-gfx/exiv2-0.25-r2.
I tried downgrading to media-libs/tiff-4.0.3-r6 and media-gfx/exiv2-0.24-r1 and recompiling Geeqie but that didn't help.

I am not alone:
https://discuss.pixls.us/t/geeqie-and-raw-viewing/958

Sample raw files at the link above.

By the way, is this bug tracker watched by whoever still maintains Geeqie?

Reported by: beep6581

**Comment by caclark** [comment]
Fixed in v1.3
