### ISSUE TITLE
image filckers on the second screen if the mouse is moved

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#232]
When I move the mouse over the image on the second screen the image is flickering. This does not happen in fullscreen, on the first screen or with other applications.

I use geeqie-1.2.2-2.mga6 on Mageia Cauldron with nvidia 352.79
video: https://youtu.be/_xn8poDu-LM

Is there any additional information I could provide?

Reported by: testerus

**Comment by hhielscher** [comment]
As stated in the video:
> Works for me with  
> geeqie-1.2.2-2.mga6 and nvidia 352.79-2 
> maybe another package has changed???

**Comment by caclark** [comment]
Fault not reproducible
