### ISSUE TITLE
custom border not working

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#233]
Preferences/Image/Appearance/Use custom border in window mode and 
Preferences/Image/Appearance/Use custom border in fullscreen mode
do not work
geeqie-1.2.2-2.mga6 on Mageia Cauldron

Reported by: testerus

**Comment by nijel** [comment]
See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=763452

**Comment by Felixoid** [comment]
https://bugs.archlinux.org/task/46086 also
