### ISSUE TITLE
Key navigation in dialogs and tabs should be improved

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#238]
Uwe Ohse proposed some improvements in these domains.

For example, he provided a patch that adds some keys to navigate in the Properties window.

Original description:
This patches enhances the file info dialog.
- The escape closes the dialog.
- CTRL-Left or -Right go to the next image in the list.
- Shift-Left or -Right select the next tab.

After some testing, this is imho a nice usability enhancement.
But the current patch uses hardcoded keys, so this feature is postponed to the introduction of configurable keys.

Reported by: zas

**Comment by caclark** [comment]
This relates to the GQview module, info.c
