### ISSUE TITLE
suggestion : move ~/.geeqie to $XDG_CONFIG_HOME/geeqie ? 

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#250]
maybe move ~/.geeqie to ~/.config/geeqie and cache files to ~/.cache/geeqie will be better.

it met X11's XDG standards, and make $HOME much cleaner.

Reported by: *anonymous

**Comment by mowgli** [comment]
Already done.

**Comment by tomaszg7** [comment]
What about thumbnails? I still get them in ~/.thumbnails instead of ~/.cache/thumbnails as described in https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-latest.html
