### ISSUE TITLE
Crop simulation

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#251]
Should be nice to be able to simulate a crop of the image (in both windowed and fullscreen mode).

This feature could be used to discuss about an image, and to propose better composition.

Reported by: fma38

**Comment by caclark** [comment]
Implemented in commit 0d404f00 at geeqie.org.
Rectangle co-ordinates can be obtained with the remote command:
`--remote --get-rectangle`

**Comment by caclark** [comment]
Bug fix for returned rectangle coordinates is at geeqie.org:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=88791d22692d624755557aa7324617c7ee6418dd
