### ISSUE TITLE
Randomize collection

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#253]
I find myself often in a need to "randomize" order of the photos in a collection, before I start arranging them into some nice order. Currently, I:

\- open new collection
- 'append from file list'
- save collection
- run my shell script that mixes the photos
- open collection

Would it make sense to add an option that would mix the photos up just in the Collection view?

Reported by: muflon

**Comment by caclark** [comment]
Commit 6bbb74b31e8
