### ISSUE TITLE
xcf support

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#260]
Not sure how easy this would be;

My workflow is currently as follows:
1) Download raw (cr2) files from memory card.
2) Browse images using geeqie
3) Load selected images from geeqie into GIMP (via UFRaw).
4) Save edited photos as .xcf and export to .jpg for printing or web view.

Generally I'll have a jpg corresponding to an xcf file but not always and often in a different folder. Since xcf saves (or can save) a preview within the file, it should be a case of digging out this preview.

Reported by: jcodous

**Comment by paperdigits** [comment]
Was the xcf viewing feature ever implemented?

**Comment by mowgli** [comment]
Yes.. It was. Well, not part of geeqie but of the loader.

Have a look at http://www.geeqie.org/cgi-bin/gitweb.cgi?p=geeqie/xcf-pixbuf-loader.git;a=summary where you can find the loader. I have it in use and it is working great. What does not work is compressed xcf files.

**Comment by paperdigits** [comment]
Forgive my ignorance, but does that mean I can view xcf files?

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am Fr den 10. Jun 2016 um 16:01 schrieb Mica:
> Forgive my ignorance, but does that mean I can view xcf files?

Yes and no. It does mean that xcf support is nothing, geeqie can do for
you, it is pixbuf-loader. You have to provide the relevant module to
support xcf and magically, geeqie will show them too as it is based on
pixbuf-loader.

Just compile the library above and install them (manually) to your local
pixbuf directory. (On my system, that is
/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xcf.so.)

Regards
   Klaus
- -- 
Klaus Ethgen                              http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16   Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1
Comment: Charset: ISO-8859-1

iQGcBAEBCgAGBQJXWyfpAAoJEKZ8CrGAGfasnwIMAMGqlwxB29jBqZhkiMgFLOKW
TCk4A0/X+hzTIDRXG5b3dc8L3PtEC0Ofj/qf2dargFk6hONxAg2NbrZGXd5oMTpY
BRREwaaku8H1uCa7t5KjqNZzYlnpLE5cKqAfqJVZQZjU09XriJipST0D/mFwVxwt
jl9fDRyVRaJGej/VwzpTs+NYtY0kuC3v3xbJWqn5njYpmOp+OtzqF72dFWrFjnyj
LQIgj4Jv4OkcVXONcf6hMRxe0wAhIyLLT5xn82yBD+fswoZqDNjgtU//lVl9LRRc
s3KO4znJ7raTVPdM89tXDefwPRalaA1Xx0/QvMxNb0Vcthg3Uvjtw4sqZLYsIHA/
7qfiGmtC4kE1jRsz4cHNSvLQazN+ivKuiCg6dqh/TnBCMVuMqQXKeN0p8lwK4o7S
QWe/DMRsas51H8vF61k6l2GAkE1FFlkjtRgzOQdEK48W0BWI7oUSP1Ffuryxexom
EDzunmrKZBcfdl/cVjyagQGx8ploKILsbPlDccaz3A==
=9LvZ
-----END PGP SIGNATURE-----

**Comment by paperdigits** [comment]
Wow. I've wanted that feature for so long, thank you. The relevant package in Fedora 23 is `xcf-pixbuf-loader`.
