### ISSUE TITLE
double click and fullscreen 2

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#262]
You already implemented the feature double click -&gt; full screen in alpha 3. Nice! 
IMHO it would be nice to leave the full screen with a double click too, but in full screen mode a click switches to the next image. This can be done with the mouse wheel - and i love this way, because you can also go backwards with the wheel, but there is no "back click" ;)

Mathias

Reported by: *anonymous

**Comment by caclark** [comment]
Fixed in commit 9c47109d3 at geeqie.org

**Comment by Safari77** [comment]
After `9c47109d3` I can't move 100%-zoomed images, geeqie just goes to next picture.

**Comment by caclark** [comment]
Ah, sorry. In all the multiplicity of ways of doing things with Geeqie I missed that.
Go to Preferences/Behavior and set "Navigation on left or middle or middle click on image" to "off".
I will update this in a day or so.
