### ISSUE TITLE
Hotkeys to change picture filters.

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#263]
I post here the mail I sent on the mailing list. Vladimir told it was a good idea and to post it here. So here it is :) : 

am a new user of Geekie. This soft is really great and I just change my workflow (I am a photograph) to use Geekie instead of Gwenview. 
"
I read that you want to improve keyboard shortcuts in the nexts releases. 
I would know if you plane to had a shortcut to change filter. 
For exemple : F7 to view .nef or to hide them. 

In my workflow I use Geekie after the import to delete all pictures (raw pictures) I don't want. Then I develop my raws in some software and save/export them in jpeg in the same directory of the original file (the raw). 

When I want to look my exported files I run Geekie to see them. But I have a few JPEG files (10 or 15 for exemple) lost in 100 or 200 raws. If, at this moment it will possible to press F7 (for exemple) to hide raws it will be great :) !

And if you want to know why I put the JPEG in the same folder of the raws it's because it's easier to tag them all together in digikam. 

Well I just want to know if you plane to make something like that. If not, take that as a wish :) . . . If I was a dev I probably could that easy but I'm really not a dev. 

Good continuation with Geekie. It's really good. 
Thank you. 

Reported by: lecoudegauche

**Comment by caclark** [comment]
Perhaps an option to group by file type would help.

**Comment by caclark** [comment]
There is now a file filter, with a number of definable presets available from a drop-down
