### ISSUE TITLE
restore jpeg lossless rotation commands

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#264]
These seem to have disappeared recently. I don't see any mention of it in the changelog, so maybe it's a bug in my distro's package of geeqie?

Anyhow, I'd like the lossless JPEG rotation feature to work like this:

\- select a bunch of thumbnails

\- right-click, select lossless JPEG rotate (please include the word lossless in the menu command; it's a real hassle to make an extra copy of a test image, rotate it in whatever app has a "rotate jpeg" command, then load both files in GIMP, set them as layers with difference blending, and check whether the operation was a lossless jpeg transform or just a standard rotate-save-as-new-jpeg...)

\- there should also be an option to do the lossless rotation automatically based on the EXIF orientation tag

\- after rotating the main image is done, the thumbnail is also rotated/regenerated (most lossless jpeg rotation features forget this; it's very annoying)

\- the EXIF orientation tag is cleared/reset

I would argue that the EXIF orientation tag manipulation options should either be scrapped or hidden by default, in favour of lossless JPEG transformation. The EXIF orientation tag causes problems:

\- some apps don't support EXIF at all, so it has no effect there

\- other apps, like geeqie, support it so well that it's transparent and you often have no way of knowing whether an image is actually right-way-up or whether it's been auto-rotated (or rather, its display has been auto-rotated). this makes the above problem worse, because if you then go to edit an image in another tool and it's lying on its side, it takes a moment to figure out why. Worse, if that app doesn't support EXIF but is nice enough to not delete the EXIF data, if you then rotate the image right-side-up and save it, geeqie will now display it on its *other* side because the orientation tag is still there.

\- some devices don't support it, e.g. photo printers and most (cheap) digital cameras lacking an orietation sensor, so loading a tag-rotated JPEG onto such a device might put the image wrong-way-up.

\- thumbnails are often not rotated properly with respect to the EXIF orientation tag, so even apps like geeqie have a difficult time knowing whether they need to rotate the thumbnail as well, or just the image.

\- EXIF information is not always preserved. It's conceivable that I might have an image in my collection that I only ever viewed with tools that support EXIF rotation transparently, so I didn't know it wasn't physically right-side-up. I decide to strip all the EXIF data off of a batch of files (say because I noticed several files have way too much EXIF data and I want to just clean them and start over), and now suddenly some are wrong-side-up.

\- lossless JPEG rotation is possible. With that in mind, why not just set the image the right way around to begin with, rather than storing the fact that it's not right-side-up in a special tag?

Reported by: thetrivialstuff

**Comment by caclark** [comment]
Fixed in commit 9313974a6 at geeqie.org
