### ISSUE TITLE
Maximize picture area

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#265]
It seems that geeqie wastes quite a bit of space (compared to gqview) with borders and windows decorations. After all it is an image viewer, so I think it would be sensible to use as much space as possible for actually viewing the image...

Attached are screenshots of gqview (2.1.5) and Geeqie (1.0beta1)

It would be really nice to have the drawing area maximized :)

Reported by: *anonymous

**Comment by caclark** [comment]
As stated above, the difference is caused by using standard icons. It does not seem worthwhile to generate non-standard icons for the sake of 6 pixels
