### ISSUE TITLE
Improve speed of Safe Delete

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#267]
This is in a sense related to 2800655, as implementing this one would render that one redundant.

Currently Safe Delete feature uses a fixed directory of the disk for its backlog. This directory might reside on other filesystems than the photos themselves - and it becomes very slow then, as the data needs to be actually copied. This spoils the otherwise near-realtime performance of Geeqie :-(

Would it be possible to make this more flexible, similarly to thumbnails? E.g., add a feature to move last few deleted photos to .deleted directory. User would be able to configure number of photos that could be stored in each of such directories.

Reported by: muflon

**Comment by caclark** [comment]
I assume this is solved via  "geeqie-delete-command.desktop"
