### ISSUE TITLE
Picture diff or picture compare feature

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#268]
Hi,
I would very much like to see the following feature: a way to show files with the same name, but different content - a bit like a visual version of the "diff" command. I'm thinking  this could be done very easily with a reversed version of the "find duplicates" feature comparing two directories.

I think this feature was mentioned in one of the announcement e-mails, but I couldn't find it on any of the todo lists or whishlist items.

Thanks in advance,
Martin Leopold.

Reported by: mleopold

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=f5d36d3ef2a47d90f676e2e95c8b0d1be7e36d9c
