### ISSUE TITLE
Image marks "save" feature

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#269]
It would be nice if the "marks" data was saved for future viewing sessions. I've found that the marks I've made during one session are cleared once I've exited and then restarted.  It would also be nice if that data was made available externally so I could then use an external program to process the files differently according to the marks I've made in geeqie.

Reported by: despino

**Comment by caclark** [comment]
> It would be nice if the "marks" data was saved for future viewing sessions

This has been discussed several times - the consensus is that marks are only temporary.

>  data was made available externally 

Commit 0890884d at geeqie .org implements a way of doing this, via a --remote command line option and a lua script.

But actually, this seems to me to be a very convoluted way of achieving this. I am not so sure this should be retained.

**Comment by tomaszg7** [comment]
You forgot to #ifdef the new code, so the build fails without LUA.

**Comment by caclark** [comment]
Thanks. Fixed in commit f0e544253.

I have to find an easy way to check compile-ability with all the possibilities - GTK2/GTK3/with/without extras.
It's a pain having to do it by hand every time - and I usually forget something.

**Comment by caclark** [comment]
Preserving marks implemented in commit 850bd515 at geeqie.org
