### ISSUE TITLE
Recusively generate thumbnails in shared cache

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#276]
On explicit request via File menu, recursively generate thumbnails in shared cache for the current directory.

This background process should not interfere with the normal thumbnail generation and vice versa. One will have to have priority, probably that of the unrecisive current directory. Hence, a breath first search would be preferred over a depth first search. Also multiple instances of geeqie should not interfere regarding this, that would be done in a similar way as the normal thumbnail generation process (if there is any).

Also it should be indicated that this process is running and an menu item should also be available to stop this.

Reported by: pander

**Comment by caclark** [comment]
This can be achieved by allocating a keystroke to the Thumbnail Maintenance menu item. The CWD will already be set when the Render button is pressed.
