### ISSUE TITLE
DjVu image support for geeqie

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#277]
There does not seem to exist a good DjVu image browser.
And Gtk folks are not going to add DjVu support to gdk-pixbuf.

Reported by: safari

**Comment by caclark** [comment]
This is a document format, which typically contains multiple pages.
Geeqie can only display one image from a file.
Also, this format does not seem to be used now.
I assume there is no reason to implement this.

**Comment by tomaszg7** [comment]
I agree that there is no reason to implement it in Geeqie, but I want to note that the format is still widely used for scanned documents.

**Comment by caclark** [comment]
>  the format is still widely used for scanned documents.

Ah, ok.
The library mentioned above will probably make it not difficult to implement.
Both .tiff and .heic formats (and DjVu) have the possibility to hold several images in one file.
I guess Geeqie should be able to handle that. I am not sure how the user interface should look, though.

**Comment by caclark** [comment]
Implemented in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=46dba2d14d7c677d1bd7b9c20b983500016d5b76

**Comment by tomaszg7** [comment]
Didn't you forget by some chance filefilter bit in your commit? And a corresponding class? Note that djvu files might have .djv extension as well.

Maybe there should be a class `document` both for pdf and djvu? 

And while you're at it, maybe revisit the issue of adding support for zipped/rared/targzed image archives useful for reading comic books? https://github.com/BestImageViewer/geeqie/issues/299 Two approaches come to mind - they could appear either as multipage document or as a virtual directory. Thinking out loud - virtual directory approach might be an option for other documents as well.

**Comment by tomaszg7** [comment]
Added filefilter entry by hand and now I see the djvu files are rendered upside down and mirrored! :D

**Comment by caclark** [comment]
> Didn't you forget by some chance filefilter bit in your commit? And a corresponding class? Note that djvu files might have .djv extension as well.

Yeh, I had a bad day. Well, just completely normal really...

> And while you're at it, maybe revisit the issue of adding support for zipped/rared/targzed image archives useful for reading comic books? #299 Two approaches come to mind - they could appear either as multipage document or as a virtual directory. Thinking out loud - virtual directory approach might be an option for other documents as well.

I think a virtual directory is out of the question - I have not seen anything that could be easily used to implement this.
Using libzip it may be possible to get a list of files within a zip, and then step through each file in the list. I don't know how things are arranged in .cbz etc. files. Maybe I will have to read some Manga to find out.

The lack of thumbnails for each page in .pdf or .djvu file makes the implementation rather lacking for anything other than a quick look. I don't think Geeqie can replace purpose-built applications. 

> Added filefilter entry by hand and now I see the djvu files are rendered upside down and mirrored! :D

I found only two .djvu files to work with. Libdjvu does have a "get-rotation" function, but it always returns 0 with these two files.
But I know that Evince uses libdjvu and somehow gets the orientation correct. I will have to see how their implementation differs.
Actually I was hoping no-one would bother to use this function :-(

**Comment by tomaszg7** [comment]
> I found only two .djvu files to work with. Libdjvu does have a "get-rotation" function, but it always returns 0 with these two files.

I was not certain if you could reproduce the problem with those files or not. If not, I was able to reproduce it also with a sample file from here: http://www.djvu.org/resources/djvu_digital_vs_super_hero_pdf.php

I also wanted to create another sample djvu file with ImageMagick. Did a trivial thing: `convert cover.jpg cover.djvu`. Unexpectedly the resulting file crashes Geeqie (it opens fine in Okular).
```
[13496.836676] pool[1836]: segfault at 0 ip 0000000000000000 sp 00007f3003055c28 error 14 in geeqie[557686910000+6c000]
[13496.836688] Code: Bad RIP value.
```

```(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000055555562d244 in image_loader_begin.part ()
#2  0x000055555562ddc1 in image_loader_thread_run ()
#3  0x00007ffff737572c in ?? () from /usr/lib64/libglib-2.0.so.0
#4  0x00007ffff7374d75 in ?? () from /usr/lib64/libglib-2.0.so.0
#5  0x00007ffff59d93a7 in start_thread () from /lib64/libpthread.so.0
#6  0x00007ffff590776f in clone () from /lib64/libc.so.6
```
I can try to recompile geeqie with `-Og` to try to get more meaningful backtrace.

Further investigation revealed that IM is doing a stupid thing while asking to convert to djvu! It simply doesn't do it :D The `cover.djvu` file was still a jpg file with different extension. While it was obviously a bad file, it is no excuse for the crash :) Maybe you should check some return values more carefully or examine magic bytes before opening the file with djvu loader. 

Using `cjb2 -clean cover.pbm cover.djvu` to create file worked for me and the file was also badly oriented.

> Using libzip it may be possible to get a list of files within a zip, and then step through each file in the list. I don't know how things are arranged in .cbz etc. files. Maybe I will have to read some Manga to find out.

I think they are just dumped into zip archive and should be displayed alphabetically. Using `libzip` might be too much bother as we would to use three libraries to cover three (or least two) compression schemes. I didn't use it but `libarchive` apparently deals with them all: https://github.com/libarchive/libarchive/wiki/LibarchiveFormats

**Comment by caclark** [comment]
> I can try to recompile geeqie with -Og to try to get more meaningful backtrace.

Thanks, but I now see where the problem is.
(I get an error message from convert - no encode delegate - but nevertheless a new file with .djvu extension is created but still with the jpeg magic number and same contents).

**Comment by caclark** [comment]
The latest commit sets a default orientation so that the image is viewable.
For the moment that will have to be sufficient.

**Comment by tomaszg7** [comment]
Great, now everything works fine.

If you're into developing this "documents" angle, another polishing idea would be to add "jump to the page" dialog. Of course, I still don't suppose anyone will be using that. Another thing would be .epub.

**Comment by caclark** [comment]
I was going to include Control-Home and Control-End as first and last page. But I go so annoyed at not being able to fix the rotation problem that I forgot about that. Maybe one day...
