### ISSUE TITLE
Gamma Switching

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#279]
While Colour Profiles support a general correction of the image display, Quick Gamma Switching is a very useful function, for example:
* Adaption to different monitor settings
* Adaption to room lighting
* Quick checking for details on a low exposure photo
* Analyzing spectrogram images for high/low intensity lines
The gamma switches would be assigned to keyboard shortcuts, for example:
1=1.0 (standard), 2=2.2 (for linear gamma images), 3=0.5 (for inverse-linear). 4=X (user defined).

Reported by: *anonymous

**Comment by caclark** [comment]
Keyboard shortcuts can be applied to any of the color profiles
