### ISSUE TITLE
no support for multi-file actions (and undo) in the sort bar

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#282]
The current version does not support multiple file move/copy/link
actions (and the equivalents undo actions) in the folder-sort
bar...(CTRL+S).

I solved the problem with the following patch on gqview, it will probably need to be updated to current geeqie code base.

Forwarded from http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=337337

Reported by: nijel

**Comment by caclark** [comment]
Fixed in commit d058419bf at geeqie.org
