### ISSUE TITLE
Random image selection

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#284]
Geeqie displays first image in a directory you specified.  I just
thought it would be useful to be able to select random image from a directory using
special option, e.g. "--select-random".

Forwarded from http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=201705

Reported by: nijel

**Comment by caclark** [comment]
Set slideshow options to random, with a long time delay, then:
geeqie --slideshow
