### ISSUE TITLE
Add option to keep ctime when rotating

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#285]
It is often useful to sort photos by ctime, which is unfortunately currently lost if image is rotated in geeqie. It would be nice if it would keep the ctime or provide option to keep it.

Originaly reported at http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=317765

Reported by: nijel

**Comment by caclark** [comment]
Fixed in commit 9313974a6 at geeqie.org
