### ISSUE TITLE
Use Gimp file format plugins

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#287]
It would be really nice if gqview would use the Gimp file format
plugins if they are detected. I know this is a major feature request
but writing an interface to the Gimp plugins would really pay off in
the long term for gqview and the whole open source community.

gqview would profit since it can show obscure and less obscure files
(.psd and .xwd come to mind) with the help of several well-tested
plugins. The community would profit since having a preview capability
for legacy data makes moving away from using closed-source operating
systems and closed-source image manipulation software more likely.

Originally reported at http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=304623

Reported by: nijel

**Comment by caclark** [comment]
The xcf and psd pixbuf loaders are documented in the Help file
