### ISSUE TITLE
Zoom 1:1 and pan on left mousebutton

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#290]
I have a suggestion for the left mouse button. Clicking and holdig it switches to zoom 1:1. Moving the mouse (while still holding the left mouse button) allows for panning the zoomed picture. Releasing the left mouse button reverts back to the original zoom level. I discovered this behavious in FastStone's MaxView/Image Viewer and i find it very intuitive.

The current binding for the left mouse button is to proceed to the next picture. There are already many ways to do that (spacebar / mousewheel / page up and -down) so it wouldn't be missed much. Or even better, make it a preference in Preferences-&gt;Behaviour-&gt;Navigation.

Reported by: *anonymous

**Comment by caclark** [comment]
Fixed (in a way) in commit e5f56d798 at geeqie.org.
I assume the requirement can be summarised as to allow mouse-only viewing - until now, changing image and panning can be done with the mouse only, but zooming also required the keyboard.
 This commit uses middle-click to toggle the mouse-wheel mode between "change image" and "change zoom".
A comment above suggests hold mouse button and use the mouse wheel. But I don't find that easy, especially when I use the mouse left-handed - hence a different implementation.
