### ISSUE TITLE
More details in overwrite warning

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#294]
If some images are copied into a folder in which they are already present a "overwrite" warning is given. In GQView there was a preview (image itself, file size, image size) of the two images by which you could determine what to do next (overwrite, cancel, rename, ...)
Since I haven't managed to find an option to activate this feature I take it that it's not there. In that case, it would be great to add this feature to geeqie. Thanks!

Reported by: *anonymous

**Comment by caclark** [comment]
Fixed in commit 2dd2516887b
