### ISSUE TITLE
zero-padded _copy_ sequence

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#298]
Currently, the _copy_ code does string collation:   _copy_1,  _copy_10, _copy_11, _copy_2, _copy_3 ... _copy_9.  Very messy.

What about zero-padding the sequence?  _copy_001, _copy_002, ... _copy_999.

Sincerely,
Ron

Reported by: *anonymous

**Comment by caclark** [comment]
Since commit 56b0d6eccc
