### ISSUE TITLE
File Compression and Archiving

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#299]
Add support to open zip { & cbz} and rar { & cbz}, and why not tar.gz and tar.bzip

There is a gqview plugin for this: https://sourceforge.net/projects/gqviewarc/

Reported by: skirhir

**Comment by caclark** [comment]
fuse-zip makes this request irrelevant for zips.
Maybe similar software is available for rars.

**Comment by tomaszg7** [comment]
I don't agree. It is not really irrelevant, it is the issue of ease of use. Now you have to mount each separate file (probably from outside of Geeqie or via hand-crafted desktop file) and then navigate to the mount directory. It is a lot of effort, you could as well as decompress the whole archive to `/tmp`. 

Typical use case for .cb[rz] files is reading comic books. It is annoying to have mount/umount each time you open a new book. There are separate viewers optimized to handling these files, but that doesn't mean that it wouldn't be good if Geeqie could seamlessly open them as well.

**Comment by ObiWahn** [comment]
Are there plans to do this?

**Comment by caclark** [comment]
> Are there plans to do this?

There does not seem to be much enthusiasm for this.
The gqviewarc source is still available on SourceForge. It gets part way to a solution, but gives dlsym run-time errors.


> It is a lot of effort, you could as well as decompress the whole archive to /tmp

I think that is what gqviewarc does - it seems to be a read-only solution.

>  It is annoying to have mount/umount each time you open a new book.

You can define .zip etc. as files types recognised by Geeqie, so they show up in the files pane. Then use a plugin to decompress them to /tmp and move to that folder.

Maybe it is possible to create a new file class called "archive file", which shows a montage of the contents in the image pane, and decompresses to a /tmp folder and moves focus to that folder when double-clicked.

**Comment by ObiWahn** [comment]
Hi, I tried `gqviewarc` as well and thought about replacing the unzip with `fuse-zip` or `avfs`.  Mabye I try this some day, you will cry as my C is pretty bad.

Is there a way to create a proper plugin something that does not require to use `LD_PRELOAD`. ...
I just saw the plugin directory and found a bunch of bash scripts. How do I know or set what parameters are send to a plugin? Is there some plugin documentation that I have overlooked? Extracting a few files with bash or python should really be doable and I would contribute the code once it is working.

**Comment by caclark** [comment]
Using gqviewarc is a neat solution from the user's point of view, but I am not enthusiastic about using code that intercepts all system file open/close commands.

Archives can be opened using shell scripts, but it is not such a good solution from a user point of view.

Download the attached file and unzip it and make it executable. This file is just an example of how this may be done, and should be improved.

Open Geeqie, go to `Edit/Preferences/Files` and create a new entry for `.zip;.rar`. This will make zip and rar files appear in the files pane. However the broken image symbol will be shown because Geeqie cannot read them.

Go to `Edit/Configure Plugins` and create a new plugin. Set
 `Name=<something sensible>`
`Exec=<full path>/display-archive.sh %f`
Save as `<something>.desktop`

You may open an archive by:
right-click on the file, then select the required plugin, or
set an icon to the plugin on the toolbar, or
set a hot key to call the plugin

[display-archive.sh.gz](https://github.com/BestImageViewer/geeqie/files/6371683/display-archive.sh.gz)

**Comment by tomaszg7** [comment]
I see you put a very limited list of extension for this feature: `.zip;.rar;.cbr;tar.gz`. From the top of the head seems you need to add also cbz (as a zip counterpart of cdr). There should be also support for many flavours of tars: tar, cbt, tgz, tar.bz2, tbz, txz and so on. Full list of supported compression from man:

```
-j, --bzip2 Filter the archive through bzip2(1).
-J, --xz Filter the archive through xz(1).
--lzip Filter the archive through lzip(1).
--lzma Filter the archive through lzma(1).
--lzop Filter the archive through lzop(1).
-z, --gzip, --gunzip, --ungzip Filter the archive through gzip(1).
-Z, --compress, --uncompress Filter the archive through compress(1).
--zstd Filter the archive through zstd(1).
```
Never heard about some but why not support it out of the box.

Also, there are things like 7z that could also get support.

Second thing: parameter expansion used in extracting extension behaves incorrectly if the filename contains a `.` anywhere else. For example, it would not work for `foo.bar.zip` as the extension would be `.bar.zip`. Replacing the rule with `${filename##*.}` would fix that, but that would break double extensions like `.tar.gz`. I don't know how to solve it in an elegant way. Maybe first check the result of `${filename: -6}` against a list of tar.gz, tar.bz and so on, and then move on with `${filename##*.}` for simple extensions?

**Comment by tomaszg7** [comment]
Ok, it was not the last thing. Several more after more testing.

1. Command for `unrar` is broken: it needs `x` option.
2. On my system Geeqie spawns another window to show the new folder, but it is in the archive directory, not in `/tmp/geeqie-archive/....`. Even run outside of this thing, `geeqie --remote --new-window /tmp/` opens Geeqie in cwd, not in /tmp.
3.  In some cases, it even leads to a segfault! The segfault occured when I tried to open a zip or rar file placed in `/tmp` directory. Not really sure what caused it. Here's the backtrace:
```
#0  0x00005555556ad983 in vd_notify_cb ()
#1  0x000055555562cc51 in file_data_check_changed_single_file ()
#2  0x0000555555632140 in file_data_new ()
#3  0x0000555555633170 in file_data_new_group ()
#4  0x0000555555653888 in layout_new_from_config ()
#5  0x0000555555653c2e in layout_new_from_default ()
#6  0x000055555568c30f in gr_new_window ()
#7  0x000055555568c9f7 in remote_cb ()
#8  0x000055555568bd7b in remote_server_client_cb ()
#9  0x00007ffff7232da8 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#10 0x00007ffff7233158 in  () at /usr/lib64/libglib-2.0.so.0
#11 0x00007ffff7233453 in g_main_loop_run () at /usr/lib64/libglib-2.0.so.0
#12 0x00007ffff7a2667d in gtk_main () at /usr/lib64/libgtk-3.so.0
#13 0x00005555555c950c in main ()
```
3. Geeqie should clean up after itself. It's not responsible to leave things in `/tmp`

**Comment by caclark** [comment]
Commit 5cf8ef14 uses libarchive instead of a plugin.

**Comment by tomaszg7** [comment]
It doesn't build for me:
```
misc.c: In function ‘open_archive’:
misc.c:442:2: error: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  442 |  chdir(destination_dir);
      |  ^~~~~~~~~~~~~~~~~~~~~~
misc.c:447:2: error: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  447 |  chdir(current_dir);
      |  ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [Makefile:1128: misc.o] Error 1
```

Moreover you're still missing some extensions - for example no short tar extensions, I propose the following set:
".zip;.rar;.tar;.tar.gz;.tar.bz2;.tar.xz;.tgz;.tbz;.txz;.cbr;.cbz;.gz;.bz2;.xz;.lzh;.lza;.7z"

**Comment by tomaszg7** [comment]
After fixing the build with something like:
```
if (chdir(destination_dir)) return NULL;
...
if (chdir(current_dir)) return NULL;
```
it still works very unpredictably. Log is full of uninformative things without any context, like "Prefix found" or "Header CRC error". 

1. Geeqie still doesn't open new window in the new directory. I think that's unrelated to this issue, it's probably a separate bug introduced by some other recent commit.
2. Some files don't decode properly. I have a RAR file which unrars correctly, but Geeqie decodes only first file, all the rest are full of zeros.
3. Is there supposed to be a way of opening the archive without enabling "left click to open"? I don't see context menu option (I didn't check the source, I admit)

**Comment by caclark** [comment]
> -Werror=unused-result

Whichever way I try I cannot get this flag to work... I assume this is set in your own CFLAGS.


> Geeqie still doesn't open new window in the new directory

Is there anything out of the ordinary in the way /tmp is mounted on your system?


> Some files don't decode properly

Do you have an example you could upload?


> Is there supposed to be a way of opening the archive without enabling "left click to open"

It is on the View menu.

**Comment by tomaszg7** [comment]
> > -Werror=unused-result
> 
> Whichever way I try I cannot get this flag to work... I assume this is set in your own CFLAGS.

No, I don't have it set on my own, it comes from `configure.ac`:

# Add -Werror to the default CFLAGS
CFLAGS+=" -Werror -Wno-error=deprecated-declarations -Wno-error=sign-compare -Wno-error=return-type"

Regardless of the flag, the warning is valid and you should better check if chdir succeeded before going on.

> > Geeqie still doesn't open new window in the new directory
> 
> Is there anything out of the ordinary in the way /tmp is mounted on your system?

It happens with all files and all directories. If I already have Geeqie started, any new window I try to open from command line, opens only in $HOME. Maybe I messed something up with my Geeqie config, I don't know.

> Do you have an example you could upload?

I'll try to find or produce one. However the issue probably lies with libarchive. On Geeqie side, I think that reporting and handling of errors from libarchive could be improved.

> 
> > Is there supposed to be a way of opening the archive without enabling "left click to open"
> 
> It is on the View menu.

Ah, I missed that. Anyway, it might be helpful to put it also on context menu (both right click on file list as on image window).

**Comment by caclark** [comment]
> The file I had problem with was identified by file as RAR 

If the problem file you have is a .cbr, maybe this link, and further links,  are relevant:
https://github.com/Seeneva/seeneva-reader-android/issues/23

The text there implies that libunrar would be better for .cbr files. It is a bit concerning that the library description has the words "non-free version", but if Okular is using it then I guess it should be ok - it would be used only for decompression.

**Comment by tomaszg7** [comment]
CBR are just renamed RAR files, so that doesn't really matter. However following the link you gave, it seems libarchive support of RAR files is rather rudimentary with many features not yet supported.

As for unrar - there is a section in FSF FAQ about it, but I don't really understand it ;) http://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs. Libunrar is described as "free version" from what I see (https://github.com/LiquidFM/libunrar/blob/master/src/license.txt), but it is "free" as in "free of cost", not as in "freedom". I'm not sure that it is worthwhile to add extra code to Geeqie to support these files.
