### ISSUE TITLE
Faster Tagging (Keywords)

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#305]
Hi,

I’d like to use geeqie to quickly tag my photo collection. Compared to other tools, especially f-spot, geeqie lacks behind, especially because there is no auto-completion in the tag entry and one has to use the mouse. Therefore, the following features would be nice:
- [ ] A keyboard shortcut to move the focus into the tag entering window, and back.
- [ ] Auto-Completion of tags against the list of keywords.
- [ ] Even better: Geeqie could optionally remember all keywords it has seen and also offer them in the auto-completion, or automatically add them to the keyword hierarchy.

For me, the keyword hierarchy has little use. My ~500 tags are too many be be browsable in a tree and using the mouse is too slow.

Thanks,
Joachim

Reported by: joachimbreitner

**Comment by mowgli** [comment]
@nomeata, this seems to be your request, right?

**Comment by nomeata** [comment]
Yes, although I found that tagging is not worth the time it takes :-)

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am Do den  5. Mai 2016 um 20:50 schrieb Joachim Breitner:
> Yes, although I found that tagging is not worth the time it takes :-)

Why not? I find, your Ideas are promising.

How would you sort images other way to find them again? If you have some
Ideas...

Regards
   Klaus
- -- 
Klaus Ethgen                              http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16   Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1
Comment: Charset: ISO-8859-1

iQGcBAEBCgAGBQJXK7K2AAoJEKZ8CrGAGfas1XAL/RBbDSkntR3f04ZFxY/AbpJQ
5m02d9pwa0TrEyC3K//orMRwuzhjNlm/XfjdTOzXrn71vI4T9zUBJHaTT7UVdO+9
nK+lCXRHuxyKgWzUqmaJA41WKkpdbXqzxUUup4At6N7FVv6/An9d78AFswvjCuaU
TAVn+TkZYAtjgSwybgkNcL94gyzLTUS80gZqQzaz5W6bdwzbxMx4MXqVPA3Jrpmq
82hM2YBKtVFt5sA83AFGxu9MlGqdz04wI3mLO3fkwN9yy2usAoUCq4dcWF2nc53D
v7fx+OUzm5P/Ul5jVKUq7SQdgu6ikGHbrHLBTkxfQWquYRYCJGCR+vpA0YduJZOY
62wruNC9CVqeJZ+4WLwkl7wrH55FDPV+SseOG5SuZDwW1ulPzTL2M6zbzWmhre2j
QRh7ViPOD6sRCvPsJgGA8RFivZRGYqAWfKxBTk/79wUFue23CwjVAfVebV4ZVZSL
QxGWwaLgw9DEvF+ZxfU3Uy/E1Je1fwO37YhPA9FUrA==
=lg5v
-----END PGP SIGNATURE-----

**Comment by nomeata** [comment]
> Why not? I find, your Ideas are promising. 

I still stand behind my suggestions above: For tagging, the above suggestions would be a usability improvement. I just doubt that I personally would use it as much as I thought I would back then.

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=bd30e33fcf9412f21a566b288e333252739031c5
