### ISSUE TITLE
Batch rename

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#307]
I want to rename all my photos with the date taken as the first part of the name, then a padding and then possibly a text. Is there a code or text I can use for this? I see in the example of the dialog box "formatted rename" that one may use "*" to retain the original file name?
It would be nice if there was a menu to set these settings in the program.
Sincerely, jekroken

Reported by: jekroken

**Comment by caclark** [comment]
This can be achieved via a plugin and a tool such as exiv2 or exiftool.
