### ISSUE TITLE
fit large images to desktop

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#311]
Zoom all images to original size, unless image is larger than desktop.  Images that are larger than desktop should be scaled to fit within the desktop.  For example, if desktop is 1440 x 900 pixels, and image is 1920 x 1080 pixels, scale image to 1440 x 900.  Reduce image to account for window decorations and panels.

Reported by: *anonymous

**Comment by caclark** [comment]
Implemented
