### ISSUE TITLE
Do not filter images by extension

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#312]
on an UNIX-like OS i had expected that a file don’t need to have a
‘correct’ filename-extension to work as suggested.

But look what geeqie does:
$ mkdir test
$ cp &lt;someimage&gt; test/filename_without_extension
$ touch test/idiot.png
$ file test/*
test/filename_without_extension: PNG image data, 1024 x 768,
8-bit/color RGB, non-interlaced
test/idiot.png:                  empty
$ geeqie test/filename_without_extension ; rm -r test

geeqie shows the image as expected. But: if i navigate through the
pictures using Pg-Up and Pg-Dwn, it only displays the “broken”
idiot.png, which is – not just according to file – no image. The real
image is ignored.

Forwarded from http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=588460

Reported by: nijel

**Comment by caclark** [comment]
Closed on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=588460
