### ISSUE TITLE
Exponential Zooming

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#313]
The current way Geeqie does zooming feels wrong to me. Currently I can enter a fixed zoom increment, which is treated additively, i.e. is added/subtracted to the nominator or denominator of the current image scale. The default increment is 0.5. While zooming from 1:1 to 1.5:1 might be too big a steap already, the same increment from 31.5:1 to 32:1 feels rather tiny in comparison.

So instead of this additive increment, I's like to see a multiplicative increment: always multiply or divide the current scale by some fixed amount. So e.g. if the user enters a factor of 1.2, you'd go from 1:1 to 1.2:1 to 1.44:1 to 1.728:1 and so on. After n steps, starting at a scale of s, you'd not end up at s+i*n for some additive increment i, but rather at s*f^n for some multiplicative factor f. That's why I'd call this exponential zooming.

I had a look at the code, thought implementing this should be easy enough, but at first glance things look more complicated than I anticipated. There are places treating zoom=0.0 as "zoom to fit", while others seem to read this as "zoom 1:1" and use negative or positive values to describe the difference to this 1:1 zoom. Until I find a lot of time to dig through all of this, I won't be able to contribute a patch.

Reported by: gagern

**Comment by caclark** [comment]
Fixed in commit f46058ba at geeqie.org
