### ISSUE TITLE
File name in full screen title

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#315]
Situation:
* Looking at jpg images in geeqie, full screen
* Having the corresponding raw images open in rawtherapee

After deciding what to do with an image, I switch windows from geeqie's full screen window to rawtherapee.

The trouble is that, with geeqie in full screen mode, neither of the two geeqie windows shows the image file name. I have to jump through a few hoops to find out. The image file name in the full screen window's title would make it very fast to find the image in rawtherapee.

Thanks :)

Reported by: bburkhart

**Comment by caclark** [comment]
Configure the Image Overlay to show the filename
