### ISSUE TITLE
Add hotkeys for directory navigation

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#317]
Hi, I know that adding too many keybindings can be rather confusing, but I'd love to be able to navigate the directories with the keyboard. The keys could be empty by default, of course. The actions I was thinking would be useful (to me) are:
- Go to parent directory
- Go to next directory in parent
- Go to previous directory in parent
- Go to first child directory

Thanks,
Arnoques

Reported by: arnoques

**Comment by caclark** [comment]
The "Up" (Go to parent directory) action can be set in Preferences/Keyboard.
The other actions can be accessed with the arrow keys.
