### ISSUE TITLE
Option to turn thumbnail generation completely off

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#318]
It'd be great to have an option allowing to turn thumbnail generation completely off.

My use case is folders with ~100 - 200 big RAW/TIFF files and even with smallest/lowest-quality thumbnanils it takes quite some time to generate thumbnails, which I'm not using at all, since always browsing in fullscreen mode. This is quite perfomance issues for non-ssd disks.

Reported by: mahdi1234

**Comment by caclark** [comment]
Select List view, and de-select Show thumbnails
