### ISSUE TITLE
TIFF multipage viewing

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#324]
I think good idea TIFF multipage image viewing. Maybe need something look like ristretto:  scroll with TIFF pages preview and navigation - buttons and hotkeys.

Reported by: viking-coyote

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=debc22c4c22026f895d4c375868aac6ac4f34ad7
