### ISSUE TITLE
Set focus to file list on start

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#327]
Well, the title says all -- please set focus on file list initially, because otherwise on each run it is necessity for the user to do it manually.

Reported by: me-macias

**Comment by caclark** [comment]
#291

**Comment by caclark** [comment]
On entry the Up/Down arrow keys move the cursor on the folder pane.

PageUp/PageDown/Backspace/Space/mouse-wheel move the cursor in the files pane.

This seems to be a reasonable key allocation.
