### ISSUE TITLE
easier way to get cwd when copying

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#329]
When copying selected files, the dialog shows the previous folder instead of the currently-browsed directory, even after a restart. I only ever use geeqie to copy/move files to subdirectories of the currently-browsed directory. Could we have either an option in Preferences to make that the default, or a button in the  copy/move dialog that puts us in "this" directory?

Reported by: unhammer

**Comment by caclark** [comment]
Commit on 2016-04-11:
1797b9e1a522b077f852aa560b35d0fca018c603
