### ISSUE TITLE
Move/Copy when there is a file to be replaces

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#330]
Hi,
Geeqie seems to have most of features listed, but problems start when you attempt to move files to a folder where at least one similar exists. ACDSee had good range of options which could be considered here: Move/Copy those with no conflict, default action (delete original on Move), if files are compared to be exactly similar, and if different: show both pictures to select 'replace' or 'rename', or further auto-rename for different files.

Reported by: docmp

**Comment by caclark** [comment]
Fixed in commit 2dd25168
