### ISSUE TITLE
how to set wallpaper permanently?

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#366]
i didn't use gnome and kde, how to use geeqie to set every time i login x, automatic set wallpaper?

Reported by: *anonymous

**Comment by mowgli** [comment]
That is not a use case for geeqie.

You can use display from imagemagick or Esetroot or xv or xsetbg.

**Comment by zkeng** [comment]
The 'Set as wallpaper' option does not work in many user cases. For example when the wallpaper is set with Feh image viewer, or with Nitrogen wallpaper manager. This and the fact that the wallpaper functionality in Geeqie can not be disabled in the application settings is confusing to users and prevent the application from being included as a preinstalled image viewer in distributions.
