### ISSUE TITLE
Geeqie 1.1 Chinese Translation 

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#372]
I just translate geeqie 1.1 in chinese. Want to share it with other people.
please find the zh_CN.po at attachment. Wish it'll be useful.

By the way, it seems there's a bug sometimes when I click 'view in new window', both old and new-opened window freeze. The Cpu consumption is not high. This occurs especially in operating at 'pan view'.

A moment ago I sent a email asking for help to geeqie-devel@lists.sourceforge.net, 'cause I dunno how to login here. But it's OK now. :)

Reported by: cnlevin

**Comment by caclark** [comment]
Implemented
