### ISSUE TITLE
Please consider committing and installing the supplied AppData file

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#373]
Please consider installing this AppData file: https://raw.githubusercontent.com/hughsie/fedora-appstream/master/appdata-extra/desktop/geeqie.appdata.xml

This is used in GNOME and KDE software installers to add the application description and some screenshots. We'd love to showcase more applications, but without the extra data file we can't. The AppData file needs to be installed to /usr/share/appdata/ on Linux and the basename needs to match the .desktop basename. It would also be great if you could integrate the file with your translation system (e.g. intltool) to make the descriptions translated.

See http://people.freedesktop.org/~hughsient/appdata/ for more details; thanks!

Richard

Reported by: hughsie

**Comment by mowgli** [comment]
@hughsie Please create a pull request.

**Comment by caclark** [comment]
I just Googled "AppStream" to find out about this. I seems to me it is something Geeqie should be involved with.
Gnome's "gnome-software" has entries for RawTherapee, Darktable, etc, but no entry for Geeqie.
Debian's "packagesearch" has an entry for Geeqie, but I think it was made by the Debian maintainer, Michal Čihař.
Unless anyone thinks Geeqie is not ready for this, I'll try to get the necessary AppStream data for Geeqie.
But we could do with a 16:9 aspect ratio screenshot of Geeqie displaying a pretty picture...

**Comment by caclark** [comment]
Implemented in commit:
http://www.geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=0fe09634043fb78aca550f6657923ffb44b761bd
