### ISSUE TITLE
Use Formatted Renaming wrong and you'll lose your pictures, PERMANENTLY!

### ISSUE THREAD

**Issue by MrDrizz** [BestImageViewer/geeqie#380]
So if you use the Formatted Renaming tool and you forget to add ## for the sequence number. Geeqie will **DELETE** all the selected pictures, and this seems to be ** PERMANENT! **
There seems no way to recover from this, the pictures are gone, not in the wastebasket, not hidden.

So make sure you have backups of your pictures before doing a mass rename.

**Comment by caclark** [comment]
On 24/04/16 19:15, MrDrizz wrote:
>
> So if you use the Formatted Renaming tool and you forget to add ## for 
> the sequence number. Geeqie will *DELETE* all the selected pictures, 
> and this seems to be ** PERMANENT! **
> There seems no way to recover from this, the pictures are gone, not in 
> the wastebasket, not hidden.
>
> So make sure you have backups of your pictures before doing a mass rename.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/BestImageViewer/geeqie/issues/380>
>
Hi

The master branch in the repository at geeqie.org now has a commit that 
eliminates this problem.


You can download the latest source tar or make a "git clone" from:

http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git


Colin Clark

**Comment by zas** [comment]
> The master branch in the repository at geeqie.org now has a commit that eliminates this problem.

https://github.com/BestImageViewer/geeqie/commits/master and http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=shortlog;h=refs/heads/master are not in sync ?
Not that it is a serious issue but I thought there was an attempt to make things clear for users / contributors.
If you are handling issues on Github but patch sources elsewhere, it will be messy again soon.
What about PRs on Github ?

**Comment by mowgli** [comment]
@zas, Well, master repository is still the one on geeqie.org. I keep them both as near as possible.

That means, yea, PRs will work fine. As shown in the hidden documentation https://gist.github.com/piscisaureus/3342247, they can be handled via command line. For example, there is one PR currently that I will look into and merge into master shortly.
