### ISSUE TITLE
fullscreen is still broken

### ISSUE THREAD

**Issue by installgentoo** [BestImageViewer/geeqie#382]
since geeqie 1.1 option "fullscreen - determined by window manager" does not work, and fullscreen is broken. it spawns a window with black border that covers your screen no matter what wm does. this has been a known bug on mailing lists 2 years ago with icewm and xmonad. i use awesome wm. no errors are logged on stdout.

**Comment by jkufner** [comment]
See https://github.com/BestImageViewer/geeqie/pull/379 - merged just few days ago.
