### ISSUE TITLE
Build fails on Debian Sid

### ISSUE THREAD

**Issue by russel** [BestImageViewer/geeqie#383]
Using 67ced95378d984c30f53d33c14d7f7427de80f25 on Debian Sid with gcc 5.3.1 (not 6.1.1), I run:

./autogen.sh --prefix=$HOME/Built

and this succeeds fine. However when building, I get a fail:
```
gcc -DHAVE_CONFIG_H -I. -I..    -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include        -I.. -I.. -g -O2 -MT image-load.o -MD -MP -MF .deps/image-load.Tpo -c -o image-load.o image-load.c
image-load.c: In function ‘image_loader_class_init’:
image-load.c:172:9: error: ‘gq_marshal_VOID__INT_INT’ undeclared (first use in this function)
         gq_marshal_VOID__INT_INT,
         ^
```

I had previously built on Fedora Rawhide with gcc 6.1.1 and it built fine.

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi Russel,

Am Mo den  2. Mai 2016 um 15:07 schrieb Russel Winder:
> Using 67ced95378d984c30f53d33c14d7f7427de80f25 on Debian Sid with gcc 5.3.1 (not 6.1.1), I run:
> 
> ./autogen.sh --prefix=$HOME/Built
> 
> and this succeeds fine. However when building, I get a fail:
> ```
> gcc -DHAVE_CONFIG_H -I. -I..    -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include        -I.. -I.. -g -O2 -MT image-load.o -MD -MP -MF .deps/image-load.Tpo -c -o image-load.o image-load.c
> image-load.c: In function ???image_loader_class_init???:
> image-load.c:172:9: error: ???gq_marshal_VOID__INT_INT??? undeclared (first use in this function)
>          gq_marshal_VOID__INT_INT,
>          ^
> ```

Did you use "apt-get build-dep geeqie" first as root? Did you do that
with original upstream version of geeqie in to position of "apt-cache
policy geeqie"? If not, please use original debian geeqie as source for
"apt-get build-dep geeqie" as the packaging informations for debian in
our upstream branches are not working well. They are old and I will not
update them next time as debian is overwriting them anyway.

I use sid myself and I can assure you that it is buildable. And the
error above really looks like you miss some dependencies on your system.

Regards
   Klaus
- -- 
Klaus Ethgen                              http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16   Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1
Comment: Charset: ISO-8859-1

iQGcBAEBCgAGBQJXKazzAAoJEKZ8CrGAGfasSAgMALptjv2CdANwlQ2osLQoUdC+
JD6WFLNrL11v4W7kh3pFsWB0lRIxE1xLqyvb96tTOisxO7w4ihGBFbhJidJN8toY
qhYCh6MhlNJFI7Fq/Pdhv2RnSA9p+DPkZ43wWbHjQqGYUsx2OEyZA2mNishzSoHo
ORJYF4eFk0gGeV26WyIoGZbV6epBJTqsnopA7l4nEM3MjcLL9QyWN7HoJr3Pu9tD
D7QLjixNSrBePEqpVnDK0yexSUh5MnzaAtYHWt1AGSJlzvx/VsfLxK48XH9yDArt
U4C8BGg0ZobRQbE4qH9h2sUBBSyyAjqGF/dUFMPOZNZhm3H7kNtp21uTl2RdE7w3
moX6la+O9HUmPJbhuz7hiIOYkj62oDwdwHrP4qJXVg1Ptsc7scuTqB03lPxonUcb
unYl9ytWGNfQ6/rSLmZuL2NvPwe+5YIFgj+DYKpA+NUiRBV83XFTmZcoNw6Z9nt1
8Z2pSByV5P3F+XkaeCaXmp88gryoib4EanWwrbKCBg==
=sG+j
-----END PGP SIGNATURE-----

**Comment by russel** [comment]
@mowgli Thanks for the reply. I hadn't done the check you suggested as I thought ./autogen.sh would fail to complete if there were missing dependencies. Also I do not have the source package repositories available on these machines. I guess I will have to on one to find out what the problem is.

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi Russel,

Am Mi den  4. Mai 2016 um 10:42 schrieb Russel Winder:
> @mowgli Thanks for the reply. I hadn't done the check you suggested as I thought ./autogen.sh would fail to complete if there were missing dependencies.

Well, most will be detected but there might be some that does not.

> Also I do not have the source package repositories available on these machines. I guess I will have to on one to find out what the problem is.

You can use the following:
```
Build-Depends: debhelper (>= 9),
    dpkg-dev (>= 1.16.1~),
    dh-autoreconf,
    libtool,
    autoconf,
    automake,
    autotools-dev,
    libgtk2.0-dev,
    libexiv2-dev,
    liblcms2-dev,
    liblircclient-dev,
    intltool,
    gnome-doc-utils,
    imagemagick,
    libtiff-dev,
    libjpeg-dev,
    liblua5.1-0-dev
```

Regards
   Klaus
- -- 
Klaus Ethgen                              http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16   Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1
Comment: Charset: ISO-8859-1

iQGcBAEBCgAGBQJXKdEdAAoJEKZ8CrGAGfasHB4L/jqeMFyEV3HUefXX1hasgC75
iwM2S51r2Fobx89kw4nOxtLIjha71dBxDMB/h11ITp3HnV3/oQgFSHGV9X1PtsPz
PsGjyPg7BjX9lqhn7mPnQeDoyyXTDdkcfdkY1SKqXJ7aUcUf/hVvpgwf0qUNwts8
cz0xx+YneDa98JkijI5IQU6m8RzGixvaSI0RzhTVEbr46NLKUXdQTMJ1OvSioJuH
dFYXoB8smnCMOp4THZ8PyZ3XKpn2LTKg2Quh1M5Muw/8eczKbNW1KOR5DcogLHIO
DPofeSkGQakwhWEdAlRO0B+qATHk2FnXv/A6BslT4wpmAGVUVVLD4fHMGqT+z1HP
rb9isaZb5WMIa6nmCyXoMpnP2s9hL6V6FzgVohR2JN+K0esKar/E6lPs0lsFmQ/h
HYDA/wQSs0a61GEwGWx37Fcif8R9GKKqtoxQQZHhSfbK4C97RUJA44vrBzITX/SR
ib9dwuap8PAj3bAj4xCu6jrPNXZvvfx1VSAYQuXOrg==
=y2lL
-----END PGP SIGNATURE-----

**Comment by russel** [comment]
I think issue needs reopening. The problem is not a dependency, but a missing definition. My comment about building on Fedora Rawhide was both true and false: it was a of a slightly earlier version of master. The error exhibits on both Debian Sid and Fedora Rawhide.:
```
gcc -DHAVE_CONFIG_H -I. -I..    -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include        -I.. -I.. -g -O2 -MT image-load.o -MD -MP -MF .deps/image-load.Tpo -c -o image-load.o image-load.c
image-load.c: In function ‘image_loader_class_init’:
image-load.c:172:9: error: ‘gq_marshal_VOID__INT_INT’ undeclared (first use in this function)
         gq_marshal_VOID__INT_INT,
         ^
image-load.c:172:9: note: each undeclared identifier is reported only once for each function it appears in
```
and searching for the string in the whole codebase reveals:
```
|> grep -r -i gq_marshal_VOID__INT_INT
Binary file src/gq-marshal.o matches
src/gq-marshal.h:extern void gq_marshal_VOID__INT_INT_INT_INT (GClosure     *closure,
src/gq-marshal.c:gq_marshal_VOID__INT_INT_INT_INT (GClosure     *closure,
src/image-load.c:			     gq_marshal_VOID__INT_INT_INT_INT,
src/image-load.c:			     gq_marshal_VOID__INT_INT,
```
So the function reference `gq_marshal_VOID__INT_INT` is indeed undeclared.

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi Russel,

Am Mi den  4. Mai 2016 um 16:35 schrieb Russel Winder:
> I think issue needs reopening. The problem is not a dependency, but a missing definition. My comment about building on Fedora Rawhide was both true and false: it was a of a slightly earlier version of master. The error exhibits on both Debian Sid and Fedora Rawhide.:
> ```
> gcc -DHAVE_CONFIG_H -I. -I..    -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include        -I.. -I.. -g -O2 -MT image-load.o -MD -MP -MF .deps/image-load.Tpo -c -o image-load.o image-load.c
> image-load.c: In function ???image_loader_class_init???:
> image-load.c:172:9: error: ???gq_marshal_VOID__INT_INT??? undeclared (first use in this function)
>          gq_marshal_VOID__INT_INT,
>          ^
> image-load.c:172:9: note: each undeclared identifier is reported only once for each function it appears in
> ```
> and searching for the string in the whole codebase reveals:
> ```
> |> grep -r -i gq_marshal_VOID__INT_INT
> Binary file src/gq-marshal.o matches
> src/gq-marshal.h:extern void gq_marshal_VOID__INT_INT_INT_INT (GClosure     *closure,
> src/gq-marshal.c:gq_marshal_VOID__INT_INT_INT_INT (GClosure     *closure,
> src/image-load.c:			     gq_marshal_VOID__INT_INT_INT_INT,
> src/image-load.c:			     gq_marshal_VOID__INT_INT,
> ```
> So the function reference `gq_marshal_VOID__INT_INT` is indeed undeclared.

I know that. But the problem is really about your build environment.

I had that issue some times in the past too. But it was always some
fucked up build environment of mine.

I have two sources for the problem:
- - You use ccache.. From time to time, especially when gcc version
  changes drastically between the first and the second build version
- - You compiled the stuff once with missing libraries and for some
  reason, make is not making it proper afterwards.

Both can be solved by issuing: "git reset --hard; git clean -fdx" and
then, after installing all dependencies that I told you, starting with
"./autogen.sh; make"

But be sure not to use ccache now or clean ccache completely with
"ccache -C".

Believe me, it is always this trouble when the error comes about the
gq_marshal_* stuff. The first time I did have that, I searched days
before I start again without ccache and with clean checkout.

Regards
   Klaus
- -- 
Klaus Ethgen                              http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16   Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1
Comment: Charset: ISO-8859-1

iQGcBAEBCgAGBQJXKiDmAAoJEKZ8CrGAGfascfoL/iWSmRVNlnOLRTsqZD6pG3VP
aMA6s7xZKLQ1yOJdp98EKdnMFILQzq+S6rvDAGPieDSVYUn8szCXyk40J9LJG0kF
+g5xe08gijCFnEa+NAnryQo5ssj52p3Kg9Irhhe+ugmm8QcKMO4whIP/Ko39NP5M
R9hVI1iMzCBI+ttAp3Sb0TrRfBzyPb5OwglKA6HH2dDy7s5GyfINUac94KLhpxES
wflY+hv5+jefJZm5+8i5o+kg/JYXOxx5NRN+YVR1eGeQCt6p8Cm6boDy9/Wv1sCy
fQ60HnZEU1Bk60V4RtR2zjVQcO7dduC7WZHgEzt1BJPz5SKAajY8Ryn86djRYlAJ
ovz7Dw1vl2C2R8zodVIX9AczfD0rGH5UKZKN57aDHhzE/LVF/JU3TUJ/M2vb7aXx
5f0Wj+zhlS3f+d47hEhxHa2P88A+sSrowQ0g1jSp5NXHK3rnYIQmTqGhiICqgdxu
J6QV0us/y4XpiCbeL/hZaFUDUGty2xoYSmuk2QPbbA==
=qCao
-----END PGP SIGNATURE-----

**Comment by mowgli** [comment]
Please click on the three dots in my last mail, Github does not handle mails greatfully. :-(

**Comment by mowgli** [comment]
Ah, I might have find the reason.
The point is that there is a receipe to _generate_ that files that are in git.

Most of the time that works well, but if gq-marshal.list has a slightly more current timestamp, it fails.

**Comment by russel** [comment]
If the symbol `gq_marshal_VOID__INT_INT` is not defined anywhere in the Geeqie code, and yet is used in the code, I do not see how the environment is part of the problem. There surely has to be at least an extern declaration in the code even if the function body is from elsewhere. This however has now become a rhetorical issue.

The hint about the git reset and git clean does seem to have done the job: the problem was not the environment but my repository. I have no idea what I had wrong, but clearly I had something wrong. Now fixed, and I am a happy bunny. :-)

(PS I build from scratch (starting with ./autogen.sh --prefix=$HOME/Built) every time so I believe there is no hysteresis. I haven't got ccache and never use it.)

**Comment by mowgli** [comment]
So, should be finally fixed. :-)

**Comment by russel** [comment]
The commit has introduced an error :-(
```
nclude/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include        -I.. -I.. -g -O2 -MT gq-marshal.o -MD -MP -MF .deps/gq-marshal.Tpo -c -o gq-marshal.o gq-marshal.c
gq-marshal.c:1:24: fatal error: gq-marshal.h: No such file or directory
```

**Comment by mowgli** [comment]
Checkout the next commit.

That part of code was really nasty!

**Comment by russel** [comment]
I believe I get good builds both on Debian Sid and Fedora Rawhide. Thanks for getting me sorted.
