### ISSUE TITLE
NEF file preview image size

### ISSUE THREAD

**Issue by jtompkins66** [BestImageViewer/geeqie#384]
I have compiled and been using geeqie1.0 and 1.1 on Ubuntu 12.04 and 14.04 fine for a long time. I recently upgraded to 16.04 and while geeqie 1.1 (using gtk2) and 1.2.3 (using gtk3) compile fine, when I view a Nikon .NEF RAW file the image shown is 160x120 pixels rather than the expected (for my D600) 6016x4016. It all worked fine on 14.04 using the same NEF files and the same geeqie 1.1 (compiled on 14.04). JPEGs and TIFFs display fine. I have noticed the pre-compiled geeqie 1.2.2 supplied by Ubuntu also works fine. But for various reasons I want to compile my own geeqie rather than always using the Ubuntu supplied one. I m still trying to figure it out but any help is appreciated!

**Comment by jtompkins66** [comment]
I figured it out. The Ubuntu "source" package for geeqie-1.2.2 has a patch:

geeqie (1:1.2.2-2) unstable; urgency=medium

  * Do not provide menu file as we ship desktop one as well.
  * Add patch to fix display if RAW images caused by gcc 5 transition
    (Closes: #800350, #798274, #799353). 

 -- Michal Čihař <nijel@debian.org>  Tue, 03 Nov 2015 08:58:05 +0100

So they claim its caused by moving to GCC 5. Here is the patch:

Subject: Fix RAW photos display with new GCC
From: David Kalnischkies <david@kalnischkies.de>

diff --git a/src/exiv2.cc b/src/exiv2.cc
index 455c8d3..98029cd 100644
--- a/src/exiv2.cc
+++ b/src/exiv2.cc
@@ -16,6 +16,7 @@
 #include <exiv2/image.hpp>
 #include <exiv2/exif.hpp>
 #include <iostream>
+#include <string>
 
 // EXIV2_TEST_VERSION is defined in Exiv2 0.15 and newer.
 #ifndef EXIV2_TEST_VERSION
@@ -1130,9 +1131,9 @@ guchar *exif_get_preview(ExifData *exif, guint *data_len, gint requested_width,
 
 	if (!exif->image()) return NULL;
 	
-	const char* path = exif->image()->io().path().c_str();
+	std::string const path = exif->image()->io().path();
 	/* given image pathname, first do simple (and fast) file extension test */
-	gboolean is_raw = filter_file_class(path, FORMAT_CLASS_RAWIMAGE);
+	gboolean is_raw = filter_file_class(path.c_str(), FORMAT_CLASS_RAWIMAGE);
 	
 	if (!is_raw && requested_width == 0) return NULL;
 
@@ -1232,10 +1233,10 @@ extern "C" guchar *exif_get_preview(ExifData *exif, guint *data_len, gint reques
 	if (!exif) return NULL;
 	if (!exif->image()) return NULL;
 
-	const char* path = exif->image()->io().path().c_str();
+	std::string const path = exif->image()->io().path();
 
 	/* given image pathname, first do simple (and fast) file extension test */
-	if (!filter_file_class(path, FORMAT_CLASS_RAWIMAGE)) return NULL;
+	if (!filter_file_class(path.c_str(), FORMAT_CLASS_RAWIMAGE)) return NULL;
 
 	try {
 		struct stat st;
@@ -1246,9 +1247,9 @@ extern "C" guchar *exif_get_preview(ExifData *exif, guint *data_len, gint reques
 		
 		RawFile rf(exif->image()->io());
 		offset = rf.preview_offset();
-		DEBUG_1("%s: offset %lu", path, offset);
+		DEBUG_1("%s: offset %lu", path.c_str(), offset);
 		
-		fd = open(path, O_RDONLY);
+		fd = open(path.c_str(), O_RDONLY);
 		if (fd == -1)
 			{
 			return NULL;

Works correctly after applying the patch

**Comment by mowgli** [comment]
If you look at current master branch, you see that the bug is already fixed in 96db62d2 two month ago.
