### ISSUE TITLE
Variables assigned but never used, filedata.c

### ISSUE THREAD

**Issue by davidsilveiro** [BestImageViewer/geeqie#385]
**src/filedata.c:383** - Variable **changed**
**src/filedata.c:2326** - Variable **have_dest**

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

How did you search for that?

Am Mi den  4. Mai 2016 um  2:00 schrieb David Silveiro:
> **src/filedata.c:383** - Variable **changed**

This is used right two lines below. But it is the debug macro that uses
it so it is optimized out in normal builds.

> **src/filedata.c:2326** - Variable **have_dest**

This is a bit less trivial.

The variable is used lines above and this assignment is not really
necessary. However, I'll leave that in for the moment as it does no
harm. This is purely cosmetic.

Regards
   Klaus
- -- 
Klaus Ethgen                              http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16   Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1
Comment: Charset: ISO-8859-1

iQGcBAEBCgAGBQJXKaLCAAoJEKZ8CrGAGfasYtAL/1j0o1jlwms0RDzJQiJngobk
05AWHdv4pnWMKb77vqAKmGbKw15YVzsVuN9AmFM3xUm5YnDiMeFV1ptBbOqN6PLf
jzIqR7yl0kQrNiB77m33KxErFx2JjHDnDgS8z48H4gLzFCsn8wrCaxl7Ec5Kl3KC
sv3Nn75r42fyDlJSctJqzKfXzHBkTM0na6PSXkxmJt72CuQWnb+QrIwj++tuKMBL
RbSgZx05/PqODwQrrgjkDB8ruAPKB5jiXEcqnFFWERPy7eUV9mk0J6abw+Wmzn/a
qK07PCa5/v7zuR+zkW5bHasiQMiQlzZWaNiGtLqnHLE3/FgLLjOtZTaWRxfeD8cy
dN3sHNeT1S53MdaVIruYEjGj70XJKR8OyPBJqjJ/ccuBxfSSFnBuIqsZcZQ6Wjsq
5qFVjFscSU4XLvNkMfMEDYNbWcpsV6PchazenJj21B9aKIJUjX5CWXKNv7Dx2nke
+WHeTfCvE7J/dQfSutZLjkHQIYjrWzx1Wxxm1le9TA==
=Z/CN
-----END PGP SIGNATURE-----

**Comment by caclark** [comment]
Variable changed - Fixed in commit a1a73a9d
Variable have_dest - Fixed elsewhere
