### ISSUE TITLE
duplicate search entries not being deleted with files

### ISSUE THREAD

**Issue by installgentoo** [BestImageViewer/geeqie#391]
in 1.0 when you delete images from disk they are cleared from duplicates.

in 1.2.3 they stay there which makes it impossible to delete sets by hand.

**Comment by installgentoo** [comment]
actually this is a problem from 1.1 and it's probably related to how slow every version post 1.0 at recognising filesystem changes.

i swear, it's like this application is getting worse with every release.

**Comment by installgentoo** [comment]
https://sourceforge.net/p/geeqie/bugs/190/

**Comment by mowgli** [comment]
Please check master version. This is closed in 8a2a369. I didn't see that bug as that important to backport it to 1.2.3.

And please don't refer to sourceforge, all bugs are migrated here[0].

[0] https://github.com/BestImageViewer/geeqie/issues/190
