### ISSUE TITLE
Update polish translation

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#392]
For @jaceq :-)

**Comment by tomaszg7** [comment]
If you need help, I can do it even though I usually use Geeqie in English.

**Comment by mowgli** [comment]
@jaceq, Have a look at Tomasz' changes (bb44257) if you have time. He is not fully clear about one or the other.

However, thanks, @tomaszg7, for the update.

**Comment by caclark** [comment]
Commit bb44257b2
