### ISSUE TITLE
Allow only one instance of Geeqie, or specify instance when loading image

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#398]
I need to be able to load images in only one instance of Geeqie, but I cannot find a way to do that, there is no "Allow multiple instances" settings I could disable. If that is the case, this is a feature request for adding that. Otherwise, please point me to where this option is.

An alternative solution would be to be able to specify whether to use an existing instance, if one exists, or to start a new one, when loading an image, though this would only be of use to people loading images via command-line.

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am Sa den 28. Mai 2016 um 19:12 schrieb Beep6581:
> I need to be able to load images in only one instance of Geeqie, but I cannot find a way to do that, there is no "Allow multiple instances" settings I could disable. If that is the case, this is a feature request for adding that. Otherwise, please point me to where this option is.
> 
> An alternative solution would be to be able to specify whether to use an existing instance, if one exists, or to start a new one, when loading an image, though this would only be of use to people loading images via command-line.

Did you try to use --remote?

   ~> geeqie --remote-help
   Remote command list:
     -n         , --next                        next image
     -b         , --back                        previous image
		  --first                       first image
		  --last                        last image
     -f         , --fullscreen                  toggle full screen
     -fs        , --fullscreen-start            start full screen
     -fS        , --fullscreen-stop             stop full screen
     -s         , --slideshow                   toggle slide show
     -ss        , --slideshow-start             start slide show
     -sS        , --slideshow-stop              stop slide show
		  --slideshow-recurse:<FOLDER>  start recursive slide show in FOLDER
     -d<[N][.M]>, --delay=<[N][.M]>             set slide show delay to N.M seconds
     +t         , --tools-show                  show tools
     -t         , --tools-hide                  hide tools
     -q         , --quit                        quit
		  --config-load:<FILE>          load configuration from FILE
		  --get-sidecars:<FILE>         get list of sidecars of FILE
		  --get-destination:<FILE>      get destination path of FILE
		  file:<FILE>                   open FILE
		  view:<FILE>                   open FILE in new window
		  --list-clear                  clear command line collection list
		  --list-add:<FILE>             add FILE to command line collection list
		  raise                         bring the Geeqie window to the top

     All other command line parameters are used as plain files if they exists.

Gruß
   Klaus
- -- 
Klaus Ethgen                              http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16   Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1
Comment: Charset: ISO-8859-1

iQGcBAEBCgAGBQJXSeDwAAoJEKZ8CrGAGfasv7AMAJdt6g73Owq7A3Oi13iVoNwl
fHJMjLyU0aqi7X9xiHupiM6qb8OpDLpewtcLwS4Y1Gw69pyvslHZ4kk94Gcnvngz
dnbaZIzT+zRgBl+xngVdo3OfAoebFTwsvvhpb/WMg96R8HTUFhgH3NQdOkMdlebg
r0xyoRKRC5urqzmIBN1eFg7PHAibtnU/8myuhkRWTZNOnw3pjNQ4N6fc8yaFl6FO
aZ/Mjqbsa44W6rRIBAFMTqGU993rnurPkZ4efHlyPZwb+wytkQfrogoTyabZhB1n
Wb6yrBwEkdG7r6HQJtwVg1S8FrC2OmDPVKyZY9VqL9mVkCP+TXUuKXeC0RBPJY3u
9j/PO95B0js3cM/VcSqnVPrX4V7dZ9GdwmtnSp5UgGyAVYw13pSV4BtxIzhTBusX
5FXW3PtyjaJxF0M4YRFNlU/Dd1tS0OfC8LSGPjWwU3vnCp9qisapiZK7I7NTb5+0
OEYnpWESu0LfCDqZ01SSjRzQBKc9Nbl/yRucLhyz1A==
=mPVS
-----END PGP SIGNATURE-----

**Comment by Beep6581** [comment]
Hello

I saw those commands before posting, but it doesn't look like they can help.
I run `geeqie 1.jpg` from a console (or, more specifically, I set up RawTherapee to use Geeqie as an external editor, using `/usr/bin/geeqie` as the command-line argument). How do I get a new image to open in the same instance? `geeqie file:2.jpg` and `geeqie --list-add:2.jpg` both open the second image in a new instance.

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Am Sa den 28. Mai 2016 um 20:17 schrieb Beep6581:
> I saw those commands before posting, but it doesn't look like they can help.
> I run `geeqie 1.jpg` from a console (or, more specifically, I set up RawTherapee to use Geeqie as an external editor, using `/usr/bin/geeqie` as the command-line argument). How do I get a new image to open in the same instance? `geeqie file:2.jpg` and `geeqie --list-add:2.jpg` both open the second image in a new instance.

geeqie --remote 2.jpg

Regards
   Klaus
- -- 
Klaus Ethgen                              http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16   Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1
Comment: Charset: ISO-8859-1

iQGcBAEBCgAGBQJXSfB3AAoJEKZ8CrGAGfasFegMAJQrKl46Dm0mDxnQAUmfZDK7
DTeMAOvGNCkKZA+SYym9GsrHdzEQouuaLgcfHOhy3TV7+1TZnjmjM2PK/4Z0IlLY
3TXGxh4mMolbAKDppWIQpzVjMAjbYsGefY5/3Brd/9zmTH4Nxgjb14kCcSNIrCt9
dOokojPfZD8L3xM6ktMWtlz665A6dbvspQ4RqX6CpeiCncbhFRE6H1xEBoL00CVz
plGyyoP+IvJVjyXKMzIiQpMRaKZb0Qm6D4KWqEnLmbsk6P1jtwPK5ZvibwBPgJpf
NHnLs4S+wLy6h21ikCiTwoNn+OfgfN7Q7cO/N5I9usx8CrC2S13cqnq6ZUS299JF
oQkHvWRVgjMvDkJEyuCdBmTgw0WScbMkSotLh3gKChcbibHc65zpoleq7jBXTx0i
lL6/fMkQQRi/3/O+p4GBXCb5SGd/WQsJFhXn28Xs5BAvs80K9T6k/OVUgNIrWzmh
ct0kjzEbFqGLpF0j3uDygV1K38UTnbtgawEkJJsd2Q==
=jcbu
-----END PGP SIGNATURE-----

**Comment by Beep6581** [comment]
That works, thank you!
