### ISSUE TITLE
list xcf files

### ISSUE THREAD

**Issue by norayr** [BestImageViewer/geeqie#405]
program lists raw files, though not always can preview them well. why not list xcf files, and in case when preview is impossible, show .jpg file with the same name, if it exists.

i keep my photos as raw, xcf, and jpg.
often need to go through the directories, and open xcf file in gimp. however geeqie does not list that xcf file and it's impossible to right click it and open it in gimp.

thank you.

**Comment by dannielsoares** [comment]
You can add custom extensions to the file types list, at preferences →files. But unfortunately .xcf, ora, kra, and psd files aren't previewed. I think that showing a file of another extension with the same name is not a solution that would work to most people. (I'm not a developer, just two-cent-ing around)

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Am Mi den  7. Sep 2016 um  2:04 schrieb dannielsoares:
> You can add custom extensions to the file types list, at preferences ???files. But unfortunately .xcf, ora, kra, and psd files aren't previewed. I think that showing a file of another extension with the same name is not a solution that would work to most people. (I'm not a developer, just two-cent-ing around)

At least .xcf files can be configured to have a preview. As it is not in
the competence of geeqie to display images, you need to tell pixbuf how
to read them. There is a loader[0] available to do so.

Regards
   Klaus

[0] http://www.geeqie.org/cgi-bin/gitweb.cgi?p=geeqie/xcf-pixbuf-loader.git;a=summary
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGcBAEBCgAGBQJXz6RRAAoJEKZ8CrGAGfash9QL/3RaqM0j2XETdjKkNHFKoPqI
TZJnTb2WcPYhFPEyHqLZpi1sSP8YGEh+f0cR+cAAerrRUGc4K2KxWt2cm91ioQVc
Xm2S+K/0IUcUaaKJm2op2Nvab9imQIK3WUQwtWj70xB85Wfcv3A4YL8jnpwEpdmh
V9/TGZCS6zQkcAkmvPJNLr88IB9JMOVZfRSMExctnDqf7M+qJnTrz7gKbcAxSlOY
zxrh2jRgYF0r54dLEYk4IryyCdF8mDWjwEVbYV23GB4hCkTNJYKRBGVIsFPpCJ9W
mAWpZmYLcahO0hwggnbz/fOXd5a+CSRQBfcvOiOA4ObfrvIVySEdr25O6FroBxy0
M5pdE/BGkyvdT7LWAoQuBTean5lhnZrXo3F3/d5PKYmM6rF20xNVCPIPL0V00JFn
BvtUTMeWcfxPtFxUFmjgvHyfZEZWHuzqbfae93Rj3ENBhvbFTr6HS88R43gwEthD
bTWSWYnKsjBfWbDgET3zkdFmnK7B9ondiVcOcnAG3w==
=I6aY
-----END PGP SIGNATURE-----

**Comment by dannielsoares** [comment]
Thanks! I didn't know about that. I wonder why GIMP itself doesn't provide it.

**Comment by caclark** [comment]
Documented in commit 64e5525bad
