### ISSUE TITLE
File sorting by number - show filename without index first

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#417]
In 1.3 files are sorted as follows:
- foo-1.tif
- foo-2.tif
- foo.tif

It would be nice if there was a sorting method which sorted like this:
- foo.tif
- foo-1.tif
- foo-2.tif

**Comment by unterwulf** [comment]
You can achieve this without changing Geeqie itself. Just make a fork of your locale with a collation sequence of your preference and run Geeqie like `LC_COLLATE=en_US.utf8@ext_first geeqie`. This will also work for other software that respects locales.
