### ISSUE TITLE
After leaving fullscreen, geeqie window does not get focus

### ISSUE THREAD

**Issue by waptaff** [BestImageViewer/geeqie#418]
Hi.  This might be an edge case because of my setup.  I use three monitors with xrandr, along with awesome window manager.

If I place geeqie on monitor 1, go fullscreen then leave fullscreen, focus comes back to geeqie on monitor 1.

Same with monitor 3.

But geeqie on monitor 2, if I go fullscreen then leave fullscreen, focus comes back to a random window on monitor 1 (or if no window, nothing has focus).

Tried the different fullscreen options (Determined by WM, Active Screen, Active Window), doesn't change the behaviour.  Tried gtk2 and gtk3 builds, behavior remains.

This was introduced with 1.3 — didn't have those issues with 1.2.3 (though there were different issues with fullscreen in 1.2.3).

Anything I can try to help troubleshoot this?

Thanks,

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi Patrice,

Am Di den 12. Jul 2016 um  4:04 schrieb Patrice Levesque:
> Hi.  This might be an edge case because of my setup.  I use three monitors with xrandr, along with awesome window manager.
[...]
> But geeqie on monitor 2, if I go fullscreen then leave fullscreen, focus comes back to a random window on monitor 1 (or if no window, nothing has focus).
> 
> Tried the different fullscreen options (Determined by WM, Active Screen, Active Window), doesn't change the behaviour.  Tried gtk2 and gtk3 builds, behavior remains.
> 
> This was introduced with 1.3 ??? didn't have those issues with 1.2.3 (though there were different issues with fullscreen in 1.2.3).
> 
> Anything I can try to help troubleshoot this?

Well, you can do a git bisect.. "git bisect start v1.3 v1.2.3" to find
out the version that introduced the problem.

However, I think that this is a corner case of the fullscreen problem we
had before. So I am not sure if it is easy fixable without breaking all
other uses.

Regards
   Klaus
- -- 
Klaus Ethgen                              http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16   Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2
Comment: Charset: ISO-8859-1

iQGcBAEBCgAGBQJXhI6HAAoJEKZ8CrGAGfas0bMMALCQtBgNqhN9mFOW3Qy1CPxI
RbZVC2xs0+W45SAiU6RolMEHF9lPk+S0Z4i8vz7sMUo+Ygs5MuYCAXfzdD+y6VKp
QijzU4MAVhfPT61TsuRwoNuRHB11uAayjDToEFX3EDtNRRn9vfFHShEWzlKSTg6W
Lz0S+LbC1HUHjkz1F3DEBQdWtOyXHrpUur/F85gsQBXRZTVBuhg3fdGPx6jrQLSc
VViPW9yS+eBhwOaJOIRfW02zrwZ9ljLanEwbOXg44CiX732R068x0txeNfAug+ab
3L/63ji6RpBzU9eoPtUrKA1Gkdc+WwSN9OCsTR8BBx1hnOKoi7Gzn9+gTwLOrdyN
K+v9Vzk9LHNJwPlKuV5lLovQ/JZWJ6vnYwmsFRWQVQvbeHU5pI+TD4LdQeiC+arC
dt3B1FHvHFkm2WwLtFuNkK/YYuhL0C1h0pkPn5+5AR+OpEXR3qbFQWUsH2YPcTgn
C7hJWBfpYGPmfILIi1Zcq3g/4PiW7X/8E8SwAN3vwg==
=8QZM
-----END PGP SIGNATURE-----

**Comment by waptaff** [comment]
Determined the commit which introduced the issue is a16635ca1d8fe42349f9e22bd311d3118eff2608

I can fix the problem locally by forcing the focus back to the geeqie window once fullscreen mode has been left.  I guess this is the intended behaviour at all times so this patch should not introduce unwanted side-effects.

Let me know if I should find another way of handling the issue.

Thanks,

[post-fullscreen-focus.patch.txt](https://github.com/BestImageViewer/geeqie/files/359178/post-fullscreen-focus.patch.txt)

**Comment by waptaff** [comment]
Created PR https://github.com/BestImageViewer/geeqie/pull/419
