### ISSUE TITLE
Bookmarks?

### ISSUE THREAD

**Issue by dannielsoares** [BestImageViewer/geeqie#431]
I find a few results that seem to indicate that there are bookmarks in Geeqie, but I can't find how to use them. Are they in GTK3 only or they're something restricted to file dialogs? I'm guessing it may be the latter, while I was hoping for something more like adding paths to the "go" menu in some more mundane fashion than the way I'm using -- "editor" files for paths with "remote" commands. 

By the way, is there a way to send a "remote" command to the same instance that is running ("or" the one that invoked the script/editor, probably those are the same)? Without that those fake bookmarks only work properly with a single instance. 

Edit/PS: I've just recently compiled the newest version, and it seems it already behaves more appropriately, "magically", as I described, instead of the -r command controlling a different instance or spawning yet another. That's funny, I thought for a moment it was behaving just as the ubuntu release or "worse" in this regard ("worse" in quotes as it's not the standard usage).

**Comment by caclark** [comment]
I think bookmarks are only used as a destination in copy/move - either the normal copy/move or via the sort sidebar.

I would like the folder pane to have an additional narrow vertical pane on the left-hand side to hold bookmarks. Clicking on a bookmark would change the focus to the indicated folder.
As with Nautilus for instance.

**Comment by caclark** [comment]
Implemented in commit e45c365df0

**Comment by tomaszg7** [comment]
From what I can see, pressing "+" in the shortcut pane opens a shortcut adding window defaulting to "/home/user". It would be more reasonable if it would default to the current active folder. Alternatively there could be an option in context menu of a directory to add a shortcut. Drag-n-dropping was not an obvious method for me.

**Comment by caclark** [comment]
A way to alleviate this is: after you press "+" the Add Shortcut dialogue itself has a set of bookmarks/shortcuts, and the top one should be the "dot" folder. Clicking that will give you the CWD.

This was implemented as a result of #329, but it works for this case too.
