### ISSUE TITLE
Add 'Losslessly rotate image' keyboard shortcuts

### ISSUE THREAD

**Issue by SimonDedman** [BestImageViewer/geeqie#436]
Somewhat related to [this](https://github.com/BestImageViewer/geeqie/issues/264);

To losslessly rotate images in v1.2 you had to go
edit> orientation > losslessly roate image [clockwise/counterclockwise]
There is no assigned keyboard shortcut not any entry in the keyboard shortcuts to add them. Please could we have this? 

(FWIW, I no longer have losslessly rotate images in [Christian Heckendorf's fork b484a28](https://github.com/heckendorfc/geeqie/tree/animation); he hasn't changed this so has losslessly rotate images been removed as a feature, or is it just the default now?)

**Comment by caclark** [comment]
It looks like the rotate options went missing on 2009-06-15, and were replaced by the single "Apply the orientation..." option.

I find the Orientation menu a little confusing - maybe newcomers/casual users do also.

The first 6 menus entries change only the displayed image - the changed orientation is lost when Geeqie closes (or probably when the associated filedata structure is deleted).

The entry "Apply the orientation to image content" ignores the displayed image, and uses only the exif orientation flag to rotate the image. The image file is updated. (The command used is exiftran -aip ).
Only jpg and tiff files are modified - others types are ignored, but no error given.

Maybe some name changes in the menu would help, and maybe the original rotation options could be restored e.g.:
Rotate displayed image clockwise
Rotate displayed image anti-clockwise
etc etc
<separator line>
Rotate disk image to exif orientation
Rotate disk image 90deg
etc etc.
---------------------------
If most image viewers these days are aware of the exif orientation flag, then rotating the image is not really necessary. Only the exif flag needs to be updated. Exiftools could then be used, which is an advantage as it supports most file types.
---------------------------
And then there is the "Write altered image orientation to the metadata" option, which is so well hidden I doubt any casual users have found it.
If this is selected, the currently displayed orientation is written to the metadata orientation flag in the file (when the write operation happens is also selectable in the options).

This is the option I've been using, along with some home-built .desktop files, to orientate scanned slides and negatives.

Maybe the reservations expressed 7 years ago about exif flags are no longer of concern, and perhaps some changes could be made.

Colin Clark

**Comment by SimonDedman** [comment]
Sounds like there's scope for some handy improvements, thanks Colin!

**Comment by caclark** [comment]
Fixed in commit 9313974a6 at geeqie.org

Additional entries on Edit/Orientation menu:
Write orientation to file
Write orientation to file (preserve timestamp)

Preferences/Metadata option "Write altered image orientation to the metadata" must be off.
Exiftran and mogrify must be installed.

Thumbnails in the cache are not updated. I'll get around to it.

**Comment by Safari77** [comment]
After running geeqie, it creates a new file in cwd:
```
$ cat null
/usr/bin/mogrify
```

Maybe you want to rethink that.

**Comment by caclark** [comment]
Fixed in commit 68c4796e43 at geeqie.org

Thanks for the comment

**Comment by tomaszg7** [comment]
You should also redirect stderr to /dev/null. Otherwise you see in console messages like "which: no exiftran in (xxxx)".

Moreover they are produced 4 times. It suggest that maybe the result should be remembered somewhere instead of repeating the test.

**Comment by caclark** [comment]
> You should also redirect stderr to /dev/null. Otherwise you see in console messages like "which: no exiftran in (xxxx)".

Fixed in commit 89575fd7b1 at geeqie.org
