### ISSUE TITLE
New release with rendering intent feature

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#439]
Hello

Could the Geeqie team please consider releasing a new version so that the color-managed world can benefit from the fact that this new version will be the first one with [correctly working rendering intent](https://github.com/BestImageViewer/geeqie/issues/414)?

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am Do den 20. Okt 2016 um 11:34 schrieb Beep6581:
> Could the Geeqie team please consider releasing a new version so that the color-managed world can benefit from the fact that this new version will be the first one with [correctly working rendering intent](https://github.com/BestImageViewer/geeqie/issues/414)?

Occasionally, yes.

There are other patches waiting for inclusion.

Please don't use the issue tracker for such requests than the mailing
list. Issue tracker should be for bugs or problems, not for such
requests.

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGcBAEBCgAGBQJYCcF2AAoJEKZ8CrGAGfas1I0L/RqKRkrb2yWtHqWvyFXXt8Xz
nxSpqw6iZ2SqACgJeveHLKAtTl8q7XVei0qixwIpLhmjbLOB/EnzIfeaya+TqZ2D
La0LHlNS0zqR16mXRKBLeVtMR6lrb7Nb4DQSzr51wTExO7S39olCqK7ME/b54rcQ
hU9a5oB1j3rNKzjfkQVTS1EBRGaXMZRNe2rkHxR6FEHNqOIc/kF4DXho+rhstrO8
46MWZ798pkinVuwyJ4qJ2F7YIWC6Q1EkRMulosPDczYW9KGw2ZZJE559NUxVHdeA
AnjH9cFRDzeLM2gEp0RJ5o2RAXRgYOte8d3WtEuab7LEKpAmXClBuFtr38YMmGQT
F/Og4j23+t0msXQlk7FeXnBtPntfxYQLJ9FSx7934V+8ma1wmNl6G9pz/yQH5BPe
32J4CDuzRR1eE4SMWEdjMK57Yasmx/WLaj2qWUxI8oKVtiyBUOJU+dIWb0OWZZTS
L7M0MCy7ygdilZ+ADp7dSXZfUq7+tQIo1loiJs8V/g==
=ERcw
-----END PGP SIGNATURE-----

**Comment by caclark** [comment]
Implemented.
