### ISSUE TITLE
User-definable toolbar

### ISSUE THREAD

**Issue by caclark** [BestImageViewer/geeqie#444]
I would like the contents of the toolbar to be definable by the user - with both menu items and valid .desktop files permitted to be included.

As a concept I think this is fairly straightforward. The array menu_entries[] in layout_util.c contains most of the possible entries, and the list of .desktop files is also already available (somewhere).

**Comment by caclark** [comment]
Implemented in commit 5ff96301d2 at geeqie.org

A problem is that there are not enough icons, so several actions share the same icon (although the tooltip shows which action is to be used).
Unfortunately these icons also show in the menus.
If this is not acceptable, I will just revert the commit until a better solution is found.

**Comment by tomaszg7** [comment]
I just tried it and configuration dialog is a bit different that I was accustomed to, but it works fine. However not everything works well with icons. For example, when I want to add a new button, there are only names and "+" sign in the popup list. It would be better to see the icons themselves there. 

Moreover, I tried to add Darktable or GIMP button and it shows fine in the toolbar, but in the preferences dialog the icon is missing.

Also, drag'n'drop reordering of icons in preferences would be good.

**Comment by caclark** [comment]
Thanks for the comments.

> configuration dialog is a bit different that I was accustomed to

I was trying to get a consistent user experience... well, that's management-speak for "it was just cut-and-paste".

> not everything works well with icons

Only gtk stock icons are displayed. It will take a bit more effort to get the others displayed, and I also want to find some way of letting the user easily create new icons for the desktop files they create.

> drag'n'drop reordering of icons in preferences would be good.

The same as other similar dialogues. One day....

**Comment by caclark** [comment]
>  It would be better to see the icons themselves 

Commit 045924fb51f3e at geeqie.org. There is still the problem that only stock icons are displayed

**Comment by tomaszg7** [comment]
Thanks, works nice.

> Only gtk stock icons are displayed. It will take a bit more effort to get the others displayed, and I also want to find some way of letting the user easily create new icons for the desktop files they create.

You'll probably aware that right now, adding a button for desktop file which doesn't specify an icon makes Geeqie display text label (however there is some strange arrow icon in the preferences) and that screws the alignment of all icons. 

I still didn't look into the possibility of using SVG icons. It shouldn't be difficult (I don't know if SVG support now is optional or not). But I don't think it should essentially make adding new icons any easier - it is already easy to export from SVG to JPG. The change would be mostly aesthetic (scaling). 

Moreover icons can be added to custom created desktop files just by putting "Icon=xxx" in the file.

**Comment by caclark** [comment]
Additional fix in commit f44b98b36 at geeqie.org
