### ISSUE TITLE
Info sidebar section heights

### ISSUE THREAD

**Issue by caclark** [BestImageViewer/geeqie#445]
Each section in the info sidebar is a fixed height - although it is possible to edit the height for some of them in the geeqierc.xml file.

It would be better if the user could change the heights. Maybe it would be possible to insert the sections into nested GtkPaned widgets.

**Comment by junkyardsparkle** [comment]
+1... when using the sidebar for tagging it would be nice to be able to use the full window height for the tag tree.

**Comment by caclark** [comment]
Fixed in commit 2ed5e0e3bd at geeqie.org.

Restart of Geeqie required for changes to take effect.
