### ISSUE TITLE
Size of subwindows not preserved across restart

### ISSUE THREAD

**Issue by SGKarp** [BestImageViewer/geeqie#466]
I use a layout with most of the window dedicated to the image on the left side, and a smaller amount of space on the right for Tools and Files (thumbnails).  I'm setting this via Edit | Preferences | Configure this window - the third choice in the "Layout" section.  I then drag the divider toward the right to set the proportions the way I want it (five columns of thumbnails).

Works fine until I exit the program and restart, at which point I find that most of the window is devoted to the thumbnails again, and I have to drag the divider to the right again.

If it matters, I'm running OpenSUSE Leap 42.2 with KDE 5, and generally launch geeqie as an "Open with" from a right-click on a folder in Dolphin.

**Comment by caclark** [comment]
Which version of Geeqie are you using? You can get that either from help/about or from the command line with geeqie -v.
You could also take a look at the file ~/.config/geeqie/geeqierc.xml after you have closed Geeqie.
The line you are interested in is "main_window.hdivider_pos = ". That value should change if you adjust the horizontal divider.

**Comment by caclark** [comment]
No further input
