### ISSUE TITLE
Refresh doesn't preserve thumbnail viewpoint

### ISSUE THREAD

**Issue by SGKarp** [BestImageViewer/geeqie#467]
Any action that causes the list of files/thumbnails to refresh returns the display to the top of the list, even if the currently-selected thumbnail is further down.

For example, after selecting the last few thumbnails and deleting or moving them, the last remaining thumbnail will be selected, but will not be visible in the list of thumbnails, because the view will be at the top of the list.

**Comment by caclark** [comment]
A work-around is to hit the space key, which moves focus to the next image. The thumbnail view will follow.

**Comment by SGKarp** [comment]
On Monday, 2017-01-16 at 01:10:16 PM, Colin Clark wrote:
> A work-around is to hit the space key, which moves focus to the next
> image. The thumbnail view will follow.

True.  Or an arrow key, which is what I've been doing.

But my most common workflow involves working on the image that's
selected after the refresh, not the "next".  I do a left-arrow then
right-arrow, and everything is back in sync where I want it.

Annoying but not earthshattering.  (A low-priority bug, in other words.)

	S.
-- 
Colors may fade in time.

**Comment by junkyardsparkle** [comment]
Note that this only affects GTK3 builds.

**Comment by hurzl** [comment]
Yes, annoying. It also happens when the files are changed by other programs.
And it wasn't there in older versions.

**Comment by hurzl** [comment]
It is really very annoying. Is it so difficult to fix or is it a bug in gtk3?

**Comment by caclark** [comment]
It annoys the hell out of me too. It isn't a GTK3 bug as such, but is a bug induced in the Geeqie code by the change from GTK2.
If you know how to compile Geeqie, at about line 1163 in view_file_icon.c(), change the code to look like:

/* ensure focus row col are correct */
vficon_find_position(vf, VFICON(vf)->focus_id, &VFICON(vf)->focus_row, &VFICON(vf)->focus_column);
#if GTK_CHECK_VERSION(3,0,0)
	if (vficon_find_iter(vf, VFICON(vf)->focus_id, &iter, NULL))
	{
	tree_view_row_make_visible(GTK_TREE_VIEW(vf->listview), &iter, FALSE);
	}
#endif
	return;
	}

It makes the problem go away, but I do not think it is the real solution.

There are three problems caused by the change to GTK3:
image flicker
this one
invisible objects

Unfortunately I have no idea how to solve any of them.

**Comment by tomaszg7** [comment]
If I may just add: there is a fourth problem - some borders are not movable, thus parts of the interface cannot be rescaled. I thought it was already solved but it reemerged.

**Comment by hurzl** [comment]
>  some borders are not movable

Maybe they are movable but the areas to pick them are too narrow

**Comment by tomaszg7** [comment]
Ah, they are movable, it's just that cursor doesn't change shape when I hover over a border. But still some parts seem to be not movable in both GTK+ 2 and 3 which I think were movable before (like parts of info sidebar), but it is probably a matter for a separate issue and I would have to check in more details also with older releases.

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Yea, GTK3 is a real pain in the ass. I cannot believe how they could
come out with such a unusable framework. But it fills into the
direction, Gnome is moving; unfortunately.

I seen many usability drawbacks with gtk+3 that makes me not use it
wherever I can. For example scrolling with mouse wheel is often only
working if the mouse pointer is inside of a very narrow scroll bar. And
with using the "Knubbel" inside of my Lenovo keyboard to scroll is more
than a pain with GTK+3.

And there are many more Usability flaws.

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAljWLT8ACgkQpnwKsYAZ
9qw6Ugv/X90YxtfxBwKc6BPERaJbbaAVw7++RK21pBZKzpxXby8FTnMYbzIwKt3j
85dOpgwp+79U3MrTsDEkG2h8HJ3XN0pZxEGSRukHh2wF504Wv34N1cf3UmnQ61DJ
Zc7Pkbd673pgNllWbh+3G4bcsGkrbMYAWG55gjZmwBuotebjqThosEL+ccdTJRbd
kbI8ATCJO17joMi2RQ23CW0p6ledmhBQMLm5ESv7kWVXFN2HWMe2PrA5kagGqtyB
JrkeZI/gho0ZO2fsmNI3ql1nVc+VEXcuZJB2Tk5dFneCy6s1+H34JY7Zu+AeaTVl
7uIGurpqf+94HgrHpGBOn2VfIVs4wBl2tXIg3Iwd+TV3gqbLDFLIrrvZDP4uRkJP
Tonwrz99LYQhgxmO+TxJMonFu4IiTsFd+Qi9z8VvSilZuqKDYiskWpflAPWfUfgm
CgIEwv4SI30EP2AV4LKQ7sHjJDro5OW+JOMkVy7hx4trYPSyeVreCpHzu5P8om7E
SZBkVRD7
=LJwL
-----END PGP SIGNATURE-----

**Comment by caclark** [comment]
Temporary fix in commit 2d3cd2.
So far as I can see, the reset of the view is caused by a call from the idle loop.
I've downloaded the GTK sources and used the debugger to try to trace where the call is from, but obviously failed.
I'll leave this problem for someone else to solve.

**Comment by SGKarp** [comment]
Well, it may be a temporary fix and highly inelegant (I have to take your word for that), but the good news is that from the user's perspective, it does solve the problem.  I spent the weekend beating on it in all of my typical use cases, and it came through with flying colors.
