### ISSUE TITLE
Colors change after fullscreen

### ISSUE THREAD

**Issue by gredner** [BestImageViewer/geeqie#474]
I've recently noticed that photos look different in fullscreen than in the windowed view, and remain different afterwards.  See the screenshots below - I navigated to an image and took a screenshot, then pressed 'f' twice to enter and leave fullscreen, and then took another screenshot.  The colors are noticeably different afterwards!  I wasn't able to take a screenshot of the fullscreen view for some reason, but the colors there appear as in the second screenshot.

Before fullscreen:
![screenshot from 2017-02-20 11-41-58](https://cloud.githubusercontent.com/assets/9915473/23134237/0573d088-f762-11e6-8dc2-275f71a79d1d.png)

After fullscreen:
![screenshot from 2017-02-20 11-42-17](https://cloud.githubusercontent.com/assets/9915473/23134238/05758856-f762-11e6-9b4f-85f94429df30.png)

**Comment by gredner** [comment]
System information:

Lenovo ThinkPad T530

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
$ geeqie --version
Geeqie 1.2.2

**Comment by mowgli** [comment]
Please update to current stable version 1.3 where this problem is already fixed.

You should ask your distribution why they deliver old versions.
