### ISSUE TITLE
Custom background color

### ISSUE THREAD

**Issue by PanderMusubi** [BestImageViewer/geeqie#476]
Some images have black borders which are not distinguishable from teh black background. When it is needed to be able to see these, preferences should offer a way to change the background color with a color picker with manual hex RGB entry.

Possibly, the default color could be changed to #222222 or even to a speckled repeated bitmap as is done in Firefox.

**Comment by caclark** [comment]
I think this is the same problem as in #233. There is a fix, but it is not yet in a release. If you go to http://www.geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git  you can download/clone the latest version.

**Comment by PanderMusubi** [comment]
Thanks. I am using version 1:1.3-1 on Ubuntu, hope to see it in the next release.
