### ISSUE TITLE
similarity duplicate search

### ISSUE THREAD

**Issue by installgentoo** [BestImageViewer/geeqie#477]
Currently there's a big problem with searching through big file collections(on order of thousands files). On medium and low similarity comparisons you will get duplicate groups with hundreds of entries which are obviously completely useless. But the algorithm is also quite capable of finding distinct duplicates which show up even in those conditions in normal pairs, it's just they're buried between groups with hundreds of false positives.

Therefore i propose adding a filter option that will automatically get rid of groups with more items than specified by user. This will immensely improve duplicate search functionality.

**Comment by caclark** [comment]
Fixed in commit 64b3e53dd4f at geeqie.org.

Additional find dupes option: sort groups with the lowest number of matches to the top of the list, and the highest number of matches to the bottom.
