### ISSUE TITLE
Metadata editing is hard to discover

### ISSUE THREAD

**Issue by dandv** [BestImageViewer/geeqie#480]
I've spend 10 minutes with Geeqie and still couldn't figure out how to edit a JPEG's metadata until it occurred to me to check "Info sidebar".

My use case is tagging images with keywords so I may be biased, but I expected metadata editing to be easily accessible via right click and also from the EXIF window, which does shows the XMP keywords.

**Comment by caclark** [comment]
Now that you have found how Geeqie's sidebar allows you to access keywords and selected exif data, do you find that easy to use?
There are probably several features that are not immediately apparent to someone trying Geeqie for the first time.
Perhaps one or two high-definition screenshots of Geeqie, with all options on display, would be useful. If they were placed in the help file introduction and on Geeqie's homepage (or even as an initial splash page), that would alert new users to the possibilities.
Hotlinks on various parts of the images leading to the relevant section of the help file would also be good..... but I doubt that will happen.
