### ISSUE TITLE
Compilation instructions

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#483]
`README`
```
## Installation

  Compilation: ./autogen.sh ; make
```

`INSTALL`
```   The simplest way to compile this package is:
  1. `cd' to the directory containing the package's source code and type
     `./configure' to configure the package for your system.
```

So which is it?

**Comment by caclark** [comment]
On initial installation, ./configure does not exist. You must first run ./autogen.sh which will create ./configure.
Thereafter, it makes no difference whether autogen.sh or configure is run.
Maybe it would make sense to update all the references to use only autogen.sh, then there can be no confusion.

After that you run "make". If you wish, you can then test-run the newly-compiled version with "./src/geeqie"

To install system-wide, you must also run "sudo make install".

**Comment by Beep6581** [comment]
Thank you for the reply, but the point of this issue is to get the instructions shipped with Geeqie to be up to date and unambiguous, not to help me personally :)

**Comment by SimonDedman** [comment]
+1 for this.
Downloaded zip, unpacked to home, went to it (/home/me/geeqie-master/), tried:
$ ./configure
configure: error: cannot find install-sh, install.sh, or shtool in auxdir "."/auxdir
$ ./autogen.sh
lots of text then same error. Tried basically all the suggestions [here](https://askubuntu.com/questions/27677/cannot-find-install-sh-install-sh-or-shtool-in-ac-aux) but nothing worked.
Please advise; seems like this is a packaging error?
Thanks

**Comment by Beep6581** [comment]
As I self-compile a few programs, I wrote a generic Bash script which can easily be tailored to any of them. It compiles a program and stores it independently in the user's `~/programs/` folder. Here is the one I use for Geeqie:
https://gist.github.com/Beep6581/c6e783207b03136dd1089f41a522efe9

**Comment by caclark** [comment]
The zips on github only get you the sources - if you want an easy install/uninstall process you have to use git clone.
Beep's script will get you a runable file, but it won't be in /usr/local/bin and I'm not sure where the html files etc end up.
If you are going to continue to download the latest sources I suggest you install git, and clone from geeqie.org. The repository there is always more up-to-date.

**Comment by Beep6581** [comment]
> Beep's script will get you a runable file, but it won't be in /usr/local/bin and I'm not sure where the html files etc end up.

That is the point of the script, to keep programs local and isolated, allowing easy juggling of development versions. "Uninstalling" is as simple as `rm -r ~/programs/geeqie`

**Comment by tomaszg7** [comment]
I can recommend GNU Stow for that purpose: https://www.gnu.org/software/stow/.

**Comment by caclark** [comment]
The file INSTALL is no longer created - I don't know why - maybe there was a change in the automake tool.
The README file is updated to include a reference to the GitHub zip problem.
