### ISSUE TITLE
Pan View - View in new window

### ISSUE THREAD

**Issue by caclark** [BestImageViewer/geeqie#484]
If an image is opened from Pan View with View in new window, the image size is set to a minimum.

At line 810 in img-view. c is the declaration:

	'gint w, h;'

The gcc documentation shows the contents of the variables should be undefined. At line 880 they are used:

	int count;
	for (count = 10; count && !w && !h; count++)
		{
		image_get_image_size(vw->imd, &w, &h);
		usleep(100000);
		}

... obviously expecting w and h to be zero. They are not (probably), so the code drops through and the image ends up displayed at a minimum or random size.
However if w and h are initialised to zero, the code goes into an infinite loop at line 880 because the pixbuf hasn't been set up.

**Comment by xsdg** [comment]
Don't you mean it ends up looping for 10 cycles (1.0 seconds) and giving up if they are initialized to zero?

**Comment by caclark** [comment]
Thanks, you're right.... sort of. It's a count-up not a count-down so it loops until count overflows back to zero. On the stone-age computer I'm using that's longer than it takes to make a cup of coffee.

**Comment by xsdg** [comment]
*sigh*

**Comment by caclark** [comment]
Fixed in commit c4d04c5a1
