### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by stefanhusmann** [BestImageViewer/geeqie#486]
Hello,

under ArcH Linux:
```
preferences.c:2394:2: warning: 'gtk_hbutton_box_new' is deprecated: Use 'gtk_button_box_new' instead [-Wdeprecated-declarations]
  hbox = gtk_hbutton_box_new();
  ^~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:257:0,
                 from main.h:63,
                 from preferences.c:22:
/usr/include/gtk-3.0/gtk/deprecated/gtkhbbox.h:62:12: note: declared here
 GtkWidget* gtk_hbutton_box_new      (void);
            ^~~~~~~~~~~~~~~~~~~
preferences.c:2400:2: warning: 'GtkStock' is deprecated [-Wdeprecated-declarations]
  button = pref_button_new(NULL, GTK_STOCK_HELP, NULL, FALSE,
  ^~~~~~
preferences.c:2406:2: warning: 'GtkStock' is deprecated [-Wdeprecated-declarations]
  button = pref_button_new(NULL, GTK_STOCK_OK, NULL, FALSE,
  ^~~~~~
preferences.c:2415:2: warning: 'GtkStock' is deprecated [-Wdeprecated-declarations]
  button = pref_button_new(NULL, GTK_STOCK_SAVE, NULL, FALSE,
  ^~~~~~
preferences.c:2421:2: warning: 'GtkStock' is deprecated [-Wdeprecated-declarations]
  button = pref_button_new(NULL, GTK_STOCK_APPLY, NULL, FALSE,
  ^~~~~~
preferences.c:2427:2: warning: 'GtkStock' is deprecated [-Wdeprecated-declarations]
  button = pref_button_new(NULL, GTK_STOCK_CANCEL, NULL, FALSE,
  ^~~~~~
preferences.c: In function 'show_about_window':
preferences.c:2512:2: warning: 'gtk_vbox_new' is deprecated: Use 'gtk_box_new' instead [-Wdeprecated-declarations]
  vbox = gtk_vbox_new(FALSE, PREF_PAD_SPACE);
  ^~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:282:0,
                 from main.h:63,
                 from preferences.c:22:
/usr/include/gtk-3.0/gtk/deprecated/gtkvbox.h:61:13: note: declared here
 GtkWidget * gtk_vbox_new      (gboolean homogeneous,
             ^~~~~~~~~~~~
preferences.c:2535:2: warning: 'gtk_hbutton_box_new' is deprecated: Use 'gtk_button_box_new' instead [-Wdeprecated-declarations]
  hbox = gtk_hbutton_box_new();
  ^~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:257:0,
                 from main.h:63,
                 from preferences.c:22:
/usr/include/gtk-3.0/gtk/deprecated/gtkhbbox.h:62:12: note: declared here
 GtkWidget* gtk_hbutton_box_new      (void);
            ^~~~~~~~~~~~~~~~~~~
preferences.c:2547:2: warning: 'GtkStock' is deprecated [-Wdeprecated-declarations]
  button = pref_button_new(NULL, GTK_STOCK_CLOSE, NULL, FALSE,
  ^~~~~~
make[3]: Leaving directory '/home/haawda/paketierung/not_maintained_by_me/geeqie-git/src/geeqie/src'
make[2]: *** [Makefile:961: all-recursive] Error 1
make[2]: Leaving directory '/home/haawda/paketierung/not_maintained_by_me/geeqie-git/src/geeqie/src'
make[1]: *** [Makefile:669: all-recursive] Error 1
make[1]: Leaving directory '/home/haawda/paketierung/not_maintained_by_me/geeqie-git/src/geeqie'
make: *** [Makefile:501: all] Error 2
==> ERROR: A failure occurred in build().
```

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am Sa den 20. Mai 2017 um 15:18 schrieb Stefan Husmann:
> under ArcH Linux:
> ```
> preferences.c:2394:2: warning: 'gtk_hbutton_box_new' is deprecated: Use 'gtk_button_box_new' instead [-Wdeprecated-declarations]
>   hbox = gtk_hbutton_box_new();
>   ^~~~
> In file included from /usr/include/gtk-3.0/gtk/gtk.h:257:0,
[...]
> make[3]: Leaving directory '/home/haawda/paketierung/not_maintained_by_me/geeqie-git/src/geeqie/src'
> make[2]: *** [Makefile:961: all-recursive] Error 1
> make[2]: Leaving directory '/home/haawda/paketierung/not_maintained_by_me/geeqie-git/src/geeqie/src'
> make[1]: *** [Makefile:669: all-recursive] Error 1
> make[1]: Leaving directory '/home/haawda/paketierung/not_maintained_by_me/geeqie-git/src/geeqie'
> make: *** [Makefile:501: all] Error 2
> ==> ERROR: A failure occurred in build().
> ```

That sounds like a typical gtk-3 problem.

Did you reconfigure it (./configure) after installing gtk3? Did it tells
you that gtk3 is used?

What version of gtk does you use?

Did you try to use --disable-gtk3 configure switch?

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAlkhUEkACgkQpnwKsYAZ
9qw8KAv/T7yBJ+WsuT6LucKXutKMbz2iC6A8PKtTFkfWXBJSXCyGsTcXLAAlLWUq
r0g/IH9pkKPGeif336g0qIkcWoqIhPmlrvo7qXAwUyyhzz7h42fqp+M5y0965StR
pInaF4eSkwOZeYt6EA1cA0dliDRUSvI6Y3a5Ig/9kc6+BbCshazEngXbvW4uukX0
yzLmqWgf+TWlk+F3GmlTd7f4VjlpNM7jfgl3O1cZNROAc9HGZlybo5DZNXNvhPWE
qT8OUFhrqOWnwMv4JWvsk6Vm0+184Pdc0LHQGqlu28Y6uV1Q/GlwQ2FVBGgBcwNM
g3Sx5xGxr7lBGUTAsjk08Zpv+1oaqkySyMNiaBEkfMFs47ZOb3335h9qQDmmHj06
Eu1rT24MkJCJVclhueGFO6zuo1Eknm4A51uMyDLYBFiFP6UdPQMokYFXqZ2KoPYF
L3rFpobRxb8NUrjAvwrqckiyQGYkXw6XXIW810Ki4bzK/2+6/YozFVKxoD+hfaSW
CbtXE1YQ
=SUMD
-----END PGP SIGNATURE-----

**Comment by stefanhusmann** [comment]
> Did you reconfigure it (./configure) after installing gtk3? Did it tells
> you that gtk3 is used?
Yes (I use the PKGBUILD from AUR, which is running ./autogen.sh, which runing ./configure) and yes:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=geeqie-git

```
Package:
  Name:          geeqie
  Version:       06b80ed3

Architecture:
  UNIX:          yes
  Win32:         no (native: no)

Flags:
  Geeqie:        
  DEFS:          -DHAVE_CONFIG_H
  CPPFLAGS:      
  CFLAGS:        -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Werror -Wno-error=deprecated-declarations
  CXXFLAGS:      -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4
  Gtk:           -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
  Glib:          -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
  Thread:        -lgthread-2.0 -pthread -lglib-2.0
  Others:	 -ljpeg -ltiff -llcms2 -lexiv2     

Localization:
  NLS support:   yes
  LINGUAS:        ar be bg ca cs da de el eo es et eu fi fr hu id it ja ko nb nl pl pt_BR ro ru sk sl sr@latin sr sv th tlh tr uk vi zh_CN zh_TW

Settings:
  Developer:     no
  Debug flags:   no
  Debug log:     yes
  Deprecated:    no

Support:
  LCMS:          yes
  Exiv2:	 yes
  Lirc:          no
  Clutter:       disabled
  Libchamplain:		disabled
  Libchamplain-gtk:	disabled
  Lua:	         no

Documentation:
  Doxygen:       /usr/bin/doxygen
  doc-tool:      /usr/bin/gnome-doc-tool


  Now you can type "make" to build Geeqie
  (or you take blue pill and the story ends :)
```

> Did you try to use --disable-gtk3 configure switch?
I now tried that, without any difference. The same version of gtk3 gets detected. 

> What version of gtk does you use?

3.22.15 from my distribution.

**Comment by caclark** [comment]
There should be many, many warnings about deprecated features. But  they should be just warnings, and not errors.
Is the output you attached just a sample, or is the total output?
If you are getting a lot of warning output, you can eliminate it by executing:

export CFLAGS=-Wno-deprecated-declarations
sudo make distclean
./autogen.sh

Then only errors and not warnings should be displayed.

**Comment by casta** [comment]
Hi,

Problem is that you set -Werror (https://github.com/BestImageViewer/geeqie/blob/master/configure.in#L21) and then, you get this since the last geocode changes (https://github.com/BestImageViewer/geeqie/commit/7d42ca045284da44b249b42564421163c5969aab#diff-4a37aac5c8f7e438572f91c0ed94cfcbR150):

```
misc.c: Dans la fonction « decode_geo_parameters »:
misc.c:150:4: erreur : ignoring return value of « fgets », declared with attribute warn_unused_result [-Werror=unused-result]
    fgets(buf, BUFSIZE, fp);                                                              
    ^~~~~~~~~~~~~~~~~~~~~~~   
```

**Comment by tomaszg7** [comment]
I noticed this problem as well. However I don't know why I hit this error only on one of my two machines (with the same gcc-5.4.0). On the other one the code builds fine.

**Comment by caclark** [comment]
There is a commit b1dd4301ed1 at geeqie.org.
I don't know if it has fixed the problem as indicated above - I don't see that error on anything I have.
There is no functional difference in the code - I just changed the style to match that used elsewhere.

**Comment by tomaszg7** [comment]
It fixes the problem for me.

**Comment by casta** [comment]
Yes indeed, thanks.
It should probably depends on glibc headers. Some may not define "fgets" with a warning warn_unused_result, and some other do.

**Comment by caclark** [comment]
Thanks for the help
