### ISSUE TITLE
Optional location of config files

### ISSUE THREAD

**Issue by caclark** [BestImageViewer/geeqie#487]
I use Geeqie on more than one computer on a small network (only one instance running at a time).
It is a pain having to copy keywords and home-brewed desktop files etc. from .config/geeqie on one computer to .config/geeqie on another.
It would be better if the location of ~/.config/geeqie and below could be separated from whatever else needs to be in rc_dir.
Keep thumbnails etc local, leave default settings as is, but have a command-line option to direct Geeqie to a common folder on the network for all the other files.

**Comment by tomaszg7** [comment]
Couldn't that be achieved just by creating a symlink?

**Comment by caclark** [comment]
A hack! Now, you already know I like to solve problems with symbolic links :-)
Yes, that could be done, but I am not sure it would be suitable for non-programmer users to be ok with that.
My comment was also motivated by a personal, laziness, reason. Over the past few weeks/months when I have been looking at bugs, my geeqierc.xml has been continually screwed up because I'm forever running earlier/broken versions. Being able to point different test versions different places would be useful. I could also solve that by symbolic links, but I'm a bit lazy.

**Comment by caclark** [comment]
#121 is a better solution
