### ISSUE TITLE
Issues using Geeqie to compare pictures

### ISSUE THREAD

**Issue by saintger** [BestImageViewer/geeqie#488]
ello,

I'm using Geeqie 1.2-3+b1 (Debian Stable) and I wanted to compare pictures as described here:
http://freesoftwaremagazine.com/articles/compare_two_images_easily_geeqie/

The fist "bug" I noticed, is that pressing "L" to float the file/folder list, open a maximized floated window which covered the compleded displayed picture.
If I reduce the size of the window and use Ctrl-H to hide and display it, the size remains the same.
But if I hit "L" several times, the maximzed file list comes up again.

The second "bug", is when hitting "U" to display pictures side by side it only works if the second selected pictures is a non-grouped pictures (for instance 2 JPEGs). If the second selected pictures is a group (collapsed jpeg + raw), the displayed pictures are the 2nd picture jpeg and the 2nd picture raw instead of the 1st picture jpeg and the 2nd picture jpeg.

The third "bug" is perhaps a missing feature ? When comparing 2 pictures side by side, one is in focus with a blue highlight around the frame. Which means that I go go forward and backward in the list for this picture by hitting space or backspace. But appart from using the mouse to switch focus to the second picture, I haven't found a keyboard shortcut to switch focus (very inconvenient as I only use the keyboard to navigate).

**Comment by caclark** [comment]
Fixed in commits 8eca5b305a, 521f209ec73 and d901af030 at geeqie.org

**Comment by saintger** [comment]
That was really fast, thanks !
It would have been nice (more intuitive) to be able to use also Alt+Up and Alt+Down when navigating in the Quad view, instead of just Alt-Left and Alt-Right. But that's only a minor comment.

Thanks again !

**Comment by caclark** [comment]
In Preferences/Keyboard you can redefine key allocations to other key combinations - only a single combination per action, but if you prefer Up/Down...

[I have no idea if there is a practice note regarding recommended key allocations. I'll maybe take a look. One day.]

**Comment by saintger** [comment]
No I mean that it would have been nice to have Alt+Up, Alt+Down in addition to Alt+Right and Alt+Left.
It makes navigation in the Quad view more intuitive than just Alt+Right and Alt+Left. ;-)

**Comment by caclark** [comment]
OK, I understand now. Probably not too difficult, but not that urgent. (Most of these one-line hacks get done when I'm watching a bad film and decide to do something better with my time. The last film was Galaxina. I think this fix would require a film worse than that. Unlikely.)

**Comment by caclark** [comment]
Alt+Up, Alt+Down implemented in commit f6a87c01 at geeqie.org

**Comment by saintger** [comment]
Thanks a lot !
