### ISSUE TITLE
Shortcut to Hide all sidebars simultaneously and fit the image to the window

### ISSUE THREAD

**Issue by arigit** [BestImageViewer/geeqie#492]
Use case: use two image viewers, or one raw developer and one image viewer, each half-tiled, for image comparison. I typically use Darktable in the left, and Geeqie in the right, or sometimes two Geeqie windows. When comparing images side by side, I hide all sidebars.

Currently, to hide the sidebars in Geeqie, I need to use Ctrl-K and Ctrl-H. Darktable provides a single shortcut to "hide everything right away" to have a clean window just showing the current image: the tab key. 

This is a feature request to add the same "Tab" shortcut to geeqie that would toggle visibility of both the Files left-sidebar and the Info right-sidebar. If either had been specifically hidden (via Ctrl-F or Ctrl-H) then the Tab key would ignore it instead of toggling visibility of it.

This could be complemented by a a new entry in the View menu to "Toggle sidebars visibility". 

The "Tab" key seems to be currently unassigned to any shortcut - it seems it's available.

**Comment by caclark** [comment]
This would not seem to be too difficult to implement. The sort manager pane should be taken into account, also.
The tab key is not used by Geeqie, but is used by GTK to shift focus. I guess it would be possible to override this (as for darktable), but I am not sure that it is a good idea to stray too far from standard practices.
Shift/control/alt tab are still available, though.

**Comment by caclark** [comment]
Fixed in commit 3229f865 at geeqie.org
Default is the backtick key, which on English keyboards is physically close to the tab key.

None of the shift/control/alt tab combinations can be used.
