### ISSUE TITLE
Geeqie doesn’t use shared thumbnail folder

### ISSUE THREAD

**Issue by deterenkelt** [BestImageViewer/geeqie#500]
The shared thumbnail folder [should be](https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-latest.html#DIRECTORY) `$XDG_CACHE_HOME/thumbnails` or `~/.cache/thumbnails`, if `XDG_CACHE_HOME` is not set. I have moved it to `/tmp/$USER/.cache`, but Geeqie continues to see it under `$HOME/.cache/`. When I remove `~/.cache` and then start geeqie, `~/.cache/thumbnails` grows.

And I watch /tmp/$USER/thumbnails at the same time. When I open new folders in Geeqie, the size doesn’t change. But if I open a new folder in Thunar, it does grow. This tells, that Thunar respects $XDG_CACHE_HOME, and Geeqie doesn’t.

![1500891514](https://user-images.githubusercontent.com/2245254/28519015-144a956e-707b-11e7-9546-f2ae09d1083f.png)

**Comment by caclark** [comment]
It looks like Geeqie uses  $XDG_CACHE_HOME to form a path to its own thumbnail folder, but leaves the path to the shared folder unchanged.
From the document referenced above, this is clearly wrong.
But if it is fixed, there is still the situation where a user wants Geeqie to have its own thumbnail folder, but not in the default location. That means either:
1. Yet another option in Preferences/General
or
2. The user selects "standard cache" and then sets  $XDG_CACHE_HOME before calling Geeqie - that's not really intuitive.

And debug output shows that the sub-folder .thumblocal is being used somewhere, somehow.

**Comment by deterenkelt** [comment]
Yet another option in Preferences would be great. Too much words to describe, so here’s a sketch.

![3_0](https://user-images.githubusercontent.com/2245254/28549403-d5e524cc-70ea-11e7-81be-b74ecb6eebf0.png)
-----
![3_0 1](https://user-images.githubusercontent.com/2245254/28549406-d964622a-70ea-11e7-89fc-0e4ba85a1f53.png)

In the current state, I do not understand, why geeqie shows two folders ‘Thumbnail cache’ and ‘Shared thumbnails cache’, as if it uses both simultaneously. It is especially confusing, that the folder geeqie uses to store its own thumbnails is not even the first, but the second. In Preferences/General I have both ‘Cache thumbnails’ and ‘Use standard thumbnail cache’ checked.

On a side note, XDG_CACHE_HOME can be set by the user, so instead of making yet another switch, Geeqie can encourage the user to change the XDG_CACHE_HOME in ~/.config/user-dirs.dirs. I would suggest to name system cache option as ‘<path> – system cache (XDG_CACHE_HOME)’, or make a hint for it like ‘To set a custom path for system thumbnail cache, alter XDG_CACHE_HOME in ~/.config/user-dirs.dirs.’

**Comment by caclark** [comment]
Thanks for the input.
Fixed in commit 559f084 at geeqie.org.
