### ISSUE TITLE
Hyper quality sometimes shows blurry image at 1:1

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#501]
Commit efc10a6b

Open an image smaller than your viewing area so that it fits at 1:1. A screenshot is a good example. The image should be perfectly sharp, but using Hyper quality makes it blurry. The other qualities don't look blurry.

If the image does not fit within the preview area, i.e. if it is bigger, then when you zoom to 1:1 it does appear sharp. It's only when the image is smaller than the viewing area.

Sample image: https://filebin.net/gko7yqiv9i95j1q5/mca_200b1_01.png
Screenshot of the problem: https://filebin.net/gko7yqiv9i95j1q5/screenshot_20170731_132945.png
Settings: https://filebin.net/gko7yqiv9i95j1q5/imgur-2017_07_31-13_41_40.png

**Comment by caclark** [comment]
This appears to be the same bug as in #192.
See there for more information.
