### ISSUE TITLE
Click to pan switches to the next image

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#502]
Commit efc10a6b

Open a large image, zoom to 1:1 or more. Left-click-and-drag to pan the preview. Geeqie switches to the next image.

Yes there is an option in Preferences > Behavior > "Navigate by left or middle click on image", but I didn't just left-click. I clicked and panned. This is different, and Geeqie should not load the next image if I left-click, hold it in and pan. In other words, the switch-to-next-image event should not fire on click, it should fire on let-go-of-click only if panning didn't occur.

**Comment by caclark** [comment]
There is a commit at geeqie.org that I think fixes this problem.

If you are compiling from sources, you will find that the repository at geeqie.org is always ahead of the repo at github - commits go there first and are later copied to github.

**Comment by Beep6581** [comment]
I confirm, this is already fixed in c7cb4da3
