### ISSUE TITLE
Better sorting, like ls -v

### ISSUE THREAD

**Issue by ultinous-nil** [BestImageViewer/geeqie#503]
I have files from 1.jpg to 12.jpg. They are sorted like this in geeqie: 10.jpg, 11.jpg, 12.jpg, 1.jpg, 2.jpg, ..., 9.jpg. If I issue an "ls -v" command in the terminal (uses so called version compare) I get my personal favorite ordering of 1.jpg, 2.jpg, ..., 9.jpg, 10.jpg, 11.jpg, 12.jpg. This ordering would improve usability for me to a great degree and maybe for others. I'm quite sure that the current ordering would not be missed.

Geeqie 1.2.2, Ubuntu 16.04

**Comment by caclark** [comment]
This is implemented in the repository at geeqie.org.
It is an option in Preferences/Files as "Natural Sort Order".
Unfortunately it will be necessary for you to compile from the sources to take advantage of this at the moment.

Issue #417 also relates to this.
