### ISSUE TITLE
Slightly rearrange keywords context menu

### ISSUE THREAD

**Issue by tomaszg7** [BestImageViewer/geeqie#507]
Hi,
Recently keywords context menu was cleaned up a bit but I think it can be done a bit better. I propose the following patch that does the following:

1. changes some icons to be unique and better matching the command
2. replace "Add keyword to all selected images" by "Add \"%s\" to all selected images" (where %s is the particular keyword). 
3. "Add keyword" command is shown only if an item was clicked. It probably should be further refined to check if it was "active keyword" or only a "helper"

[keywords-menu.patch.gz](https://github.com/BestImageViewer/geeqie/files/1265049/keywords-menu.patch.gz)

**Comment by caclark** [comment]
Fixed in commit 8702dec8 at geeqie.org
