### ISSUE TITLE
Increase number of marks to 10

### ISSUE THREAD

**Issue by tomaszg7** [BestImageViewer/geeqie#509]
Given that marks can be used to conveniently set keywords, it would be very convenient to increase their number. I propose to increase it to 10, with last mark being designated "0". 

I'm not really certain if it is a good idea to make tenth mark named "0" - it is for sure makes the code more complicated. It is however more compatible with key bindings and also overlay marks look better imho.  It is easy to do it the other way.

I hope I didn't miss anything in the code. It seems to work OK for me.
[geeqie-marks-10.patch.gz](https://github.com/BestImageViewer/geeqie/files/1290191/geeqie-marks-10.patch.gz)

**Comment by caclark** [comment]
In icon view I cannot see all of the marks. Would it be possible to display them as two rows of 5?

**Comment by tomaszg7** [comment]
It is definitely possible, however I don't know how to do it ;) I don't know GTK, tried to understand the code and I think I did. However since I don't know enough about it, I can't begin to imagine how to fix it. 

Fortunately, to fix the problem in icon view, it is enough to decrease spacing a bit. Tested with both GTK2 and 3 and it seems to fit, at least on my system.

[geeqie-marks-10_v2.patch.gz](https://github.com/BestImageViewer/geeqie/files/1294291/geeqie-marks-10_v2.patch.gz)

BTW. In GTK2 interface mark checkboxes in the filter area (above the files) and next to the images are aligned in the same way. In GTK3 it is not so, in image area they take much more space.

**Comment by caclark** [comment]
Unfortunately I still cannot see all the check-boxes.
I would still like to see how it looks with two rows of 5. I think (maybe) it's just a matter of adjusting the arithmetic of the check-box layout (and the cell rectangle).
It's all in cellrendericon.c - the layout is at about line 840, and the recognition of the mouse clicks is at about line 970.
I will look at it again in a few days. At the moment I have another problem.... tax return....

**Comment by tomaszg7** [comment]
Ok, I'll look at it. I suppose the reason you don't see all the boxes is smaller thumbnail size or some difference in the themes. Thus I'm afraid it might be difficult to get it right without a reasonable test case... Further decreasing spacing and toggle size did the trick for me with small thumbnails. However looking at line 632: 
`calc_width = MAX(calc_width, TOGGLE_SPACING * cellicon->num_marks);`
makes me wonder why it is so... I will probably have to dig in deeper. It's difficult to hack a GTK app not knowing anything about GTK ;)

**Comment by tomaszg7** [comment]
Apparently the problem was not in cellrendericon.c at all. It was in view_file_icon.c vficon_get_icon_width() and it was a pre-existing bug. You can see that when you chose icons, disable text and chose small thumbnails, you will see only a few of checkboxes. 

Attached patch fixes it but I didn't yet look at making marks in two rows. That's next (and possibly separate) problem.

[geeqie-marks-10_v3.patch.gz](https://github.com/BestImageViewer/geeqie/files/1304307/geeqie-marks-10_v3.patch.gz)

**Comment by caclark** [comment]
Implemented in commits db9a2d605 and f6831eee50 at geeqie.org

**Comment by caclark** [comment]
Now that the number of marks has increased to ten, do users find it a little difficult to use marks when they are displayed in the file view as a row of checkboxes?

Would it be preferable to display the marks as a set of digits from 1 to 0, with unselected shown as light grey and selected as bold?

(The OSD shows marks as a set of digits, with selected marks displayed against a green background)
