### ISSUE TITLE
Install higher quality icons

### ISSUE THREAD

**Issue by tomaszg7** [BestImageViewer/geeqie#511]
Right now, Geeqie installs only a 48x48 png icon into prefix/share/pixmaps/. Unless there is some deeper reason I think it should also put several bigger resolution files (probably into prefix/share/icons/hicolor/) including scalable. Copying gqview_icon.svg to prefix/share/icons/hicolor/scalable/geeqie.svg does the trick for me, but I don't know enough about autotools to submit a patch.

**Comment by qarkai** [comment]
@caclark Looks like duplicate of #179.
