### ISSUE TITLE
The "Back" button does not operate correctly

### ISSUE THREAD

**Issue by caclark** [BestImageViewer/geeqie#512]
The "Back" button simply rotates between the last two folders accessed.

**Comment by caclark** [comment]
Fixed in commit 776d9f6b72 at geeqie.org

**Comment by tomaszg7** [comment]
To make better use of this feature it would be good to be able to use mouse back/forward buttons to navigate it. I don't think it is possible to map mouse buttons to actions globally via UI. I also don't know how to do it globally in whole Geeqie. However I was able to map it to clicks in the image area via the following patch:

[geeqie-mouse-back.patch.gz](https://github.com/BestImageViewer/geeqie/files/1346843/geeqie-mouse-back.patch.gz)

BTW Your commit 39cbcfb55eb391a008c0571e8ad67fc703bac759 "Do not send debug data to terminal" seems a bit broken - it suppresses also valid Geeqie output, like "-h". Moreover, if someone explicitly specifies "-d" flag, he really wants to see those messages. There are many use-cases where they might be useful, for example I don't see a way to save or filter existing log.

**Comment by caclark** [comment]
> seems a bit broken - it suppresses also valid Geeqie output, like "-h".

Oh, oh... thanks for pointing that out.

> if someone explicitly specifies "-d" flag, he really wants to see those messages. There are many use-cases where they might be useful, for example I don't see a way to save or filter existing log.

The command line option --log-file:filename will save the debug output. Do you mean you want to save the contents of the log window, when Geeqie has been started without the --log-file option?

**Comment by tomaszg7** [comment]
> The command line option --log-file:filename will save the debug output. Do you mean you want to save the contents of the log window, when Geeqie has been started without the --log-file option?

Right, didn't notice --log-file option. But even taking it into account it complicates things a bit. As far as I understand, now -d does nothing - I think there should be a way to put the output to stdout easily. Before I could do for example: "geeqie -d | less", now that would require "geeqie -d -o /dev/stdout | less". Moreover silencing the output is only partially successful as a lot of GTK (at least GTK3 errors and warnings still get printed).

**Comment by caclark** [comment]
> now -d does nothing 

That's not exactly so. The debug data goes to the log window. I find that easier to use than the console, because I can change the debug level and regexp term easily.

One of the situations I was trying to avoid was when debugging and starting Geeqie by
src/geeqie --debug=4 &
then using the console to send remote commands. The terminal just gets clogged by the debug data that is going to the log window anyway.

But, no matter, I'll just reverse the commit.
By the way, nothing goes to stdout - it all goes to stderr.

**Comment by tomaszg7** [comment]
> That's not exactly so. The debug data goes to the log window. I find that easier to use than the console, because I can change the debug level and regexp term easily.

But you cannot regexp existing log (or I just couldn't find a way) - all it does is filtering new lines. So, unless you know exactly what you are looking for, you might just easily miss something.

> By the way, nothing goes to stdout - it all goes to stderr.

You're right, I forget about it. I should have written "|&" :) However I would prefer debug to go to stdout, as it is really not error in most cases... But that is just a personal preference.

What I mean is that I don't claim that something is fundamentally wrong (except for the missing output from -h), I just feel it is somewhat inconsistent. If you're going to use log window, you don't really need any switches, you have GUI for that. "--debug" would just change initial value of debug level. On the other hand, if you want to have the log in a file, you need "--debug -o:file". So you need to specify "--debug" only when you want to have a file and in this case in the old situation "-o" was just a substitute for "2>". In any case it would be good to at least clarify what those options do, e.g. where does debug messages end up. Maybe a way to resolve the thing would be to add a "-q" or "--quiet" and make "-o:" turn it on implicitly.

**Comment by tomaszg7** [comment]
There is still something wrong or at least unexpected with the behaviour of "Back" button. Consider a scenario: a directory `A` with two subdirs `B` and `C`. Start in `A` and enter `B`, then press back and enter `C`. Now pressing back again moves you to `B`, instead of parent dir `A`, which is what I would expect. 

It is consistent with the description in `history_list.c` but I don't think it is correct from the point of view of user. The generated history chain is obviously `A, B, C` and I don't know how to implement it better. I believe most e.g. browsers "forget the future" when adding a new entry somewhere in the middle of the chain. That's also not an ideal solution, but I don't know if there is any.
