### ISSUE TITLE
Shortcut/Feature: Select random image

### ISSUE THREAD

**Issue by Nanolx** [BestImageViewer/geeqie#516]
As the title says it would be nice to have a shortcut/feature "select random image".

**Comment by caclark** [comment]
#284 also refers to this subject.
Is this your intent - select from a single folder- or would it be to select from a recursive search?  (That could end up very time consuming)
Use a timer to periodically refresh the random image?

**Comment by caclark** [comment]
Could you use the slide-show feature, set to random, and with a long time delay?

**Comment by Nanolx** [comment]
In theory yes, but that would require two button presses (start + stop slide-show), which is not as handy.

Though, that's what I'm currently doing, actually; and the reason I asked.

**Comment by caclark** [comment]
If you need a single keystroke, set up a desktop file containing:
geeqie --remote --slideshow
geeqie --remote --slideshow
and allocate a keystroke to it.
Depends on the slideshow being set to random, of course.

**Comment by Lovewyrm** [comment]
Seconding this request. Add a bindable action to it, please.

**Comment by caclark** [comment]
It is possible to do this via a plugin, e.g. a script to execute:
find . -iname "*jpg" -o -iname "*.nef" | shuf -n 1
and then use whichever geeqie --remote command you prefer to show the file.
The advantage is that you can code it to use whatever parameters you want to select a file: type, folder recursion, file size etc. -  and you can do this right now, if you feel in the mood :-)
As with any plugin, you can put it in a menu or on the toolbar.
The disadvantage is that you either code in the file types you want, or you have to parse geeqierc.xml to get the filetypes set in Preferences/Files.
If this method were to be a standard plugin, it might require a better tool than Zenity - maybe Yad, but then that is another dependency.

If it were coded into Geeqie, it is rather more effort of course. Yet another tab on Preferences to select all the possibilities users might require etc.

I guess it is 6 of one, or half a dozen of the other, as some people say.

**Comment by Nanolx** [comment]
I'm currently using a script of my own which does X on command Y (not just for that purpose here):

* [randomfile](https://gitlab.com/Nanolx/bashstyle-ng/blob/master/rc/functions/randomfile
** the script used to fancy-print `-h` is here [bashstyle-help](https://gitlab.com/Nanolx/bashstyle-ng/blob/master/rc/functions/bashstyle-help)

Now I can call it like (multiple args after -- allowed):

`randomfile -z geeqie -r File: -- /home/chris/Pictures/*`

The script does currently not recursively parse directories, as it drastically impacts performance (imagine something like `-- /home/chris/Pictures/* /home/chris/Images` and now every item in Pictures is checked `test -d` ...).
