### ISSUE TITLE
copy path inserts quotes around path

### ISSUE THREAD

**Issue by archenemies** [BestImageViewer/geeqie#520]
When I select "Copy Path" from the drop-down menu, the copied path string has quotes around it. This is undesirable in many cases. True that it makes it easier to paste the path into most shells, but it makes it harder to paste it into e.g. open file dialogs. And the behavior is unexpected - if I paste something into a shell, I expect to type the quotes myself (if it needs quotes, which usually it does not).

**Comment by caclark** [comment]
The code calls g_shell_quote() which is defined as 

> Quotes a string so that the shell (/bin/sh) will interpret the quoted string to mean unquoted_string . If you pass a filename to the shell, for example, you should first quote it with this function

So someone thought about this, and deliberately inserted this call into the code.
Maybe the reasoning was the case where you select multiple files, and the filenames have spaces. Pasting that kind of unquoted string would be confusing.

**Comment by archenemies** [comment]
Regarding selecting multiple files, I think that's a good hypothesis for the origin of this behavior. I didn't realize that it's possible to copy multiple paths.

Perhaps there can be two options, one where we copy just filenames with newlines between, and one where we copy filenames with quotes and spaces. "Copy Path" vs "Copy Quoted Path".

Another solution would be only inserting quotes when multiple files are selected.

Perhaps this can be fixed together with #137.

**Comment by caclark** [comment]
Whatever the solution, it will involve extra menu items or keystroke modifiers.
For the moment you can implement your own solution, if you wish.
Allocate e.g. <alt>C to a new desktop file, and in that file echo the %f or %F parameters to xclip.

**Comment by archenemies** [comment]
Thanks but I don't understand "Allocate e.g. C to a new desktop file"...

**Comment by caclark** [comment]
Open Edit/Preferences/Configure editors
Click New to create a new desktop file, and call it my_copy.desktop
Edit the contents to include
Exec=my_copy.sh %f
Name="my copy"
Save it.
Open Edit/Preferences/Preferences and select the Keyboard tab
Somewhere in the list will be your new desktop file
Click on the Key column and type alt C , or similar and save
Create a script file called my_copy.sh containing
echo "$1"|xclip

Then whenever you press the selected keystroke your shell script will be executed.

If you want to see which keystrokes are available, click Help/Keyboard Map.
The map image will probably be initially displayed at a very small size - but that's just another Geeqie bug.

**Comment by archenemies** [comment]
Thank you @caclark.

I implemented your suggestion and checked that it works.

I think it's great that this level of configuration is possible. However, I think that the default configuration should also give similar behavior, so that users don't need to create special scripts just to copy a filename properly.

I'm glad that I learned something new, but I submitted this issue primarily because I wanted to help improve Geeqie and I hope that it is possible to make progress on this and other bugs. Thanks again.

**Comment by caclark** [comment]
It looks like people using Windows have the same problem -  and also solve it with a bit of a hack.
The default for Windows is also to copy file/path names with quotes.
By the way, did you realise you can drag-and-drop from the file or folder pane to get the file/folder name?
I guess maybe the way is to code shift-C and shift-DnD to be copy without quotes.

**Comment by archenemies** [comment]
I use a tabbed window manager so I don't usually drag-and-drop stuff, I prefer copy/paste.

My own preference is to have two menu items in the drop-down menu. This is because I just don't use Geeqie very much, and I upload photos even less. So if "copy" is bound to a keystroke but not in the drop-down menu, I'll likely forget it by the next time I use Geeqie. "Next time" may be as long as six months later. Even though it's a great piece of software! I just don't work with images that much.

Thanks @caclark for following up.

**Comment by mowgli** [comment]
Just my 2 cents. I think that the feature is usefull for the most of us (including me as I do many things on the shell and inserting already quoted stuff is a real help).

On the other hand, for GUI only stuff you might better use drag&drop instead of copy&paste.

**Comment by caclark** [comment]
I don't see a way to fulfil all aspects of this request without including another menu item. This looks a bit clumsy and increases the length of the menus.
Commit b0cb5d87 at geeqie.org implements this.
DnD actions still quote the data.
