### ISSUE TITLE
Set as wallpaper should be removed

### ISSUE THREAD

**Issue by zkeng** [BestImageViewer/geeqie#526]
Please remove the 'Set as wallpaper' option from future releases of Geeqie.
The 'Set as wallpaper' option does not work in many user cases. For example when the wallpaper is set with Feh image viewer, or with Nitrogen wallpaper manager. This and the fact that the wallpaper functionality in Geeqie can not be disabled in the application settings is confusing to users and prevent the application from being included as a preinstalled image viewer in distributions.

**Comment by mowgli** [comment]
I don't think that it is a good idea to remove a feature due to incompatibility introduced by unrelated software.

The bug lies in feh or nitrogen, not in geeqie. The feature in geeqie does exactly what it is made for.
