### ISSUE TITLE
source directory is not writable

### ISSUE THREAD

**Issue by installgentoo** [BestImageViewer/geeqie#527]
in recent master builds geeqie can't copy anything from or to root.

if we try to open file on root with "-f" it gives (geeqie:4056): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
and fails.

**Comment by caclark** [comment]
Could you give some details of how you run Geeqie?
Are you running Geeqie as root?
What are the read/write attributes of the files you are using?

**Comment by installgentoo** [comment]
it occurs whether i run it as root or user.

the file attributes are just your normal attributes- rw-r--r--

/ (which is the root i'm talking about, not the root user's directory) is owned by me and is rwxrwxrwx

1.3 works just fine.

**Comment by caclark** [comment]
Thanks.
Fixed in commit 74096520 at geeqie.org

**Comment by installgentoo** [comment]
thank _you_
