### ISSUE TITLE
'move' always use last used directory

### ISSUE THREAD

**Issue by mikiholiday** [BestImageViewer/geeqie#528]
There should be a setting to select the last used directory or the current directory.
Fg. when checking my photos I want to move the best pictures to another directory on the same level as I am on. But the offered directory I used last time has nothing to do with current project.

**Comment by caclark** [comment]
If you are using the copy/move dialogue, the left-hand panel contains bookmarks (or shortcuts).
The top one should be the "dot" folder. Clicking on that moves the dialogue to the current folder.

**Comment by mikiholiday** [comment]
Well, I think I do not have that one.
Thanks for your answer.

![geeqie_move_dialog](https://user-images.githubusercontent.com/32914187/31792190-80711e90-b51b-11e7-87f3-1c1b99078097.png)

**Comment by caclark** [comment]
> And Desktop did not work. Nothing happens if I click on it.

Clicking a "bookmark"  will set the path. If the displayed path is already at the path defined in the bookmark, nothing will change.

> Collections points to .local/share/geeqie/collections. I do not really get what it is good for.

This is a result of code being reused - in this case the Collections entry does not make sense, and should not be there. I guess that's just another bug.

However these "bookmark" entries are all user-definable. Right click on them to redefine or delete them.
New entries can be created by drag-and-drop of a folder.

In this case I suggest you edit the Collections entry, and change the Name to be "." (a single full-stop).
This is treated as a special case, and clicking an entry with this name will always set the path to the CWD.

**Comment by mikiholiday** [comment]
It was really helpful. Thanks.

I changed 'Desktop' to 'desktop' and now it works.

But using . or .. does not work, because it takes me to /home/user/ or /home/.
Probably when I open a file using 'Open with Geeqie' that does not set the path correctly.

Ok. I set geeqie %f for jpeg files and set Collections to '.'. Now it works almost as I want, but the '..' on the right pane does not work anymore. So I can not go to the parent folder if I use 'Collections'. Subfolders work.
Using other bookmarks make '..' work again.

**Comment by caclark** [comment]
I'm sorry, but I'm not sure if you have solved the problem you have.

When you right-click on the Collections bookmark, change the "Name" field from "Collections" to ".", and leave the "Path" and "Icon" fields alone.

Does that solve the problem?

**Comment by mikiholiday** [comment]
I am not sure I understand you exactly.
I set the 'Name' to '.' and 'Path' and 'Icon' to empty but it does nothing.
Than set the 'Path' to '.' as well and it works. Except the parent folder not reachable.

**Comment by caclark** [comment]
Which version of Geeqie are you using?

**Comment by mikiholiday** [comment]
1.2.2 Ubuntu

**Comment by caclark** [comment]
Sorry, I should have asked that first. The "dot" facility was included in v1.3.
However note that since v1.3 there have been more than 200 bug fixes and enhancements. Although it is a little more effort, compiling from sources does have worthwhile advantages.

**Comment by mikiholiday** [comment]
Well, you are right. I should try compiling from source.
Thank you for your help.
