### ISSUE TITLE
Remove Changelog.html and Readme.html from Makefile.am

### ISSUE THREAD

**Issue by tomaszg7** [BestImageViewer/geeqie#532]
In the commit 9caaac8fe283f59eecdd6caedc7cffb1817728e8 "Remove more links to sourceforge" files Changelog.html and Readme.html were removed. However they were not removed from Makefile.am thus causing a build fail.

**Comment by caclark** [comment]
I saw that - I guess I should have checked with Klaus about the reason for it.
Earlier today I made a new commit that generates README.html and ChangeLog.html during the build process. There should be no build fail with this.

My reasoning for wanting the html files is:
They are easier for the user to read
You can use the browser search facility to easily search for words and phrases
ChangeLog.html has hyperlinks to the GitHub commit, and so from there to the origination issue

But, as always, if someone thinks this is the wrong way to go I can just revert the commit.

**Comment by tomaszg7** [comment]
Yeah, I saw that commit but it didn't fix the problem. I just rechecked on a clean copy and I still get

```
make[2]: Entering directory '/tmp/geeqie'
./gen_readme.sh
make[2]: *** [Makefile:1147: README.html] Error 1
make[2]: Leaving directory '/tmp/geeqie'
make[1]: *** [Makefile:667: all-recursive] Error 1
make[1]: Leaving directory '/tmp/geeqie'
make: *** [Makefile:499: all] Error 2

```

**Comment by caclark** [comment]
Fixed in commit 4064414bb at geeqie.org

**Comment by tomaszg7** [comment]
BTW. Since `Changelog` itself is also generated, so it probably should be removed from git tracking.

**Comment by caclark** [comment]
I guess that's mostly true - actually the first 6000 or so lines are entries made by John Ellis in pre- CVS/GIT days. Currently they are extracted and then pasted back onto the end of the git log.
So those first set of lines should be saved maybe as a discrete file.

**Comment by tomaszg7** [comment]
It might even be better to keep those separate as formally they are a changelog of another project (GQview) and it is not obvious right now when looking at `Changelog`. Something like `Changelog.gqview` or simply `Changelog.old` might be some solution

BTW. Files `CODING` and `HACKING` still refer to svn, not to git. Also `BUGS` refers to sourceforge mailing lists.

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am Di den 31. Okt 2017 um 14:02 schrieb Tomasz Goli??ski:
> BTW. Since `Changelog` itself is also generated, so it probably should be removed from git tracking.

No, that is only partly generated. There is some stuff that doesn't come
from git.

Gruß
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAln54ZAACgkQpnwKsYAZ
9qxrqgwAgO/nQSDGPI538qJEpESmbIgfI783Htfa3GlpE+YG46ydz7sL4v4yZ2gn
7/C1+S6MniqoC4MEXsPe168hnv8x18ZqGZLO5cODbbLIQbkivy3yKjK6dT8ri72O
yiz3PQciTLbg8wDqAo5maseKLxP5BB2Q6yJaDmrdbMf1VnFjc6E8Y60TLpSr+v7t
UW1Jtq0LfxXFMPnxn/vU090XnXTZqhh4zR63hGq3avuzxwNXmKGhxHGZwybPUmon
dfQp3jpOUyXzk6luCT0LQy9onwAUt5n3mHK5qhglpZ5csK6wp8ovGj+umsyxVFek
oCIlXUTcClX1iIHj3u+V/PF0xlQBLJr+0lQIwqchWrYTbP/aATCFJfL3GZkFLKy9
IzZRkJxRD/eanKDrS8VyW9hvkQOf1E7cLI6/HCjvYry+9D55KGOFdT2hXN9q9PgC
0zi6DN+C7l/4Pdr0RZj5b5TlubiOnqtqpR2RlK1kX26oZsLhSnIv2ZSH59+w0Mgt
GxaLU6kI
=epy6
-----END PGP SIGNATURE-----

**Comment by tomaszg7** [comment]
> No, that is only partly generated. There is some stuff that doesn't come from git.

Yes, I understand that. But each build modifies it and that adds noise to `git diff` output.

**Comment by caclark** [comment]
> BTW. Files CODING and HACKING still refer to svn, 

The CODING file also requires doxygen comments to be this style:
`   /**
    * \brief This is a short description of the function.`

Unfortunately I've used the alternative style of `* @`.

This because the editor I use has a plugin that automatically creates this style; and `* @` is easier to grep for.
But I guess it's no big problem. With 100,000 lines of code and 100 lines of comments, the code:comment ratio is looking better than I've seen in some commercial projects.
It would be easy to change either way.
