### ISSUE TITLE
fails to make install if markdown not install

### ISSUE THREAD

**Issue by unhammer** [BestImageViewer/geeqie#533]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION

```
Geeqie 3d8820a4
```

### OS / DISTRIBUTION
xubuntu 17.04

### SUMMARY
make install fails because there is no README.html

### STEPS TO REPRODUCE
don't have markdown installed, then run

`./autogen.sh --prefix=$HOME/PREFIX/geeqie && make -j4 && DESTDIR=/tmp/ make install`

I'd prefer if README.html was in git even though it's generated, but I guess configure could only build/install it if markdown detected.

**Comment by caclark** [comment]
Fixed in commit 605297a690 at geeqie.org
