### ISSUE TITLE
Copy Path uses wrong clipboard

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#536]
f882d3ca

The "Copy path" context menu item seems to use the PRIMARY clipboard, which means you cannot ctrl+v paste it. It should use the CLIPBOARD clipboard so that ctrl+v is possible.

**Comment by tomaszg7** [comment]
It already has its issue: https://github.com/BestImageViewer/geeqie/issues/137

**Comment by Beep6581** [comment]
Duplicate of #137
