### ISSUE TITLE
Sort Configure Plugins by default

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#538]
f882d3ca

Edit > Configure Plugins, the list is not sorted. Would be nice if it was sorted by the Name column by default.

**Comment by caclark** [comment]
Fixed in commit 0ede96cf1d at geeqie.org

**Comment by Beep6581** [comment]
Thank you @caclark , fix confirmed!

Though strange, when I open About Geeqie, it shows commit f882d3ca, but git describe shows `v1.2-400-g`0ede96cf and I must be using it since I just deleted the build and recompiled.

**Comment by caclark** [comment]
> when I open About Geeqie, it shows commit f882d3c, but git describe shows v1.2-400-g0ede96cf 

I think this is because autom4te.cache is not cleared by "make distclean". If you delete the folder and re-run autogen.sh, I think everything will be as it should.

I don't if this is a bug, or if the Geeqie installation instructions need to be amended to include commands to delete the folder.

**Comment by Beep6581** [comment]
I continued this in #542
