### ISSUE TITLE
Incorrect scaling in Zoom to fit mode

### ISSUE THREAD

**Issue by beelze** [BestImageViewer/geeqie#540]
* Bug Report
```
Geeqie 0ede96cf
```

Images scales incorrectly in Zoom to fit mode. For instance, for image with dimensions 753 × 324 I see 3.82:~1 scaling (fullscreen on 1920 × 1200 monitor), whilst Fit Horizontal/Vertical works fine. In not-fullscreen mode Zoom to fit works incorrectly too.
The numbers 3.82×324=1238 and 3.82×753=2876 not correlating with nothing.

Enlargement for zoom to fit set to 500%, limit size when autofitting – 150%.

The same behaviour I see at least in two last years, on Xfce/Mate, with or without Compiz, i965 or proprietary nvidia drivers, on any monitor(s), so DE/WM/video driver is not relevant.

**Comment by caclark** [comment]
The "Limit image size when autofitting" option specifies a zoom factor for the window:

> This percentage will affect the size of the image when Fit image to window is set. Instead of using 100% of the window, it will use the specified percentage. It allows one to keep a border around the image (values lower than 100%) or to auto zoom the image (values greater than 100%). It affects fullscreen mode too. 

So in your case 1920 * 1.5 / 753 = 3.82

**Comment by beelze** [comment]
Thanks for the explanation. Maybe «Limit image size when autofitting» should be renamed because it is not obvious that this option overrides «Zoom to fit» logic (or, maybe, extendes it)

**Comment by caclark** [comment]
> Maybe «Limit image size when autofitting» should be renamed

Commit b0ea0793d4 at geeqie.org

**Comment by MXB2001** [comment]
This option is utterly misleading. Expected: Limits zoom factor to % entered. So 100% should mean at most it will double the size of an image when autofitting a small picture. What it actually does is unlikely to be useful to the majority of users.
