### ISSUE TITLE
About window shows old commit

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#542]
Continuation of #538

> I think this is because autom4te.cache is not cleared by "make distclean". If you delete the folder and re-run autogen.sh, I think everything will be as it should.
>
> I don't if this is a bug, or if the Geeqie installation instructions need to be amended to include commands to delete the folder.

Deleting the build folder, running `make clean`, `make distclean`, and re-running `autogen.sh` made no difference, About still shows the old commit. Anyway doing the above should not be necessary, as that means that everything would need to be recompiled, even if not much changed between commits. Looks like a bug to me.

**Comment by caclark** [comment]
Deleting that folder definitely works for me.
It would be a help if you could identify where the old commit ID is coming from - because it must be somewhere in your build tree. After a distclean could you run a grep to find which files contain that ID? 
Make sure every file is grepped - all "dot" files and "dot" folders too.
You can ignore files such as configure and Makefile which will show up, but get regenerated anyway - but somewhere there will be a file containing that ID.

**Comment by Beep6581** [comment]
@caclark here you go:
http://dpaste.com/2YA05TX
https://i.imgur.com/QxfXVbx.png

**Comment by caclark** [comment]
The old ID is still in the cache files. Try:
`rm -r autom4te.cache`
`./autogen.sh`

This is an unforeseen effect from using the commit ID as a revision number - it was done this way so that bug reports would show exactly which commit is being used.
Maybe a solution is to simply disable generation of the cache.

**Comment by Beep6581** [comment]
Confirmed, that worked.

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am Sa den 11. Nov 2017 um 16:51 schrieb Beep6581:
> > I think this is because autom4te.cache is not cleared by "make distclean". If you delete the folder and re-run autogen.sh, I think everything will be as it should.
> >
> > I don't if this is a bug, or if the Geeqie installation instructions need to be amended to include commands to delete the folder.
> 
> Deleting the build folder, running `make clean`, `make distclean`, and re-running `autogen.sh` made no difference, About still shows the old commit. Anyway doing the above should not be necessary, as that means that everything would need to be recompiled, even if not much changed between commits. Looks like a bug to me.

I also cannot see at the moment why you have different informations.

Did you try "git reset --hard; git clean -fdx" and then rebuild?

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAloIR4YACgkQpnwKsYAZ
9qx1PAv/SgNXaYRiK/exuS+iQIN188dnK0YNHKQHTJ5SrAStC+fkAZItmL9NtkEI
pQWcHReDC/ldQMG3ppCGDpPyLIxZB9s/FptNwZSmgTeSlZOXGogss8fxE0YkgQ+i
3KFOj/t1rvJgOdTo0oC3gB7urZ54R4+EZgIVIWeMyN/gLwg3uvt168bbA+S8hNPX
4cCqrELHGEDbyrqB6EWPaY2jVaOVmBKccOZXWjlAJaQ87zADWRjTsOXWVC1Pbbbu
XNjP4fx8wwddxYbRUV+T6GikEiKKPH31EYm7I1r+49YsoTvs7GqsGN5qC6QQIJE9
8nKJ5J21Ur/HCHeCZSQTMoYf0RRExpGoZnNZ5XEG4U098V7yheVph/KGZiwgUuz+
6VXN39GstShAkqF/0AFcOA5ky1uLtchYMrVZfKMVIw1iawSQMp5XSMWdManezwAi
kPm6rGPMMsWFU2CC64qAkr+1wJXO3/471nNadnXXBkRSUpkD/mxliKRfTauqLvvT
9It2szXh
=n5jL
-----END PGP SIGNATURE-----

**Comment by caclark** [comment]
Revised re-installation documents in commit e702a744b4 at geeqie.org.

Use:
`sudo make uninstall; sudo make maintainer-clean; ./autogen.sh; make -j<no. of cpu cores>; sudo make install`

**Comment by Beep6581** [comment]
```
$ make uninstall
$ make maintainer-clean
$ ./autogen.sh --prefix="$HOME/programs/geeqie"
$ make install
```
Confirmed, works.
