### ISSUE TITLE
Failure to assign keys <Primary>p, <Primary>n and <Primary>f to new actions

### ISSUE THREAD

**Issue by marcelpaulo** [BestImageViewer/geeqie#546]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie a2504a3a
```

### OS / DISTRIBUTION
Xubuntu 17.10

### SUMMARY
If I try to assign keys **<Primary>p**, **<Primary>n** or **<Primary>f** to new actions, keyboard preferences show that they have been assigned, but they still cause their default actions.

### STEPS TO REPRODUCE
1. Assign keys **<Primary>p**, **<Primary>n** or **<Primary>f** to any actions
1. Click on the keys
1. They should cause the new actions, but instead they cause their default actions

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am So den 26. Nov 2017 um 16:27 schrieb Paulo Marcel Coelho Aragão:
> ### SUMMARY
> If I try to assign keys **<Primary>p**, **<Primary>n** or **<Primary>f** to 

What do you mean with "<Primary>"? I never heard of such a key.

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAlobwv4ACgkQpnwKsYAZ
9qxMdQwApDjiGvn0sTtpo093FbGcRpzmc7wQ7fRTq1yUxoi5DTrhTinlZFpHFsl1
OIumR06e0SUZERdXV/5tYcevFGpyKl92qgd2vwSlyjwtY9TkNG6jSZn3iBjrj9xS
yxS77Qx8Yy3ymT/FC3wPz37sRzDam/dTm+AP4K+TNBEoDdTcxjVL0X+r/qLthN0g
yJMsu9v5QnQyHUrQQchRvDAXL5OALDj3ytAOPfhUpy6DGxyPlVlojoSFF/unQGjk
h587GZpB5sOdp/AfJyMKTAmnyPG2dZoE+VwHo5H3hF71PYyawpvG3ygyTMan7JjL
cEjYfeUKMgJ28+I0dglK+M2N09Qe1X/jc/chC7xD5R8+FJet1EhNfKL/vwt54egc
5GWgqmepER5iWTp8P2bTNbYmZfRcHL3iuTE2gu8BYJfYEkkrUNJoGQCjTl391Kyw
azO1d/EftDSMIe6ksrwbmsViPWTJyZc1+a0p/gtXvIlpILYnEbknX1+Mq0uCFZOY
MWkH1lTW
=bhIv
-----END PGP SIGNATURE-----

**Comment by caclark** [comment]
I cannot replicate this behaviour.
Does this effect apply to any action you try to redefine?
The only suggestion I can make at  the moment is to look at:
`~/.config/geeqie/accels`
where you will see how the keys are allocated.
The other possibility is that is related to the upgrade to Ubuntu 17.10 - I am still using 17.04 and will be for the next few weeks.

[The redefinition of "control" to "primary" seems to be a GTK thing. I think it's something to do with being able to handle differing keyboard layouts for different operating systems - probably Mac is the problem]

**Comment by marcelpaulo** [comment]
> What do you mean with "<Primary>"? I never heard of such a key.

@mowgli, that's how **Ctrl** is encoded in _~/.config/geeqie/accels_

> Does this effect apply to any action you try to redefine?

@caclark, oh my, I cannot reproduce it myself anymore ! Yesterday I couldn't redefine external plugins, but right now I was able to redefine any actions, internal or external. I'm wondering if yesterday I was careless enough not to have clicked on **Apply** after remapping the keys.

Anyway, please accept my apologies for raising an unnecessary issue.
