### ISSUE TITLE
Send text output to stdout

### ISSUE THREAD

**Issue by JohnCC330** [BestImageViewer/geeqie#548]
### ISSUE TYPE

* Feature Request

### GEEQIE VERSION

```
Geeqie 5a6cd202
```

### SUMMARY

Output from eg. geeqie -h goes currently to stderr. Seems most, if not all
other programs send output to stdout
### STEPS TO REPRODUCE

geeqie -h | grep version    
or, say:
geeqie -h > geeqie_help

Don't work. Not very urgent or important, but maybe easy to solve?

**Comment by tomaszg7** [comment]
It was also discussed for a while in https://github.com/BestImageViewer/geeqie/issues/512

**Comment by JohnCC330** [comment]
Hi Tomasz,  Thanks for that indication (and for the work on geeqie in general!). Didn't know about !& (though I knew about most other variants). Cheers

**Comment by caclark** [comment]
Fixed in commit 11622a75 at geeqie.org
