### ISSUE TITLE
Update geeqie ICON

### ISSUE THREAD

**Issue by jEsuSdA** [BestImageViewer/geeqie#552]
Hi!
What do you think about changing the geeqie icon.
I think the nowadays icon is a bit older.

Maybe a modern one like the Papirus icon should be fine:

[geeqie.svg.zip](https://github.com/BestImageViewer/geeqie/files/1523741/geeqie.svg.zip)

![geeqie](https://user-images.githubusercontent.com/5833446/33514665-366dba6a-d758-11e7-86cb-34e7deb244e3.png)

Thanks!

**Comment by tomaszg7** [comment]
I think that some kind of update is needed but I wouldn't be in favour of such a drastic change. But the least that should be done is installation of higher quality icons that are already there: https://github.com/BestImageViewer/geeqie/issues/511

**Comment by qarkai** [comment]
@caclark Related to #179.
