### ISSUE TITLE
Ratings seems to be broken

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#554]
8e848353

I want to cull images uploaded from an SD card, so I copied the raw files to disk, hit Alt+1 to assign "Rating 1", and nothing happens. I tried Edit > Rating > Rating 1, nothing happens.

Tried on raw files (ARW), PNG and JPEG.

Does rating work, where would I see each image's rating, and how do I view only images with some specific rating?

**Comment by Beep6581** [comment]
"Marking" works and fulfills my culling needs, but I'm still curious about ratings and why they seem to not work.

**Comment by caclark** [comment]
Ratings are stored in xmp data, so you will see them in the info sidebar
The permitted values (-1, 0..5) are defined somewhere on the web - but the link to Adobe (where I think this data is defined) in the Help file has gone dead.
The Search page has an option to filter on ratings.

There is some information in the Help file regarding ratings, but it is hard to find.

I know that a technical document without an index is not much use - but I've tried, and failed,  several times to create an index for the Help file.

I guess you could log another issue about that, but me, I'm just trying to reduce the number of outstanding issues ... :-)

[And I would say that Marks are more suitable for the task of deleting  unwanted files - I think Ratings are intended as a more permanent attachment to the image]

**Comment by Beep6581** [comment]
I am familiar with the XMP spec.

I examined the files using ExifTool and saw no stored XMP ratings.

So there seem to be two issues here:
1. Storing the XMP rating seems to not work currently (I tried ARW, PNG and JPG).
2. Geeqie should be verbose if storing the rating failed or is not possible (I guess/hope Geeqie does not edit raw files, for example, but in that case it should popup an error that storing ratings in raw files is not possible/not allowed, unless the user enables editing raw files in Preferences).

**Comment by caclark** [comment]
After you set a ratings value, the icon on the far right of the status bar will become enabled.
Click on it to show a status window about the metadata to be written.
Click on the "File Details" button, and that will display the location the metadata will be written to.

**Comment by Beep6581** [comment]
Confirmed that it works. The rating was written to the XMP file in `~/.local/share/geeqie/...`, and to the image itself when I set that in preferences.

This dialog would be more readable if the hbox wasn't heterogenous, so that the right side doesn't take up half the space even when it shows a image which takes a fraction of the space:
![imgur-2017_12_06-11 28 53](https://user-images.githubusercontent.com/5844619/33657189-c43b6c66-da78-11e7-955f-40b15558befd.png)

**Comment by caclark** [comment]
Because of the sizing problems of dialogues in GTK3, there is a new option in Preferences/Windows to remember the size/position of dialogue windows.
But if you cannot resize that dialogue window to a smaller width, then that is a problem I was not aware of.

**Comment by Beep6581** [comment]
It's not about the dialog's size but of the hbox or whatever was used to halve it. In that dialog the filenames are more important than the preview.

**Comment by caclark** [comment]
> This dialog would be more readable if the hbox wasn't heterogenous, so that the right side doesn't take up half the space when it shows an image which takes just a fraction of the space:

Fixed in commit 29d858934 at geeqie.org
