### ISSUE TITLE
Geeqie won't start if clutter fails to init

### ISSUE THREAD

**Issue by tomaszg7** [BestImageViewer/geeqie#559]
### ISSUE TYPE
* Bug Report

### SUMMARY

Enabling gpu-accel at build time makes Geeqie fail to start if for some reason `gtk_clutter_init()` fails. I believe in this case, Geeqie should revert to normal `gtk_init()`. However that poses an additional problem - GPS bar pane won't work. 

I think that Geeqie should keep a variable to remember if clutter was initialized and act accordingly. Here's my attempt to resolve the issue: 

[geeqie-clutter-fallback.patch.gz](https://github.com/BestImageViewer/geeqie/files/1573117/geeqie-clutter-fallback.patch.gz)

### STEPS TO REPRODUCE
Compile Geeqie with gpu-accel enabled and e.g. update nvidia-drivers without reloading the module and restarting X ;)

**Comment by caclark** [comment]
Hello Tomasz

Are you able to get gpu-accel to work?

I am still not able to get anything sensible. Initially there is a run-time error that is generated by rc_set_shader() -  that seems to be there only to generate the checker-board background colour.
Patching that out gets images displayed with false colours... and a pretty rapid crash from a memory access problem.

**Comment by tomaszg7** [comment]
Nope. Just like in https://github.com/BestImageViewer/geeqie/issues/397 I didn't look at the code. I just had clutter installed from the time I wanted to see how GPS bar looks like and it was autodetected since then causing me trouble each time I updated drivers.

FWIW I just checked GPU render with Nouveau and all I get is black image (as opposed to various colours on proprietary Nvidia). Will try to check on AMD later.

**Comment by tomaszg7** [comment]
Seems the patch is not working as expected. Deeper testing shows that the app doesn't recover correctly from a failed `gtk_clutter_init()` call. Calling a plain `gtk_init()` afterwards makes app crash in the main gtk loop. I don't see a way around it and only way to mitigate the problem that comes to my mind would be to introduce a command line option to choose between `clutter` and `noclutter` gtk init.

**Comment by gusnan** [comment]
I am guessing that this bug in Debian is related to this:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966509

**Comment by caclark** [comment]
There is a new commit for this - as suggested by Tomasz there is a command line option:
`geeqie --disable-clutter`
If a user continually has this problem it will be necessary to set an alias.
I am not sure about storing this in the options, but anyway the init. needs to be done before the options are read. `gtk_init` is supposed to be executed before any other gtk functions are used.
[Actually gtk functions are used in main.c before the init. - but I don't feel too enthusiastic about changing things around]

**Comment by ildar** [comment]
Excuse me, I don't catch it: is it supposed to be normal to have the application crashing and to provide just a workaround (cmd line option)?

**Comment by tomaszg7** [comment]
As far as I know, the app is not crashing. It is just exiting with description of error.

**Comment by ildar** [comment]
Yes, my fault. It's not crashing.
But from a user POV a GUI app printing something to stderr and exiting is
the same.

**Comment by tomaszg7** [comment]
So what should be the alternative? If Geeqie cannot initialize graphic interface, all it can do is output text error to the console. Simplest solution from user's point of view would be to compile Geeqie without clutter support if it is broken on some system.

**Comment by ildar** [comment]
possible alternative: try running with clutter, if fails then warn and run
without it.
Regarding broken clutter: I don't know exactly but many clutter apps run
just fine. Only Geeqie fails.

**Comment by caclark** [comment]
There is a new commit in the repo. relating to this.
As Thomas mentions, the GTK graphics is not available, so I used the command line program Zenity - which might not be in all distributions .

The message is still rather brief, and does not reference the underlying problem (whatever it is).

I vaguely recall another discussion about faults of this type requiring *both* console and GUI messages - but I don't remember where.

gtk_clutter_init() is used rather than clutter_init(), because that is what the documentation says is the correct way (although the word "should" is used, rather than "must").
So I am wary of using clutter_init() to make a test. And even so, the user would end up running a program with reduced functionality without warning.

**Comment by tomaszg7** [comment]
That was the original idea, however it didn't work: https://github.com/BestImageViewer/geeqie/issues/559#issuecomment-355757996 Maybe other applications are doing something smarter, I don't know. If you would give me an example of clutter app that works fine on your system, maybe we could see the source and figure something out.

**Comment by ildar** [comment]
[geeqie.ltra.txt](https://github.com/BestImageViewer/geeqie/files/6693750/geeqie.ltra.txt)
[shotwell.ltra.txt](https://github.com/BestImageViewer/geeqie/files/6693751/shotwell.ltra.txt)

**Comment by tomaszg7** [comment]
Hmm, Shotwell doesn't mention clutter anywhere in their source code. It probably uses some shared Gnome way of initializing clutter. On top of it, it is written in Vala... I don't think I know enough about Gnome to dig anything out (at least not with current time restrains).

**Comment by ildar** [comment]
One more nice thing about it:
```
$  LANG=C GDK_SYNCHRONIZE=1  geeqie --disable-clutter

(geeqie:3975550): Gtk-WARNING **: 11:32:06.553: Theme directory
48/mimetypes of theme Qogir has no size field

Unable to initialize the Clutter backend: no available drivers found.
Run ?shotwell --help? to see a full list of available command line options.
```
This is when I try to run Shotwell from inside the Geeqie. Somehow Geeqie
brakes things out (Shotwell runs fine by itself). I'm guessing that ENV
manipulations were added?
