### ISSUE TITLE
"Create folder" under "move" should select new folder

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#56]
[ Forwarded from Debian BTS: http://bugs.debian.org/529531 ]

When I select some files, right-click, and say "move", and then say
"New folder", I can create a folder.  It's very nice--if I've entered
the name of a folder that doesn't exist, that name is moved into the
new folder's name.  But then:

Desired behaviour: Create folder and add it to the target path.

Actual behaviour: Create folder.  If folder name was copied from
target path below, it is removed from target path when it is
created.  I always have to remember to double-click it (or re-enter
its name below) before it appears in the target path.  Tedious!

Thanks for the great software!

Reported by: cg25

**Comment by caclark** [comment]
Another fix in commit 5428ae8e0 at geeqie.org
