### ISSUE TITLE
Displayed images, image overlays and thumbnails are blurry on Hi-DPI displays

### ISSUE THREAD

**Issue by zivanfi** [BestImageViewer/geeqie#561]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION

```
Geeqie 5a6cd20
```

### SUMMARY

On Hi-DPI displays, GTK/GDK application pixels automatically correspond to blocks of device pixels as described [here](https://wiki.gnome.org/HowDoI/HiDpi). In addition to querying the screen/window size (which is in application pixels), applications can also query the scale factor between device pixels and application pixels. If I understand correctly, geeqie should display higher resolution pixbufs on its UI (multiply the pixbuf size by the scale factor) in order to use the actual resolution of the display. Geeqie apparently does not do this, therefore displayed images and image overlays are blurry on Hi-DPI displays.

Additionally, in Hi-DPI mode a grid appears over the displayed images. This is probably a consequence of cutting pixbufs to tiles and displaying them side-by-side. In Hi-DPI mode these tiles do not seem to touch each other. This may be a geeqie bug or a GTK/GDK bug.

### STEPS TO REPRODUCE

One way to set up Hi-DPI mode is using the system preferences of almost any desktop environment. This usually results in a Hi-DPI scale factor of 2. This already makes the issue visible, but for testing I recommend a scale factor of 4, which makes the problem even more apparent. To do this, start geeqie by issuing `GDK_SCALE=4 geeqie`.

I attached some screenshots that demonstrate the problem (please open them in full resolution for inspection). First, for a reference, I started geeqie without any Hi-DPI scaling by issuing `GDK_SCALE=1 geeqie` and displayed a photo:

![unscaled](https://user-images.githubusercontent.com/20930533/34319068-e7ff342c-e7d7-11e7-85dd-bfe73b76e080.jpg)

Please note that on the screenshot above the zoom level is 1:1, so what you see are the actual pixels of the photo.

Next, I started geeqie using `GDK_SCALE=4 geeqie` and displayed the same photo:

![scaled](https://user-images.githubusercontent.com/20930533/34319070-f27555f8-e7d7-11e7-8c63-aba06e87e016.jpg)

Things worth noting here:

- The text in the status bar is very crisp, because it is handled by GDK/GTK.
- In contrast, the text in the image information overlay is very blurry. The surrounding white rectangle is blurry as well.
- The displayed photo has clearly lost a lot of detail compared to the non-HiDPI screenshot and has become very blurry. Now it consists of 4x4 blocks.
- There is a clearly visible grid over the image.

Please also note that on this screenshot the zoom level is 1:4; the photo had to be zoomed out in order to appear at the same size. Although one could argue about whether a zoom of 1:1 or 1:4 should result in the same displayed size (i.e., whether the Hi-DPI scaling factor should become a part of the zoom ratio or not), either of them would be fine on its own as long as it works consitently with fit to screen. The important thing is that since we zoomed out, 4x4 image pixels correspond to a single application pixel, which in turn corresponds to 4x4 device pixels (due to Hi-DPI scaling). So since we have an image pixel for every device pixel, we should see individual pixels as separate device pixels.

**Comment by caclark** [comment]
> Additionally, in Hi-DPI mode a grid appears over the displayed images. This is probably a consequence of cutting pixbufs to tiles and displaying them side-by-side. In Hi-DPI mode these tiles do not seem to touch each other. This may be a geeqie bug or a GTK/GDK bug.

I don't have a high-resolution monitor, but the grid effect can be replicated simply by executing
`GDK_SCALE=2 geeqie`

Other image viewers don't show this effect , so it must be a Geeqie problem.

**Comment by zivanfi** [comment]
> Other image viewers don't show this effect , so it must be a Geeqie problem.

That's true, but other image viewers typically don't display images split to tiles. It seems to me that Geeqie does a lot things (scaling, zooming, scrolling) that other image viewers leave to GTK widgets. Those viewers get Hi-DPI support "for free", while in Geeqie the mixture of Hi-DPI-aware drawing of GTK and non-Hi-DPI aware drawing of the application itself may bring out strange side-effects.

For example, let's suppose that Geeqie splits pixmaps into tiles of 10x10 pixels size (a round number for our convenience), and places those at the following X coordinates:

- 1st column starts at X = 0, ends at X = 9.
- 2nd column starts at X = 10, ends at X = 19.
- 3rd column starts at X = 20, ends at X = 29.
- ... and so on.

The tiles touch each other, since X = 10 is right after X = 9 (and so on).

Now if GTK/GDK automatically doubles these values in Hi-DPI mode, we get:

- 1st column starts at X = 0, ends at X = 18.
- 2nd column starts at X = 20, ends at X = 38.
- 3rd column starts at X = 40, ends at X = 58.
- ... and so on.

This time there is no tile covering the X = 19, X = 39, ... pixel columns, which may explain the grid effect.

This is just a theory, I suspect that *something* like this may be happening, but certainly not *exactly* this, because this would lead to a grid width of 3 pixels for GDK_SCALE=4, but the width of the grid lines is only 1 pixel in reality. Actually, it's not even 1 pixel, it seems that those pixels get displayed as well, but with some amount of transparency. You can see this when changing from one image to the next and the images have different colors. You can also alternate between zoom-to-fit and zoom-to-1:1 repeatedly on a single photo. After the first cycle, the grid gets fainter and by the second time it disappears entirely.

**Comment by caclark** [comment]
>  It seems to me that Geeqie does a lot things (scaling, zooming, scrolling) that other image viewers leave to GTK widgets.

The initial design decisions were made by John Ellis 20 years ago. Things have changed...
But that doesn't help your problem.

The tile size is set in line 63 of renderer-tiles.c Make that a larger number, and the grid effect will go away.
The coding error is still there, of course.

The blurriness is still there. I made some changes with xrandr, which (maybe) improved things a little for me.
But the problem remains.

> After the first cycle, the grid gets fainter and by the second time it disappears entirely.

I don't see this effect (but I'm not using a hi-res monitor)

**Comment by zivanfi** [comment]
> The initial design decisions were made by John Ellis 20 years ago.

I didn't mean to criticize these design decisions, it was just an observation. In my opinion Geeqie is a better and faster image viewer than the others I know and this may partly be due to these design decisions.

> Make that a larger number, and the grid effect will go away.

That sounds like a good short-term fix, thanks.

> The blurriness is still there.

I think that could be addressed by creating GDK_SCALE-times larger pixbufs than what seems necessary, and I have experimented with multiplying some sizes in pixbuf-renderer.c, but to no avail.

**Comment by zivanfi** [comment]
While searching the internet for how to make pixbufs on Cairo surfaces Hi-DPI-aware, I found a similar issue in another application and a patch that fixes it:

https://mail.gnome.org/archives/commits-list/2015-August/msg06718.html

This looks exactly like what is needed here. I did the same modification in rt_tile_render(), which made Geeqie render to device pixels instead of to application pixels. However, without updating the tile alignment as well, there is huge gap between the tiles. But at least the tiles and the overlay are not blurry any more, so it looks promising.

![1st-step](https://user-images.githubusercontent.com/20930533/34419173-a93cb618-ec02-11e7-9207-cc8d6e48f29f.jpg)

**Comment by zivanfi** [comment]
I created pull request #573 with a fix for the displayed images (both blurriness and grid artifact are gone). Image overlays and thumbnails are not addresset yet and are still blurry.

**Comment by caclark** [comment]
Partial fix in commit 705cf22ee in main repository at geeqie.org.
Commits there are synched back to the repository here at github.

**Comment by zivanfi** [comment]
Since my commit only solved the problem with displayed images, I created #582 for image overlays and #583 for thumbnails.
