### ISSUE TITLE
v1.4 not merged back into master

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#565]
Hello

I see that v1.4 was tagged in the `stable/1.4` branch, but that branch has not been merged into `master`, and so `master` is missing some commits and it's missing the v1.4 tag, and if one gets the latest `master` code the release notes, news and other files still make no mention of v1.4.

**Comment by mowgli** [comment]
This will never be done! The stable branche are not ment to be merged back to master and poluting it with release stuff.

If you read the commit log, you see that some relevant stuff is committed there too. But only the relevant stuff as it should be.

**Comment by tomaszg7** [comment]
Except for the `NEWS` file part. It wasn't updated in `master`.

**Comment by Beep6581** [comment]
This issue is marked as "invalid" while `master` still links to the 1.3 tarball and still makes no mention of 1.4 and still points to the obsolete Sourceforge mailing list...
What pollution are you referring to?
https://github.com/BestImageViewer/geeqie/compare/stable/1.4

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am Di den  2. Jan 2018 um  0:35 schrieb Beep6581:
> This issue is marked as "invalid" while `master` still links to the 1.3 tarball and still makes no mention of 1.4 and still points to the obsolete Sourceforge mailing list...
> What pollution are you referring to?
> https://github.com/BestImageViewer/geeqie/compare/stable/1.4

Sorry, but did you ever had a look at the current master?

dfcc7037b37c did the same mailing list related stuff in master.

ebecbdef159b did the website changes in master

On the other hand, we don't want to have the gtk2 default in master and
we want to have version strings from commit rev-parse. All would be
drown away with a merge.

Please, if you complain about something not in master, check before.

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAlpKya4ACgkQpnwKsYAZ
9qxvlQv9HSBzEka+o1jO4ql55GoaEoUiS4j/yZ4kNM+B/TDo80jZ2r1WVRsJ4Fdk
b/tF9FJaj0Ts8dOfuOqx6FJEMQlKW+7seouI2zvIm4ee57oKY8BLF5iHRKxuSt3j
kWb/0AjTfozIaVTdgB3tk5aVg3FDxVnCMkgQf4U+pJsH5XCWy/WJqL7EBCKZlSn6
/JD7fVLkTV+tG146DjeGUBhj0VLBkP6lj4VqrrshfU92yNzyv1omgHzD3dFvQhZA
jUWjk+2qXGM6vxnJC5hyPQaN1lPKqCHra4ExrU3YgxYRb90Wf+qBQf0ypnAsntJO
GOzYbvIKYy4IXZLVMsjz7B+1F0YAMQrtxSIiTE+LixRqwYBnGrOyjtaG4FUeuR3h
0tPvrHFpPg8EkJ/V4oU/wazmwx6e1XHTPFw7Ev1NRaUoCT/tHHu2A+y4l1kt8bXR
YRNDByKzJaKYxP06drss5aGPCp57VaU3XzHGXIQuw8zWH9ZP1UBA8c6JKyyq6L5Z
YWWvKa26
=vpX5
-----END PGP SIGNATURE-----

**Comment by tomaszg7** [comment]
I did check and `NEWS` is still not updated: http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=blob;f=NEWS;h=9e11fed57e2bf882f18aaf4e30b1474ff420c8b4;hb=HEAD

**Comment by Beep6581** [comment]
I missed the website and mailing list change commits because GitHub uses the symmetric difference `...` comparison, while I should have used the plain `..` comparison in git which GitHub [doesn't seem to support](https://github.com/BestImageViewer/geeqie/compare/master..stable/1.4).

> Sorry, but did you ever had a look at the current master?

Indeed, and the release notes still point to the 1.3 tarball:
[`README.md`](https://github.com/BestImageViewer/geeqie/blob/master/README.md) line 105
and [`NEWS`](https://github.com/BestImageViewer/geeqie/blob/master/NEWS#L1) still makes no mention of 1.4.

The issue of `README.md` in `master` pointing to the 1.3 tarball is due to `README.md` in `stable/1.4` still pointing to the 1.3 tarball.
