### ISSUE TITLE
submenu items "variable set but not used" errors in 1.4

### ISSUE THREAD

**Issue by mattdm** [BestImageViewer/geeqie#566]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
Geeqie 1.4

### SUMMARY
Geeqie 1.4 turns on `-Werror` by default. Fedora has `-Wall` by default in our build system, so this ends up being more strict that probably intended. In particular, I'm seeing a lot of `-Wunused-but-set-variable` warnings/errors. One of these is in `color-man.c` — I'm going to file a separate issue for that one. The rest all related to commit commit ae34634113b2cb77e530f576bd1b85b3d02e7a4d on 2017-08-18 — there are a bunch of `submenu` variables and one `item` variable set but not used. I'm not sure what the consequences are here (presumably the constructed submenu doesn't show?), but clearly something is not right.

### STEPS TO REPRODUCE
Build with `-Wunused-but-set-variable` on the end of CFLAGs... observe errors.

**Comment by mowgli** [comment]
We don't have Wall on for a reason. If Fedora does that, it needs to fix that at the moment.

However, patches are welcome. There is many dead code and variables. But that does not reduce the compiling result. Although, I like them to be fixed one day.

**Comment by mattdm** [comment]
For what it's worth, this (and issue #567) are the only places where this warning occurs. This one seemed of particular note because it relates to a recent patch.

**Comment by caclark** [comment]
Fixed in commit 09fd5e6fc at geeqie.org
