### ISSUE TITLE
unused return value in color-man.c

### ISSUE THREAD

**Issue by mattdm** [BestImageViewer/geeqie#567]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
Geeqie 1.4

### SUMMARY
In the function `color_man_get_profile_name()`, we have:
```
#ifdef HAVE_LCMS2
                                cmsUInt32Number r;
                                char buffer[20];
                                buffer[0] = '\0';
                                r = cmsGetProfileInfoASCII(profile, cmsInfoDescription, "en", "US", buffer, 20);
                                buffer[19] = '\0'; /* Just to be sure */
                                return g_strdup(buffer);
```

And the `r` variable is never actually used. From the LittleCMS [documentation](https://github.com/mm2/Little-CMS/blob/master/doc/LittleCMS2.9%20API.pdf), `cmsGetProfileInfoASCII()` returns "_Number of required bytes to hold the result. 0 on error_". Presumably since buffer size is passed into the function, LittleCMS does the checking and This is Fine, but it still seems a little scary. Should probably at least assert that the return value is not greater than 20 (and isn't 0).

### STEPS TO REPRODUCE
Enable `-Wunused-but-set-variable`

**Comment by caclark** [comment]
Fixed in commit 571f5871 at geeqie.org
