### ISSUE TITLE
Released geeqie-1.4.tar.xz does not contain ChangeLog

### ISSUE THREAD

**Issue by mattdm** [BestImageViewer/geeqie#568]
It looks like the ChangeLog file has been ditched in favor of generating from the git changelog. Nothing wrong with that, but the generated ChangeLog didn't make its way into the source tarball release, and since there's no git history in the source tarball, `gen_changelog.sh` doesn't work. In the future, could this be generated for the source release? Thanks!

**Comment by voyageur** [comment]
Indeed I had the same problem when working on the Gentoo version bump. For now I filtered out ChangeLog and ChangeLog.html from the installation targets

**Comment by mowgli** [comment]
True, I missed that. Will be fixed in 1.4.1 but it makes no sense to create a release just for that.

**Comment by mattdm** [comment]
Thanks. And yes, I agree that there's no need for a release just for this.

**Comment by avindra** [comment]
Please exclude the screenshots from the tarball as well.
