### ISSUE TITLE
reducing window size stops at a certain width

### ISSUE THREAD

**Issue by haheute** [BestImageViewer/geeqie#575]
### ISSUE TYPE
Feature Request

### GEEQIE VERSION

```
Geeqie 1.4
```

### OS / DISTRIBUTION
Arch Linux with XFCE

### SUMMARY
Something happened to horizontal window scaling.  I can't resize the window smaller than a certain amount.

### STEPS TO REPRODUCE
I assume it is a feature and not a bug (?), but when I try to drag the whole geeqie window small, it just stops at approximately 970px width. Vertical is no problem, but this "min-width" is a bit annoying. 

I used to do this quite often to reduce the image size and compare it to an image (thumbnail) in another window. Now I have to detach the file-list-area to be able to drag the window small...  Just want to inform and give feedback.

**Comment by caclark** [comment]
I suspect this is yet another GTK2/GTK3 problem.
Are you taking a package from a repository or compiling from sources?
If you are compiling from sources could you try:
`./autogen.sh --disable-gtk3`

**Comment by caclark** [comment]
For information only: looks like this is caused by the status bar - GTK2 allows the components to be compressed to zero when changing the width of the main window, but GTK3 does not.

**Comment by caclark** [comment]
> I used to do this quite often to reduce the image size and compare it to an image (thumbnail) in another window. Now I have to detach the file-list-area to be able to drag the window small

If you have "fit image to window" set you can re-size the window vertically, or by using the left-side divider of the image pane. This isn't the way you wish to work, but it is some kind of solution.

As this is a result of the development kit, unfortunately this becomes a "Can't fix" problem.
