### ISSUE TITLE
give user warning/error when it is impossible to update EXIF orientation

### ISSUE THREAD

**Issue by jose1711** [BestImageViewer/geeqie#577]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
```
Geeqie 1.4
```

### OS / DISTRIBUTION
Should not be distribution-specific but anyway: Arch Linux 64bit

### SUMMARY
Issues while updating EXIF orientation flag using ```Orientation - Write orientation to file``` are only reported to console, user is hence uninformed that a problem has occurred.

### STEPS TO REPRODUCE
Taky any image file, change ownership to root user, run Geeqie is a regular user, change orientation using ```[```, then ```Write orientation to file``` to have the EXIF tag updated. Get no warning/error message even though the operation was unsuccessful.

**Comment by caclark** [comment]
For information only: this isn't a problem updating an exif tag, it occurs when the image file itself is updated using exiftran or mogrify. The problem is in the bash shell script `geeqie-rotate`.

**Comment by jose1711** [comment]
yes, i can see that. from the script it looks like exiftran is never supposed to fail:
```
   exiftran -i "$1" "$3"
   return 0
```

**Comment by caclark** [comment]
Fixed in commit c6a41bb at geeqie.org
