### ISSUE TITLE
GitHub mirror is out of sync

### ISSUE THREAD

**Issue by zivanfi** [BestImageViewer/geeqie#580]
The sync mechanism between the main repo and GitHub seems to be broken (supposing there is one). The Git repository here is lagging behind the main repo (git://www.geeqie.org/geeqie.git) by 20 days and 10 commits.

**Comment by tomaszg7** [comment]
It was discussed here: https://github.com/BestImageViewer/geeqie/issues/471. As I understand, it is by design. I think it would be good to state in this repos description that it is only a backup not always up-to-date repo.

**Comment by mowgli** [comment]
Its by intent. Github repo is just for convenience. The authoritative repository is on geeqie.org. There is no automatic sync between them.
