### ISSUE TITLE
A file of about 19MB displayed abnormally at a ratio of 1: 1 and many others showed normal

### ISSUE THREAD

**Issue by progsourcemy** [BestImageViewer/geeqie#586]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
commit 2fac47dd838c8361744472ab16875c8e6f107771
Many versions before is not normal, I have not seen the normal version, for this picture.

```

```

```

### SUMMARY

The following file of about 19MB displayed abnormally at a ratio of 1: 1 and many others showed normal
https://upload.wikimedia.org/wikipedia/commons/8/86/Alongtheriver_QingMing.jpg

### STEPS TO REPRODUCE

For my config,open the file above,press  k   in the keyboard,the picture is not normal,press   +   in the keyboard,the picture is  normal.

**Comment by caclark** [comment]
Geeqie issue #12 gives some information about a bug in gdk-pixbuf with images > 32768 pixels.
The image you quote is 38414 pixels wide.
The bug notice is now at:

> https://bugzilla.gnome.org/show_bug.cgi?id=163090

(First reported by John Ellis in 2005!)
It looks like this bug will never get fixed.

**Comment by progsourcemy** [comment]
Thank you.
