### ISSUE TITLE
Shift + Direction is not accelerated in image viewer like help file suggests

### ISSUE THREAD

**Issue by kuwanger** [BestImageViewer/geeqie#599]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
Geeqie 1.1

GTK+ version 2.24.23

### OS / DISTRIBUTION

Ubuntu 14.04

### SUMMARY
Shift + Left/Right/Up/Down scrolling in fullscreen is not accelerated as the help suggests.  This is because layout_util.c's call to layout_image_scroll doesn't include a multiplier if GDK_SHIFT_MASK unlike every other instance of an image_scroll.

### STEPS TO REPRODUCE
As above, Shift+Direction scrolling is at 1 pixel, not 3 pixels.  The fix is simple.  At line 178 in layout_util.c add:

    if (event->state & GDK_SHIFT_MASK)
      {
      x *= 3;
      y *= 3;
      }

**Comment by caclark** [comment]
Fixed in commit f62fd076 at geeqie.org
