### ISSUE TITLE
Window "Edit command results" with GTK3 has disproportionate spacing (OK with GTK2)

### ISSUE THREAD

**Issue by marcelpaulo** [BestImageViewer/geeqie#600]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
```
Geeqie 7f5ac747
```

```
GTK3
```

### OS / DISTRIBUTION
Linux, Xubuntu 17.10

### SUMMARY
The dialog window `Edit command results` with GTK3 has disproportionate spacing (it doesn't with GTK2). The spacing between the title and the textbox is disproportionate, ugly.

### STEPS TO REPRODUCE
1. With geeqie GTK3, run any plugin which whose desktop file has `X-Geeqie-Verbose=true`. I ran one called `booklet`.
1. Shrink the `Edit command results` window vertically to its smallest height:
![image](https://user-images.githubusercontent.com/10074769/38170495-67287240-355d-11e8-9112-8dca8cbb83d5.png)
1. Gradually increase its height. The textbox height and the spacing between it and the title is kept equal as the height of the window is increased, and the final result is disproportionate, ugly. Here's the same window stretched to its maximum height:
![image](https://user-images.githubusercontent.com/10074769/38170523-2d887bce-355e-11e8-902e-dfff9e448d3a.png)
1. With geeqie GTK2, repeat the previous steps. Here's the same window stretched to its maximum height:
![image](https://user-images.githubusercontent.com/10074769/38170539-acf02614-355e-11e8-80ee-59d5a24f8d6a.png)
    You can see that the spacing between title and textbox is not the same as the textbox height, so the final result seems proportional, pleasing.

**Comment by caclark** [comment]
Fixed in commit 57d6435c at geeqie.org

**Comment by caclark** [comment]
The commit is in the main geeqie repository which is at geeqie.org. All changes go there first, and are sometime later mirrored to the repo at github.
If you make a:
`git clone git://www.geeqie.org/geeqie.git` 
you will get the latest commits.

An overview of the main repo is on web page:
`http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git`

**Comment by marcelpaulo** [comment]
Oh, please forgive me, @caclark, for my misunderstanding, I really didn't know about geeqie's main repository. I'll stick to it henceforth. Thanks a lot !

**Comment by marcelpaulo** [comment]
Have just built from the main repo, and now the window in GTK3 is even better than in GTK2 ! Once again, thank you very much for the fix and your patience with my misunderstanding !
