### ISSUE TITLE
Show over-/underexposed

### ISSUE THREAD

**Issue by putzwasser** [BestImageViewer/geeqie#601]
### ISSUE TYPE
* Feature Request

### SUMMARY
It would be nice to have a switch to show over-/underexposed areas in an image. Something like darktable has: https://www.darktable.org/2016/10/raw-overexposed/. It would be of great help to sort out photos that are over-/underexposed.

**Comment by caclark** [comment]
Attached is a .diff that might address this problem. 
I have no idea if this is what is wanted, so I will not put it into the repo until someone has commented on it.
It is enabled/disabled by Shift-G (it is substituted for the grey-scale function).
[601_1.diff.gz](https://github.com/BestImageViewer/geeqie/files/3364979/601_1.diff.gz)

**Comment by caclark** [comment]
Implemented in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=7c39c03f7df504dc5803b222c4d85e619341ec60

**Comment by tomaszg7** [comment]
Would be nice if (following example of aforementioned `darktable`) it would be possible to toggle this using a button in a lower right corner (like e.g. color managment).

**Comment by caclark** [comment]
I wondered if that would start to make the status bar too cluttered.
The same function can be achieved by putting the relevant icon on the toolbar.

**Comment by tomaszg7** [comment]
Maybe you're right - I was thinking that things that directly affect the image should be readily visible. Other thing would be e.g. greyscale mode.

**Comment by caclark** [comment]
> it would be possible to toggle this using a button in a lower right corner (like e.g. color managment).

The latest commit at geeqie.org makes the toolbar section of the status bar user-definable.
