### ISSUE TITLE
Cannot delete a non-empty directory: File deletion failed

### ISSUE THREAD

**Issue by marcelpaulo** [BestImageViewer/geeqie#606]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
+paulo:~/tmp$ geeqie --version
Geeqie 7ce4193d
```

## CONFIGURE
```
     Config results:
    -=-=-=-=-=-=-=-=-

Package:
  Name:          geeqie
  Version:       7ce4193d

Architecture:
  UNIX:          yes
  Win32:         no (native: no)

Flags:
  Geeqie:
  DEFS:          -DHAVE_CONFIG_H
  CPPFLAGS:
  CFLAGS:         -Werror -Wno-error=deprecated-declarations -Wno-error=sign-compare -Wno-error=return-type
  CXXFLAGS:      -g -O2
  Gtk:           -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
  Glib:          -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
  Thread:        -lgthread-2.0 -pthread -lglib-2.0
  Others:        -ljpeg  -llcms2 -lexiv2 -lclutter-1.0 -lcogl-path -latk-1.0 -lcogl-pango -lcogl -lgmodule-2.0 -pthread -lwayland-egl -lgbm -ldrm -lEGL -lXrandr -ljson-glib-1.0 -lgio-2.0 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgobject-2.0 -lglib-2.0 -lwayland-cursor -lwayland-client -lxkbcommon -lwayland-server -lX11 -lXext -lXdamage -lXfixes -lXcomposite -lXi -lclutter-gtk-1.0 -lclutter-1.0 -lcogl-path -lcogl-pango -lcogl -lgmodule-2.0 -pthread -lwayland-egl -lgbm -ldrm -lEGL -lXrandr -ljson-glib-1.0 -lwayland-cursor -lwayland-client -lxkbcommon -lwayland-server -lX11 -lXext -lXdamage -lXfixes -lXcomposite -lXi -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lchamplain-0.12 -lclutter-1.0 -lcogl-path -latk-1.0 -lcogl-pango -lcogl -lgmodule-2.0 -pthread -lwayland-egl -lgbm -ldrm -lEGL -lXrandr -ljson-glib-1.0 -lgio-2.0 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgobject-2.0 -lglib-2.0 -lwayland-cursor -lwayland-client -lxkbcommon -lwayland-server -lX11 -lXext -lXdamage -lXfixes -lXcomposite -lXi -lchamplain-gtk-0.12 -lclutter-gtk-1.0 -lchamplain-0.12 -lclutter-1.0 -lcogl-path -lcogl-pango -lcogl -lgmodule-2.0 -pthread -lwayland-egl -lgbm -ldrm -lEGL -lXrandr -ljson-glib-1.0 -lwayland-cursor -lwayland-client -lxkbcommon -lwayland-server -lX11 -lXext -lXdamage -lXfixes -lXcomposite -lXi -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -llua5.1

Localization:
  NLS support:   yes
  LINGUAS:        ar be bg ca cs da de el eo es et eu fi fr hu id it ja ko nb nl pl pt_BR ro ru sk sl sr@latin sr sv th tlh tr uk vi zh_CN zh_TW

Settings:
  Developer:     no
  Debug flags:   no
  Debug log:     yes
  Deprecated:    no

Support:
  LCMS:          yes
  Exiv2:         yes
  Lirc:          no
  Clutter:       yes
  Libchamplain:         yes
  Libchamplain-gtk:     yes
  Lua:           yes
  FFmpegthumbnailer:    yes

Documentation:
  Doxygen:
  doc-tool:
```

### OS / DISTRIBUTION
Linux (Xubuntu 18.04)

### SUMMARY
geeqie fails to delete non-empty directories:
![image](https://user-images.githubusercontent.com/10074769/39865762-5528cf00-5424-11e8-9b96-f76e81baa29a.png)

It deletes empty directories.

I created directory _~/tmp/foo_ with a single empty file _~/tmp/foo/afile_, ran `geeqie --debug=4`, captured the output and pasted it [here](https://paste.ee/p/xZ9HP).

### STEPS TO REPRODUCE
1. Create a directory: `mkdir foo`
1. Create an empty file inside the directory: `touch foo/afile`
1. Fire geeqie, try to delete `foo`:
![image](https://user-images.githubusercontent.com/10074769/39866079-74888b32-5425-11e8-98c4-c68e485dc4f0.png)

**Comment by marcelpaulo** [comment]
I have a very vague recollection that file management operations could be implemented via user-created scripts, I searched the user manual but found nothing. I have a distinct impression of having read about this in the user manual, perhaps it was an older geeqie version ?

**Comment by marcelpaulo** [comment]
> Geeqie provides the option for a set of overrides for certain operations.
> They are described in Help/Additional Preferences/Plugins Configuration/Special Plugins

Yes, these are the ones ! I looked at this page but thought it referred only to the other, non-special, plugins, so didn't read it all the way down.

I had tried to create a non-special plugin that simply ran `rm -rv`, but experimenting I learned that it can only act on files. I'll experiment with `geeqie-folder-command.desktop` or `geeqie-delete-command.desktop`, and post the results back here.

> Searching the help files isn't too good. I used the google search site:geeqie.org/help file delete command

Thanks for the tip ! 

> If you have a folder with jpegs, I think you will be able to delete the folder.

You're right, I've just tested it !

**Comment by p-himik** [comment]
The issue is more pronounced when you enable thumbnail caching in the current image directory. It creates a hidden directory `.thumbnails`, and basically completely locks you from removing the directory from `geeqie`. Since it's not possible to override the delete command in this case, I think this issue should be reopened.

**Comment by caclark** [comment]
I find that if I use the desktop file
`geeqie-delete-command.desktop`  
I can delete one level of sub-folder downwards - presumably because Geeqie does not see the .thumbnail folder and so runs the external command.

**Comment by p-himik** [comment]
@caclark I must admit I haven't checked it prior to writing - I've just read the comment that it doesn't work with directories and assumed the same when there's only `.thumbnails`. But as you said - it does work. Thanks!
Although I'm still not sure what would be the purpose of different deletion mechanisms for dirs with non-hidden subdirs and for dirs without them. But at least I don't see this issue in my workflow.
