### ISSUE TITLE
Thumbnails not color-managed

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#608]
`v1.2-476-g`7ce4193d
Save the images from http://www.color.org/version4html.xalter
The images display correctly in the main area, but the thumbnails seem not to be color-managed at all (both ICC v2 and v4 image thumbs are incorrect).

**Comment by tomaszg7** [comment]
I noticed that some time ago (when struggling with a bug in Gimp). Thinking about it, there are two ways to go: either embed the color profile in thumbnails or convert them to sRGB.

XDG standards is not very precise https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-latest.html:

> The image format for thumbnails is the PNG format, regardless in which format the original file was saved. To be more specific it must be a 8bit, non-interlaced PNG image with full alpha transparency (means 255 possible alpha values). However, every program should use the best possible quality when creating the thumbnail. The exact meaning of this is left to the specific program but it should consider applying antialiasing.
>
> If the original file contains metadata affecting the interpretation of the image, it should be respected as much as possible. In particular, metadata specifying the orientation of the original image data should always be respected. The image data should be transformed as specified by the metadata before generating the thumbnail. JPEG files commonly have Exif orientation tags. TIFF files may also have Exif orientation tags, although this is less common. It is less critical, but still desirable, to respect other image metadata, such as white balance information.

Profile can be considered a "metadata affecting the interpretation of the image" and that means that image data should be "transformed as specified by the metadata before generating the thumbnail". That would imply saving thumbnails in sRGB. 

However I'm not sure if it is reasonable to do so. Thumbnails generation would take significantly longer. Maybe it could be an option.

**Comment by cytrinox** [comment]
I've a lot of images with Linear Rec2020 profile embedded, the thumbnails are very dark.
I would suggest transforming the thumbnail to sRGB instead of embedding a profile. Geeqie can share thumbnails with other applications so it has a benefit when all files are just sRGB.
