### ISSUE TITLE
File->Symlink doesn't have underscore to call from keyboard

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#61]
File-&gt;Symlink command doesn't have an underscore letter to call from keyboard (after ALT-F) in 1.0beta1."y" seems to be not taken in that menu.

Reported by: szpak

**Comment by caclark** [comment]
Open Edit/Configure Plugins, and find the entry for symlink.desktop.
Include an entry for:
X-Geeqie-Hotkey=<keyname>
