### ISSUE TITLE
Wrap and/or truncate long file names in file list view

### ISSUE THREAD

**Issue by zsau** [BestImageViewer/geeqie#614]
When the file list view is narrow, especially when thumbnails are shown, there's not much space for long file names. Right now the pane shows a horizontal scroll bar in that case, which is not great for usability.

Alternatives would be to wrap and/or truncate the file name-- just spitballing here, but if the number of available lines of text can be determined from the cell height, then the file name could be wrapped onto any "extra" lines. Alternatively, the user could simply specify how many lines to use for the file name via a preference.

But whether or not wrap is implemented, the name could still be too long to fit: in that case it should be truncated/ellipsized (ideally with a mouseover tooltip to show the full name).

**Comment by caclark** [comment]
Commit ecdcba776 at geeqie.org addresses this.
The tooltip is set to the column 1 data - which means that in list-with-thumbnails the size and date is displayed as well as the filename.
I don't see much hope for a more complex solution.

**Comment by zsau** [comment]
Thanks! I'd still urge at least disabling the horizontal scroll bars in favor of truncation, as horizontal scrolling is poor UX (see https://webstandards.hhs.gov/guidelines/79 and https://www.nngroup.com/articles/scrolling-and-scrollbars/).
