### ISSUE TITLE
Find Duplicates use multicore multithread all cores threads

### ISSUE THREAD

**Issue by SimonDedman** [BestImageViewer/geeqie#615]
### ISSUE TYPE

* Feature Request

### GEEQIE VERSION

```
Geeqie 5a6cd202
```

```

```

### SUMMARY
Does the Find Duplicates feature use all cores/threads of multicore multithread processors? It doesn't *look* lie it does but it's hard to tell. Would be great if this could be coded in somehow.

**Comment by caclark** [comment]
I think only the image loader code runs in another thread. Everything else is in the main thread.

**Comment by caclark** [comment]
The first stage is to read all the files involved. Having multiple threads fighting for the same disk may not improve the speed proportionally. SSDs would help  I guess.

Klaus has already mentioned somewhere that the comparison is the least of the speed problems in this area.

If you have thumbnail caching enabled, the checksum and similarity data is also cached. That will help.

[There are --remote options to clean the thumbnail cache and render thumbnails. This was in response to someone who wanted to run them from a cron job.
Maybe the same could be done to create checksums and sim data.]

**Comment by SimonDedman** [comment]
Thanks Colin, sorry for the slow reply.

You make good points about the file reading, and interesting to note about
the thumbnail caching. I occasionally delete that cache but maybe it's
worth keeping it!

So are you thinking that the --remote option could be called as part of the
duplicate finder to create checksums & sim data *per thread*?

Cheers, as always!

**Comment by caclark** [comment]
Keeping an up-to-date thumbnail cache makes a significant time saving when opening folders containing a large number of files.

The --remote option means that cache maintenance (cleaning orphaned thumbnails and creating new ones for files that have been downloaded but not yet opened in Geeqie) can be done from the command line. That means you can set a cron job to run every hour or every day to make sure the cache is complete.

If you make searches based on file similarity, having the .sim data cached will also make a significant time saving. At the moment there is no command to create a .sim file cache (no equivalent of "Render thumbnails for a folder"). Such a command would enable .sim cache generation to be run also from a cron job at regular intervals.
At the moment the only way to create the .sim cache is to make a search using the similarity option.

The third subject is exif data. The read from the image file is slow. Exif data *is* cached in Geeqie, but only in memory. It would be worthwhile considering caching exif data along with thumbnails and .sim files.

I think that simplifying the caching of all three items world  be easier to implement than multi-threading, and would have an appreciable effect on usability. Then try to get multi-threading working.

My own vague attempt at speeding things up is to keep the cache on an SSD, and the images on old-fashioned hard-drives. But I've probably got the wrong way round. If money were not a problem...

**Comment by caclark** [comment]
For the image similarity checks, perhaps the similarity function could be changed to use a perceptual hash.
Comparing hash values would be simpler and therefore faster.
Also if the comparison function could be done on a GPU, the massive parallelism of modern GPUs would make a substantial difference.
[Note that I have no knowledge of perceptual hash generation, and even less about GPU programming.]

**Comment by SimonDedman** [comment]
Well it all sounds very impressive regardless of whether nobody knows how to do it!

**Comment by deutrino** [comment]
The reason I ended up on this issue is because, when running 'find duplicates recursive' on a large tree full of photos with thumbnail caching turned off, the "reading similarity data" step is slow, but my CPU seems barely utilized. The step before reading similarity data seems to max out a single CPU core, whereas reading similarity data seems to spread about 1.5 cores worth of work across all 8 cores. This is on an i7-8650U laptop, 5.4.x kernel, with an SSD. It just makes me curious what the bottleneck is.

**Comment by caclark** [comment]
@deutrino 
Creating the file list is limited by the speed of access to the single disk.

When you do not have thumbnails enabled you have also disabled caching of the similarity data.  The similarity data therefore has to be generated for each image during the similarity checks.
Geeqie is single thread with the exception of the image loader. So one thread will be loading an image, and the second thread 
is doing the computing and comparing of the similarity data.

Which cores are used is determined by the operating system, not by Geeqie.

Things will not  improve until I get around to implementing the changes I mentioned above.

**Comment by SimonDedman** [comment]
Wow, fair play Klaus, looks like a lot of work, congrats!

**Comment by mowgli** [comment]
Am Sa den 17. Apr 2021 um 17:36 schrieb Simon Dedman:
> Wow, fair play Klaus, looks like a lot of work, congrats! 

Credits go full to Colin, as he closed it in bc7652a. It was only copied
to github by a automatic sync that I implemented so it runs under my
account.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by SimonDedman** [comment]
Ah ok. Well thanks both - got the latest version running now. Cheers!
