### ISSUE TITLE
Man page disagrees with --remote-help

### ISSUE THREAD

**Issue by junkyardsparkle** [BestImageViewer/geeqie#619]
geeqie 1.4

I was struggling with the remote commands for opening a file in a new window, attempting to use `-r --view:<FILE>` as given in the man page, and finally viewed the output of `--remote-help` just because the error message kept telling me to... turns out that the command is actually `-r view:<FILE>` (no hyphens)... weird, but ok. Same is true for `--file:` and `--File:` commands. I'm not sure why these are different, or whether it should be changed in the source or the man page, but either way, they should agree...

Also had to discover by trial-and-error that the view command wants an absolute file path, which is reasonable given that the concept of CWD is tricky for remote commands, but perhaps this should be spelled out in the docs?

**Comment by junkyardsparkle** [comment]
Actually, RE: that second part, it seems that geeqie interprets the file arguments as being relative to whatever the CWD was on startup, regardless of what directories it may be browsing currently... so a relative path will work in the remote commands if the CWD is the same (or if there is no already running instance of geeqie). It would probably make more sense for the instance being launched with the remote command to qualify the full path of the file argument itself before handing it off... unless that's a bad idea for reasons I'm too stupid to see? :)

**Comment by caclark** [comment]
The "raise" option also has no prefix. The options "view" and "file" date back to the days of GqView.
The problem with changing them is that there may be a user who has put the current style into a script.

It should be possible to use getcwd() to get where Geeqie --remote was called from, and form an absolute path to any file parameters. That would be sensible.

**Comment by junkyardsparkle** [comment]
Yes, breaking the old syntax would be a bad idea, but maybe there wouldn't be any harm in *allowing* those options to be prefixed, for consistency's sake?

**Comment by caclark** [comment]
Partial fix in latest commit at geeqie.org:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=c71b207544af63a94e4d43f53820d7e357605b64

**Comment by caclark** [comment]
Latest commit at geeqie.org allows remote commands --file: and --view: to display files relative to the folder the remote command is executed from:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=a4a37be7894dde500b5a9098c39dc45ee30237be
