### ISSUE TITLE
Skip the "Move files?" dialog

### ISSUE THREAD

**Issue by feuerbach** [BestImageViewer/geeqie#622]
### ISSUE TYPE

* Feature Request

### GEEQIE VERSION

```
Geeqie 1.4
```

### OS / DISTRIBUTION

Fedora 28

### SUMMARY

After an update, I noticed an extra confirmation dialog when moving files:

![screenshot_20180710_235222](https://user-images.githubusercontent.com/24844/42542127-47cfb63a-849d-11e8-96ed-84d73df05623.png)

Sorting files into directories requires many of these move operations, and this extra dialog window is just an additional time waste/distraction, since I know I won't need it.

Would you please allow disabling it similarly to how the deletion confirmation dialog could be disabled?

Thanks!

### STEPS TO REPRODUCE

Choose "Move..." from the file menu and select the target directory. An extra dialog shows up.

**Comment by caclark** [comment]
The first dialogue you see should be to choose the destination folder. That has three buttons - Cancel, With rename and Move.
The default button for that dialogue can be switched between Move and With rename using an option on Preferences/Behaviour.
Does changing the default action solve the problem, or is it something else?

**Comment by feuerbach** [comment]
Thanks for the quick response Colin.

In the version I'm using (`geeqie-1.4-4.fc28.x86_64`), there are only "Cancel" and "Move" buttons, and there doesn't appear to be a setting for that:

![screenshot_20180711_110410](https://user-images.githubusercontent.com/24844/42565030-38ffb364-84fa-11e8-96af-17f30976db72.png)

I'll try to get a more recent version then — could you let me know what version you are using?

**Comment by caclark** [comment]
The dialogue was changed in response to a comment similar to yours.
Unfortunately it will be necessary for you to compile from sources - geeqie.org has the latest commits:
`git clone git://www.geeqie.org/geeqie.git`

This script might help if you have a problem with dependencies:
`https://www.freelists.org/post/geeqie/Install-dependencies-script'

**Comment by feuerbach** [comment]
git master works as you described — thanks!
