### ISSUE TITLE
Filter files by shell or regular expression pattern

### ISSUE THREAD

**Issue by marcelpaulo** [BestImageViewer/geeqie#624]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
```
Geeqie eb896440
```

```
     Config results:
    -=-=-=-=-=-=-=-=-

Package:
  Name:          geeqie
  Version:       eb896440

Architecture:
  UNIX:          yes
  Win32:         no (native: no)

Flags:
  Geeqie:
  DEFS:          -DHAVE_CONFIG_H
  CPPFLAGS:
  CFLAGS:         -Werror -Wno-error=deprecated-declarations -Wno-error=sign-compare -Wno-error=return-type
  CXXFLAGS:      -g -O2
  Gtk:           -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
  Glib:          -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
  Thread:        -lgthread-2.0 -pthread -lglib-2.0
  Others:        -ljpeg -ltiff -llcms2 -lexiv2 -lclutter-1.0 -lcogl-path -latk-1.0 -lcogl-pango -lcogl -lgmodule-2.0 -pthread -lwayland-egl -lgbm -ldrm -lEGL -lXrandr -ljson-glib-1.0 -lgio-2.0 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgobject-2.0 -lglib-2.0 -lwayland-cursor -lwayland-client -lxkbcommon -lwayland-server -lX11 -lXext -lXdamage -lXfixes -lXcomposite -lXi -lclutter-gtk-1.0 -lclutter-1.0 -lcogl-path -lcogl-pango -lcogl -lgmodule-2.0 -pthread -lwayland-egl -lgbm -ldrm -lEGL -lXrandr -ljson-glib-1.0 -lwayland-cursor -lwayland-client -lxkbcommon -lwayland-server -lX11 -lXext -lXdamage -lXfixes -lXcomposite -lXi -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lchamplain-0.12 -lclutter-1.0 -lcogl-path -latk-1.0 -lcogl-pango -lcogl -lgmodule-2.0 -pthread -lwayland-egl -lgbm -ldrm -lEGL -lXrandr -ljson-glib-1.0 -lgio-2.0 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgobject-2.0 -lglib-2.0 -lwayland-cursor -lwayland-client -lxkbcommon -lwayland-server -lX11 -lXext -lXdamage -lXfixes -lXcomposite -lXi -lchamplain-gtk-0.12 -lclutter-gtk-1.0 -lchamplain-0.12 -lclutter-1.0 -lcogl-path -lcogl-pango -lcogl -lgmodule-2.0 -pthread -lwayland-egl -lgbm -ldrm -lEGL -lXrandr -ljson-glib-1.0 -lwayland-cursor -lwayland-client -lxkbcommon -lwayland-server -lX11 -lXext -lXdamage -lXfixes -lXcomposite -lXi -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -llua5.1

Localization:
  NLS support:   yes
  LINGUAS:        ar be bg ca cs da de el en_GB eo es et eu fi fr hu id it ja ko nb nl pl pt_BR ro ru sk sl sr@latin sr sv th tlh tr uk vi zh_CN zh_TW

Settings:
  Developer:     no
  Debug flags:   no
  Debug log:     yes
  Deprecated:    no

Support:
  LCMS:          yes
  Exiv2:         yes
  Lirc:          no
  Clutter:       yes
  Libchamplain:         yes
  Libchamplain-gtk:     yes
  Lua:           yes
  FFmpegthumbnailer:    yes
  Pdf:           yes

Documentation:
  Doxygen:
  doc-tool:

```

### OS / DISTRIBUTION
Linux / Xubuntu 18.04

### SUMMARY
Is it possible to filter files by shell pattern or regex ? I've looked everywhere but the only filtering mechanisms I've found are:

- file extensions
- marks

When editing images, I usually add suffixes to each edited version. If I want to look only at the original images or a particular version of all images, I would need to filter them with a filename pattern. Of course, I can do that using marks, but it's cumbersome because I'd need to mark the photos one by one.

It would be even more useful if it were possible to associate patterns to mark numbers, I think that would be ideal.

**Comment by caclark** [comment]
> https://www.freelists.org/post/geeqie/Missing-features-cropping-images-and-filtering-filenames

The above item seems to be asking for the same feature. But I still have no real idea about how to implement this in the main window (but also did not give it any thought).

The regex is another matter - the Search page does not support regex in either Filename or Comment search. Maybe I'll start with that and then think how to integrate it into the main window.

**Comment by marcelpaulo** [comment]
> The above item seems to be asking for the same feature

Precisely. I also agree with something else R. Diez wrote: thanks a lot for geeqie ! Hands down, it's the most flexible and comprehensive, and at the same time intuitive image viewer in the Linux ecosystem. I suspect I use a small fraction of its features, but whenever I need something extra, I dig a little and discover that it was already there, waiting for me.

> the Search page does not support regex in either Filename or Comment search

I mentioned regexes but I'd risk a guess that most of the time people go for shell globbing patterns, or more specifically, **\***. But then again, it's always useful to have regexes up the sleeve.

**Comment by marcelpaulo** [comment]
Incidentally, what is the preferred way to report geeqie issues/feature requests: here or on the mailing list ?

**Comment by caclark** [comment]
> Incidentally, what is the preferred way to report geeqie issues/feature requests: here or on the mailing list ?

Github is good for tracking bugs and feature requests, so if there is a specific item it should go to github.
General comments and less precise queries would be better on the mailing list.

Commit 15637 at geeqie.org implements regex for some items on the search page. Using Glib's PCRE was probably the easiest way, and for basic searches the user will see no difference - I hope.

**Comment by marcelpaulo** [comment]
I've just built from master @geeqie.org, and regex search is working fine! Shame on me, I had never used the search page before, it will be incorporated in my workflow now.

Thanks, @caclark !

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=eb348ad698d5ee1d55218442548aae986552d296

**Comment by marcelpaulo** [comment]
This is really really great, thank you so much, @caclark ! I've just built geeqie from geeqie.org master. It's working really great. You implemented it in a really unobstrusive way.

I have only 1 doubt: I typed 3 different regexes, and I imagine that the down arrow to the right of the text entry box would show the previously typed regexes:
![image](https://user-images.githubusercontent.com/10074769/44169521-0d6e8a00-a0ab-11e8-9a5f-f556f22302e1.png)

but if I click on it, nothing happens.

**Comment by caclark** [comment]
Ah, sorry - it's a bug. If you type a newline after the text, that text is stored for future use in the drop-down box.
But... you only see it after you restart Geeqie.
I will fix that tomorrow.

Also the way the text is initially selected isn't too wonderful, but I am not sure how to fix that.

**Comment by marcelpaulo** [comment]
> you only see it after you restart Geeqie

Indeed, I've just confirmed it.

> Also the way the text is initially selected isn't too wonderful

The really important thing is: you type a PCRE and it filters files that match. The rest is candy.

Once again, thanks a lot for this feature ! I've missed it ever since I started using geeqie, but kept working around it and never bothered to open a feature request.

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=521629986e62a0aa4b413f5cf255eb72c0db7ebf

The number of entries in the combo box is limited to 10 (for no particular reason).
To delete an entry, select it from the drop-down, click on the text box to select the text, press delete, press enter.

There is an element of confusion if more than one Geeqie window is open. The combo box contents in each window can be different, but only one of them is stored in the history file. Just another problem...

**Comment by junkyardsparkle** [comment]
AFAIK there's still a similar history issue when running bash in multiple xterms, for example. Only the last closed is ultimately saved. I wonder if it would make sense to append to history only after a reload-on-close or something? In any case, this is a nice additional feature, thanks.

**Comment by marcelpaulo** [comment]
> Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=521629986e62a0aa4b413f5cf255eb72c0db7ebf

This is really cool, ticking along nicely. Entry deletion working flawlessly too.

> There is an element of confusion if more than one Geeqie window is open

Everyone should be running `geeqie -r`, hence sticking to a single Geeqie window. That's how I do it. So no problem here.

Thanks a lot, @caclark, for this really useful and well implemented feature!

**Comment by caclark** [comment]
>  I wonder if it would make sense to append to history only after a reload-on-close or something?

I took the easy way and just implemented a simple text-only combo that is part of each ViewFile object (the object that displays the files pane) - so each Geeqie window has a different ViewFile object and different combo data.

(Incidentally, there was a commit made a while ago to ensure there is only ever one instance of Geeqie running at any one time. If you call Geeqie a second time, all that happens is that a new window is opened in the current instance).

The proper solution is for the combos to access a single data source, so they all display the same data. That's possible, but it's unlikely that I'll get around to it - well, unless I find myself watching a really bad film :-(.
