### ISSUE TITLE
Animated GIFS lead to high CPU load

### ISSUE THREAD

**Issue by bato2501** [BestImageViewer/geeqie#626]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

Name            : geeqie
Version         : 1.4-2
Description     : A lightweight image browser and viewer
Architecture    : x86_64
URL             : http://www.geeqie.org/
Licenses        : GPL2
Groups          : None
Provides        : None
Depends On      : exiv2  gtk2  lcms  ffmpegthumbnailer
Optional Deps   : librsvg: SVG rendering [installed]
                  fbida: for jpeg rotation
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 5.05 MiB
Packager        : Antonio Rojas <arojas@archlinux.org>
Build Date      : 2018-04-01T12:12:46 CEST
Install Date    : 2018-07-29T16:35:58 CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

### OS / DISTRIBUTION

Arch Linux

### SUMMARY

Viewing animated gifs leads to high cpu load.

### STEPS TO REPRODUCE

Browse through some animated gifs. The issue is more pronounced when in full-screen and when gifs are big (>10mb).

**Comment by caclark** [comment]
Fix in commit at geeqie.org.
File is read asynchronously, so no longer blocks while the file is read.
Cpu load is still high, but this is unavoidable.
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=409c912d2fe31adde4f70e8ee1dcbf0104ffc483
