### ISSUE TITLE
Keywords are not adding properly to selected files

### ISSUE THREAD

**Issue by ghost** [BestImageViewer/geeqie#629]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.4
```

```
Gtk+ 2.24.32
```

### SUMMARY
Setting keywords works fine for one image, but when several images are selected, there is a problem: the new keyword(s) are added to all selected images, but for the last one they are not added, but replace existing ones.

### STEPS TO REPRODUCE

1. Copy 3 images to a folder. 
2. Set keywords for each image separately, e.g. `kw1` for the first one, `kw2` for the second and `kw3` for the third. 
3. Now select both the second and the third images.
4. Erase `kw3` in the Keywords list and type `new_kw`.
5. Click on the list with right mouse button and choose “Add keywords to selected files”.
6. See, that the image 2 has its old keyword `kw2` and `new_kw`, while the image 3 only has `new_kw`, its `kw3` has disappeared.

Indeed, we removed `kw3` for it to not be added to the image 2. Because if the list of Keywords is not cleared, all the keywords of the last selected image in the group would get added to all selected images.

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am Di den 14. Aug 2018 um 22:20 schrieb deterenkelt:
> ### SUMMARY
> Setting keywords works fine for one image, but when several images are selected, there is a problem: the new keyword(s) are added to all selected images, but for the last one they are not added, but replace existing ones.
[...]
> Indeed, we removed `kw3` for it to not be added to the image 2. Because if the list of Keywords is not cleared, all the keywords of the last selected image in the group would get added to all selected images.

My first Thoughts was "work as intended" but then I saw the problem.

First of it, you can use the right click in the right part to add one
keyword explicitly.

However, for your problem, I do not really see a way to fix that with
the current dialog. The box is the one for the selected image and no
meta box. So if you change something there, you change the keywords of
the current image. The action in side menu is just an extra action.

One way would be to have all keywords of all images in some Heisenberg
state. But currently I have no idea how to implement that.

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAltz3rIACgkQpnwKsYAZ
9qwhzAv+NlH3SrnFQQP+XZA0ILBDlttvTdueshr4ErpGI6nYCB/dLGClROyZF+1N
Q29c+Wvion783/WFhNTZOVwfeZoFofdfiNW7kow6Qz3mv3GTg7tpkztLV4otL2Et
kI0m0LtbDBWV3ouVJ/ZnZ/E+Q2uiRTvvLFC1B5lrRS6F4IUis3R2w64P73b2NcP5
edA50sKy7zWwiop2iPAeJ+8Bl9nhBcp85Kp6utgGQ1wDDq+clQtEWu6JApQdNCZK
DqdvGybb5EL0jTGOvt5k8vPUA/lbFrtfO/+PFKPK+w1wfpMnZEK87kY1xv3YGOrh
czcCekSr5TjxYpNSYH0buelwLD7XCB5Ee1/+ZFUIU2UJ4PXO0U81cWW8lQbvyN1e
BUdaZ03PnYjC4oK7eWB2t6kLpa+4IKzGDbwY+tsOq2PAk16Sgyla9PrWblOsT4HZ
Ni80xMqa2LYwL4jk6cyoEyYJnwEfHmNmWjPQQGQ/14AK4/DQFEJ2oGsf3Derdcxj
uDn64t62
=Afjo
-----END PGP SIGNATURE-----

**Comment by caclark** [comment]
The info panel is always showing the data for an image. Even if "select none" is set, the data for an image is shown. So there is no way to to put the info panel in a state disconnected from any image.

Maybe the menu command should be "Add selected keywords to selected files".

**Comment by deterenkelt** [comment]
> First of it, you can use the right click in the right part to add one keyword explicitly.

I’m sorry, what do you mean? I’ve tried to select one keyword (`new_kw`) and `kw3` tags along.
