### ISSUE TITLE
Compilation script for all distributions

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#631]
Hey

I noticed that you have a `geeqie-install-debian.sh` script. I wanted to point out that I wrote and maintain a script to compile Geeqie independently on any distro:
https://discuss.pixls.us/t/compiling-geeqie-in-linux/6200?u=morgan_hardwood
https://github.com/pixlsus/Scripts/blob/master/build-geeqie

I maintain scripts for compiling various programs, they all use a common structure to make maintenance easier. To prevent maintenance problems concerning installing dependencies across various distributions (different package managers, different versions available, sometimes a package's name changes, etc.), all of my scripts leave installing the dependencies to the user. These should be clearly documented by each project. See for example RawTherapee: http://rawpedia.rawtherapee.com/Linux#Dependencies

You're welcome to add it to your repo. I can send PRs when things change.

**Comment by caclark** [comment]
Link to script included in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=e335e4d84c69e5b8d5f0d369a200a083e9ee59f7

List of dependencies still incomplete.
