### ISSUE TITLE
geeqie core dumps (for me) on symlink copy

### ISSUE THREAD

**Issue by pittendrigh** [BestImageViewer/geeqie#640]
geeqie 1.4 on Mint Linux Tara.

If I copy a  -type f image from here to there everything is fine.

But if I try to copy a symlink from here to there geeqie core dumps. Every time.

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=7562336c2d025dfc85e3795034594711379bc0ed

The fault is caused by the additions of #544.
