### ISSUE TITLE
Zoom by mousewheel

### ISSUE THREAD

**Issue by pauledd** [BestImageViewer/geeqie#643]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
```
Geeqie 1.4
```

```
gtk3
```

### SUMMARY
It would be nice if one can zoom in/out an image just with the mousewheel at the point where
the pointer is currently located

**Comment by caclark** [comment]
Are you referring to a magnifier glass/tool type of feature?

**Comment by caclark** [comment]
There is a mouse-only zoom function in Geeqie. In Edit/Preferences/Behaviour make sure that "Navigation by left or middle click" is not checked.
Mouse middle-click will then toggle the mouse wheel function between "zoom" and "next image".
When zooming, once the image fills the window the point under the cursor will remain in view as you continue to zoom in.
The zoom increment is on Edit/Preferences/Image.

**Comment by pauledd** [comment]
damn, I totaly missed that option, thanks! Even if this middle-click-enable-zoom is a bit annoying I can live with that :)
