### ISSUE TITLE
Hide Bars cannot be toggled after Geeqie restart

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#645]
88791d22

1. Run Geeqie.
2. Click the backtick ` keyboard shortcut to trigger View > Hide Bars. The sidebars disappear.
3. Click the backtick again, the sidebars appear. All good so far.
4. Click the backtick again, the sidebars disappear.
5. Restart Geeqie. Geeqie starts without sidebars, still good since that's the way we left off.
6. Click the backtick, the sidebars do not appear. Problem.

**Comment by caclark** [comment]
Temporary work-around: right-click and un-check "Hide file list"

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=74e04b2e8d63f558ae678dce744bf83740f03bff

**Comment by Beep6581** [comment]
Fix confirmed.
