### ISSUE TITLE
fullscreen does not work over multiple monitors

### ISSUE THREAD

**Issue by jiribohac** [BestImageViewer/geeqie#650]
### ISSUE TYPE
* Bug Report
### GEEQIE VERSION
geeqie 1.3 and geeqie_1.4+git20181019
### OS / DISTRIBUTION
Debian stable
Problem in both the distribution version of geeqie and self-backported package from sid.
### SUMMARY
The system has two monitors forming a single wide screen spanning both monitors, set up with xrandr.
In Debian Jessie, geeqie was able to do fullscreen spanning both monitors.
Now, only one monitor is used for Fullscreen. We use geeqie for polarized stereo projection and cannot use it after updating to Debian Stretch and beyond.
My window manager is icewm, but I get the same results with kwin, metacity or openbox.
However, when I don't run any window manager, the fullscreen works correctly over both monitors.

### STEPS TO REPRODUCE
1) Set up two monitors with something like
xrandr --output VGA-1 --auto
xrandr --output HDMI-1 --auto --right-of VGA-1

2) go to Preferences->Windows->Fullscreen and in Location select either "Active screen" or "Screen 0:0, full size"

3) press "f" for full screen.

Image should be displayed on both monitors, but it is not.

I believe this is caused by commit a16635ca1d8fe42349f9e22bd311d3118eff2608 ("Fix fullscreen - remove all the garbage which breaks things and let Gtk do its job.")
I have spent some time looking for ways to fix this. I think gtk_window_fullscreen() will not use multiple monitors without some extra work. gdk-window-set-fullscreen-mode() has been introduced in GDK 3.8 which seems to do just what is needed. 

I see three possibilities
1) backport gdk-window-set-fullscreen-mode() into src/compat.c to get that functionality without introducing a dependency on GDK 3.8+
2) use low level X11 magic directly, as implemented by gdk_x11_window_apply_fullscreen_mode(). googling "_NET_WM_FULLSCREEN_MONITORS" shows many projects using this
3) bring back some of the code removed by @jkufner  in a16635ca1d8fe42349f9e22bd311d3118eff2608.

Indeed using just gtk_window_fullscreen() without any further hacks gives better result for single-monitor fullscreen.
However, when one of the "Screen *, full size" options is chosen, i.e. "options->fullscreen.screen % 100 == 0", we could use the old
code, making use of gdk_window_set_override_redirect() and gtk_window_set_keep_above() instead of gtk_window_fullscreen()

I can try to fix this, but being very new, I would like to get some advice which option seems most acceptable.

Thanks for any hints!

**Comment by jkufner** [comment]
I think that if statement like this would be the best solution:

    if (/* we want fullscreen on all monitors*/) {
        gdk_window_set_fullscreen_mode(fs->window, GDK_FULLSCREEN_ON_ALL_MONITORS);
    }

I don't know which part of the removed code provided such function, so I would not recommend to return it. Any hacks cause problems and dealing with X11 causes headaches...

See https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#GdkFullscreenMode and https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#gdk-window-set-fullscreen-mode

ps: Please don't break the current behavior as it is what most people expect. The stereoscopic projection is way less common than a laptop connected to a TV to show some photos from holidays.

**Comment by caclark** [comment]
Implemented in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=1d8d758e8adc56e1ff9bf0defccaa47bcb08c3b4

**Comment by jkufner** [comment]
What the following condition means?

    if ((options->fullscreen.screen % 100) == 0)

**Comment by jiribohac** [comment]
@jkufner it means it's the full screen, not just one single monitor. See the comment above fullscreen_prefs_get_geometry()

**Comment by jkufner** [comment]
Ok, that makes sense now. (However, a comment for the future generations would be nice.)

**Comment by jiribohac** [comment]
FWIW, selecting a specific single monitor does not work in icewm - with or without this patch. I'm always getting the image on the first monitor. I'm still debugging it. So far i think the bug is in icewm and not geeqie...

Someone might have been using the broken "full size" option, as a workaround to get the image on a monitor they otherwise cannot get it on. Hopefully I can fix the icewm issue soon.

Anyway, a16635c seems to have been a little too hurried, as the GTK implementation is rather unreliable on different window managers. And e.g. openbox does not support _NET_WM_FULLSCREEN_MONITORS yet, so my fix does not do anything there, the "full size" option remains broken.
