### ISSUE TITLE
geeqie fails to build against new exiv2 0.27

### ISSUE THREAD

**Issue by david-geiger** [BestImageViewer/geeqie#654]
Hi,

On Mageia Cauldron geeqie 1.4 fails to build against new exiv2 0.27, see the attached build log:

[geeqie_build_log.txt](https://github.com/BestImageViewer/geeqie/files/2718653/geeqie_build_log.txt)

Regards,
David

**Comment by caclark** [comment]
Implemented in latest commit at geqeqie.org:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=f9213c8ad796cf4571b2606435c32753040ec645
