### ISSUE TITLE
make install fails on POTFILES.in (random-image plugin)

### ISSUE THREAD

**Issue by gusnan** [BestImageViewer/geeqie#656]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
1.4 + git commit c71b207544af63a94e4d43f53820d7e357605b64
(Latest git from geeqie.org, plus/minus a commit or two)
```
```
GTK2
```

### OS / DISTRIBUTION
Debian unstable

### SUMMARY
make install fails on POTFILES.in - the random-image plugin has the wrong folder / filename (it uses '_' when it should be '-') 

This simple patch should fix it:
(I cannot provide it as a pull request (yet) since the commits that this affects hasn't come to github yet, but is only available on geeqie.org)

```
From: =?utf-8?q?Andreas_R=C3=B6nnquist?= <gusnan@debian.org>
Date: Sun, 6 Jan 2019 14:31:11 +0100
Subject: Fix random-image plugin filename and folder in POTFILES.in

---
 po/POTFILES.in | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/po/POTFILES.in b/po/POTFILES.in
index 87caba2..4b0f4e3 100644
--- a/po/POTFILES.in
+++ b/po/POTFILES.in
@@ -5,7 +5,7 @@ plugins/export-jpeg/export-jpeg.desktop.in
 plugins/tethered-photography/tethered-photography.desktop.in
 plugins/camera-import/camera-import.desktop.in
 plugins/image-crop/image-crop.desktop.in
-plugins/random_image/random_image.desktop.in
+plugins/random-image/random-image.desktop.in
 plugins/rotate/rotate.desktop.in
 plugins/symlink/symlink.desktop.in
 plugins/template.desktop.in
```

My build error:

make[2]: Leaving directory '/build/geeqie-1.4+git20190106/src'
Making check in po
make[2]: Entering directory '/build/geeqie-1.4+git20190106/po'
make[2]: *** No rule to make target '../plugins/random_image/random_image.desktop.in', needed by 'geeqie.pot'.  Stop.
make[2]: Leaving directory '/build/geeqie-1.4+git20190106/po'
make[1]: *** [Makefile:674: check-recursive] Error 1
make[1]: Leaving directory '/build/geeqie-1.4+git20190106'
dh_auto_test: make -j1 check VERBOSE=1 returned exit code 2
make: *** [debian/rules:4: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
I: copying local configuration
E: Failed autobuilding of package

**Comment by caclark** [comment]
Fixed in commit latest  commit - thanks:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=ebcff68bd49c9f0f40c6c72f5eb4148318f950d0
