### ISSUE TITLE
String comparison to translated string causes crash

### ISSUE THREAD

**Issue by gusnan** [BestImageViewer/geeqie#661]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
Latest Git version of Geeqie, GTK 2

### OS / DISTRIBUTION
Debian Testing / unstable

### SUMMARY
Running Geeqie in non-English (or to be specific, in languages where
"Filter" is translated to something other than "Filter") crashes geeqie
when trying to add a new filter in the Files tab of the Preferences dialog.

See the check in src/preferences.c line 1065, where the code compares a
column title to "Filter", without taking translations into consideration,
which means the comparison will fail on any language where "Filter" is
translated to something other than "Filter".

I couldn't reproduce the problem in the Debian bug report, but that is because
I run in Swedish, and the word "Filter" is the same in English as in Swedish.

See the Debian bug report at
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923018

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=0004617a71100553a13e49e7208e401f2493b72c
