### ISSUE TITLE
Use grammatically correct month names in pan view

### ISSUE THREAD

**Issue by tomaszg7** [BestImageViewer/geeqie#663]
Pan view in calendar and timeline modes prints out month name using %B with `strftime()`. However in some languages it produces genitive case, not nominative which looks grammatically wrong. Since glibc-2.27 there is a way around it (I'm really shocked that it was not introduced earlier): https://sourceware.org/ml/libc-announce/2018/msg00000.html

Here's the patch to utilize it: https://github.com/tomaszg7/geeqie/commit/92377fb4e6f42fc58ab75c2c5c53d3f37578d761I'm not creating a PR since this repo is outdated with respect to main repo and PR would contain a lot of other stuff.

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=73472a2b3952f63272ad21dd41aaab6509631199
