### ISSUE TITLE
Sprite File from RISC OS   

### ISSUE THREAD

**Issue by AspireONE** [BestImageViewer/geeqie#666]
* Feature Request

Hello,

any chance for geeqie to support Sprite File from Risc OS? 

http://fileformats.archiveteam.org/wiki/Acorn_Sprite
https://www.4corn.co.uk/articles/websites/www95/acorn/library/ref/sprite.html
http://www.netsurf-browser.org/projects/librosprite/

**Comment by caclark** [comment]
From my point of view, I do not think it likely that this will be implemented.
Unless there is a great demand, it would not seem to be worth the time to implement it.
Of course, someone else might be willing to do this.
