### ISSUE TITLE
Ability to restore last safely deleted images

### ISSUE THREAD

**Issue by matrixik** [BestImageViewer/geeqie#667]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION

```
Geeqie 1.4
```
Installed with apt.

### SUMMARY
Ability to restore last safely deleted images.

### STEPS TO REPRODUCE

I have disabled config file delete, enabled delete key and enabled safe delete.
I would like to see option (best with some simple/standard keyboard shortcut like `Ctrl+z`) to restore last deleted image/images if they are still in `/home/<user>/.local/share/geeqie/trash` folder.

Now I need to go to this folder and move them back by hand, and fix they names because now they have additional numbered prefix and they are not grouped anymore when they have same name.

Thank you for working on Geeqie.

**Comment by caclark** [comment]
The latest version of Geeqie has the option to use the system trash facility, which provides a much better method of file recovery.
There is also a command-line option for that, which means that it may be possible to create a plug-in, linked to a keystroke, which un-deletes the last file.

If you wish to use the latest version and you are using Debian, I think it possible to download a more recent version from here:
http://archive.ubuntu.com/ubuntu/pool/universe/g/geeqie/

For Debian users there is also the script which will download, compile and install the latest version:
wget http://cclark.uk/geeqie-install-debian.sh

Sorry for the brief response. My internet connection is about to go off for a few days.

**Comment by matrixik** [comment]
I have Geeqie now compiled from source.

Could you tell me where I can find command-line option for recovery of last deleted file (both jpg and raw at the same time)?

**Comment by caclark** [comment]
The commands are in the trash-cli package.
The commands trash-list and trash-restore will help you.

**Comment by matrixik** [comment]
Thank you.
Looks like `trash-restore` works only in interactive mode so I can't simply run two times `trash-restore 0`. Will need to think how to make it work...

**Comment by caclark** [comment]
I think that the first two fields of trash-list are the date/time the file went into the trash can.
Sort on those fields and take the last one. Well, maybe that could work...
