### ISSUE TITLE
Viewer should display folders in one panel and their playable files (playlist) in the other I think

### ISSUE THREAD

**Issue by michael466722** [BestImageViewer/geeqie#668]

**Comment by alerque** [comment]
...it already does this. The file tree widget and the file or thumbnail list widget is already separate.

**Comment by michael466722** [comment]
I think it would be useful if viewer displays all viewable files in current folder.

**Comment by michael466722** [comment]
I mean with files in folders which are in current folder.

**Comment by alerque** [comment]
Speaking as an end user, I don't think that would be a better interface. It would make it hard to navigate, and confuse navigating to a location with browsing what's in that location (something I tend to be doing one or the other of but not both, and allocate screen space differently accordingly). Also it wouldn't leave an easy way to show thumbnails in place of the file listing. Having a folder nav tree in one place and a display of what is in that folder in another pane is a pretty usable paradigm.

**Comment by michael466722** [comment]
But first in file list may be what is directly in folder.
