### ISSUE TITLE
rating is not readable

### ISSUE THREAD

**Issue by lordcenzin** [BestImageViewer/geeqie#670]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION

```
Geeqie 1.4
```

### OS / DISTRIBUTION
Arch Linux

### SUMMARY
I am unable to read what is written into "Rating" in the info panel. The input text field is too short (in height) and characters are not readable. No way to resize the pane height

### STEPS TO REPRODUCE
Open Geequie, enable Info Sidebar (ctrl+K), rating is already among preset panes but the content is not readable.
The image does not have any rating.
[an example](https://imgur.com/Y9uSONQ.png)

**Comment by caclark** [comment]
There is a setting for this in Edit/Preferences/General, at the bottom of the tab.
You will need to save the change and restart Geeqie to see the effect.

**Comment by lordcenzin** [comment]
I swear I looked into all menus...:)
by the way the default is too small, isn't it? Which use justifies that size? Maybe I am using it wrong.

**Comment by caclark** [comment]
It looks ok on GTK2, so I guess there is some historical baggage involved.
My intention is to use gtk_panes for the panel so that the user can drag the dividers to the required size.
One day...
