### ISSUE TITLE
Changing width columns in Exif window 'locks' computer

### ISSUE THREAD

**Issue by kneops** [BestImageViewer/geeqie#671]
* Bug Report

### GEEQIE VERSION
1.4

### OS / DISTRIBUTION
Linux Mint 19 Cinnamon

### SUMMARY
Trying to change the width of the columns in the Exif windows makes makes everything else freeze. The icon (left and right arrow) remains visible and there is nothing that I can do except restart the computer.

I'm not familiar with how to test other branches or scripting, I just wanted to report this.

**Comment by caclark** [comment]
OK, I can replicate that problem - but I assume it will take a while to isolate it.

It is not necessary to restart your computer.
Switch to a terminal window e.g. press control-alt-F4
Login
Type the following command:
ps -e | grep geeqie
You will see a process number for geeqie. Then type:
kill process_id
where process_id is the id for geeqie
Then switch back to the gui by:
control-alt-F7

**Comment by alerque** [comment]
@caclark There are easier ways to do that ;-) Try `pkill geeqie` or `killall geeqie`.

**Comment by kneops** [comment]
Hi Colin.

Thanks for the tip about not needing to restart my computer :)

Jack<https://www.jacktummers.com>



Op 20-05-19 om 12:20 schreef Colin Clark:

**Comment by gusnan** [comment]
This pull request ^ should fix this - Please try it out.

**Comment by caclark** [comment]
Unfortunately it does not seem to make a difference.
I am running the checks on Linux Mint 19 Cinnamon 64-bit.
(A very brief look using the debugger shows it looping in poll.c in glibc)

**Comment by caclark** [comment]
This seems to be a problem with v1.4 and the latest libraries - rather than a problem with Mint, as I had first thought. Compiling the latest version of geeqie with the latest libraries does not give a problem.
So the options are:
1) compile the latest version of geeqie from sources (I can give you some help with that if you want to take that route)
2) avoid resizing those columns until a new geeqie distribution is made

**Comment by kneops** [comment]
Thanks Colin!

I think I will personally go for option 2 :) I don't need to view the 
Exif with every single picture and I can use other software until an 
update is available.

Jack




Op 21-05-19 om 14:19 schreef Colin Clark:
