### ISSUE TITLE
Simultaneous runs of geeqie interfere with each other

### ISSUE THREAD

**Issue by dkogan** [BestImageViewer/geeqie#676]
Hi. This issue isn't new, I'm just only now writing it up.

I'm using the bleeding edge Debian build. It's here, I think: https://github.com/BestImageViewer/geeqie/commit/431adf320f4ce0ba31fb7a07ea53aca03c21fcbd

I'm using Debian GNU/Linux on an amd64 box.

Recipe:

1. chdir to any directory with images
2. geeqie. The program pops up, and displays the first image
3. chdir to another directory with other images
4. geeqie

My expectation is that at this point another geeqie instance runs, creating a new window, displaying an image from the second directory. What happens instead is that the first instance (started in step 2) is found, and reused. This opens up a second window in the same process, and the new window shows the same image as in step 2. I.e. I don't get to see the image in the directory in step 3.

A variation is to run 'geeqie *' instead of 'geeqie'. This fails also. In this case, the original process is reused once again, and the new window once again shows the old image. BUT here the first geeqie window actually changes to display one of the new images. I.e. the second invocation of geeqie modifies what the first window is showing.

The mechanism that is making this break is the remote system. In my usage I never want the remote to do anything, so for me running a locally-patched geeqie without the remote solves the issue. Some sort of logic where the remote only applies to the first geeqie process, and subsequent ones run standalone probalby would make this work reasonably for 90% of the users.

Thanks!

**Comment by caclark** [comment]
Could you try aliasing "geeqie" to "geeqie ."? I think that gets you the mode of operation you are looking for.

**Comment by dkogan** [comment]
Hi. That doesn't quite work. Usually I don't want to look at ALL the
files in a directory, but at a subset: 'geeqie a.jpg b.jpg' and such.
And as described before, a second 'geeqie' invocation:

- opens a window that displays images that I didn't ask for (and doesn't
  display the images I DID ask for)

- changes the images displayed in the first window.

Both of these behaviors are never what the user wants. My feeling is
that unless the user issues a 'geeqie -r' the remote should do nothing.
That would produce the expected behavior.

Thanks.

**Comment by caclark** [comment]
The attached .diif is only a partial solution.  There are still problems with command line collections and view_file_icon.
[676-01.diff.gz](https://github.com/BestImageViewer/geeqie/files/3293101/676-01.diff.gz)

**Comment by klayman** [comment]
I would like the separate instances of geeqie to be independent too. In earlier versions ctrl+q closed only the active window of geeqie, but now any subsequent call to geeqie attaches to the first instance and issuing ctlr+q closes all the windows. It's very annoying. The saved window geometry is applied only to the first image and all other windows are positioned by the window manager - that's not the expected behavior for me as well.

**Comment by caclark** [comment]
> ctlr+q closes all the windows.

Control+W closes a single window. Control+Q closes all windows.

> The saved window geometry is applied only to the first image and all other windows are positioned by the window manager

Could you try the "Edit/Preferences/Windows/Use Saved Window Positions Also For New Windows" option and see if that gets the mode you want?

**Comment by klayman** [comment]
> Control+W closes a single window. Control+Q closes all windows.

Yes, I know. Alt + F4 closes a single window as well. But is there any way to run multiple independent instances of geeqie? If I opened, say, 3 different images, accidentally pressed ctrl+q instead of ctrl+w, and executed 'geeqie image.png' then I get 3 identical windows with the same image.png.

> Could you try the "Edit/Preferences/Windows/Use Saved Window Positions Also For New Windows" option and see if that gets the mode you want?

Thanks, that seems to be what I was looking for.

**Comment by caclark** [comment]
> then I get 3 identical windows with the same image.png

In "Edit/Configure This Window" there is an option to start with the last used path.
Does using this option improve things?

**Comment by klayman** [comment]
> In "Edit/Configure This Window" there is an option to start with the last used path.
> Does using this option improve things?

It seems to have no effect on this behavior.

**Comment by Lovewyrm** [comment]
If you open the geeqierc file directly then you can just delete all the lines that have the offending setting there.
See:
https://github.com/BestImageViewer/geeqie/issues/707

If you follow that up with a layout options change to "not close" geeqie "when this window is closed", then you can close any additional geeqie instance without killing the rest.
Closing the last one kills it, of course.

This has no effect on the directory behavior of the OP, though.

**Comment by dkogan** [comment]
Hi. I really see the current default behavior of geeqie-as-a-server as being very counterintuitive, and surprising to the user. In my usage at least, there're no circumstances where I want separate geeqie windows talking to each other in any way. Can we flip the default so that all "remote" functionality is disabled unless some commandline option is given? It sounds like we're trying to do what web browsers do (one application but multiple windows, C-q closes all windows, etc). But other than web browsers I can't think of anything else that works this way.

Thanks

**Comment by DrMcCoy** [comment]
> I really see the current default behavior of geeqie-as-a-server as being very counterintuitive

Same. Can I force geeqie to use a new instance?

I use separate X screens, and I now can't open geeqie twice to run on these two X screens. As soons as I open the second geeqie on the second screen, it quits and opens a window on the first screen. Since they're separate X screens, I can't move the window either.

At least GIMP, which also does weird stuff like that, lets you migrate windows to another X screen (which is...eeeh, but at least a workaround), but geeqie doesn't seem to have that. Neither does it seem to have a "--new-instance" option like Firefox does.

**Comment by caclark** [comment]
If you need an immediate fix and you are compiling from sources, take out the section at line 424 in main.c
Or after starting the first instance, delete $HOME/.config/geeqie/.command and run a second instance.

Note that the reason for the change was #162, and that some of the problems noted above are a result of bugs in the code not related to how many instances are running.

I guess "--new-instance" is the easiest way, but maybe still a problem with geeqierc/xml.

**Comment by waptaff** [comment]
Agree with @DrMcCoy, @dkogan and @klayman: not a fan of the behavior on multiple instances running simultaneously.  I expect `geeqie` to open the current working directory when started without options.  It's been, after all, the default behavior of the last 10 years (and 10+ more if counting `gqview`).  Muscle memory is strong on this one.

I don't mind if that Inter-Process Communication mode is available somehow (I guess _some_ people like it) but the default behavior has to be at least achievable somehow (in preferences, say).  For now, I'll patch it out, following @caclark's suggestion; here it is for people who are not sure what to do.

[no-remote-behavior.patch.txt](https://github.com/BestImageViewer/geeqie/files/4028899/no-remote-behavior.patch.txt)

**Comment by jan-spurny** [comment]
I have the same problem - my workflow leads to many separated viewer instances and geeqie makes it hard or impossible.

I encountered this (again) because I just did fresh debian10 install.
I hate to do that, but I always end up removing `geeqie` and manually building old `gqview`, because it does everything I need and doesn't do things that annoy me (like this "linked instances" behaviour).
It would be nice if I wouldn't have to do that.

**Comment by atomsymbol** [comment]
Maybe the following patch will help those building from source:

[no-single-instance.patch.txt](https://github.com/BestImageViewer/geeqie/files/4148372/no-single-instance.patch.txt)

If running Gentoo Linux, the patch can be put in /etc/portage/patches for seamless integration with the package build process.

**Comment by caclark** [comment]
There is a new commit at geeqie.org.
If you wish the original fucntionality alias "geeqie" to "geeqie -n" or "geeqie --new-instance".
Note that there is only one geeqierc.xml file.
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=92b4e3e7257ed48a1d3e5389bac8f7e326ef4829

**Comment by dkogan** [comment]
Hi. Thanks for working on this. I just pulled from git, and tried this again. I'm at 92b4e3e7257ed48a1d3e5389bac8f7e326ef4829 (from 2020/2/3; latest master as of 2002/3/30).

The default behavior is weird even if you DO want some sort of single-instance behavior. Let's say I have images in dir1/ and in dir2/.

I do this:

1. `cd dir1; geeqie`. New window pops up with images in dir1
2. In another terminal.  `cd dir2; geeqie`. New window pops up with images in dir1

If you want one session, do you want a second invocation of geeqie to open up a new window? If you DO want a new window, do you want this new window do something different depending on whether there's another geeqie running somewhere? The most common single-instance applications (web browsers) don't do this. If I run "firefox", it'll open a new window at the home screen whether I have a firefox instance running already or not. So I argue "geeqie" should show images in the current directory, whether it's the first in a session, or not.

Let's do this slightly differently. If the second invocation is `cd dir2; geeqie .` then I get the old behavior: the first window is unchanged, and I get a new window with images from dir2.

If the second invocation is `cd dir2; geeqie *` then I get a behavior that really feels like a bug: the first window changes to show images from dir2 (even though it was launched from dir1 and was showing those images). And the new window shows images from dir1 (even though the user asked for dir2). This is the most problematic of the 3 cases, and unfortunately it's also the most common use case: we hit this if trying to see individual images rather than all images in a directory.

Looks like the behaviors are consistent if the first invocation uses `geeqie` or `geeqie .` or `geeqie *`.

Thanks for working on geeqie.

**Comment by caclark** [comment]
> I'm at 92b4e3e (from 2020/2/3; latest master as of 2002/3/30).

It looks like you have cloned the repo. here at GitHub.
The repo. at  geeqie.org is where the commits are first made, and the repo. here is synced sometime later. If you clone from geeqie.org you will always get the latest state.

---
There is a commit at geeqie.org which might - or might not - fix some of these problems:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=19b59255f7682ab3acf0ce9bdb62de592f69617b

**Comment by dkogan** [comment]
Hi. I just tried the new commit, and it makes all these issues go away. Thank you so much! I'm closing the issue.

**Comment by j-b-grenouille** [comment]
FYI

I like to deside my selfe how a programm behave and I'm really annoyd by automated interactions from modern desktops, dbus, systemd and co.

-n (--new-instance) is currently not working

while i run my programms from console, I delete the geeqie socket direkt after start by using an function
the function is part of my bashrc



```
function geeqie () {
  /usr/bin/geeqie $@ &
  rm -f ~/.config/geeqie/.command
        }
```



so every geeqie started by a console command 

`geeqie [options] [path or image]`

is independent
