### ISSUE TITLE
The image overlay should show the full image path, not just the filename

### ISSUE THREAD

**Issue by dkogan** [BestImageViewer/geeqie#678]
Hi. Suppose you have 2 directories with images where the images have identical filenames (a common use case for me). And then you do this: 'geeqie path1/image.jpg path2/image.jpg'

If you pop up the image overlay (by hitting 'i') you'll get a little information box about the file you're looking at. This box contains the filename, but not the full path. So in this case the user is never sure which of the two files they're looking at. Showing the full path would resolve this. A really simple patch to do that:

```
diff --git a/src/image-overlay.c b/src/image-overlay.c
index e94d7529..1f59a553 100644
--- a/src/image-overlay.c
+++ b/src/image-overlay.c
@@ -244,7 +244,8 @@ static GdkPixbuf *image_osd_info_render(OverlayStateData *osd)
 
 	if (!fd) return NULL;
 
-	name = image_get_name(imd);
+	name = image_get_path(imd);
 	if (name)
 		{
 		gint n, t;
```

Maybe this is a bit heavy-handed, but SOMETHING along those lines would help usability a lot.

Thanks.

**Comment by caclark** [comment]
The Overlay Screen Display (OSD) is definable in Edit/Preferences/OSD.
The good news is that there is a "path" parameter option.
The bad news is that I have a vague recollection that this parameter did not get implemented.
If that is so, I think implementing it as an OSD parameter is the way to go..

**Comment by dkogan** [comment]
Aha. That's a very useful pointer, thanks! Here's a patch to implement
this. I just tested it, and it produces the desired behavior. Thanks!


```
diff --git a/src/image-overlay.c b/src/image-overlay.c
index e94d7529..6116b5a1 100644
--- a/src/image-overlay.c
+++ b/src/image-overlay.c
@@ -307,6 +307,7 @@ static GdkPixbuf *image_osd_info_render(OverlayStateData *osd)
 		osd_template_insert(vars, "number", g_strdup_printf("%d", n), OSDT_NO_DUP);
 		osd_template_insert(vars, "total", g_strdup_printf("%d", t), OSDT_NO_DUP);
 		osd_template_insert(vars, "name", (gchar *) name, OSDT_NONE);
+		osd_template_insert(vars, "path", (gchar *) image_get_path(imd), OSDT_NONE);
 		osd_template_insert(vars, "date", imd->image_fd ? ((gchar *) text_from_time(imd->image_fd->date)) : "", OSDT_NONE);
 		osd_template_insert(vars, "size", imd->image_fd ? (text_from_size_abrev(imd->image_fd->size)) : g_strdup(""), OSDT_FREE);
 		osd_template_insert(vars, "zoom", image_zoom_get_as_text(imd), OSDT_FREE);
```

**Comment by caclark** [comment]
Implemented in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=724b16b42a2b3ece94035906b48e193986c3ea84

**Comment by mowgli** [comment]
Hi,

Am Sa den  8. Jun 2019 um 20:30 schrieb Dima Kogan:
> Hi. Suppose you have 2 directories with images where the images have identical filenames (a common use case for me). And then you do this: 'geeqie path1/image.jpg path2/image.jpg'
> 
> If you pop up the image overlay (by hitting 'i') you'll get a little information box about the file you're looking at. This box contains the filename, but not the full path. So in this case the user is never sure which of the two files they're looking at. Showing the full path would resolve this. A really simple patch to do that:

That is a good application for using lua. You can use
`%lua/test.lua/%` where lua/test.lua is the file
~/.config/geeqie/lua/test.lua where you can display everything you want.
(Last path part, full path or, like me, some original file date:
```lua
exif = Image:get_exif();
mydate = Image:get_date();
mysource = "F";
exifdate1 = exif:get_datum("Exif.Photo.DateTimeOriginal");
if (exifdate1) then
   mydate = exifdate1;
   mysource = "EP";
end
return os.date(mysource .. ": %c", mydate);
```

Methods registered for the image are:
- get_path
- get_name
- get_extension
- get_date
- get_size
- get_exif
- get_marks

You can choose the file name as you want, I just have test.lua...

The part lua/ is important and not changeable. The full format is
`%lua/<file>/<inline>%` where file could be emtpy for inline lua or the
inline part is ignored when you specify a file.

Note, that inline stuff does not work with `:` inside.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
