### ISSUE TITLE
wrong GPS

### ISSUE THREAD

**Issue by jirazy** [BestImageViewer/geeqie#691]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

"Geeqie 5e259bb1"

GTK+ v3

### OS / DISTRIBUTION

opensuse 15.1

### SUMMARY

GPS-coorrdinates set wrong using drop image to map

### STEPS TO REPRODUCE

Compiled latest version of Geeqie 5e259bb1. This version sets GPS-coorrdinates wrong - using drop image to OSM:
jzl@jizhp440:~/Pictures/foto/NX2000-Jirka/20190722> exiftool -s -G 190722-123608-NX2000.jpg|fgrep -i gps
[XMP]           GPSLatitude                     : 238 deg 58' 16.00" N
[XMP]           GPSLongitude                    : 107 deg 12' 46.00" E
[Composite]     GPSLatitudeRef                  : North
[Composite]     GPSLongitudeRef                 : East
[Composite]     GPSPosition                     : 238 deg 58' 16.00" N, 107 deg 12' 46.00" E

When run from commandline I see messages:
Error: Directory Samsung2, entry 0x0035 Sub-IFD pointer 0 is out of bounds; ignoring it.
unable to parse GPS coordinate '50,53,691734,N'

unable to parse GPS coordinate '14,33,087680,E'

Warning: Failed to convert Xmp.exif.GPSLatitude to Exif.GPSInfo.GPSLatitude
Warning: Failed to convert Xmp.exif.GPSLongitude to Exif.GPSInfo.GPSLongitude
May be I forget something in compilation. But what?

With older version Geeqie 593356f8 I can set this properly. That version I compiled at 2018-08-26.
jzl@jizhp440:~/Pictures/foto/NX2000-Jirka/20190722> exiftool -s -G 190722-123608-NX2000.jpg|fgrep -i gps
[Composite]     GPSLatitude                     : 50 deg 53' 40.68" N
[Composite]     GPSLatitudeRef                  : North
[Composite]     GPSLongitude                    : 14 deg 33' 20.73" E
[Composite]     GPSLongitudeRef                 : East
[Composite]     GPSPosition                     : 50 deg 53' 40.68" N, 14 deg 33' 20.73" E

I can't attach config. Web complains "Something went really wrong, and we can’t process that file. Try again."

**Comment by caclark** [comment]
> I can't attach config. Web complains "Something went really wrong, and we can’t process that file. Try again."

Github only accepts certain file types.
Could you please try:
gzip <filenane>
then upload <filename>.gz

**Comment by jirazy** [comment]
[config.zip](https://github.com/BestImageViewer/geeqie/files/3423976/config.zip)
I catch it. Problem is in locale settings. The behavior is the same in both versions. Geeqie behaves OK when executed as
env -u LANGUAGE LANG=en_US.UTF-8 geeqie
My usual setting is LANG=cs_CZ.UTF-8 and in this environment geeqie cannot parse coordinates.

**Comment by caclark** [comment]
European locales use a comma as a decimal separator.
The XMP spec. specifies a dot as a decimal separator.

Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=f8c32ee3a703aa6ef48c5644ecff9658d9182c0e
