### ISSUE TITLE
Tag for 1.5 and NEWS for >=1.4 are missing

### ISSUE THREAD

**Issue by AMDmi3** [BestImageViewer/geeqie#692]
Having tags and actual changelog is crucial for packaging

**Comment by gusnan** [comment]
Check out the stable/1.5 branch. At least the NEWS file is updated there. I don't know about any 1.5 tag though. In Debian I have got the 1.5 tar.xz for packaging, which works just fine.

**Comment by mowgli** [comment]
Well, Tag v1.5 is there and the news file is also updated. Both are also uploaded on github which is not the main location for the repository.

**Comment by gusnan** [comment]
Sorry about missing the tag - I am simply not looking carefully enough. :) Thanks for all your work!

**Comment by AMDmi3** [comment]
Thanks for the tag. Missing NEWS items in master branch is still an issue.
