### ISSUE TITLE
Offer for help by @n3storm

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#694]
Hi, I have been a long time user of Geeqie and now I am back. I am glad is still maintained and faster than ever.

If you are interested in maintaining geeqie.org site, even revamping it to look modern I offer my self to host and maintain the site.

Drop me a message to hola@estudionexos.com in case I don't see github notification.

_Originally posted by @n3storm in https://github.com/BestImageViewer/geeqie/issues/471#issuecomment-293651755_

**Comment by mowgli** [comment]
Hi Klaus and all Geeqie devs:


This is WIP:

http://geeqie.estudionexos.com/

Icon is a mix of two Tango icons (file image icon modified by me) I
propose this icon for distribution. License is same as Tango icons.


TODO:

Image optimization: Background images are slow yet cause they are
retrieved from a third party site (no problem with copyrights)
Pexels.com https://www.pexels.com/photo-license/

History section background image makes difficult to read text in some
resolutions.

More screenshots/screencaptures.

My setup is in Spanish so some Geeqie literals appears in Spanish. If it
is too noticeable I made need to remake screencaptures.


QUESTIONS

What to do with online manual (host and rework with screenshots? remove
from site?)

Do we have to highlight something I've missed? Features order is correct?


REQUEST

If anybody would like to contribute with original
screenshots/screencaptures and background images please contact me.


Let me know what you think so far.

Cheers,

Néstor

_Original posted in #471_

**Comment by mowgli** [comment]
Closing in favor of #226

**Comment by caclark** [comment]
> What to do with online manual (host and rework with screenshots? remove
from site?)

There is no index for the Help file, and it would be a considerable effort to create one.
Without an index or a way of searching the Help file, its value is reduced.

However if the Help file is online, a search engine can be used to find the relevant paragraphs.
In my opinion, using a search engine is easier than using and index. For that reason there is an item on Geeqie's Help menu to do that.

I think it important that the Help file stays online at geeqie.org.
