### ISSUE TITLE
Option to reset zoom and fit image to window on image change

### ISSUE THREAD

**Issue by juef17** [BestImageViewer/geeqie#695]
### ISSUE TYPE
* Feature Request

### SUMMARY
Add an option to automatically reset zoom and fit image to window on image change

### STEPS TO REPRODUCE
When browsing through my photos, I like to zoom on some of them often. But then, when I change to the next image, the zoom is kept and I have to go and make the image fit to the window again. IrfanView on Windows has this by default.

I might as well use this feature request to mention how great Geeqie is. I just heard about it and it is everything I ever wanted for a Linux image viewer. Thank you!

**Comment by caclark** [comment]
On the status bar at the bottom of the Geeqie window is a pane that shows the current zoom setting.
If you click on that button several options are shown which take effect when you move to the next image.

**Comment by juef17** [comment]
There it is! :D  I looked everywhere in the preferences, but I had not seen that. Thank you for the reply, and again for the great piece of software <3

**Comment by caclark** [comment]
On the Help menu is an item for on-line help search. That defaults to using duckduckgo (although maybe google does a better job). You can change that option in Preferences/General.

The on-line help file may be a bit out of date, but sometimes it can give worthwhile results.
