### ISSUE TITLE
No histogram for Nikon D850 files.

### ISSUE THREAD

**Issue by paperdigits** [BestImageViewer/geeqie#697]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION

```
geeqie 1.5
```

Flatpak on KDE Neon

### SUMMARY

How does geeqie make it's histograms? I have a Nikon D850 and can't see the histogram. But I can see histograms for the Nikon D750 and Fuji X-T20.

**Comment by caclark** [comment]
I downloaded some D850 raw files from here:
https://froknowsphoto.com/nikond850raw/

The histogram shows ok. Could you please check if these files work on your installation?

**Comment by paperdigits** [comment]
I do not see the histogram from those sample files, so I guess it is something in my flatpak build. I've uploaded the flatpak manifest here: https://github.com/pixlsus/flatpak-geeqie 

If you have any idea what might be the problem, @caclark I'd be grateful for the assistance.

**Comment by caclark** [comment]
This may be related to the large file size of the images.
Try setting Preferences/General/Decoded Image Cache Size to something big - e.g 1GB
If that works then reduce the setting down to whatever works for you.

[I believe there may also be a problem with the way this setting is stored. If at first it does not work, try setting Preload Next Image and then Apply, Save, exit Preferences, exit Geeqie and then restart.
Just another problem - maybe.]

**Comment by paperdigits** [comment]
@caclark ah yes, I changed the cached size to 2 GB, and now i get the histogram! Thank you!
