### ISSUE TITLE
Menubar takes too much space

### ISSUE THREAD

**Issue by installgentoo** [BestImageViewer/geeqie#702]
![2019-08-01-221344_1366x768_scrot](https://user-images.githubusercontent.com/2088917/62320818-e4a4f780-b4a9-11e9-9c6e-7f0d78d6455e.png)
### ISSUE TYPE

* Feature Request

### GEEQIE VERSION

```
Geeqie 1.5
```

```
gtk2
```

### OS / DISTRIBUTION

gentoo

### SUMMARY

menubar in 1.4 does not go over the layout with images.
in 1.5 it does go over and a lot of space is wasted with a gray empty menubar. anyone knows which commit changed this? is this intentional?

### STEPS TO REPRODUCE

launch 1.5

**Comment by mowgli** [comment]
Well, that was bd11ce89f2e9…
It was a intentional change. Maybe that should be configurable.

**Comment by installgentoo** [comment]
thanks.

probably yes. i'll just patch it out for myself locally.

**Comment by Cantuccini-Lori** [comment]
As a suggeston: Maybe if we could put bookmarks in the menu bar, like in krusader, that would be nice.
But I am not sure, if this is possible.

**Comment by caclark** [comment]
> Maybe if we could put bookmarks in the menu bar, like in krusader,

This can be done with a plugin, but it is a rather tedious process to do more than once.
Create a plug-in containing a  `--remote --file:<somewhere>` command.
Make sure the plug-in has an icon.
You can then access it via the plugins menu, or you can insert it on the toolbar.

This is not as convenient as a built-in drag-and-drop solution.

**Comment by installgentoo** [comment]
>if we could put bookmarks

Why do you guys want to put trash into gui?

It's an image viewer, it just displays images. Why do you constantly want to reduce the size of the area allocated to these images?

I don't understand you.

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=5ae1d8323249e6e51af351a85b3ea27ad3b9d1bf

Additional option in Preferences/General
