### ISSUE TITLE
Toolbar status class filter

### ISSUE THREAD

**Issue by tomaszg7** [BestImageViewer/geeqie#705]
### ISSUE TYPE
* Feature Request

### SUMMARY

Just the idea - since status bar (and main toolbar) are now customizable it might be convenient to be able to put a class filter there similar to the one in pan view. Or alternatively, maybe existing filefilter could incorporate a way to filter by class. Or sort dialog?

**Comment by caclark** [comment]
The existing file-filter box would seem to be the sensible place.
Maybe an a push-button to open a drop-down of checkboxes.
That would not take much more space in that panel.

**Comment by caclark** [comment]
Hello Tomasz
Here is a suggestion for implementing a class filter along with the file filter.
If you have time, please let me know what you think.
[class_filter_1.diff.gz](https://github.com/BestImageViewer/geeqie/files/3481602/class_filter_1.diff.gz)

**Comment by tomaszg7** [comment]
Thanks. I'm now out for vacations. I'll try it when I get back.

**Comment by caclark** [comment]
Implemented in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=be7fbeeeb2171a254976156e1601e8e89a4e0ca3

**Comment by tomaszg7** [comment]
I only got around to checking it but it seems you have two bugs with "Select all". Here's a patch. 
```
--- a/src/view_file/view_file.c
+++ b/src/view_file/view_file.c
@@ -997,9 +997,9 @@ static gboolean vf_file_filter_class_set_all_cb(GtkWidget *widget, gpointer data
        gint i;
        gboolean state;
 
-       if (g_strcmp0("Select all", gtk_menu_item_get_label(GTK_MENU_ITEM(widget))) == 0)
+       if (g_strcmp0(_("Select all"), gtk_menu_item_get_label(GTK_MENU_ITEM(widget))) == 0)
                {
-               state == TRUE;
+               state = TRUE;
                }
        else
                {
```

I'm still not sure about the UI, how it is hidden, but I don't have a better idea without cluttering other parts of the screen. Generally I believe that UI becomes too complicated with many features hidden...

**Comment by caclark** [comment]
> I only got around to checking it but it seems you have two bugs with "Select all". Here's a patch.

Thanks for taking the time to look at this.

> I'm still not sure about the UI, how it is hidden, but I don't have a better idea without cluttering other

For this project the users are the Design Dept., the QA Dept., the Test Dept. and the Ergonomics Dept. Maybe someone will come up with a better layout...

Commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=c63a3a2bb60ae496f9bd9ea1247435c722b9e6b2

**Comment by tomaszg7** [comment]
I found another bug in the filter code: if you have two Geeqie windows open and change filter settings in one (e.g. disable images) then after you change directory in another window, the filter setting will leak through to that window as well (i.e. images will become hidden). Moreover you won't see it in filter pull down list - it will still show images as enabled. You would need to disable it and re-enable it to display it normally.
