### ISSUE TITLE
Feature request: BPG (Better Portable Graphics) support

### ISSUE THREAD

**Issue by telychko** [BestImageViewer/geeqie#706]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
```
$ geeqie --version
Geeqie 1.5
```

### OS / DISTRIBUTION
```
$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux

$ uname -a
Linux PhenomX4 5.2.6-arch1-1-ARCH #1 SMP PREEMPT Sun Aug 4 14:58:49 UTC 2019 x86_64 GNU/Linux
```

### SUMMARY
BPG (Better Portable Graphics) is a new open-source image format which was created by programmer Fabrice Bellard in 2014. Its purpose is to replace the JPEG image format when quality or file size is an issue. Its main advantages are:

* High compression ratio. Files are much smaller than JPEG for similar quality.
* Supported by most Web browsers with a small Javascript decoder (gzipped size: 56 KB).
* Based on a subset of the HEVC open video compression standard.
* Supports the same chroma formats as JPEG (grayscale, YCbCr 4:2:0, 4:2:2, 4:4:4) to reduce the losses during the conversion. An alpha channel is supported. The RGB, YCgCo and CMYK color spaces are also supported.
* Native support of 8 to 14 bits per channel for a higher dynamic range.
* Lossless compression is supported.
* Various metadata (such as EXIF, ICC profile, XMP) can be included.
* Animation support. 

[Home Page: https://bellard.org/bpg/](https://bellard.org/bpg/). There are source code/libraries for support BPG format.

**Comment by caclark** [comment]
The referenced code installs only the two command line utilities, but not the libbpg library.
It would be easier if the library was installed also.

**Comment by telychko** [comment]
> The referenced code installs only the two command line utilities, but not the libbpg library.
> It would be easier if the library was installed also.

Yes, it is. Library is compiled but not installed. I think because library is compiled as static library. Seems there is no way to compile shared library. Hope it is not a problem.

**Comment by caclark** [comment]
The code libbpg.c no longer compiles.
The first problem I see is that some defs that are missing.
The system avcodec.h (under /usr) is dated 02-05-2019.
The file avcodec.h in the source tar is dated 21-04-2018.
It seems that libbpg has not been kept up-to-date. Maybe there is no more interest in this format.

**Comment by caclark** [comment]
I think this should be marked as a "will not implement" feature.
