### ISSUE TITLE
Orientation menu needs offering for 90 degree rotation.

### ISSUE THREAD

**Issue by stephenboston** [BestImageViewer/geeqie#709]
* Feature Request

### GEEQIE VERSION

```
1.5.1
```

```

```

### SUMMARY
Orientation menu needs an option to rotate an image 90 degrees -- as needed to rotate an image from landscape to portrait or vice versa.

**Comment by caclark** [comment]
The orientation menus have options for clockwise and counter-clockwise rotation.
Although it is not shown explicitly, these are 90 deg. rotations.

**Comment by stephenboston** [comment]
That's not what I'm seeing. It is a 180 rotation. A bug then. I'm using the version from the Ubuntu 19.04 repository, on MATE. I'll resubmit as a bug of that would be better for you.

**Comment by caclark** [comment]
Which setting do you have for Edit/Preferences/Metadata/Write Altered Image Orientation To The Metadata ?

Would you try changing the setting for Exif Rotate on the status bar?

And could you please try each of the orientation commands:
rotate clockwise
rotate counter-clockwise
rotate 180
mirror
flip
original state

and let me know what effects you see for each of them?

**Comment by stephenboston** [comment]
This problem seems to be specific to only one of my machines because the other two running the same geeqie version on the same OS version behave just as you say. The only big differences between the the problem machine and the others is that it uses NVIDIA and  NVME but that seems too low level doesn't it? 

Anyway -- not your problem. Thanks for your response.
