### ISSUE TITLE
Apply the orientation to image content not working

### ISSUE THREAD

**Issue by Massimo-B** [BestImageViewer/geeqie#710]
The feature
"Apply the orientation to image content" is not working anymore on geeqie-1.5.1.

Rotating the picture works, but after calling the "Apply.." the rotation is reset. On the STDOUT I only see
```
processing /home/mo/picture.jpg
```
Build on Gentoo:
```
Installed versions:  1.5.1(13:11:58 28.08.2019)(exif ffmpegthumbnailer gpu-accel gtk3 jpeg lcms map nls pdf tiff -debug -doc -lirc -lua -xmp)
```

**Comment by caclark** [comment]
I do not think that anything has changed in this area.

Rotation requires: ImageMagick, exiftran, exiv2
Settings that may affect rotation:
1. Exif rotate button on the status bar
2. Edit/Preferences/Metadata/Write Altered Image Orientation To The Metadata
3. Edit/Preferences/Files - if the file type is writeable

When you run Geeqie from the command line you may get more diagnostic data by:
1. Edit/Configure Plugins/Apply The Orientation.... plugin. Set the plugin to be verbose - look for "# X-Geeqie-Verbose=true" at the bottom of the desktop file.
2. In the geeqie-rotate script, include "set -x"

**Comment by Massimo-B** [comment]
I don't see any failure here:
```

/home/mb/Pictures/0.NEW/RN5.Mo.sync/IMG_20190907_093614.jpg
+ GQ_METADATA_DIR=/home/mb/.local/share/geeqie/metadata
+ get_sidecars=
+ '[' x-g = x-g ']'
+ get_sidecars=yes
+ shift
+ rotate_image_file=
+ rotation=
+ '[' x/home/mb/Pictures/0.NEW/RN5.Mo.sync/IMG_20190907_093614.jpg = x-r ']'
+ preserve_mtime=
+ '[' x/home/mb/Pictures/0.NEW/RN5.Mo.sync/IMG_20190907_093614.jpg = x-t ']'
+ '[' -n '' ']'
+ for file in "$@"
+ '[' -n yes ']'
+ geeqie -r --get-sidecars:/home/mb/Pictures/0.NEW/RN5.Mo.sync/IMG_20190907_093614.jpg
+ read sidecar
+ '[' '!' -w /home/mb/Pictures/0.NEW/RN5.Mo.sync/IMG_20190907_093614.jpg ']'
+ rotate /home/mb/Pictures/0.NEW/RN5.Mo.sync/IMG_20190907_093614.jpg
++ echo jpg
++ tr '[:upper:]' '[:lower:]'
+ ext=jpg
+ '[' xjpg = x ']'
+ gq_metadata=/home/mb/.local/share/geeqie/metadata//home/mb/Pictures/0.NEW/RN5.Mo.sync/IMG_20190907_093614.jpg.gq.xmp
+ '[' -f /home/mb/.local/share/geeqie/metadata//home/mb/Pictures/0.NEW/RN5.Mo.sync/IMG_20190907_093614.jpg.gq.xmp ']'
++ sed -e 's|Xmp.tiff.Orientation *||'
++ exiv2 -PXkv /home/mb/.local/share/geeqie/metadata//home/mb/Pictures/0.NEW/RN5.Mo.sync/IMG_20190907_093614.jpg.gq.xmp
++ grep Xmp.tiff.Orientation
+ gq_orientation=8
+ '[' 0 '!=' 0 ']'
+ case "$ext" in
+ '[' -n '' ']'
+ exiftran -aip /home/mb/Pictures/0.NEW/RN5.Mo.sync/IMG_20190907_093614.jpg
processing /home/mb/Pictures/0.NEW/RN5.Mo.sync/IMG_20190907_093614.jpg
+ exiv2 -M 'set Xmp.tiff.Orientation 1' /home/mb/Pictures/0.NEW/RN5.Mo.sync/IMG_20190907_093614.jpg
+ '[' 0 '!=' 0 ']'
+ '[' -n 8 ']'
+ exiv2 -M 'set Xmp.tiff.Orientation 1' -M 'set Exif.Image.Orientation 1' /home/mb/.local/share/geeqie/metadata//home/mb/Pictures/0.NEW/RN5.Mo.sync/IMG_20190907_093614.jpg.gq.xmp
+ '[' 0 '!=' 0 ']'
+ return 0
+ ret=0
+ read sidecar
+ ret=0
+ '[' 0 '!=' 0 ']'
+ exit 0
```
The original picture has Exif data Orientation top, left.
Doing 'Rotate counterclockwise' or shortcut [ rotates the picture and changes the Exif data Orientation: left, bottom. At this moment, the file stats have not changed. (Where is the new Exif stored?)
Doing "Apply the orientation..." resets the Orientation: top, left. This time the file stats have changed, so the file has been written, but the picture looks like before the applied orientation.

**Comment by caclark** [comment]
The option "Apply the orientation to image content" rotates the image file on disk to the orientation as specified by its Exif Orientation tag.

Does the option "Write orientation to file" give you the result you are looking for?

**Comment by Massimo-B** [comment]
This option is disabled here.
However:
1. "Apply the orientation to image content" was working for me all the years before. Not sure if geeqie or some of the dependencies is broken now.
2. "Apply the orientation to image content" actually does what I want. It rotates the image loss-less according to the flags and write the rotated image back in order that other clients that don't know about rotation flags are showing the same.
3. Do I understand that correct, that "Write the orientation to file" just updates the EXIF flags? I thought rotating itself already does that.

**Comment by Massimo-B** [comment]
Curiously, calling ```/usr/lib/geeqie/geeqie-rotate -g```  outside of geeqie works as expected, and a refresh in geeqie shows the rotated data while also the preview is rotated as expected.

What could go wrong when calling the link from inside geeqie? Set to Verbose = true I only see
```
processing /home/mb/Pictures/NEW/IMG_20191115_202241.jpg
```
just like the normal STDOUT when calling manually.

**Comment by caclark** [comment]
Ref:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=fdb45ac5f99283775d655fa36b23b4be7905951e

There is a typo. error in the shell script. It fixes the problem with the test case I used. If it fixes your problem also, sorry it took so long to find it.
