### ISSUE TITLE
Deleting image should not scroll file list unnecessarily

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#711]
v1.2-696-gcbffa0a3

1. Image `2198` is about to be deleted. Note that the next image, `2200`, is already visible in the file list.
![screenshot_20190915_173235](https://user-images.githubusercontent.com/5844619/64923973-c556f500-d7df-11e9-9ef1-497e0f03257c.png)
2. Delete `2198`. Instead of just highlighting `2200`, the list is unnecessarily scrolled to place the "next" image at the top, making me lose my point of reference:
![screenshot_20190915_173301](https://user-images.githubusercontent.com/5844619/64923974-c8ea7c00-d7df-11e9-9b91-a4f611c55265.png)

Please make Geeqie not scroll the list if the "next" image is already visible.

**Comment by caclark** [comment]
This is the same problem as #467

**Comment by Beep6581** [comment]
Some time ago I patched RawTherapee to scroll only when the relevant thumb is partially or entirely not visible. I'm unfamiliar with Geeqie's code base and with C but maybe the idea helps:
https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/filebrowser.cc#L1763
