### ISSUE TITLE
ability to return to previous image if home/end was pressed occasionally

### ISSUE THREAD

**Issue by BigSerpent** [BestImageViewer/geeqie#712]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
```
Geeqie dea60db2
```

```
gtk 3.22.30
```

### OS / DISTRIBUTION
Linux Mint 19.2 Mate x64

### SUMMARY
I often press home/end occasionally. I'd like to have a shortkey to return to the previously active image.

### STEPS TO REPRODUCE
While browsing a directory with images with geeqie, press home/end.

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=417c2b44b60d99f423bfed1beb7571284bce4574

Additional entries on Go menu. Use Edit/Preferences/Keyboard to set a key binding if required.
