### ISSUE TITLE
/ for action search

### ISSUE THREAD

**Issue by aoloe** [BestImageViewer/geeqie#715]
Feature Request

### SUMMARY
/ should start an action search dialog where one can type letter to launch a command.

### STEPS TO REPRODUCE
- /
- Gnu
- Return
- Starts Gimp to edit the current selected images

You can see notes about the implementation in Gimp
https://wiki.gimp.org › index.php › Specs:Action_Search_Dialog

or from Scribus

https://bugs.scribus.net/view.php?id=15552
(based on the implementation by the Olive video editor) 

(implementation for Inkscape might be underway...)

(If you add this feature, please rename the "Gnu Image Manipulation Program" plugin in "Gimp Gnu Image Manipulation Program" (or simply Gimp) so that it's easy to start it : - )

**Comment by aoloe** [comment]
- the action should triggered by typing the / key (ctrl-/ is also an option)
- a small dialog with a text field  and an empty drop down list shows up
- as soon as the user types a letter the drop down is filled with the matching commands
- when pressing the return button, the action is triggered
- bonus points for implementing a "camel case" matching (typing "gimp" would select "Gnu Image Manipulation Program")

you can see an animated gif of it in the implementation i've created for scribus:  
https://github.com/aoloe/scribus-plugin-actionSearch

you can download an appimage for scribus (ctrl-/), gimp (/) or olive (/) to test the feature...  
(presonally, i tend to use / very often in gimp)

since you already have a list of all possible actions, you can for sure use that, instead of querying the list of all menu items!

**Comment by caclark** [comment]
Implemented in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=20c128644acbf9e2f75a120bd43482bb9f5f5551

> (If you add this feature, please rename the "Gnu Image Manipulation Program" plugin in "Gimp Gnu Image Manipulation Program" (or simply Gimp) so that it's easy to start it 

Use Edit/Configure Plugins and change the "Name=" line of the Gimp entry to whatever you feel appropriate.
The modified .desktop file is saved in $HOME/.config/geeqie/applications

**Comment by aoloe** [comment]
hi @caclark , thanks for implementing this!
i will test it as soon as it hits debian testing...

concerning the editing of entries in the configs: i've been using computer for so many years, and i've learned that software should have good behaviors; and that i should refrain from tweaking them to fit my habits (and rather change my behavior to match what the developer thought was a good behavior... or write a ticket, of course).

in this specific case, i really think that most people know that software under the name "Gimp" and not "Gnu Image Manipulation Program"... and i would even dare to say that most casual users will not recognize Gimp under that name.
If you really want to keep the legacy full name, you're welcome to do so (and it's not wrong!) but it would be helpful for most users to change it in "Gimp (Gnu Image Manipulation Program)"... or simply call it "Gimp" as most people do : - )
and if you don't so, when using the ctrl+/ i will simply type gnu to get there...

**Comment by caclark** [comment]
> If you really want to keep the legacy full name, you're welcome to do so (and it's not wrong!) but it would be helpful for most users to change it in "Gimp (Gnu Image Manipulation Program)"

The .desktop file you see is created by the Gimp developers, not by the Geeqie developers.
If you open Edit/Configure Plugins, select the Gimp entry and look at the right-most column you will see the .desktop file is located under /usr. This file is part of the Gimp installation.

If you edit the file with Geeqie, you will see that the modified file is then saved under /home.

When looking for .desktop files, Geeqie first looks under /home and then under /usr. Therefore the .desktop files the user has created or modified take precedence.

If you delete the modified .desktop file, Geeqie will revert to using the one located under /usr.

**Comment by aoloe** [comment]
thanks you for the information!
i was not aware that geeqie was taking the name from the desktop file.

i will try tell the gimp developers that i have an issue with their name... they will love : - )
