### ISSUE TITLE
Sort Manager Feature regression: Copy/move/link selection lost on closing

### ISSUE THREAD

**Issue by 7eggert** [BestImageViewer/geeqie#716]
* Feature Request

With the geeqie version of Debian Jessie, I used to open the sort manager and move the files.

Now I still do the same, but then I'll notice that I copied the files instead and I have to undo or  redo sometimes several minutes of work.

The selection of move/copy should either be saved or there should be a default in the settings.

My current version: Geeqie 1.5.1
OpenSuSE Tumbleweed

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=10f07b7868349932aa610db35bf739bef65bb5a5
