### ISSUE TITLE
How to handle filenames with newline characters by remote commands?

### ISSUE THREAD

**Issue by przepompownia** [BestImageViewer/geeqie#718]
Hello,

How to properly escape filenames with special characters in remote commands? The following quoting of the strange file name is not sufficient. It can unintentionally execute a command. 

```bash
geeqie -r --get-sidecars:"$(printf 'first\n-ct:clear\nthird.jpg')"
```
Is it potential bug or not sufficient escaping only?

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=27e185d16561d5ac9ede691a506159116296fa91
