### ISSUE TITLE
Debian install script failed, no HEIC support

### ISSUE THREAD

**Issue by dandv** [BestImageViewer/geeqie#721]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie ced761e4
```

### OS / DISTRIBUTION
Ubuntu 18.04

### SUMMARY
The Debian installer apparently completed (it's been taking very long so I went away, and when I cam back to the computer, the Zenity window was closed), but there were errors in the console, and HEIC images are not supported (#610), even though I've made sure to check `libheif` when installing.

### STEPS TO REPRODUCE
```
$ wget https://raw.githubusercontent.com/BestImageViewer/geeqie/master/web/geeqie-install-debian.sh
$ ./geeqie-install-debian.sh 
./geeqie-install-debian.sh: line 529: gdk-pixbuf-query-loaders: command not found
./geeqie-install-debian.sh: line 542: gdk-pixbuf-query-loaders: command not found
./geeqie-install-debian.sh: line 554: gdk-pixbuf-query-loaders: command not found
./geeqie-install-debian.sh: line 310:  6059 Done                    sleep 100
      6060 Terminated              | zenity --title="$title" --text="Checking for installed files" --width=370 --progress --pulsate 2> /dev/null
```

**Comment by caclark** [comment]
I think this is a problem with the HEIC header (or "magic number").
When I coded this the only files I found used "ftypheic".

Perhaps you could try:
`strings file-name | grep ftyp`
and see what code your files are using.

I assume I either did not look in the official spec., or did not want to include a file-type until I had a sample with which to check the functionality.
I now have found sample files of type "ftypmif1" so I will include that.

On the one hand it is not good to change the code for each header - and on the other I don't want to include a header without having first verified that the decoder works for it.

**Comment by caclark** [comment]
The errors from the install script are eliminated in the latest version.

Geeqie handles all heic/heif images that I have been able to find samples of.
