### ISSUE TITLE
Remote cmd's output: allow separate filenames with a null character

### ISSUE THREAD

**Issue by przepompownia** [BestImageViewer/geeqie#722]
Thanks for fixing #718, but it is not the end of the story. I still cannot correctly separate filenames returned by the output if any of them contains newline character. 

Please add something like `-print0` in `find`.

**Comment by caclark** [comment]
Fixed in commit:
http://www.geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=498f49d9ab687d8eda99ca59d140bc0b74f3d119

Example usage:
geeqie --remote --print0 --get-sidecars:<FILE>

**Comment by przepompownia** [comment]
Wow, now even without using `--print0` and setting `IFS` empty in bash I have correctly separated filenames when I put it into a remote commands. 

```bash
mapfile -t sidecars < <(geeqie -r --get-sidecars:"$(realpath "20191002\ 165^M617.dng")")
 geeqie-test-files $ ls -go "${sidecars[@]}"
-rw-rw---- 1 23374012 paź  2 16:56 '/tmp/geeqie-test-files/20191002\ 165'$'\r''617.dng'
-rw-rw---- 1  4877750 paź  2 16:56 '/tmp/geeqie-test-files/20191002\ 165'$'\r''617.jpg'
```
