### ISSUE TITLE
Openstreetmap not working

### ISSUE THREAD

**Issue by Massimo-B** [BestImageViewer/geeqie#723]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
Geeqie 1.5.1
```

```
x11-libs/gtk+-3.24.11
```

### OS / DISTRIBUTION

Gentoo Linux
```
[I] media-gfx/geeqie
          Installed versions:  1.5.1(13:54:56 22.11.2019)(exif ffmpegthumbnailer gpu-accel gtk3 jpeg lcms map nls pdf tiff -debug -doc -lirc -lua -xmp)

[I] media-libs/libchamplain
          Installed versions:  0.12.20(0.12)(13:54:27 22.11.2019)(gtk introspection -gtk-doc -vala)
```
### STEPS TO REPRODUCE

GPS Map in the sidebar is enabled, the picture has GPS information and shows a pointer in the map, but the map tiles are not loading.
In netstat I see a connection of geeqie to 81.7.11.83:443 which is konqi.openstreetmap.org

Starting with --show-log-window shows the log window, but the window is just empty.

**Comment by caclark** [comment]
Nothing has changed in Geeqie in this area for  long time.
On my system (Ubuntu) libchamplain is still 0.12.19-3

If you right-click and select a different map does anything happen?
When you zoom in/out on the map, does the status line change to show "Map loading"?

**Comment by Massimo-B** [comment]
Same issue for all different maps. Only "Cycle Map" shows some bitmaps with a "API Key Required" logo.
The other maps like "Mapnik" are just empty, status line has "Loading map" with 0% progress.

netstat shows:
```
tcp        0      0 10.195.222.170:45006    144.76.70.77:443        ESTABLISHED 19163/geeqie        
tcp        0      0 10.195.222.170:42626    81.7.11.83:443          ESTABLISHED 19163/geeqie
```
I can file a bug report for Gentoo. Maybe the build isn't valid or some dependency is missing. ldd has all links complete. But I don't know how to debug that further. The maps have been working some time ago. I have already rebuilt geeqie and libchamplain.

**Comment by Massimo-B** [comment]
Zooming out to Zoom level 6, I can see some bitmaps, but zooming to 8 or 10 I see tiles with a red "X" on the top left.

**Comment by Massimo-B** [comment]
I was able to get one map working, that is Nr.3 "Transport map". This one is working on all zoom levels. I guess this is rather something about the Openstreetmap API or service. Do you still have cached bitmaps? Can you still see the map tiles after clearing the bitmaps?
The Zoom level 6 on "Mapnik" dopes not always work. Right now, even zooming to lowest zoom level does not show any bitmaps. Maybe there is no refresh if the http request is blocking in the background.

Right now I'm just going on working with the "Transport map", looking clean and tidy.

**Comment by caclark** [comment]
If it is possible, I suggest you compile with libchamplain 0.12.19.

I will probably not look at any problems with 0.12.20 until it is part of the Debian release.

**Comment by Massimo-B** [comment]
Same behavior after rebuilding both media-libs/libchamplain-0.12.19-r1 and geeqie.

**Comment by caclark** [comment]
I am not at home at the moment so I do not have a spare computer to install Gentoo onto [and even if I did, I am probably not competent to do so :-(  ].

So I'll take another guess. The cache is under $HOME/.cache/champlain.
Perhaps you could delete the cache and try again?

**Comment by Massimo-B** [comment]
Can't reproduce right now, going to reopen if it happens again...
