### ISSUE TITLE
Unsharp print results

### ISSUE THREAD

**Issue by Massimo-B** [BestImageViewer/geeqie#726]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
Geeqie 1.5.1
```

```
x11-libs/gtk+-3.24.11
```

### OS / DISTRIBUTION

Gentoo-Linux ~amd64

### SUMMARY

Printing from a 300dpi PNG file results in unsharp print results. Same file printed from Firefox is sharp as usual. The file itself is sharp enough in Geeqie when zooming.

**Comment by tomaszg7** [comment]
I stumbled upon similar issue at one point, but I don't remember any details at this moment.

**Comment by caclark** [comment]
Could you post a link to an image which exhibits this effect? Thanks..

**Comment by Massimo-B** [comment]
Of course..
![out](https://user-images.githubusercontent.com/3286728/71242341-08a88e80-230e-11ea-8b0b-f776772c88b8.png)
![out_scan](https://user-images.githubusercontent.com/3286728/71242343-08a88e80-230e-11ea-9991-9dbc64cce25e.jpg)
I created the first file from the PDF media print of this page with 300dpi, and scanned the result with 300dpi again. The effect is only minor here, though it is there and the result could be far sharper... Printing from PNG or JPG using geeqie I mostly only need for scanned text document that I have only in this formats instead of PDF. So readable font and sharp edges are important. The result of 200dpi or 300dpi bitmap files are not usable, looking like 75dpi re-scaled scans.

**Comment by caclark** [comment]
If you are compiling from sources, perhaps you could take a look at this patch to see if it solves the problem - and doesn't cause other problems.
[726-1.diff.gz](https://github.com/BestImageViewer/geeqie/files/4428127/726-1.diff.gz)

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=d3ce705d4e16898d5d7a32ae0056955a7d6982f6
