### ISSUE TITLE
wish: bigger thumbnails for 32" screens

### ISSUE THREAD

**Issue by Cantuccini-Lori** [BestImageViewer/geeqie#727]
### ISSUE TYPE
Feature Request

### GEEQIE VERSION
Geeqie 1.5.1 in Debian Sid under Plasma 5.14

### OS / DISTRIBUTION
Debian Sid

### SUMMARY
It would be nice to have bigger thumbs in Geeqie, 256x256 pixel is too small for photographers to see details and differences on 32"-Screens

**Comment by tomaszg7** [comment]
That's probably fairly easy to implement, but are you sure you need thumbnails that big? If you want to see details, wouldn't split screen view or multiple windows be much better option? Moreover in Pan View there already is an option for really large image sizes.

**Comment by caclark** [comment]
I see in the code that there is the possibility to set custom thumbnail sizes, but I don't see how the user can do this.

However it can be achieved by the following steps:
Stop Geeqie
Open $HOME/.config/geeqie/geeqierc.xml in an editor.
Find and edit the following lines:
`thumbnails.max_width =`
`thumbnails.max_height =`
(The maximum value is 512)
Save the file and re-start Geeqie

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=cde469eee1a984b0c9745c87117a50c326d6c289

**Comment by Cantuccini-Lori** [comment]
wow. Thanks. That is really great. I tested 384px and it seems perfect for 32". I had to rebuild the thumbnaillibary, but thats okay.
If there is a tool that could it recoursivly, it be a great reccomandation

**Comment by Cantuccini-Lori** [comment]
found the thumbnail-option in geeqie. Great work!

**Comment by caclark** [comment]
> found the thumbnail-option in geeqie. Great work!

I guess you refer to Edit/Cache Maintenance/Render Thumbnails/Include Subfolders

In addition to that there is a remote command:
`geeqie --remote  --cache-render-recurse:<folder>`

This was included at the request of someone who has a very large number of images.
The idea is that the thumbnail maintenance can be routinely scheduled by an anacron or cron job.

**Comment by Cantuccini-Lori** [comment]
Thanks. I will try that.
I found another little "bug":

I changed
thumbnails.max_width = 384
thumbnails.max_height =384

and the new thumbnails are in a good size. But if I open a pic with gimp, the thumbnail is changing to 256px. 
If you implementet it in the new version, maybe the bug is not present anylonger

**Comment by Cantuccini-Lori** [comment]
Just another question (if somebody is reading this).
I have Geeqie 1:1.5.1+git20200808-2a27c9ab-1 in Debian Sid. I newly installed my system and cannot find the option to show bigger thumbnails than 256x256.
Could you help me, if my version is to old and if I need to be more patient, or if I miss something
Thanks!

**Comment by caclark** [comment]
With that version, on `Edit/Preferences/General` there should be an option for `Thumbnails/Custom Size` which allows a size up to 512x512.

**Comment by Cantuccini-Lori** [comment]
mean while I recompilled with the debian script and I found it. 
Maybe I was blind before. Sorry, if it was my mistake.
Thanks for you help!!!!

My second problem is here, and I will post a description in a minute. If you know how to solve, please help. Thanks
https://github.com/BestImageViewer/geeqie/issues/728

**Comment by Cantuccini-Lori** [comment]
Last thing: As quality I selected "Hyper" but the 384x384 thumbs still are a little blury. Is there any way to make them a little sharper / high quality?
Thanks for your time and help.

**Comment by caclark** [comment]
The GDK Pixbuf documentation has this comment about GDK_INTERP_HYPER:

> **Deprecated**: this interpolation filter is deprecated, as in reality it has a lower quality than the GDK_INTERP_BILINEAR filter (Since: 2.38)

As an experiment, in `Edit/Preferences/General` you could disable `Cache thumbnails and sim files`. This will make Geeqie use a different method to create thumbnails - but I have not looked at the details of this part of the code.

**Comment by Cantuccini-Lori** [comment]
I tested BILINEAR and it works like a charm :)
thanks!
It also seems that now the thumbs do not change size anylonger. Everything perfect.

I reccomend to remove the text behind Hyper (best but slow)

Thanks for your help
