### ISSUE TITLE
Keyboard shortcut mapping questions

### ISSUE THREAD

**Issue by beskhu3epnm** [BestImageViewer/geeqie#730]
### ISSUE TYPE

* Question

### GEEQIE VERSION

```
1.4
```
### OS / DISTRIBUTION
```
Linux Mint.
```

### SUMMARY

Hi. I simply have a few questions about keyboard shortcut mapping. I want to attribute keyboard shortcuts to certain commands. Can you inform me how to do the following:

- Double-click to enter/exit full-screen mode
- Right/left cursor keys to move to the next/previous image
- Scroll wheel zooms in/out while in full-screen mode
- Copy to specified directory
- Move to specified directory
- Move to trash (as opposed to delete) (no warning message)

Also, how do you set it so the viewer refits to default zoom for next image.

**Comment by caclark** [comment]
Keyboard mapping is on Edit/Preferences/Keyboard.
Help/Keyboard Map shows most of the current settings.

> Double-click to enter/exit full-screen mode

The default keys for full-screen toggle are "f", "v" and "F11"

> Right/left cursor keys to move to the next/previous image

The cursor keys cannot be redefined.

> Scroll wheel zooms in/out while in full-screen mode

Go to Edit/Preferences/Behaviour and clear "Navigation by left or middle click o image". Mouse middle-click toggles the mouse wheel action between zoom and scroll.

> Copy to specified directory
Move to specified directory

You must create a plugin to do this. Use Edit/Configure Plugins to crate a new desktop file, and point it to a script which executes the required actions.

**Comment by caclark** [comment]
Keyboard mapping is set in Edit/Preferences/Keyboard.
The current mapping is shown in Help/Keyboard Map.

> Double-click to enter/exit full-screen mode


The default keys for toggle full-screen are "f", "v", and "F11".
They can be re-mapped.


> Right/left cursor keys to move to the next/previous image


The cursor keys cannot be re-mapped.

> Scroll wheel zooms in/out while in full-screen mode


Go to Edit/Preferences/Behaviour and clear "Navigation by left or middle click on image".
Mouse middle-click will then toggle the scroll-wheel action between scroll and zoom.

> Copy to specified directory
Move to specified directory


This can only be done by creating a new plugin and pointing it to a script which executes the desired function.
Plugins are created in Edit/Configure Plugins/New
Note:
Open View/Sort - additional destinations can be set. A single mouse-click will copy or move the selected files to the destination. A keyboard shortcut cannot be set to this action.

> Move to trash (as opposed to delete) (no warning message)

There is a bug in this area. I will fix it in the next few days.

> Also, how do you set it so the viewer refits to default zoom for next image.

On the Geeqie status bar, click on the field that shows the current zoom value. The zoom setting can then be set.

**Comment by beskhu3epnm** [comment]
Well, unfortunately then Geeqie is not for me.
