### ISSUE TITLE
History: [path_list] consist of only one path.

### ISSUE THREAD

**Issue by przepompownia** [BestImageViewer/geeqie#733]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
0d08a02

### SUMMARY
I see recently visited directories only within the single process. The list is not persisted in `path_list` section of `history` file at the exit. Only the most recent visited directory is persisted in the config and in `history`. After adding some path manually in the file, it is visible in the list after starting geeqie. 

I have not found any setting that might cause this behavior.

**Comment by caclark** [comment]
What value do you have set in Edit/Preferences/Behaviour/Recent Folder List Maximum Size?

**Comment by przepompownia** [comment]
Probably I accidentally removed "0" from 10 in the config file... ;)

Thanks! ;)
