### ISSUE TITLE
Starting with --remote --new-window opens two windows

### ISSUE THREAD

**Issue by przepompownia** [BestImageViewer/geeqie#734]
`geeqie --remote --new-window` works as expected when there is already running `geeqie`. Otherwise this commands opens the main window and the new one. 

Is the second case expected behavior? If not, please fix it. If so, please add something like `--new-window-if-any-exist`.

I would like to start command using `geeqie --remote --new-window` both as a geeqie plugin and from the shell.

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=5a145e787d4d65690b85b32909a1c01ebe762df9

**Comment by przepompownia** [comment]
Thanks!
