### ISSUE TITLE
Please migrate from gnome-doc-tool to yelp-build

### ISSUE THREAD

**Issue by gusnan** [BestImageViewer/geeqie#736]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
```
1.5.1
```

### OS / DISTRIBUTION
Debian Unstable

### SUMMARY
Geeqie uses gnome-doc-tool to build documentation, which is deprecated, both in Debian and upstream. The Debian GNOME team doesn't consider gnome-doc-utils to be suitable for release in Debian 11 Bullseye. In addition gnome-doc-utils is dependant on Python 2, which is to be removed in Bullseye too, so chances are that this bug will be severity serious (in Debian) soon.

The supported replacement is yelp.m4 in yelp-tools, and there's a porting guide available:

https://wiki.gnome.org/Initiatives/GnomeGoals/NewDocumentationInfrastructure

Debian bug at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947525.

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=c9ea0d5b58270f360530ccf70d0a90758fe47490

**Comment by tomaszg7** [comment]
It would be nice if it would still be possible to build Geeqie without doc. I don't have either `gnome-doc-tool` nor `yelp-build` on my system and before this commit I was able to build Geeqie. Now `autogen.sh` fails but commenting out `DIE` in the check for `yelp-build` makes Geeqie compile fine again.

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=6ee904772d9670c615b3ed803efe7d6de7c82c28
