### ISSUE TITLE
Don't create new folder without confirmation

### ISSUE THREAD

**Issue by przepompownia** [BestImageViewer/geeqie#737]
### ISSUE TYPE
* Bug Report
### SUMMARY
Sometimes I accidentally run the action of creating a new folder then cancel it. As a result, I get an unwanted folder named "New folder*" which I have to delete later.
### STEPS TO REPRODUCE
- Run any action that create a new folder.
- press Escape to cancel

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=b7a34ebb5ed235575b3dcc9635d9c98d74aa0fd5

**Comment by przepompownia** [comment]
Thanks!
