### ISSUE TITLE
%unknown class of images not grouped with jpegs

### ISSUE THREAD

**Issue by mhellwig** [BestImageViewer/geeqie#743]
I am using geeqie 1.5.1 under ARCH.
I am aware of the fact that the new canon .cr3 raws aren't supported basically by any program under linux as of yet. That is not my problem.
What is my problem that nevertheless, I want the .cr3 raws that my camera creates to be grouped together with the jpegs of the same filename (as geeqie does with e.g. the cr2 raws of older cameras).
I've tried (I think) every combination of settings under the "files" header that I could think of, I've even tried just adding .cr3 as a recognized extension and set its type to unkown, but still, I can only get geeqie to exhibit one of the two following behaviours:
* show only the jpegs OR
* show jpegs and raws (where the raws are replaced by a "broken file"-icon) but they aren't grouped

Neither are usable for quick browsing-and-deleting of photos. I need to be able to step through the jpegs and delete any pair of files that I want to with a one-button action (as was possible with cr2).

I re-iterate, I _know_ that cr3s aren't supported (yet). I don't need to read or interpret them, they just need to be grouped together with their respective jpegs so that they can be deleted as a pair.

**Comment by caclark** [comment]
Instead of setting the .cr3 extension as "unknown", try setting it to "raw image".
I made a quick check and it seemed to work, but there may be other negative interactions that I did not see.
The .cr3 thumbnail will always show as the broken image - but when grouped, the jpeg thumbnail is shown.

**Comment by mhellwig** [comment]
holy shit thanks that works .. _many_ thanks!

**Comment by caclark** [comment]
> I am aware of the fact that the new canon .cr3 raws aren't supported basically by any program under linux as of yet

See #744
