### ISSUE TITLE
Better support HiDPI - thumbnail size

### ISSUE THREAD

**Issue by vnnv** [BestImageViewer/geeqie#747]
### ISSUE TYPE

* Feature Request

### GEEQIE VERSION

```
Geeqie 1.5.1
```
Is it possible to add more thumbnail sizes? Currently the biggest thumbnail size is 256x256 pixels, but using HiDPI display - 3840x2160 resolution - the size of the thumbnails is like 128x128 on FullHD display.

**Comment by caclark** [comment]
This is covered in a "closed" issue. A fix for this is in the repo. at geeqie.org, but #727 shows a way you can edit your configuration file to get any size you wish, up to 512x512.
You can re-open this issue if 512x512 is not big enough.
