### ISSUE TITLE
Allow to make layouts persistent and selectable

### ISSUE THREAD

**Issue by przepompownia** [BestImageViewer/geeqie#751]
### ISSUE TYPE
* Bug
* Feature request

### GEEQIE VERSION
```
a097dd6
```
### SUMMARY
User-defined layouts are useful functionality. Usually I want to decide about the EXIF keys subset or the way file list presentation (icons/text etc.). 

Geeqie loses any layout of window that was closed before exit application. I would like to make layout persistent. 

Any newly opened window seems to have the layout uncontrolled by user. I would like to select one of persistent layouts as the default in such case or manually choice one of existing (at least by a remote command).

Currently I have versioned my `geeqierc.xml` and checkout it to restore the customized list of layout. 

While writing this issue I came up with the idea of using a separation configuration file as a temporary workaround (`geeqie -r --config-load:/tmp/geeqierc.xml`) ~but it seems to behave in a buggy way to describe in a separate issue~ (edit: it occurred only when the original config file had empty layout ids and more than one layout: new additional windows appeared beside these defined in the config file).

**Comment by caclark** [comment]
> Currently I have versioned my geeqierc.xml and checkout it to restore the customized list of layout.

If you are using --config-load, you may use any file name;   geeqierc.xml is just the default.
When Geeqie opens multiple windows, a unique ID is given to each window. You will see these IDs if you enable Edit/Preferences/Windows/Show Window IDS.
If you create several config. files with different names, you can change the ID used by editing the \<layout\>\<id\> field in each config.file.
When you use --config-load, if a window with the same ID is already open, that one is updated (maybe problems with this). If not a new window is opened.
Of course, when you close the window, all changes are written back to the default filename of geeqierc.xml

**Comment by przepompownia** [comment]
In other words, Geeqie
- persists each layout of window that is present at the exit
- removes from persisting each layout of window that is absent at the exit.
The storage of layouts is the default config file, independently of what config was used with `--config-load` option. 

Affecting the config file that seemed not to be used is a strange behavior. The next running with the default config file surprises with additional unexpected windows (coming from the alternate file).

Even if the additional file were changed instead of the default, then we still would have the same problem of losing each layout of window that is absent at the exit. 

My proposition is to:
- allow flag some layouts as persistent
- not necessary open all persistent layouts at the start - rather on demand or, as currently, if they were present at the last exit
- allow flag the one of persistent layouts as the default for opening new window.

**Comment by caclark** [comment]
The attached .diff is my suggestion to implement this.
The changes are:
The option Edit/Configure This Window/Exit Program When This Window Is Closed is deleted
Executing "Close Window " when window "main" has focus will close all open windows
The window "main" can be identified by the word "Geeqie" in the window title - other windows have the word "geeqie"
A layout can be cloned from any window that has the focus
New windows follow the current format - i.e. named "lw\<n\>"
Any window with a name starting with the characters "lw" is treated as before
If you wish a layout to be remembered, you must change the name so that the first two characters are not "lw"
Identifying windows can be helped with the option Preferences/Windows/Show Window IDs
If you use anything other than the default 3-pane layout you may encounter #760 

[751-1.diff.gz](https://github.com/BestImageViewer/geeqie/files/4342958/751-1.diff.gz)

**Comment by przepompownia** [comment]
Layout ids are not shown until the first image is displayed. Please start geeqie in a directory without images. 

Please see at some test

```sh
#!/usr/bin/env bash

set -v
cd
defaultConfig='.config/geeqie/geeqierc.xml'
alterConfig='/tmp/geeqierc.xml'
seconds=2

showPersistedLayouts() {
    command grep -P '^\s+id = ' "$1" "$2"
}

geeqie --version
git checkout --force -- "$defaultConfig"
command cp --verbose "$defaultConfig" "$alterConfig"
showPersistedLayouts "$defaultConfig" "$alterConfig"

geeqie --remote --close-window --id:main &>/dev/null
sleep "$seconds"
showPersistedLayouts "$defaultConfig" "$alterConfig"
git checkout --progress --force -- "$defaultConfig"
git diff "$defaultConfig"

showPersistedLayouts "$defaultConfig" "$alterConfig"
geeqie --remote --config-load:"$alterConfig" --close-window --id:main &>/dev/null
sleep "$seconds"
showPersistedLayouts "$defaultConfig" "$alterConfig"
git checkout --progress --force -- "$defaultConfig"

geeqie --remote --config-load:"$alterConfig" --close-window --id:a1 --close-window --id:main &>/dev/null
sleep "$seconds"
showPersistedLayouts "$defaultConfig" "$alterConfig"
git checkout --progress --force -- "$defaultConfig"

perl -i -p -e 's/(^\s+id = ")main"/\1a2"/' "$alterConfig"
showPersistedLayouts "$defaultConfig" "$alterConfig"
geeqie --remote --config-load:"$alterConfig" --close-window --id:a1 --close-window --id:a2 &>/dev/null
sleep "$seconds"
showPersistedLayouts "$defaultConfig" "$alterConfig"
git checkout --progress --force -- "$defaultConfig"

```
and its output:

```
cd
defaultConfig='.config/geeqie/geeqierc.xml'
alterConfig='/tmp/geeqierc.xml'
seconds=2

showPersistedLayouts() {
    command grep -P '^\s+id = ' "$1" "$2"
}

geeqie --version
Geeqie a02121d2
git checkout --force -- "$defaultConfig"
command cp --verbose "$defaultConfig" "$alterConfig"
'.config/geeqie/geeqierc.xml' -> '/tmp/geeqierc.xml'
showPersistedLayouts "$defaultConfig" "$alterConfig"
.config/geeqie/geeqierc.xml:        id = "main" 
.config/geeqie/geeqierc.xml:        id = "a1" 
/tmp/geeqierc.xml:        id = "main" 
/tmp/geeqierc.xml:        id = "a1" 

geeqie --remote --close-window --id:main &>/dev/null
sleep "$seconds"
showPersistedLayouts "$defaultConfig" "$alterConfig"
.config/geeqie/geeqierc.xml:        id = "main" 
/tmp/geeqierc.xml:        id = "main" 
/tmp/geeqierc.xml:        id = "a1" 
git checkout --progress --force -- "$defaultConfig"
git diff "$defaultConfig"

showPersistedLayouts "$defaultConfig" "$alterConfig"
.config/geeqie/geeqierc.xml:        id = "main" 
.config/geeqie/geeqierc.xml:        id = "a1" 
/tmp/geeqierc.xml:        id = "main" 
/tmp/geeqierc.xml:        id = "a1" 
geeqie --remote --config-load:"$alterConfig" --close-window --id:main &>/dev/null
sleep "$seconds"
showPersistedLayouts "$defaultConfig" "$alterConfig"
.config/geeqie/geeqierc.xml:        id = "main" 
/tmp/geeqierc.xml:        id = "main" 
/tmp/geeqierc.xml:        id = "a1" 
git checkout --progress --force -- "$defaultConfig"

geeqie --remote --config-load:"$alterConfig" --close-window --id:a1 --close-window --id:main &>/dev/null
sleep "$seconds"
showPersistedLayouts "$defaultConfig" "$alterConfig"
.config/geeqie/geeqierc.xml:        id = "main" 
/tmp/geeqierc.xml:        id = "main" 
/tmp/geeqierc.xml:        id = "a1" 
git checkout --progress --force -- "$defaultConfig"

perl -i -p -e 's/(^\s+id = ")main"/\1a2"/' "$alterConfig"
showPersistedLayouts "$defaultConfig" "$alterConfig"
.config/geeqie/geeqierc.xml:        id = "main" 
.config/geeqie/geeqierc.xml:        id = "a1" 
/tmp/geeqierc.xml:        id = "a2" 
/tmp/geeqierc.xml:        id = "a1" 
geeqie --remote --config-load:"$alterConfig" --close-window --id:a1 --close-window --id:a2 &>/dev/null
sleep "$seconds"
showPersistedLayouts "$defaultConfig" "$alterConfig"
.config/geeqie/geeqierc.xml:        id = "main" 
.config/geeqie/geeqierc.xml:        id = "a1" 
/tmp/geeqierc.xml:        id = "a2" 
/tmp/geeqierc.xml:        id = "a1" 
git checkout --progress --force -- "$defaultConfig"
```
Bugs:
- If the default file is used, then it still loses additional layout. 
- If the default file is not used then it also is touched. 
- If the alternate config does not contain `main` layout, then geegie opens additional `main` window. 

I did not found how to display windows list so the script does not show it. 

Thank you for accepting my proposal and the first attempt.

**Comment by przepompownia** [comment]
Please also notice `sleep` command. I need to wait some time to persisting default file.

**Comment by caclark** [comment]
> Layout ids are not shown until the first image is displayed.

This is a bug - or perhaps merely a deficiency. There is a problem that the ID is not known when the window is created. I did not think it worthwhile trying to solve the problem.

> I did not found how to display windows list so the script does not show it.

The window layouts are stored in $HOME/.config/layouts/*.xml
The filename is the same as the ID.
If necessary a remote command can be created, e.g.
`--remote --get-window-list`


I wanted to change the way window names are allocated so that the ID "main" always exists.

A new user with this patch will always have a  window "main".
You have config. files without "main" because of the way Geeqie previously operated.

The "main" config. file holds the global values. The files in the layouts folder contain only layout information for that window.

I set this to work in the way I think I would use it - always start with "main" (set to my normal use), and the option to open other layouts when needed.
Can you work with this as it is, or is it essential to have each layout as a individual entity?

**Comment by przepompownia** [comment]
> This is a bug - or perhaps merely a deficiency. There is a problem that the ID is not known when the window is created. I did not think it worthwhile trying to solve the problem.

Probably not if it can take too much your time.

> The window layouts are stored in $HOME/.config/layouts/*.xml
Sorry, I have to review this patch as much as it can be understandable for me. Indeed, additional layouts were saved in `layouts` :) 

After browsing the patch I discovered the new menu - it's not a joke ;)

Yesterday I made test by the old way, that seems to be not quite appropriate to the change. 

It's time to use the new way without reading any alternate file. 

```
rm -fv ~/.config/geeqie/geeqierc.xml
geeqie --remote --new-window --id:a2
Remote Geeqie not running, starting....
remote sent window ID that does not exist:"a2"
```
but a2.xml exists and it can be open from the menu of the (unwanted) main window that is opened instead (or beside). Maybe this command is incorrect against the expected result.

The current state of your work allows to persist and read alternate layouts using GUI but I can not open any selected layout (exclusively) by any remote command. 

> `--remote --get-window-list`

It could be usable for test purposes. along with `--go-home` and `--print-current-directory`.

Why the main window layout cannot be kept separately (i.e. like any additional layout) by default? To remember the latest window set we could keep only references, not whole definitions. It looks clearer and would simplify tracking the default config by VCS.

**Comment by caclark** [comment]
> geeqie --remote --new-window --id:a2

Would you try this command instead:
`geeqie --remote --config-load:<full-path-to-layouts-folder>/a2.xml`

It is possible to update the config-load code to automatically search for an ID in that folder - I just did not get around to that yet.
If Geeqie is not running, executing the above command will open window "main" and then the window "a2".
If you do not want to see window "main", maybe you could use wmctrl to minimise it.
I also have the idea to include a new main option, for other reasons:
`geeqie --open-minimized`


-----------
>  --go-home

--remote --file:$HOME`
will do this.

> --print-current-directory

`--remote --tell`

will give the full path to the current image. Unfortunately it does not give a response if the current folder is empty. I guess that could be changed

------------

> Why the main window layout cannot be kept separately

The code is (to me) an incomprehensible maze - with no documentation. 
I try to keep any changes as small as possible, while allowing something to be achieved.

**Comment by przepompownia** [comment]
> --remote --file:$HOME`
I meant layout's `home_path`, sorry for inaccuracy due to not pasting the whole test, but only its first command. I have used `--tell` also there. 

`geeqie --remote --config-load:$HOME/.config/geeqie/layouts/a2.xml` - this command actually opens `a2` layout along with the main window. It may be a workaround while there is no alternative. 

> The code is (to me) an incomprehensible maze - with no documentation.
I try to keep any changes as small as possible, while allowing something to be achieved.

Thank you all the more for this step. Maybe @tomaszg7 (blamed as author of the large piece of code) would help to separate layout from the main file and allow open Geeqie without the main window. 

Apart from issues mentioned above, currently I do not see any errors. What do you think about merging this step and trying to improve it in potential new iteration?

**Comment by caclark** [comment]
> I meant layout's home_path

The only way is to scan the config. file.

Geeqie has a Lua interface, but that is rather limited. In the future that may get expanded to provide more access to internal data.

**Comment by caclark** [comment]
Implemented in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=d992670d230e1c0c6af22e2f818e80d00205dcbf

**Comment by przepompownia** [comment]
> separate layout from the main file and allow open Geeqie without the main window

It seems to be simpler if we split them into separate issues and close current.
