### ISSUE TITLE
Window ergonomics

### ISSUE THREAD

**Issue by installgentoo** [BestImageViewer/geeqie#755]
### ISSUE TYPE

* Feature Request

### GEEQIE VERSION

```
1.5.1
```

```
GTK2
```

### OS / DISTRIBUTION

Gentoo

### SUMMARY

1. Commit bd11ce89f2e9ea7a8c3ead34887e98e9dbf1202c
Why was this done? It just eats up space in the icon view. Who want this area taken up by empty space? Revert this commit, and let people set up however much of the toolbar they want to see.

2. Why does the search filter appear in the icon view? It's just taking space there. There's free space in the directory tree and free space in the bottom status bar(even if you enable all the regular icons), you should move it to one of these locations. Or make it a popup, like in filechooser, i dunno.

![2020-02-09-231412_1366x768_scrot](https://user-images.githubusercontent.com/2088917/74100342-c889bd80-4b92-11ea-8ac9-a110deb4170c.png)

Right now in 1.5.1 there's a huge empty square taking space from the images that you actually want to look at.

### STEPS TO REPRODUCE

Launch geeqie

**Comment by rysson** [comment]
I think you can hide "Hide file list" (Ctrl-H).
File list it;s OK for me, but now menu takes more place and I can not shrink file list panel (panel is not resized).

**Comment by installgentoo** [comment]
fixed in master, there's an option for this
