### ISSUE TITLE
Set default option for file drag-drop, skipping "Move/Copy/Symlink" popup

### ISSUE THREAD

**Issue by ekalin** [BestImageViewer/geeqie#756]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
```
Geeqie 1.5.1
```

```
Gtk3 3.24.13
```

### SUMMARY
When dragging and dropping a file or files to another folder without any key selected, a pop-up menu is displayed asking if the user wants to move, copy or symlink the file to the new directory.

This can be suppressed by shift+drag (move) or ctrl+drag (copy), but it's inconvenient that an extra key must be held down, and selecting from the pop-up menu for each file is also inconvenient.

I propose a setting that defines the default behavior, so that if set to "move" then just drag-drop would move the files. If shift of control are held, then the default behavior is overridden.

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=c3bc39aafc618f548e8a8132311f2485ce636549

Additional option on Preferences/Behavior
