### ISSUE TITLE
Loading fullscreen windows on different monitors

### ISSUE THREAD

**Issue by Epy** [BestImageViewer/geeqie#765]
Hello

### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
```
Geeqie 1.4+git20190121+431adf32
```

### OS / DISTRIBUTION
Debian 10 (stable at this moment)

### SUMMARY
Loading a conf file withe multiple _layout_ nodes doesn't allow to choose the monitor

### STEPS TO REPRODUCE
Open geeqie with `geeqie -f -s --config-load:.config/geeqie/multimonitors_conf.xml`

In this xml file I have multiple _layout_ nodes but all instances and fullscreen windows open on main screen

In `.config/geeqie/geeqierc.xml` file there is a `fullscreen.screen` option that seems to do what I'd like but its in the _global_ config node. Could each _layout_ have its own `fullscreen.screen` parameter ?
Is there another option I missed ?

Thank you
I used the Debian 9 packaged version for a long time, I really like the improvements !

**Comment by caclark** [comment]
The relevant parameter is set in Edit/Preferences/Windows/Location
You can set this to be Determined By Window Manager so that fullscreen is on the monitor displaying the layout window.

If you want all layout windows displayed on a single screen, but displaying fullscreen on various other monitors, that is something else.

Maybe a new --remote command so that the destination screen can be set dynamically would be better.

**Comment by Epy** [comment]
I'd like to set this in command line, I've checked the parameter you told to find it changes the fullscreen.screen option in xml file (101, 102, 103). Are you saying there is another way to do this ?
If I can have only the fullscreen slideshow windows set on each monitor that could do the trick for me :)
Other option could be to open 3 instances each with its own xml config file. I would then set the screen for each one I think.
The new remote command could be another way also

**Comment by caclark** [comment]
I'm sorry, but I do not fully understand what you want to achieve, but I will explain what can (and cannot) be done. Maybe that will help get a solution.
I have Preferences/Windows/Location set to Determined By Window Manager.
I am using two monitors.
I start Geeqie and ensure the main window is on the left-hand monitor.
I open a new Geeqie window (with ID lw1) and move it to the right-hand monitor.
The command
`geeqie --remote --id:main --fullscreen-start`
brings the left-hand monitor fullscreen.
and the command
`geeqie --remote --id:lw1 --fullscreen-start`
brings the right-hand monitor to fullscreen.

-----
If someone has a three monitor setup, and has two Geeqie windows open on monitor 1, and would like to direct fullscreen of layout "main" to monitor 2 and fullscreen of layout "lw1" to monitor 3 - that is not possible.
Maybe a new --remote command could be written to achieve that.

----


The latest version of Geeqie has a new command
`geeqie --new-instance`
but note that there is only one geeqierc.xml file - this may cause confusion.





If you want to clone Geeqie, please use the repo. at geeqie.org, not the one at GitHub.
The one at geeqie.org is always the latest.

**Comment by Epy** [comment]
Your explanation is clear, thank you
What I hoped to do is the same thing as your first example but automatically
Starting 3 instances or 3 windows of geeqie and have them or their fullscreen on a defined monitor

I also have the parameter set to Determined By Window Manager, if I launch geeqie from command line 1 or 2 or 3 times, all windows will be on the main monitor, which is normal; if I activate fullscreen with a remote command all three will be on the same monitor, also normal.

I thought one parameter in xml file could allow to pre-set 3 window (3 layouts as in xml file when I mouse-open 3 windows by dragging it) on a defined monitor for each with this option in layout xml node or another one.

That was only a wish to automate some things but not critical. I'm not a software developper (only python and shell scripts) so I couldn't modify or fork geeqie; I would not know where to start :))

Thank you for your time, if you think nothing could be done easily with this you can close this issue :)
