### ISSUE TITLE
Parallel build problem

### ISSUE THREAD

**Issue by AMDmi3** [BestImageViewer/geeqie#766]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
1.5.1
```

### OS / DISTRIBUTION
FreeBSD

### SUMMARY
Parallel build failure was [reported](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245052) on FreeBSD. Couldn't reproduce it, but as always with parallel build issues it's dependent on a lot of things.

The cause seem to be in `src/gq-marshal.{c,h}` generation:
https://github.com/BestImageViewer/geeqie/blob/92b4e3e7257ed48a1d3e5389bac8f7e326ef4829/src/Makefile.am#L304-L308
These files must be generated before compiling any sources which reference them, but it doesn't seem to be the case. 

### STEPS TO REPRODUCE
Try to build geeqie with certain (unknown) number of jobs.

**Comment by AMDmi3** [comment]
It has been confirmed that my mitigation of this problem, by building `gq-marshal.c` before the normal build, works.

**Comment by caclark** [comment]
Fixed, I hope, in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=881468bec8b73966ce6d3b1c1b9986d9faf1ce22

**Comment by AMDmi3** [comment]
Thanks, will ask original submitter to test since I cannot reproduce the problem. Btw, it could be more correct to depend on `gq-marshal.h` here.

**Comment by caclark** [comment]
> be more correct to depend on gq-marshal.h here.

Thanks.

Fixed in commit:
http://www.geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=55ed33bc10771ae7e2929d643cfcedaa8a7f7a27

**Comment by AMDmi3** [comment]
I've discovered a way to reproduce the problem by adding `sleep 1` to `gq-marshal.h` and `gq-marshal.c` targets. Either of your changes fixes it, thanks again!
