### ISSUE TITLE
Feature request: twin file-panels with ability to move to next image simultaneously

### ISSUE THREAD

**Issue by gonerodes** [BestImageViewer/geeqie#767]
### ISSUE TYPE

* Feature Request

### GEEQIE VERSION

```
Geeqie 1.4
```

```

```

### OS / DISTRIBUTION

Ubuntu 18.04.4 LTS

### SUMMARY

Since the application supports two panels for images, I think would be valuable for the **user** to be **able to move to the next image comparison** with just **one click** or keystroke.

It is quite common that the images to be compared have **common prefix filename** which means that they can also have a common sorting.

e.g. Let's say someone performs a **bulk blur operation on 100 images** and outputs the resulting images under `blurred/` directory. Now he wants to **compare the resulting images with original ones**.

### Possible Usage (using twin-file-panel view):

- User sets the **left file panel to `images/`** path and the **right file panel to `images/blurred`** path. 
- Select **first file from the 1nd file panel** (automatically associated to the 1st image preview panel)
- Select **first file from the 2nd file panel** (automatically associated to the 2nd image preview panel)
- Now with each click to the `next-sync button` he can **move to the next comparison**

**step option:**

- **In case** user wants to bulk compare **images on the same directory** (e.g. image1.jpg/image1-blurred.jpg ... e.t.c) he could **repeat the above** process **but set a `next-sync-step` value** (e.g. to 2 or 3) depending on how many versions of each image exist in the directory.
- Then select **first image from 1st file-panel** and **second image from 2nd file-panel**.
- Now by clicking on `next-sync button` he would **move by 2** and the comparison **effect would be the same as above.**

**Comment by caclark** [comment]
Using the split windows feature, it might be possible to do this

I think the "step option" is unlikely.
The Select/Show File Filter function allows the files displayed to be filtered by regular expression. If you use a consistent file naming convention maybe you would be able to select the file group you require.
You can also select file sets and put them in temporary Collections, and then drag-drop the collection on a split window.

**Comment by caclark** [comment]
Attached is a .diff that implements synchronised image selection for split windows.
A problem is that I could not find a free modifier key to select this function.
This implementation uses the scroll-lock key. There is at least one problem with this - Xubuntu (at least) does not enable the scroll-lock key by default.
Ergonomically, maybe the caps-lock key would be better, but no doubt there are other problems with that.
[767-1.diff.gz](https://github.com/BestImageViewer/geeqie/files/4464560/767-1.diff.gz)

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=ff3ba3c98e7da2238814037425555b4d63118a5d
