### ISSUE TITLE
Viewing folder with large amount of images slows closing down geeqie

### ISSUE THREAD

**Issue by gusnan** [BestImageViewer/geeqie#768]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
Geeqie 1.5.1
```

```
GTK2
```

### OS / DISTRIBUTION

Debian unstable, Linux 5.6.0-1-amd64

### SUMMARY

View a large amount of files in a foder shared over an nfs network, when closing down geeqie runs a stat on each of them (accoring to strace) - Is this really necessary? This results in the window getting frozen, and soon I get a "The program isn't responding - would you like to close it anyway?" before it soon closes by itself - this should be avoidable. I have been thinking if it would be possible to close the visible window before doing described stat to avoid the message, but I don't know if that is doable.

This is a bit like #761 , but I don't think it is related since my problem is on close-down, and not on startup.

### STEPS TO REPRODUCE

As in the summary, view a folder containing a large amount of files over nfs (in my case some 2000 files in the folder), and then you will experience the delay I describe in the summary.

**Comment by caclark** [comment]
Please go to Edit/Preferences/Behavior.
If the Save Marks On Exit is set, please try with it unset.

If it is already unset, I will have to think some more...

**Comment by gusnan** [comment]
Ohh, that seems to have been it! Thanks! Closing this bugreport. (I'll reopen if I still run into it later).

**Comment by caclark** [comment]
Using Marks really slows things down in other places. I will get around to documenting where this happens..... sometime.
