### ISSUE TITLE
What's this repo is about, if there is a repo on http://geeqie.org already

### ISSUE THREAD

**Issue by klartext** [BestImageViewer/geeqie#770]
The last commit here on github is from Feb 3.
In the geeqie.org repo, tha last commit is from May 12, so seems to be the repo where work is going on.
Is the github repo only updated for stable versions? Or switched development away from github?
Please clarify this in the README. It's not obvious, so please make it explicit.
Thanks.

**Comment by mowgli** [comment]
Am Sa den 16. Mai 2020 um 18:56 schrieb klartext:
> The last commit here on github is from Feb 3.
> In the geeqie.org repo, tha last commit is from May 12, so seems to be the repo where work is going on.
> Is the github repo only updated for stable versions? Or switched development away from github?
> Please clarify this in the README. It's not obvious, so please make it explicit.

The official reporitory is on www.geeqie.org.

Github is only used for issue tracking. The repository there is just for
convenience and is synced manually from time to time. There is no
automatic sync.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by caclark** [comment]
Warning paragraph included at top of README.
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=4800e2c1ae84d618c19ab330d53e4c528a2a000f
