### ISSUE TITLE
Huge image display issue

### ISSUE THREAD

**Issue by terrancewong** [BestImageViewer/geeqie#772]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION

```
Repository     : openSUSE-Tumbleweed-Oss
Name           : geeqie
Version        : 1.5.1-2.1
Arch           : x86_64
Vendor         : openSUSE
```

### OS / DISTRIBUTION

- Description:	openSUSE Tumbleweed
- Release:	20200528

### SUMMARY

Large image display at 1:1 has issue. zoomed 1:1.05 or 1.05:1 looks normal.

Same for tif and jpeg

### STEPS TO REPRODUCE

* screenshots

![1:1.05](https://pbs.twimg.com/media/EZkeiwfU0AAA0e9?format=jpg&name=orig)

![1.05:1](https://pbs.twimg.com/media/EZkeiwdVcAEOzh0?format=jpg&name=orig)

![1:1](https://pbs.twimg.com/media/EZkeiwcU8AAXILu?format=png&name=orig)

**Comment by caclark** [comment]
I installed openSUSE-Tumbleweed and geeqie 1.5.1-2.1, but did not see the problem.
Could you give a link to an image which shows this effect?

**Comment by terrancewong** [comment]
seems happen when image dimension > 32768.

**Comment by terrancewong** [comment]
You can make one using imagemagick

```
convert -size 38400x2400 tile:/usr/share/wallpapers/openSUSEdefault/contents/images/3840x2400.jpg result.jpg
```

**Comment by caclark** [comment]
OK, I can replicate the problem on openSUSE, but not on my normal system.
It may take a while to find the problem.

**Comment by fidergo-stephane-gourichon** [comment]
I can reproduce the problem on Xubuntu 20.04 running plain geeqie package. 

Had a random picture and used convert command line above to tile it to 38400 pixels wide. 

Indeed pressing "z" for 1:1 shows the problem. Changing to any other zoom ratio (even nearly 1:1) and the problem no longer shows. I guess there is a different code path for the 1:1 case?

**Comment by fidergo-stephane-gourichon** [comment]
32767x1079 -> no issue
32768x1079 -> reproduced
1919x38400 -> no issue
1919x65500 -> no issue

Better title: "images 32768 pixels wide or more get pixelated when shown 1:1"

**Comment by caclark** [comment]
I normally use Xubuntu.
Without GPU accel. the problem exists.
With GPU accel. there is no problem.

I suppose that is a fractional advance in knowledge of the problem. It will still take some time, I guess...

**Comment by terrancewong** [comment]
FYI  the chunk width is 128 pixels, seems related to 
```
src/renderer-tiles.c:63:#define PR_TILE_SIZE 128
```

**Comment by terrancewong** [comment]
confirmed, I wrote a replacement of `gdk_pixbuf_copy_area`, this one works fine. should submit a bug to OpenSuSE
```
1303       // quick & dirty replace
1304       int srs = gdk_pixbuf_get_rowstride (src);
1305       int drs = gdk_pixbuf_get_rowstride (dest);
1306       guchar *psrc = gdk_pixbuf_get_pixels (src);
1307       guchar *pdst = gdk_pixbuf_get_pixels (dest);
1308       printf("copy %016x to %016x", (size_t)psrc, (size_t)pdst);
1309       for(int y = 0; y < pb_h; y++)
1310         {
1311         for(int x = 0; x < pb_w; x++)
1312           {
1313           for (int c = 0; c < 3; c++) 
1314             pdst[(y * drs) + x*3 + c] = psrc[(-(int)offset_y + pb_y + y) * srs + (-(int)offset_x + pb_x+x)*3 + c];
1315           }
1316         }

```

**Comment by caclark** [comment]
The computer I use for this died yesterday, and it may be a few days before I look at it again.
Just before the system failed I concluded that the problem originated with commit 0dfeec9a9a7298d4c5389bb9 (2015-08-11).
