### ISSUE TITLE
GTK3 and the readme.md

### ISSUE THREAD

**Issue by ArielRosenfeld** [BestImageViewer/geeqie#775]
### ISSUE TYPE

* Feature Request

### GEEQIE VERSION

```
Geeqie 1.5.1
```

```
gtk2
```

### OS / DISTRIBUTION
Archlinux

### SUMMARY
The Readme.MD still describes GTK3 support as experimental, as GTK3 has been out for a while now, GTK2 hasnt had a recent update and the maintainers are asking developers to use GTK3 instead maybe its time to change the wording at least?

having asked the devs at archlinux to compile with GTK3 the cite this as the reason they are sticking to GTK2
https://bugs.archlinux.org/task/66964

### STEPS TO REPRODUCE
Read the Readme.MD

**Comment by mowgli** [comment]
Well, there are at least two problems that are known to us.
1. Mouse wheel handling is only working correct when using the libinput X driver for mouse. When using the more common evdev driver, it is broken. This is troubles, many GTK applications have an issue with by setting the `GDK_CORE_DEVICE_EVENTS` environment to one but the documentation for this environment does not allow to guess to solve that troubles.
2. There is some flickers in image display on complex displays. Maybe @colin could tell more about that.

Additional, scroll bars are somewhat broken sometimes but I believe, that has to do with the mouse wheel problem mentioned above.

It is pretty sad and frustrating that the gnome team does not care at all about that troubles even though it blocks many transitions.

**Comment by ArielRosenfeld** [comment]
1. which linux distribution doesnt use xf86-input-libinput? its supposed to be the catchall replacing every other input device.

libinput works fine for me with KDE on archlinux

2. can you list the bug of the complex displays? maybe i can test if its still valid

**Comment by caclark** [comment]
> There is some flickers in image display on complex displays. Maybe Colin could tell more about that.

This is a reference to issue #602. It is a result of a change in the way an event is handled in GTK2 and GTK3. The flicker is an annoyance, rather than a critical bug.

I have been using the GTK3 version since it first appeared in about 2012. The possibility to use the GPS map outweighs the above annoyance.

From my point of view I would say that the word "experimental" is no longer valid in connection with the GTK3 version.

If the people packaging Geeqie move to the GTK3 version, those who prefer to use GTK2 still have the possibility to do that, providing they are willing to make the effort to compile from sources.
A while ago I provided a script (unfortunately Debian only) which gives the user the choice of installing either the GTK2 or GTK3 version.

**Comment by ArielRosenfeld** [comment]
> > There is some flickers in image display on complex displays. Maybe Colin could tell more about that.
> 
> This is a reference to issue #602. It is a result of a change in the way an event is handled in GTK2 and GTK3. The flicker is an annoyance, rather than a critical bug.
> 

cannot recreate this in KDE on archlinux (Nvidia) on both the 1.5.1 and git version.

is it specific to gnome or a driver?

**Comment by caclark** [comment]
The effect is seen only when compiled with GTK3. I think the archlinux package is compiled with GTK2.
After you have compiled from sources, please check what you have compiled against e.g.
`grep gtk-3  config.log`
Then try as described in "Steps to reproduce" in #602 

It is not dependent on the graphics card.
It is because of the difference between the GTK2 "expose" event and the GTK3 "draw" event.

**Comment by ArielRosenfeld** [comment]
i checked with ldd and while you are correct about the native geeqie being gtk2 the AUR package geeqie-git is linked to gtk3

**Comment by mowgli** [comment]
Am Fr den 12. Jun 2020 um  6:29 schrieb ArielRosenfeld:
> 1. which linux distribution doesnt use xf86-input-libinput? its supposed to be the catchall replacing every other input device.

Well, libinput only support a subset of parameters you have available in
evdev.

I don't know which distributions use what. But it is always a choice of
the user which he prefers.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by caclark** [comment]
I think we have reached an impasse here, but at some time or other a decision has to be made.
Eventually GTK2 will become unsupported, and then presumably packagers like Debian will no longer include the libraries.

If the wording of the README is stopping packagers using the GTK3 version, my suggestion is to remove the "experimental" statements from the README and wait for the complaints to be made.
If there are no complaints, things will be fine. If there are specific complaints, they can be fixed.

[And then there is GTK4 which is scheduled to arrive in Autumn 2020. I started to read the GTK3 to GTK4 migration manual, but after a couple of minutes had to get a beer from the 'fridge - well, several beers. It seems to me that the GTK4 migration will be worse than the GTK3 migration.]

**Comment by mowgli** [comment]
Hi Colin,

Am Do den 18. Jun 2020 um 15:50 schrieb Colin Clark:
> I think we have reached an impasse here, but at some time or other a decision has to be made.
> Eventually GTK2 will become unsupported, and then presumably packagers like Debian will no longer include the libraries.

That is my fear. Cause of this I even thought about porting to QT. But I
think, that might be also a big project that is not realistic.

> [And then there is GTK4 which is scheduled to arrive in Autumn 2020. I started to read the GTK3 to GTK4 migration manual, but after a couple of minutes had to get a beer from the 'fridge - well, several beers. It seems to me that the GTK4 migration will be worse than the GTK3 migration.]

Couldn't we just skip from Gtk2 to Gtk4? :-)

But from your experiences I would say, that is a bad idea. ;-)

Gruß
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by caclark** [comment]
Well, I didn't hear any opposing views, so the README now states that both GTK2 and GTK3 versions are "stable".
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=c3029a4db75fc2e647ef61149e24021db4a5c4ef
