### ISSUE TITLE
Slow deduplication

### ISSUE THREAD

**Issue by installgentoo** [BestImageViewer/geeqie#777]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
Geeqie 1.5.1

```
gtk2
```

### OS / DISTRIBUTION
gentoo

### SUMMARY
When you have a lot of duplicates, upwards of thousand, deletion slows to a crawl. On 50k duplicates it takes minute+ to delete one of the duplicates. And then there are 49999 left to go.

This is obviously an issue with deduplicate view reloading info on all files after each deletion. It should probably reload once, after a command(such as deletion of seleted files) have been completed.

If you're comparing two filesets you can speed this up to ~100 files per second by clicking "compare two filesets" after deletion starts, then geeqie forgets about checking on existing files, but remembers to complete the deletion.

### STEPS TO REPRODUCE
Get a shitton of images, copy them into another dir, compare two dirs.

**Comment by JoneKone** [comment]
Still an issue, confirmed.
