### ISSUE TITLE
After clicking on one of the number keys on the keyboard - the tooltip doesn't disappear

### ISSUE THREAD

**Issue by Cosmograph** [BestImageViewer/geeqie#778]
* Bug Report(?)
Version 1.4
The number keys are set to toggle marks (I don't even know what this means). I probably accidentally clicked on one of them. But along with that (or I clicked on something else) - now a tooltip with information about the image - is shown on the screen\image; like: image name, date etc. How do I get rid of it?
(edit) It's also in single window mode now. If I open an image in a different folder - the current switches to that image.

**Comment by caclark** [comment]
Maybe you typed the "I" key, which brings up the Overlay Screen Display.
If so, disable it via the `View/Image Overlay` menu.

If not, could you post a small screenshot of the problem?

**Comment by Cosmograph** [comment]
Yes, it was View -> Image Overlay.
It's one of those things - that it's difficult to find; even though I went over all the settings after installation.
Thank you.
