### ISSUE TITLE
dangerous duplicate finder deletes original, leaves dangling symlink

### ISSUE THREAD

**Issue by btittelbach** [BestImageViewer/geeqie#782]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
Geeqie 1.5.1
```

### OS / DISTRIBUTION

GNU/Linux Ubuntu 20.04

### SUMMARY

The duplicate finder treats symlinks as normal files (tested with checksum). After searching for duplicates symlinks to images are reported as an duplicate image with the same filesize and content. This is dangerous, as the symlink only points to another file and once that actual file is deleted, the image is gone.

### STEPS TO REPRODUCE

1. Copy some images to `/tmp/test`
2. Create a subfolder `/tmp/test/selected_the_best`
3. symlink some images of `/tmp/test` into `/tmp/test/selected_the_best`
4. drag folder `/tmp/test` into duplicate finder and select "add recursively" (e.g. using checksum)
5. select first group
6. delete duplicates
7. verify that all your images are now lost

### PROPOSAL

- A safe quick fix would be to just ignore symlinks
- A better fix would be to check if a file is a symlink and then ignore it _if_ the symlink points to the 'duplicate'

**Comment by caclark** [comment]
Oh dear!

If I am looking for duplicate files, simply deleting a symbolic link to a duplicated file does not make sense to me. Although other users may have a different view.

If I have duplicate files with symlinks, I would probably want to delete the entire symlink chain that points to a duplicate file as well as the file itself. Although other users....

---

When I am looking for duplicates, I am only interested in the "real" files and not a symlink. Therefore the suggestion of ignoring symlinks seems the best solution.

If users have created symlinks, it would then up to them to find and delete broken links.

**Comment by btittelbach** [comment]
Sounds like a good solution to me. :+1: 
Deleting dangling linux symlinks afterwards is rather easy, so I think it's ok to leave this to the user afterwards.

- Example zsh:` rm -v **/*(-@)`
- Example find: `find -xtype l -exec rm {} \;`

Btw, I think this was obvious and understood but just to be 100% sure: geeqie viewer should not ignore symlinks, just the duplicate finder :-)

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=d6195e586128dcda176951f6874ba33b9a6f2abc
