### ISSUE TITLE
Broken link on http://www.geeqie.org/ to http://www.geeqie.org/web/geeqie-install-debian.sh

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [BestImageViewer/geeqie#784]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

not applicable

### OS / DISTRIBUTION

not applicable

### SUMMARY

Broken link on http://www.geeqie.org/

### STEPS TO REPRODUCE

On http://www.geeqie.org/ one can read

> For Ubuntu and other Debian-based systems, this script will download Geeqie sources, all dependencies, and compile and install Geeqie. You may also select which optional libraries to install.

with a link to http://www.geeqie.org/web/geeqie-install-debian.sh which 404's.

**Comment by caclark** [comment]
Thanks.

You can also use:
`wget https://raw.githubusercontent.com/BestImageViewer/geeqie/master/web/geeqie-install-debian.sh`

**Comment by mowgli** [comment]
Thanks, fixed.

**Comment by fidergo-stephane-gourichon** [comment]
Thanks for your quick reaction! 

Checking. Hmm, now http://www.geeqie.org/ links to http://www.geeqie.org/geeqie-install-debian.sh which still 404's.

```
curl -s http://www.geeqie.org/ | grep debian.sh

        <p>For Ubuntu and other Debian-based systems, <a href="/geeqie-install-debian.sh"> this script</a> will download Geeqie sources, all dependencies, and compile and install Geeqie. You may also select which optional libraries to install.</p>

curl -v http://www.geeqie.org/geeqie-install-debian.sh 2>&1 | grep HTTP

> GET /geeqie-install-debian.sh HTTP/1.1
< HTTP/1.1 404 Not Found
```

**Comment by mowgli** [comment]
Ah, yes, fixed. I missed that I excluded all .sh from being uploaded.
