### ISSUE TITLE
White flash on image when resizing window.

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [BestImageViewer/geeqie#787]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
/usr/bin/geeqie --version

Geeqie 1.5.1
```

> What GTK toolkit is used to compile Geeqie?

Mmh, it's from official Ubuntu 20.04 repositories.

Appears to be gtk2, see below.

```
ldd /usr/bin/geeqie | grep -i gtk

	libgtk-x11-2.0.so.0 => /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007f81b1987000)
```

### OS / DISTRIBUTION

Xubuntu 20.04, running XFCE.

### SUMMARY

Every time window is resized, the image flashes white.

### STEPS TO REPRODUCE

* Open geeqie
* Optionally open a big image. Here the geeqie logo is enough.
* Use the facilities provided by window manager to resize the window.

#### Expected

* No white flash on the image (would would it flash to white anyway?)

#### Observed

* White flashes on the image. Sometimes one, sometimes several, sometimes horizontal white streaks only.

#### Additional information

* Observed since 1.5.1 (Xubuntu 20.04).
* Never observed in previous versions (Xubuntu 19.10, Geeqie 1.4 and below).

* Happens with tools floating or not.
* Not always visible in all circumstances (for example, much less visible on small image).
* Most dramatic when image is big.
* Only the image area flashes white, not the border around it.

#### Analysis

* The problem might actually lie in some dependency not in geeqie itself. Yet it is visible in geeqie!
* Although it is only a minor annoyance here, this could be a big problem for some users as bright flashes are known to cause health incidents on some persons.

**Comment by fidergo-stephane-gourichon** [comment]
Remark that when browsing an image collection, I could not observe any white flash.

With big images, the effect is dramatic: advancing to next image is fine, resizing window cause a continuous white flicker (with interference patterns between draw order and RAM scan to send lines to monitor) on all the image area.

**Comment by caclark** [comment]
Does this still occur with the latest commit?

**Comment by fidergo-stephane-gourichon** [comment]
Hi @caclark . Thank you for your attention.

I can't observe the problem any more, neither in 1.5.1, nor in latest master 955709eb5885dd130cc47aee493d193df982a3de . I haven't change the hardware, only applied Ubuntu 20.04 update regularly. Perhaps the problem was in some dependency and was fixed there?

I guess we can close this, and reopen later if needed?
