### ISSUE TITLE
White flash on image when window gains focus, multiple flashes when loses focus

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [BestImageViewer/geeqie#788]
This issue is different from #787. I considered making it the same, but indeed it is probably a different place in code, and anyway these are to be tested separately.

### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
/usr/bin/geeqie --version

Geeqie 1.5.1
```

> What GTK toolkit is used to compile Geeqie?

Mmh, it's from official Ubuntu 20.04 repositories.

Appears to be gtk2, see below.

```
ldd /usr/bin/geeqie | grep -i gtk

	libgtk-x11-2.0.so.0 => /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007f81b1987000)
```

### OS / DISTRIBUTION

Xubuntu 20.04, running XFCE.

### SUMMARY

Every time window gains or loses focus, the image flashes white.

### STEPS TO REPRODUCE

* Open geeqie
* Optionally open a big image. Here the geeqie logo is enough.
* Click on another window.
* Click again on image window.

The windows don't have to overlap. That is: *no redraw event is needed at all* in the circumstances that cause the bug.

#### Expected

* No white flash on the image (why would would it flash to white on *focus change* anyway?)

#### Observed

* White flashes on the image. Sometimes one, sometimes several, sometimes horizontal white streaks only.

#### Additional information

* Observed since 1.5.1 (Xubuntu 20.04).
* Never observed in previous versions (Xubuntu 19.10, Geeqie 1.4 and below).

* Happens with tools floating or not.
* Not always visible in all circumstances (for example, much less visible on small image).
* Most dramatic when image is big. 
* Only the image area flashes white, not the border around it.
* Most dramatic when *losing* focus, probably 3-4 flashes, much more than when gaining focus.

#### Analysis

* The problem might actually lie in some dependency not in geeqie itself. Yet it is visible in geeqie!
* Although it is only a minor annoyance here, this could be a big problem for some users as bright flashes are known to cause health incidents on some persons.

**Comment by caclark** [comment]
Does this still occur with the latest commit?

**Comment by fidergo-stephane-gourichon** [comment]
Hi @caclark . Thank you for your attention.

I can't observe the problem any more, neither in 1.5.1, nor in latest master 955709e . I haven't change the hardware, only applied Ubuntu 20.04 update regularly. Perhaps the problem was in some dependency and was fixed there?

I guess we can close this, and reopen later if needed?
