### ISSUE TITLE
Wish disentangled "guidelines" image overlay hotkey, not off/parameters/parameters+histograms/guidelines

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [BestImageViewer/geeqie#790]
### ISSUE TYPE

* Feature Request

### GEEQIE VERSION

```
/usr/bin/geeqie --version

Geeqie 1.5.1
```

> What GTK toolkit is used to compile Geeqie?

Mmh, it's from official Ubuntu 20.04 repositories.

Appears to be gtk2, see below.

```
ldd /usr/bin/geeqie | grep -i gtk

	libgtk-x11-2.0.so.0 => /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007f81b1987000)
```

### OS / DISTRIBUTION

Xubuntu 20.04, running XFCE. 

### SUMMARY

Wish hotkey to enable/disable capture parameters (the rectangle that shows f stops, shutter speed, ISO, etc) was not mixed with histogram and guidelines display.

### STEPS TO REPRODUCE

* Launch geeqie
* Look for a key to see image capture parameters, find that key `i` is designated for this.
* Press `i` key (the 'i' of 'icon') repeatedly.

#### Expected

* As in previous versions of geeqie, having 3 states is okay: nothing, parameters, parameters+histogram.

#### Observed

* A fourth state has appeared: guidelines. Why not.
* Whereas the 3 other states are quick, this fourth state causes the whole picture to flash white and slowly draw again with a double rectangle pattern, slowly, much more slowly that an image normally appears, maybe 5-10 times more slowly.
* Found no way to just toggle histogram+parameters on/off, and *not* display that strange double rectangle patterns named "guidelines" which displays really slowly

### Discussion

* What is the point of this "guidelines" pattern? Does it really belong here?
* Its addition is an annoyance: it displays slowly, causes the whole picture to repaint slowly, plus that white flash. 
* Unless the whole world needs this as much as the other parameters + histogram (I doubt it), perhaps the guidelines would rather have their own hotkey.
* Keys are reassignable easily, but end user cannot disentangle this "guideline" state from other states traditionally associated with the 'i' key.

**Comment by fidergo-stephane-gourichon** [comment]
The "guideline" state is still observed with 1.5.1, but no longer observed with 955709eb5885dd130cc47aee493d193df982a3de . No more white flash in both cases.

**Comment by fidergo-stephane-gourichon** [comment]
The annoyance was mostly that the guidelines were very slow to draw. Slow like one second whereas I can advance and fully see 5-30 images per second depending on the image definition.

All in all, as I'm not interested in the guidelines, current master fixed this "wish".

**Comment by caclark** [comment]
Option deleted in 89c5590a2
