### ISSUE TITLE
geeqie does lots of potentially slow work at exit time

### ISSUE THREAD

**Issue by dkogan** [BestImageViewer/geeqie#792]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie d39c61fd
```

```
     Config results:
    -=-=-=-=-=-=-=-=-

Package:
  Name:          geeqie
  Version:       d39c61fd

Architecture:
  UNIX:          yes
  Win32:         no (native: no)

Flags:
  Geeqie:        
  DEFS:          -DHAVE_CONFIG_H
  CPPFLAGS:      
  CFLAGS:         -Werror -Wno-error=deprecated-declarations -Wno-error=sign-compare -Wno-error=return-type
  CXXFLAGS:      -g -O2
  Gtk:           -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16
  Glib:          -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
  Thread:        -lgthread-2.0 -pthread -lglib-2.0
  Others:        -ljpeg -ltiff -llcms2 -lexiv2     -llua5.3

Localization:
  NLS support:   yes
  LINGUAS:        ar be bg ca cs da de el en_GB eo es et eu fi fr hu id it ja ko nb nl pl pt_BR ro ru sk sl sr@latin sr sv th tlh tr uk vi zh_CN zh_TW

Settings:
  Developer:     no
  Debug flags:   no
  Debug log:     yes
  Deprecated:    no

Support:
  LCMS:          yes
  Exiv2:         yes
  Lirc:          no
  Clutter:       disabled
  Libchamplain:         disabled
  Libchamplain-gtk:     disabled
  Lua:           yes
  FFmpegthumbnailer:    no
  Pdf:           disabled
  HEIF:          no
  WebP:          yes
  DjVu:          yes
  J2K:           yes

Documentation:
  Doxygen:       /usr/bin/doxygen
  doc-tool:      

```

### OS / DISTRIBUTION
Debian/sid

### SUMMARY
Hi. When I close geeqie it likes to issue lots of stat() calls on all images in the directory it's looking at. If there are a lot of images and/or if the disk is slow, this can take a very long time, and I end up killing geeqie instead of waiting for it to exit itself. This happens even if I'm not looking at, or interacting with the other images at all.

### STEPS TO REPRODUCE
1. ```geeqie image.jpg``` in a directory where there are lots of other images. I'm not looking at the other images; they're just there.
2. Close geeqie

geeqie now tries to exit, and the graphical window stops responding. But the window doesn't go away, and I don't get the console back until it can call stat() on every images in the directory that I didn't look at. I don't know what it's trying to do, but it shouldn't be doing anything at all with images I didn't ask it to think about.

Note that this is not a recent regression.

Thanks

**Comment by gusnan** [comment]
Sounds similar to https://github.com/BestImageViewer/geeqie/issues/768.

**Comment by dkogan** [comment]
Yes, that's the same issue. Thanks for pointing that out. I didn't find that earlier. I'm closing the report.
