### ISSUE TITLE
Release a new version so ditributions can test the code, please

### ISSUE THREAD

**Issue by ArielRosenfeld** [BestImageViewer/geeqie#793]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
```
Geeqie 7eda2f82

```

```
GTK3
```

### SUMMARY
It has been a year since the last release and GTK3 got many fixes that will allow distributions to use GTK3

A Timed release would be nice so distributions that only use official releases can use and test the new features

### STEPS TO REPRODUCE
if you ask for a GTK3 version of geeqie distributions will tell you to wait for a release see https://bugs.archlinux.org/task/66964

**Comment by caclark** [comment]
v1.7.1
