### ISSUE TITLE
Restored windows all show the same location

### ISSUE THREAD

**Issue by madduck** [BestImageViewer/geeqie#796]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.5.1+git20200723
```

### OS / DISTRIBUTION
Debian unstable

### SUMMARY
On startup, geeqie tries to restore all instances of the previous run (also see #795). But it does not restore location, and instead shows the same folder in all of them.

Ideally, a fix to #795 would mean that there is no concept of a session anymore like there seems to be, and that a window might be restored, but not multiple ones at the same time.

Otherwise, the only sensible thing to do would be to restore the previous windows with their previous locations, and add a new window for the context in which geeqie was started.

### STEPS TO REPRODUCE

1. Reproduce the steps for #795.
2. Run `geeqie folder3`, and note how two windows open, and both will show `folder3`.

**Comment by caclark** [comment]
Menu item `edit/configure this window` allows the startup directory to be `no change` or `restore last path` or `home path`

As you note, when you start Geeqie from the command line and provide a directory name, that will override the configuration setup for all windows.

I would prefer the solution that a command line directory overrides the "main" window, but not the subsidiary windows.

**Comment by madduck** [comment]
I am not sure why configuring the startup directory of any particular window would help. Wouldn't this need to be a global preference?

Even if I start Geeqie without a command line argument, it'll open multiple windows, all pointing to the home directory.

**Comment by caclark** [comment]
This issue is partially addressed in comit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=0b0e48bc49ef3fe725cceaa58d725ce9cc6da60f
