### ISSUE TITLE
In-window sizing wrongly crops menu/toolbox

### ISSUE THREAD

**Issue by madduck** [BestImageViewer/geeqie#797]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.5.1+git20200723
```

### OS / DISTRIBUTION
Debian unstable

### SUMMARY
If the window manager does not allow geeqie to restore window dimensions but e.g. forces the window into a grid, then it may be such that the toolbox and menu get cropped on the left, as shown here:

![image](https://user-images.githubusercontent.com/195073/89966703-e4862d00-dca3-11ea-964e-08f298f5d7bf.png)

Increasing the width of the toolbox makes the menu appear in full, and also prevents the cropping:

![image](https://user-images.githubusercontent.com/195073/89966887-3e86f280-dca4-11ea-918b-a728bd15ab9e.png)

Arguably though, the toolbox should always have a minimum size such that cropping is not necessary.

**Comment by caclark** [comment]
> Arguably though, the toolbox should always have a minimum size such that cropping is not necessary.

I am not too sure about that. I think the user should be allowed to minimize panes as they wish.

The menus/toolbar can be shifted to the top of the window with the option `edit/preferences/general/expand menu and toolbar`. 
If you do not use the toolbar, it can be hidden with `view/files and folders/hide toolbar`

**Comment by madduck** [comment]
Thanks, that works in my case.
