### ISSUE TITLE
no image under wayland

### ISSUE THREAD

**Issue by 532910** [BestImageViewer/geeqie#799]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.5.1+git20200808-2a27c9ab
```

### OS / DISTRIBUTION
debian sid

### SUMMARY
No image is shown. No errors on console. Previews are shown.

### STEPS TO REPRODUCE
just run geeqie on wayland

**Comment by gusnan** [comment]
What if you go to the menu Edit->Preferences -> Image tab, and change the checkbox "Use GPU acceleration via Clutter library" and restart geeqie?

**Comment by 532910** [comment]
It works fine with GPU acceleration via Clutter.

**Comment by 532910** [comment]
Why is it closed? I still believe this is an issue that should be fixed.

**Comment by caclark** [comment]
Fixed in commit 89c5590
