### ISSUE TITLE
Duplicate finder 'show thumbnails' bug, needs turning off & on

### ISSUE THREAD

**Issue by SimonDedman** [BestImageViewer/geeqie#800]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
1.5.1
```

### GTK toolkit
```
Ubuntu default
```

### OS / DISTRIBUTION
Xubuntu 20.04

### SUMMARY
Duplicate finder: 'show thumbnails' works, but if it's already turned on when you run a dupe search, thumbnails won't be shown. One needs to click the box off then on to force them to show. Not a biggie, but worth mentioning while I'm on here for something else!
Cheers!

**Comment by caclark** [comment]
I don't see that effect.
Does this happen with all types of duplicate search?

**Comment by SimonDedman** [comment]
Hiya, example:

![image](https://user-images.githubusercontent.com/4599748/91649411-a3727480-ea28-11ea-8b70-1eccce98bef3.png)

> Does this happen with all types of duplicate search?

Not sure, I only ever compare similarity. LMK if there's anything I can send in terms of build info that might help diagnose if there's a difference between the performance of our two builds.

Cheers!

Simon

**Comment by caclark** [comment]
Ah, sorry. I see the bug now.
It was fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=9c6d21c5ba8d55aa11b70820cd20ec0d5421d3f1
