### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by AMDmi3** [BestImageViewer/geeqie#802]
I, as a maintainer of FreeBSD geeqie port, was just asked by a user to package the latest git version of geeqie because a user needs HEIF support. The previous official release was a year ago, isn't it time to publish new official release so everyone could benefit of new features?

Also wanted to note that github repository misses latest commits from www.geeqie.org/geeqie.git and 1.5.1 tag.

**Comment by gusnan** [comment]
Debian is preparing for the next release - Debian 11 - full freeze in February; it would be great to have a new fresh release before that, and not just a git snapshot. Please make releases more often, it greatly helps downstream distributions.

**Comment by AMDmi3** [comment]
@caclark

**Comment by caclark** [comment]
> Debian is preparing for the next release - Debian 11 - full freeze in February; it would be great to have a new fresh release before that, and not just a git snapshot

The concept of a "release" does not exist in Geeqie. Perhaps in the days of GQview that happened.
But right now the process of "requirement - implementation - test - approval" does not happen - there is no-one to do that.
No objectives are set. It is just a matter of continuous updates, bug creation, and bug fixes.

If it is simply a matter of including a branch with the tag v1.6, I can do that. Anything more complex is getting to be unlikely.

**Comment by mauro3** [comment]
If I remember correctly, head to  https://github.com/BestImageViewer/geeqie/releases and "Draft a new release".  As far as I'm concerned (using a rolling-release distro) no "requirement - implementation - test - approval" is needed.  Maybe avoid tagging right after some major update landed as then the chances of new bugs is higher; but then you can always tag a bug-fix release. Tnx!

**Comment by caclark** [comment]
Perhaps there could be a discussion about if there should be a formalised release timetable for Geegie in the future e.g.

fixed interval
interval relative to an e.g. Debian/Ubuntu release
only after signifiant change (and "significant" is TBD)
only after enough people complain for a long period of time

I'm in favour of the fourth option...

[
In terms of getting something halfway between a Debian release and compiling from source code, I am hopeful that AppImages 
will fill the gap by permitting users to download frequently updated images.  (snaps and flatpaks both have other problems).
Unfortunately I don't understand the documentation.
This would be an advantage as it might increase the number of people bug finding between Debian-style releases.
]

**Comment by AMDmi3** [comment]
> If it is simply a matter of including a branch with the tag v1.6, I can do that.

If the master branch is stable enough, even random regular tagging would probably be OK. The thing is that if you don't tag, distros will either start packaging git snapshots, introduce their own incompatible versioning schemes, which will lead to a mess (no ability to tell which repository has up to date version, which contains a vulnerability or bug and which has it fixed), or don't update geeqie at all. Neither case benefits geeqie, maintainers or users.

**Comment by mowgli** [comment]
Hi Folks,

Am Di den 10. Nov 2020 um 12:20 schrieb Colin Clark:
> > Debian is preparing for the next release - Debian 11 - full freeze in February; it would be great to have a new fresh release before that, and not just a git snapshot
> 
> The concept of a "release" does not exist in Geeqie. Perhaps in the days of GQview that happened.
> But right now the process of "requirement - implementation - test - approval" does not happen - there is no-one to do that.
> No objectives are set. It is just a matter of continuous updates, bug creation, and bug fixes.
> 
> If it is simply a matter of including a branch with the tag v1.6, I can do that. Anything more complex is getting to be unlikely.

First a big thank to Colin to keep the development up. After myself
quasi retirement due to lack of time (started to study again), he is the
only one left. And he does a very good job.

If it come to release, I did that process in the past and it takes some
time. Especially the collection of new features takes the most time.

I could do that again but I would need help for writing the new features
list.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by caclark** [comment]
Hello Klaus - thanks for the help. A lack of time is not a problem for me, but a lack of understanding of git is.
My idea of a repository is a room with filing cabinets.

Attached is a proposal for the list of changes. If you need something more please let me know.
[NEWS.gz](https://github.com/BestImageViewer/geeqie/files/5531440/NEWS.gz)

**Comment by mowgli** [comment]
Hi Colin,

Am Do den 12. Nov 2020 um 16:12 schrieb Colin Clark:
> Hello Klaus - thanks for the help. A lack of time is not a problem for me, but a lack of understanding of git is.

For me it is the complete way around. :-)

Git is not hard and my tool in any curcumstances in life.

I will prepare a release from the proposal.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by mowgli** [comment]
Just released v1.6
