### ISSUE TITLE
Extra underscore in toolbar.c

### ISSUE THREAD

**Issue by jose1711** [BestImageViewer/geeqie#809]
Not sure but I think the "_" in 
https://github.com/BestImageViewer/geeqie/blob/0ff5c85b082fa2b1dc578807fac8dbfd9b93421c/src/toolbar.c#L133
is redundant.

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=f2adc39381f3a2e46366f13190001367fa996cb8
