### ISSUE TITLE
The --enable-debug-flags option results in compile errors

### ISSUE THREAD

**Issue by caclark** [BestImageViewer/geeqie#815]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
Geeqie 1.5.1+git20200904-0ff5c85b

```

### STEPS TO REPRODUCE

Execute:
`./autogen.sh  --enable-debug-flags`
`make`

**Comment by gusnan** [comment]
I am taking a look at this - I'll come back with a pull request.

**Comment by gusnan** [comment]
You can close this issue, it was fixed by the pull-request above.
