### ISSUE TITLE
Apt & Git installs lack EXIV2 etc support; debian install script error

### ISSUE THREAD

**Issue by SimonDedman** [BestImageViewer/geeqie#817]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
1.5.1+git20200824-5f2afc4b
```

```
Config results:
    -=-=-=-=-=-=-=-=-

Package:
  Name:          geeqie
  Version:       1.5.1+git20201001-f8dcb10b

Architecture:
  UNIX:          yes
  Win32:         no (native: no)

Flags:
  Geeqie:        
  DEFS:          -DHAVE_CONFIG_H
  CPPFLAGS:      
  CFLAGS:         -Werror -Wno-error=deprecated-declarations -Wno-error=sign-compare -Wno-error=return-type
  CXXFLAGS:      -g -O2
  Gtk:           -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread 
  Glib:          -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include 
  Thread:        -L/usr/lib/x86_64-linux-gnu -lgthread-2.0 -pthread -lglib-2.0 
  Others:	 -ljpeg -ltiff       

Localization:
  NLS support:   yes
  LINGUAS:        ar be bg ca cs da de el en_GB eo es et eu fi fr hu id it ja ko nb nl pl pt_BR ro ru sk sl sr@latin sr sv th tlh tr uk vi zh_CN zh_TW

Settings:
  Developer:     no
  Debug flags:   no
  Debug log:     yes
  Deprecated:    no

Support:
  LCMS:          no
  Exiv2:	 no
  Lirc:          no
  Clutter:       no
  Libchamplain:		disabled
  Libchamplain-gtk:	disabled
  Lua:	         no
  FFmpegthumbnailer:	no
  Pdf:	         no
  HEIF:	         no
  WebP:	         yes
  DjVu:	         no
  J2K:	         yes

Documentation:
  Doxygen:       
  doc-tool:      /usr/bin/yelp-build

```

### OS / DISTRIBUTION
Xubuntu 20.04

### SUMMARY
Installing with git clone or apt results in no support for exiv2 & various others. Trying the geeqie-install-debian.sh script fails:
./geeqie-install-debian.sh: 21: Syntax error: "(" unexpected
Is there a straightforward way to address this? Just hunt down all the dependencies and install from source one by one?
Thanks!

**Comment by caclark** [comment]
I cannot replicate this fault.
>  Just hunt down all the dependencies and install from source one by one?

The install script contains a list of all the dependencies that are needed, if you wish to follow that route.

The following command will re-download the script:
`wget https://raw.githubusercontent.com/BestImageViewer/geeqie/master/web/geeqie-install-debian.sh`

Also:
`./geeqie-install-debian.sh --version` should show "2019-12-30".
Which version is shown for your installation?

**Comment by SimonDedman** [comment]
Thanks Colin.

`./geeqie-install-debian.sh --version` gives permission denied, but it's 2019-07-22, downloaded from http://www.geeqie.org/ last night.

The new version gives the same error, just at line 20 now. It's `sh ./geeqie-install-debian.sh` right?

Thanks again.

**Comment by caclark** [comment]
I think that the execute bit is not set for the file. Try:
`chmod +x ./geeqie-install-debian.sh`

And then:
` ./geeqie-install-debian.sh`

This extra action is missing from the download instructions -  to be fixed, sometime.

**Comment by mowgli** [comment]
Hi Simon,

Am Di den  6. Okt 2020 um 16:19 schrieb Simon Dedman:
> `./geeqie-install-debian.sh --version` gives permission denied, but it's 2019-07-22, downloaded from http://www.geeqie.org/ last night.

Then you did not make the script executable.

> The new version gives the same error, just at line 20 now. It's `sh ./geeqie-install-debian.sh` right?

No, that is wrong. sh (/bin/sh) on debian systems is a dash which does
not have the features needed for the script.

The script therefor runs under another shell if used proper.

Regards
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by SimonDedman** [comment]
Beautiful, thanks chaps, sorry to have bothered you. Cheers again!
