### ISSUE TITLE
Latest version Cant' display the DNG files, previous were OK

### ISSUE THREAD

**Issue by githubrunbyidiotsthatforcecreateaccnts** [BestImageViewer/geeqie#818]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.5.1
```

### OS / DISTRIBUTION
ununtu focal LTS

### SUMMARY
DNG files are not displayed, no thumbnails in preview, chechered pattern in image view window

### STEPS TO REPRODUCE
open DNG file

filecache.c:file_cache_get:89:cache miss: fc=0x564beb1e1d10 /mnt/PhotosRaw/DJIDrone/100MEDIA/DJI_0014.DNG
filecache.c:file_cache_put:123:cache add: fc=0x564beb1e1d10 /mnt/PhotosRaw/DJIDrone/100MEDIA/DJI_0014.DNG
filedata.c:file_data_ref_debug:682:file_data_ref fd=0x564beb51b3a0 (5): '/mnt/PhotosRaw/DJIDrone/100MEDIA/DJI_0014.DNG' @ filecache.c:125
image-load.c:image_loader_setup_source:808:Usable reduced size (preview) image loaded from file /mnt/PhotosRaw/DJIDrone/100MEDIA/DJI_0014.DNG
image-load.c:image_loader_start_thread:1080:Thread pool num threads: 1
image-load.c:image_loader_setup_loader:645:Using custom tiff loader
JPEGPreDecode: Improper JPEG sampling factors 2,1
Apparently should be 2,2..
renderer-tiles.c:rt_queue_schedule_next_draw:1548:redraw priority: 2pass
image.c:image_read_ahead_done_cb:696:   32.089974 (+00000.969162) read ahead done for :/mnt/PhotosRaw/DJIDrone/100MEDIA/DJI_0014.DNG
filecache.c:file_cache_get:89:cache miss: fc=0x564beb1e2ff0 /mnt/PhotosRaw/DJIDrone/100MEDIA/DJI_0014.DNG
filecache.c:file_cache_put:123:cache add: fc=0x564beb1e2ff0 /mnt/PhotosRaw/DJIDrone/100MEDIA/DJI_0014.DNG
filedata.c:file_data_ref_debug:682:file_data_ref fd=0x564beb51b3a0 (6): '/mnt/PhotosRaw/DJIDrone/100MEDIA/DJI_0014.DNG' @ filecache.c:125
image.c:image_complete_util:285:   32.090075 (+00000.000101) image load completed "/mnt/PhotosRaw/DJIDrone/100MEDIA/DJI_0014.DNG" (preload)
![zScreenshot from 2020-10-09 16-49-34](https://user-images.githubusercontent.com/72613762/95591219-af9e1880-0a4f-11eb-9825-3b552f1c91e1.png)

**Comment by caclark** [comment]
Geeqie displays some .DNG samples form http://www.rawsamples.ch.
Can you upload a sample that fails? (Try gzip on the file before uploading)

**Comment by githubrunbyidiotsthatforcecreateaccnts** [comment]
> Geeqie displays some .DNG samples

Not only that, it did display them in previous version... The file in question attached. Thanks!
[DJI_0014.DNG.gz](https://github.com/BestImageViewer/geeqie/files/5355553/DJI_0014.DNG.gz)

**Comment by caclark** [comment]
> Not only that, it did display them in previous version

May I ask if images from that same camera were displayed in a previous version of Geeqie, and if so which version - e.g. v1.5, v1.4 ?

Thanks....
