### ISSUE TITLE
Turning off mouseover info

### ISSUE THREAD

**Issue by codesterribly** [BestImageViewer/geeqie#819]
* Feature Request

Geeqie 1.5+git20200904-0ff5c85b

### SUMMARY

I would like the ability to turn off mouseover info, so no file modification date, size, etc. when I am moving around the window.

Thank you.

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=4d5f032ecf0466198e19f80cad1630614c2bf3d4

The tooltip seems redundant, so is removed.
