### ISSUE TITLE
Un-full-screen doesn't work. Regression.

### ISSUE THREAD

**Issue by dkogan** [BestImageViewer/geeqie#821]
* Bug Report

### GEEQIE VERSION
I observe this in Debian/testing and in the git HEAD:
```
Geeqie 1.5.1+git20200808-2a27c9ab
Geeqie 1.5.1+git20201001-f8dcb10b
```
I do NOT observe this in Debian/stable:
```
Geeqie 1.4+git20190121+431adf32
```

Toolkit:
```
gtk3
```

### OS / DISTRIBUTION
Debian/sid

### SUMMARY
I observe this in my fairly obscure window manager (notion), but this used to work for many years, and I would like it to keep working.

'f' works to go to full-screen. 'f' again should move geeqie back to the standalone window in the same workspace we were at. Instead, it is moved to its own workspace (where it remains full-screened), and this workspace isn't selected. Instead we go back to the terminal window where geeqie was launched. The meaning of "workspace" is window-manager specific, but if we could revisit the code touching the full-screen logic, that'd be nice. Let me know if I should bisect this.

### STEPS TO REPRODUCE

- 'f' to full-screen geeqie. This works for me
- 'f' again should go back to where we were. Instead I get something completely different (see above description)

**Comment by caclark** [comment]
I am not able to replicate this problem.

> Let me know if I should bisect this.

It would be helpful to know which commit changed things.

**Comment by dkogan** [comment]
Hi.

> I am not able to replicate this problem.

I imagine this is window-manager specific. It would be interesting to
try on a less-obscure tiling wm. In any case, the offending commit is
this:

  https://github.com/BestImageViewer/geeqie/commit/bcd783c02

It flips a really old switch around some really old code.

Thanks

**Comment by caclark** [comment]
> I imagine this is window-manager specific. 

I had installed Notion, but didn't see a problem (apart from culture shock), so the underlying reason must be elsewhere.
Is there anything else that might have an influence ? (e.g. I use Nvidia cards)

**Comment by dkogan** [comment]
Hmmm. I just ran some experiments on a separate box. I tried i3 and awesome (two other tiling WMs), and they look like they're working ok, although I have no idea how to use them. 

I then went back to notion in Debian/stable (same as the one in Debian/sid today). And the geeqie in Debian/testing (recent-enough to show the issue). I blew away the configuration: `rm -rf ~/.notion`. I started X, and I get two panes, with some help displayed on the right. I press F12, type `bash` and press TAB and then press ENTER. And it gives me a terminal. Then I `geeqie whatever.jpg`. This comes up correctly. I press `f`, and it goes full-screen correctly. Then I press `f` again, and it pops back to the terminal used to start geeqie, and the geeqie goes somewhere else. This is not what you're seeing?

**Comment by caclark** [comment]
I have just noticed that the original change request arrived by email, and is not listed here. So I will add it  here for completeness:

> Geeqie shows the original main window in the list of windows while alt-
tabbing in Gnome as a blank window. This is an annoyance since if you
open multiple windows in geeqie and fullscreen then you will get an
extra window for each one.
The geeqie source code contains an unused #ifdef for solving this
problem by hiding the original main window while in full screen.

I see that you are compiling from sources. Could you re-comment the line in fullscreen.h, and check if the result is ok?
If that works I will include a preference option to enable/disable it. That will be a lot less effort than me trying to find the reason for this.
(I will perhaps include another tab in Preferences for "Obscure and rarely used" options).

**Comment by dkogan** [comment]
Yes, that line in fullscreen.h is the culprit.

Do you have an understanding of how window managers work here? I don't know nearly enough to comment whether geeqie or notion are doing something wrong. Do you know if other applications that have full-screen modes cause the same GNOME annoyance described in the email you just posted?

**Comment by caclark** [comment]
> Do you have an understanding of how window managers work here

I know nothing....
The advantage of open systems is that the users can do what they want - and unfortunately they do so at every opportunity! Different window managers, distributions, colour schemes and any number of other things.
It is not possible for a tiny project like Geeqie have a test setup to cover all the possibilities, let alone make the code work everywhere, every time.
Windows and Mac developers have an easy life - although they probably complain about users too :-)

If having another option solves the problem, that is the way to go (and don't look too closely at the Geeqie code - there are more than a few hack-arounds in there besides this one).

**Comment by dkogan** [comment]
Another option is to unconditionally put the #ifdef back to what it was :)

The #ifdef and the thing they protect were added to the git in the initial cvs import in 2005, so we'll probably not know why the author chose to add this switch, but leave it off. I can imagine that the author knew that this would cause some problem in some cases, and that this is what we're seeing.

It would be interesting to see if the issue that was resolved by flipping this switch exists in other tools, and if not, to see how they resolve it. Do you use gnome and see the alt-tab gnome issue with other tools? Off the top of my head, media players (vlc, mpv, ...) and media viewers (mupdf, ...) have the 'f'-to-fullscreen functionality, and they all work here, with notion.

**Comment by caclark** [comment]
> Another option is to unconditionally put the #ifdef back to what it was

The problem of Geeqie windows appearing twice when alt-tabbing needs to be fixed, so reverting is not a good way.
I have implemented a user-definable option in `Edit/Preferences/Behaviour`

http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=1e0d4128c17abf22333ee828ec86a83a36827bcf
