### ISSUE TITLE
Installation failed - gdk-pixbuf-query-loaders: command not found

### ISSUE THREAD

**Issue by weirdAndi** [BestImageViewer/geeqie#824]
Hi,

I tried to install geeqie with the .sh-script for Ubuntu  from http://www.geeqie.org/ and failed.

an error occured in terminal:

_andreas@andreas-TUX:/home$ sudo ./geeqie-install-debian.sh
                                                          ./geeqie-install-debian.sh: Zeile 529: gdk-pixbuf-query-loaders: Befehl nicht gefunden  (means command not found)
./geeqie-install-debian.sh: Zeile 542: gdk-pixbuf-query-loaders: Befehl nicht gefunden
./geeqie-install-debian.sh: Zeile 554: gdk-pixbuf-query-loaders: Befehl nicht gefunden
andreas@andreas-TUX:/home$_ 

What's confusing is, that the command already appeared some lines above, without an error.
What to do?

Thanks for help.
Andi

geeqie 1.5.1
Kernel: 5.4.0-53-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/devolo-updates.list 
           1: deb http: //update.devolo.com/linux/apt/ stable main
           Active apt repos in: /etc/apt/sources.list.d/mono-official-stable.list 
           1: deb https: //download.mono-project.com/repo/ubuntu stable-focal main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //ftp-stud.hs-esslingen.de/pub/Mirrors/packages.linuxmint.com ulyana main upstream import backport
           2: deb http: //ftp.halifax.rwth-aachen.de/ubuntu focal main restricted universe multiverse
           3: deb http: //ftp.halifax.rwth-aachen.de/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //ftp.halifax.rwth-aachen.de/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner

**Comment by caclark** [comment]
Ah, sorry. The version of this script on geeqie.org is out of date.
However by running that script, you have downloaded the latest version. You may run the downloaded version.
e.g.
`./geeqie-install-debian.sh    # you have already done this`
`cd geeqie                            # the latest files from the repo. have been downloaded here`
`./geeqie-install-debian.sh   # this is the up-to-date version`
