### ISSUE TITLE
how to default to opening "." when no arguments present

### ISSUE THREAD

**Issue by archenemies** [BestImageViewer/geeqie#828]
### ISSUE TYPE

* Feature Request

### GEEQIE VERSION

```
$ geeqie --version
Geeqie 1.5.1
```

### SUMMARY

When I start Geeqie with no arguments, it seems to default to opening a folder of pictures which is already open in another running Geeqie istance. I'd rather have it open the current directory `.` by default. Has this behavior changed recently, or was it always like this?

**Comment by caclark** [comment]
This seems to be fixed, but I don't know when.
