### ISSUE TITLE
Geeqie remembers desktop

### ISSUE THREAD

**Issue by xhsdf** [BestImageViewer/geeqie#832]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
1.6.1 from the Arch repos

### OS / DISTRIBUTION
up-tp-date Arch Linux with Openbox

### SUMMARY
Geeqie now opens on the virtual desktop it was last used on, making it pretty much unusable.

### STEPS TO REPRODUCE
1. Open image on desktop 1
2. Close Geeqie
3. Open image on desktop 2
4. Sadness

**Comment by caclark** [comment]
Until this gets fixed, you can go to `Edit/Preferences/Windows` and de-select `Remember window positions`.

**Comment by xhsdf** [comment]
Well, I want it to remember the position. I'll just keep using 1.5.1 for now.
1.6.1 is also slow and the menu is broken.
