### ISSUE TITLE
Geeqie window opens in random/arbitrary workspace

### ISSUE THREAD

**Issue by virati** [BestImageViewer/geeqie#835]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
Geeqie 1.6

GTK3 1:3.24.24-1

### OS / DISTRIBUTION
Arch Linux, i3-wm

### SUMMARY
When starting geeqie (from terminal or dmenu) geeqie alway moves itself to either workspace 0 or 2, instead of previous behavior where it opens in the active workspace.

### STEPS TO REPRODUCE
'> geeqie'
Observe window briefly flash in the current, active workspace before disappearing to either 0 or 2.

**Comment by caclark** [comment]
This is probably the same as #832 - Geeqie opening in the last workspace used.
A fix has been committed.
