### ISSUE TITLE
Tag multiple pictures at once

### ISSUE THREAD

**Issue by london111** [BestImageViewer/geeqie#839]
If I select multiple pictures and add a tag, it only adds the tag to one picture. Is there another way to add a tag to multiple pictures?

**Comment by mowgli** [comment]
Hi,

Am Sa den 26. Dez 2020 um  9:50 schrieb london111:
> If I select multiple pictures and add a tag, it only adds the tag to one picture. Is there another way to add a tag to multiple pictures? 

There is, just right click on the tag and you see it.

Gruß
   Klaus
-- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C

**Comment by london111** [comment]
Ok, thanks!
