### ISSUE TITLE
Control image rotation in pan view

### ISSUE THREAD

**Issue by london111** [BestImageViewer/geeqie#845]
If I browse images in pan view and click on an image to show it, it sometimes shows up in the wrong orientation. Is there any way to control the rotation in this view? In particular show it auto rotated according to the exif information?

**Comment by caclark** [comment]
>  Is there any way to control the rotation in this view? In particular show it auto rotated according to the exif information?

Unfortunately not.
This problem is also mentioned, in a way, in #462
