### ISSUE TITLE
Image flickers when a window/menu is opened/closed above Geeqie's window

### ISSUE THREAD

**Issue by pezcurrel** [BestImageViewer/geeqie#848]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
Geeqie 1.6
```

### OS / DISTRIBUTION

Up-to-date Arch Linux

### SUMMARY

With GPU acceleration disabled, image flickers when a window or menu is opened/closed above Geeqie's window (with GPU acceleration enabled it doesn't, but I don't want to use GPU acceleration since image quality is much worse when zoomed).

### STEPS TO REPRODUCE

1. Open an image in Geeqie
2. Open (or close) any of Geeqie's menus, or another program's window: image flickers

**Comment by caclark** [comment]
> With GPU acceleration disabled, image flickers when a window or menu is opened/closed above Geeqie's window

This problem is mentioned in other bug reports - but I don't recall which ones at the moment.
The problem originates in the differing way in which certain signals are handled in GTK2 and GTK3.
(The relevant source files are renderer-clutter.c and renderer-tiles.c)
It is unlikely that this bug will get fixed.

I am interested in the problem with image quality when zoomed, as I cannot replicate it.
Could you post a couple of screenshots which show the difference - and with which settings you used?

**Comment by pezcurrel** [comment]
> It is unlikely that this bug will get fixed.

:'(

> I am interested in the problem with image quality when zoomed, as I cannot replicate it.
> Could you post a couple of screenshots which show the difference - and with which settings you used?

Ok, see the attachments.
![geeqie_with_gpu_accel](https://user-images.githubusercontent.com/33592962/106362413-ff685e80-6322-11eb-9e90-b6bd9241d0d9.png)
![geeqie_with_gpu_accel-settings](https://user-images.githubusercontent.com/33592962/106362450-27f05880-6323-11eb-909e-408edcea6171.png)
![geeqie_without_gpu_accel](https://user-images.githubusercontent.com/33592962/106362455-2c1c7600-6323-11eb-9773-d07c8f0c44f3.png)
![geeqie_without_gpu_accel-settings](https://user-images.githubusercontent.com/33592962/106362478-51a97f80-6323-11eb-88a5-8a47e1a7c865.png)

**Comment by joeytwiddle** [comment]
Note sure if it's helpful but my version of geeqie has an option under Preferences > Behaviour > GPU > Override disable GPU.

![Screenshot_20210202_011448](https://user-images.githubusercontent.com/911799/106493449-1c07c080-64f4-11eb-9927-bc38a8500f62.png)

I have also told my window manager to disable compositing when geeqie windows are open.

**Comment by pezcurrel** [comment]
> Not sure if it's helpful but my version of geeqie has an option under Preferences > Behaviour > GPU > Override disable GPU.
> I have also told my window manager to disable compositing when geeqie windows are open.

Tried them both, same result :(
Thank you anyway :)

**Comment by caclark** [comment]
Fixed in commit 89c5590
