### ISSUE TITLE
Cannot view image files

### ISSUE THREAD

**Issue by twocoolbeans** [BestImageViewer/geeqie#849]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
Geeqie 1.6

### OS / DISTRIBUTION
Arch

### SUMMARY
Images are not visible. Only see a white screen in place of all images files. started occurring after update to 1.6.

**Comment by caclark** [comment]
Could you try:- open `Edit/Preferences/Image` and set `Use GPU acceleration` to on. Then restart Geeqie.

**Comment by twocoolbeans** [comment]
Resolves issue. Thank you. Was stuck using Windows for a few weeks due to exclusive applications, unfortunately.
