### ISSUE TITLE
can not switch to list view in folder pane with keyboard

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#85]
The manual says you can switch between the list and tree view in 
the folder pane with ctrl-T
However ctrl-T only switches to the tree view and not back to the list view.

One of the menu's shows you should be able to switch back to the
list view with meta-L, however this does not seem to work (I'm working in
a gnome environment, I tried several keyboard settings).
Also this is not practical, since even if this could work, many people use different
keyboard configurations when it comes to modifier keys like Alt, Meta, Super, Winkey, etc.
Meta will not always be there.

Since the keybindings of geeqie are not configurable the best solution in my opinion
should be to comply with the manual and use ctrl-T to toggle between the two views.
This also seems more usable since you don't have to remember the strange meta-L exception.
The meta-L keybinding seems to be the only meta modifier key binding in geeqie.

PS thank you for forking gqview and continue development, making it a really nice tool!

Reported by: haakje

**Comment by caclark** [comment]
Fixed in commit 1b57b82a57 at geeqie.org
