### ISSUE TITLE
Mouse locked in column adjusting mode in Exif window

### ISSUE THREAD

**Issue by jarnos** [BestImageViewer/geeqie#857]
Sorry, no time to check the latest version, but I did not find a bug report about this. I think developers can check this quickly and know, if there has been some development in this regard in later versions. 

### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
Geeqie 1.5.1
```

```
 
```
I did not compile, but package geeqie 1:1.5.1-8build1 has libgtk2.0-0 as dependency.

### OS / DISTRIBUTION

Xubuntu Linux 20.04
 
### SUMMARY

If I open the Exif Window (that has title Metadata) and drag at the edge of a column title field to adjust its size, mouse is locked in that mode even if I release the mouse button.

### STEPS TO REPRODUCE

See above. Mouse cursor stays in that mode even if I mode it out of the window, and even if I focus to another application, and mouse clicking does not work anymore until I terminate geeqie.

**Comment by caclark** [comment]
It occurs when compiled with GTK2, but not with GTK3.
Unless the bug is easy to find and easy to fix, it probably will never be fixed.
If GTK2 is going to be around for a while it would be better to make the column widths non-adjustable when compiling with GTK2 (on my system the bug crashes Xorg).
