### ISSUE TITLE
Geeqie occasionally forgets that Use Rubbish bin should be enabled

### ISSUE THREAD

**Issue by joeytwiddle** [BestImageViewer/geeqie#858]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.6 (but also happened in some earlier versions)
```

### OS / DISTRIBUTION
Linux / Manjaro / KDE 5

### SUMMARY
I have the option "Use Geeqie Rubbish bin location" enabled.

But every now and then, delete stops working. When I go and look at the settings, the option has been disabled, and I have to re-enable it!

### STEPS TO REPRODUCE
I'm afraid I don't see a pattern. It just happens sometimes.

Frequency: Maybe once a month, after opening geeqie 100 times.

### QUESTION
Are there any parts of the code that might disable this option?

If so, what triggers that code?

![Screenshot_20210202_111627](https://user-images.githubusercontent.com/911799/106547879-fd7fe480-6548-11eb-993c-e70103a68760.png)

**Comment by caclark** [comment]
> delete stops working

Does the file remain, or is it moved to the system trash, or is it deleted?

> Are there any parts of the code that might disable this option?

It is set only in the Preferences dialogue.

When you open Preferences/Behaviour after the problem occurs, which of the Delete radio buttons is set?

**Comment by joeytwiddle** [comment]
> Does the file remain, or is it moved to the system trash, or is it deleted?

When I press the Delete button, nothing happens. The file remains.

I'm sorry I don't remember which of the other two radio buttons is set. I will keep an eye out next time!

**Comment by joeytwiddle** [comment]
It happened again. When I go to the preferences, I see "Use system Rubbish bin" has been selected. So I guess there are two issues:

1. Why has it reset to that?
2. Why does "system Rubbish bin" not work?

In case it helps, here are some lines from my `geeqierc.xml`:

```
            file_ops.enable_in_place_rename = "true" 
            file_ops.confirm_delete = "false" 
            file_ops.confirm_move_to_trash = "false" 
            file_ops.enable_delete_key = "true" 
            file_ops.use_system_trash = "true" 
            file_ops.safe_delete_enable = "true" 
            file_ops.safe_delete_path = "/home/joey/j/trash/GEEQIE_TRASH" 
            file_ops.safe_delete_folder_maxsize = "128" 
            file_ops.no_trash = "false" 
```
