### ISSUE TITLE
Remote recursive slideshow stopped working in 1.6

### ISSUE THREAD

**Issue by elfez** [BestImageViewer/geeqie#859]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.6
```
```
libgtk-3
```

### OS / DISTRIBUTION

Debian testing

### SUMMARY
`--slideshow-recurse` no longer seems to do anything. Prior to upgrading to 1.6 the following command would launch a recursive slideshow

`geeqie --remote -f  --slideshow-recurse:<path> -ss`

Instead it now simply shows the geeqie logo. I can only get a slideshow to work by removing `--slideshow-recurse` and changing `-ss` to `-s`, but of course then it doesn't recurse.

### STEPS TO REPRODUCE

Run `geeqie --remote -f -s --slideshow-recurse:<path>`.

**Comment by caclark** [comment]
Are you using a tilde in <path>? If so, could you try without?

**Comment by elfez** [comment]
No, it's pretty much always with relative paths. I just tried it with an absolute path and it made no difference.

**Comment by caclark** [comment]
What is the output of `geeqie --version`?

> Instead it now simply shows the geeqie logo

Which folder is being displayed?

When you call `geeqie --remote` is geeqie already running or are you starting it for the first time?

**Comment by elfez** [comment]
> What is the output of `geeqie --version`?

`Geeqie 1.6`

> 
> > Instead it now simply shows the geeqie logo
> 
> Which folder is being displayed?

Running the command my home dir the file list shows the contents of the home dir. Running geeqie normally (ie `geeqie /tmp/test`), where the file list shows the target directory

> 
> When you call `geeqie --remote` is geeqie already running or are you starting it for the first time?

Starting first time. However, running it with a window already open works!  It also seems to fix the delay issue in #860. I'll update issue that with the findings.

**Comment by elfez** [comment]
I did a bit of digging and it seems it's a patch Debian applies that causes the problem. The patch in question is the fix for #822 (e6c5624). I notice it does touch remote.c, but that's where my C abilities end.

I also tested the delay from #860 and that has the same effect, so I'm guessing that can be closed as a dupe.

**Comment by caclark** [comment]
Fixed in commit:
https://github.com/BestImageViewer/geeqie/commit/100bd6ae6d964b9072777440ab98fb3187e90d2e
