### ISSUE TITLE
Remote slideshow delay is ignored

### ISSUE THREAD

**Issue by elfez** [BestImageViewer/geeqie#860]
### ISSUE TYPE
* Bug Report
* 
### GEEQIE VERSION
```
Geeqie 1.6
```
```
libgtk-3
```

### OS / DISTRIBUTION

Debian testing

### SUMMARY

When running a remote slideshow with a delay specified it is ignored in favour of the delay set in the geeqie preferences.

### STEPS TO REPRODUCE

* Set slideshow delay to 5s in geeqie's preferences
* Run `geeqie --remote -s --delay=1 <path>`

The slideshow will run but only change image every 5s, not 1s as requested on the command line. I have also tried this with `--delay=0:0:1` in case I'd misunderstood the man page.

**Comment by caclark** [comment]
Could you try re-ordering the parameters?:
`geeqie --remote file:<path>  --delay=1 --slideshow`

**Comment by elfez** [comment]
Unfortunately that only results in the geeqie logo being displayed. Reordering without using `file:` displays the images, but doesn't change the delay.

**Comment by caclark** [comment]
After issuing a `--remote --delay`  command, could you look in `Edit/Preferences` to check that the command has been processed correctly?
Each command line argument is processed in turn.
The delay default is not fixed - it is set to whatever the last `--remote --delay` command set it to.

**Comment by elfez** [comment]
As mentioned in #859 `--delay` works if a window is already open. It also updates the relevant pref to the new value. The pref value is not updated if it is started without an existing window, regardless of option position on the command line.
