### ISSUE TITLE
Geeqie handles non-existing files in a user-unfriendly way

### ISSUE THREAD

**Issue by dkogan** [BestImageViewer/geeqie#863]
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.6+git20210130-5e1d3224 GTK3

Latest from git as of today
```

```
GTK-3
```

### OS / DISTRIBUTION
Debian/sid

### SUMMARY

When requesting images to display, the user may make a mistake, and ask geeqie to display a non-existent file. Geeqie throws a confusing error message, and potentially displays images the user didn't ask for.

Let's say we run `geeqie 1.jpg 2.jpg 3.jpg xxx.jpg`, and `xxx.jpg` doesn't exist. Geeqie then shows the existing files only, and the only error is this on the console:

```
invalid or ignored: xxx.jpg
Use --help for options
```

The complaint should ideally be in the gui somewhere, and it would be great if it was reworded to indicate that "xxx.jpg" was a file it couldn't find. The meaning of "invalid or ignored" is not very clear. Also, if we ask to see only non-existing files, geeqie then falls back to showing other images in the current directory. This is unhelpful since the user didn't ask for those images. And due to the quiet error messages, the user is led to believe that the images being shown ARE what they asked for.

Thanks for working on geeqie!

**Comment by dkogan** [comment]
How about this for a simple and effective solution: make the error message fatal. So the message can stay on the console, but the Geeqie window simply doesn't come up, and we exit. That's a reasonable thing to do if the user asks to see an image that doesn't exist, I think.

**Comment by caclark** [comment]
The command line parameters are examined in turn, each one checked sequentially in the following list until there is a hit:
is dir
is file
is collection
is web URL
then each known option in turn

If there is not a hit, it is considered "invalid" (in some way or other).

In the example above the context indicates that it is a missing file. It is not so easy to determine that in code.

If Geeqie is being called from the command line, the error message is there to see.
The output could be directed to the log window (`Help/Log Window`), but that is even more invisible than output to the console.

I had considered an icon on the status bar that blinked when a new message was sent to the log window, but took that idea no further.

At the moment I am thinking that popping up a small message window that fades after a couple of seconds would be a better way.

**Comment by dkogan** [comment]
Yeah, I thought it could be something like that (arguments may represent several things, and if nothing matches the intent is impossible to determine). Having thought about it some more, I'm really thinking that anything non-matching should be a fatal error: that's how pretty much every command-line tool works. A pop-up error message could be OK, as long as geeqie doesn't then fall-back on displaying images the user didn't ask for. That's a recipe for user confusion, I think.

Thanks

**Comment by caclark** [comment]
> A pop-up error message could be OK, as long as geeqie doesn't then fall-back on displaying images the user didn't ask for. That's a recipe for user confusion, I think.

I would like to avoid the situation where (and I can't give a specific example right now) I have somehow or other executed a program from somewhere.... and nothing happens. I then have to open a terminal window and call the program directly from the command line - and then can see the error message that caused the fail.

**Comment by dkogan** [comment]
Hi. Yes, I definitely agree that user feedback is important. geeqie can be invoked from the shell (what I do 100% of the time) or from some sort of graphical shell, and the two cases require different types of feedback. I guess in a perfect world, the error message would go to the console or graphical window, depending on how geeqie was executed, but doing that reliably sounds hard, and possibly not worth the effort. So the graphical window is probably the way to go.

**Comment by caclark** [comment]
I have not found any Human Interface Guidelines - type of document that discusses partially correct command line input.
e.g.

- multiple files on command line, some exist and some do not
- file exists but `--geometry=` is incorrect

My suggestion is any error, notify the user with a modal pop-up and then exit.

**Comment by volkerwysk** [comment]
Hi. I think it should open a popup window, which informs the user that the file could not be found. Geeqie might be started from the command line, but it's still a GUI application.

What should happen after the user clicks away the pop up window, should depend on what the he has in mind. If he just wanted to see the one image, which doesn't exist, then geeqie should quit. If he wanted to restore the session and add one (or several) windows to it, then the session should be restored, skipping the non-existent pictures from the command line.

I'm not really saying, that geeqie should read the user's mind. :-)  An option, say "-S", could be introduced, which tells geeqie to restore the session. "geeqie -S" would simply restore the session like it was before, without adding anything. "geeqie -S _nonexistent_.jpg", on the other hand, would report the error and also restore the last session. If "-S" is not specified, then geeqie would quit after the user clicks away the message.

If there is no "-S", it could ask whether to restore the session, if there is any. If configured accordingly, it could skip the question and always do so. Or some menu item or icon could be used as the way to tell geeqie to restore the last session. 

I guess that most users don't need or want sessions at all. Geeqie is just an image viewer, after all. But then, I don't use all geeqie features. Sessions might make more sense to me, if I did.

Regards
Volker

**Comment by dkogan** [comment]
Hi. Thank you very much for fixing this! I just tried out the latest version in git (955709eb5885dd130cc47aee493d193df982a3de) and I do indeed see error messages when asking for non-existing files.

I see a new problem however. Let's say `/tmp/a.jpg` and `/tmp/b.jpg` exist. `geeqie /tmp/a.jpg` works properly. But `geeqie /tmp/a.jpg /tmp/b.jpg` does NOT work: it displays the first image in `/tmp` which could be neither of these files. This is probably a work in progress to fix some other issues, but I'd like to point it out.

**Comment by caclark** [comment]
>  But geeqie /tmp/a.jpg /tmp/b.jpg does NOT work: it displays the first image in /tmp which could be neither of these files

I do not see this effect. I think there must be another factor involved.
The last commit effectively merely changed `printf` statement to calls to a warning dialogue.

**Comment by dkogan** [comment]
Thanks for the note, Colin. I just checked, and indeed this was unrelated. After building from source my `"geeqie" = "geeqie -n"` alias wasn't triggering, so the remote was active, and I was hitting one of the old "remote causes geeqie to show images I didn't ask for bugs". So this is a different issue. I thought you fixed that one, though?
