### ISSUE TITLE
Remember the window size, but not the workspace

### ISSUE THREAD

**Issue by CatalinFrancu** [BestImageViewer/geeqie#864]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
```
Geeqie 1.6
```

### OS / DISTRIBUTION

Arch Linux with XFCE 4.16

### SUMMARY

Since a few months ago, the preference _Windows > Remember window positions_ also remembers the workspace. When I open Geeqie, it opens on the last workspace and switches to it. I can turn the option off, but in that case Geeqie forgets the window size as well.

This can be confusing when I close Geeqie and underneath it I see a different workspace than I was expecting.

It would be nice if Geeqie remembered the window size (I like it maximized), but opened on the active workspace. I believe this used to be the default behavior. Could we perhaps have two separate preferences for size and workspace?

### STEPS TO REPRODUCE

1. Tick the checkbox for _Windows > Remember window positions_.
2. Try to open Geeqie on various workspaces, e.g. by double-clicking an image file on the Desktop.
3. Geeqie remembers its size and workspace.
4. Clear the checkbox for _Windows > Remember window positions_.
5. Try to open Geeqie on various workspaces again.
6. Geeqie opens on the active workspace, but also forgets the window size.

**Comment by caclark** [comment]
There is a commit that fixes this problem:
https://github.com/BestImageViewer/geeqie/commit/9443a0929a6f73010f5f86c3147ada7288a10f8a
