### ISSUE TITLE
Geeqie hangs when opened through Nautilus or GNOME

### ISSUE THREAD

**Issue by flaphoschi** [BestImageViewer/geeqie#865]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION

```
Geeqie 1.6
```

```
gtk3 1:3.24.24-2
```

### OS / DISTRIBUTION
Archlinux
geeqie 1.6-4

### SUMMARY
Geeqie hangs and doesn't respond when open from GNOME-Shell or Nautilus (double click on image file).

### STEPS TO REPRODUCE

$ geeqie -r
or
GNOME-Shell -> Alt+F1 -> geeqie -> ENTER
or
Nautilus -> Double-Click on Image

Downstream bugreport at Archlinux:
https://bugs.archlinux.org/task/69569

After some fiddeling I'm rather sure that glib2-2.66.6 is causing this. Here is the [changelog](https://gitlab.gnome.org/GNOME/glib/-/commits/glib-2-66/). The release glib2-2.66.5 and lower are not affected. My personal guess - and really just a guess - is [g_memdup2()](https://gitlab.gnome.org/GNOME/glib/-/commit/5e5f75a77e399c638be66d74e5daa8caeb433e00) which replaces `g_memdup()`? Or some of the other commits between?

**Comment by flaphoschi** [comment]
With glib2 == "2.66.6":
```
$ geeqie -r # -r is used by the desktop entry, too
Remote Geeqie not running, starting...

(geeqie:252808): GLib-CRITICAL **: 00:14:04.716: g_io_channel_set_line_term: assertion 'length_size > G_MAXUINT' failed

(geeqie:252818): GLib-CRITICAL **: 00:14:04.873: g_io_channel_set_line_term: assertion 'length_size > G_MAXUINT' failed

```
With glib2 == "2.66.5":
```
geeqie -r

(geeqie:253008): Gdk-WARNING **: 00:15:30.759: Native Windows taller than 65535 pixels are not supported
Remote Geeqie not running, starting...
```
The "Native Windows taller..." message seems to be normal.

**Comment by caclark** [comment]
If you are compiling from sources, could you try this:?

lines 134 and 378 of `remote.c`
change: `g_io_channel_set_line_term(channel, "<gq_end_of_command>", -1);`
to: `g_io_channel_set_line_term(channel, "<gq_end_of_command>", 19);`

**Comment by flaphoschi** [comment]
That fixes the issue! Thanks :)

For my understanding:  
Glib2 now forbids [forbid very long line terminator strings](https://gitlab.gnome.org/GNOME/glib/-/commit/ecdf91400e9a538695a0895b95ad7e8abcdf1749) which is a following [g_memdup2()](https://gitlab.gnome.org/GNOME/glib/-/commit/5e5f75a77e399c638be66d74e5daa8caeb433e00)? I'm not familiar with this API. I assume `g_io_channel_set_line_term()` is intended for public usage? Storing the signed int value `-1` in an unsigned seems to be a breaking change :thinking:
And the character string literal "<gq_end_of_command>" includes by convention a \0 at the end.

**Comment by caclark** [comment]
> That fixes the issue

I don't think this is a Geeqie problem, so I will not change the code (yet, anyway).

The expression `length_size > G_MAXUINT` evaluates to `FALSE`.
The call `g_return_if_fail(FALSE)` causes an abort.

This would seem to be a glib bug for which there does not seem to be an issue logged.
Ah, well.... as you discovered the bug, I guess it is down to you to report it... :-(

**Comment by flaphoschi** [comment]
I'm writing right now a bug report ;)
Thanks

**Comment by flaphoschi** [comment]
https://gitlab.gnome.org/GNOME/glib/-/issues/2323

Thank you! I'm closing here.
