### ISSUE TITLE
I cannot set backspace as "change to the parent directory" ("up") command

### ISSUE THREAD

**Issue by imre84** [BestImageViewer/geeqie#868]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Gtk-Message: 23:55:18.342: Failed to load module "canberra-gtk-module"
Geeqie 1.5.1
```

```
Package: geeqie
Architecture: amd64
Version: 1:1.5.1-8build1
Priority: optional
Section: universe/graphics
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Andreas Rönnquist <gusnan@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 13083
Depends: libc6 (>= 2.29), libcairo2 (>= 1.2.4), libexiv2-27 (>= 0.27.2), libffmpegthumbnailer4v5, libgcc-s1 (>= 3.0), libgdk-pixbuf2.0-0 (>= 2.27.1), libglib2.0-0 (>= 2.51.0), libgtk2.0-0 (>= 2.24.0), libjpeg8 (>= 8c), liblcms2-2 (>= 2.2+git20110628), liblirc-client0, liblua5.1-0, libpango-1.0-0 (>= 1.14.0), libpangocairo-1.0-0 (>= 1.14.0), libstdc++6 (>= 5.2), libtiff5 (>= 4.0.3), geeqie-common (= 1:1.5.1-8build1), sensible-utils
Recommends: exiftran, exiv2, ufraw-batch, zenity, imagemagick, librsvg2-common, cups-bsd | lpr
Suggests: gimp, xpaint, geeqie-dbg, libjpeg-progs, ufraw
Breaks: geeqie-common (<= 1:1.5.1-2)
Replaces: geeqie-common (<= 1:1.5.1-2), gqview
Filename: pool/universe/g/geeqie/geeqie_1.5.1-8build1_amd64.deb
Size: 611992
MD5sum: ce0440e0a929a69b361796b374807cf5
SHA1: f56d6cb2eecf3098eb0dd197544623f0cde961f2
SHA256: 1e5b408647357bf69120de366c588297d6dbc50983699af7c673e47157b14ffe
Homepage: http://geeqie.org/
Description-en: image viewer using GTK+
 Geeqie is a browser for graphics files offering single click viewing of
 your graphics files. It includes thumbnail view, zoom, filtering
 features and external editor support.
Description-md5: d54bfbbaf76572caf1fcc02be235dc50
```

### OS / DISTRIBUTION
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

up-to-date

### SUMMARY
I cannot set "backspace" as "change to the parent directory" ("up") command

### STEPS TO REPRODUCE
1. start geeqie
2. click "szerkesztés" ("edit") on your menubar
3. click "preferences..." on the menu
4. select "keyboard" from the sidebar of the preferences window
5. in the "accelerators" list scroll down to the entry "Up"
6. click in the key column of the row "Up", the text "Új gyorsbillentyű..." ("new hotkey...") will be displayed here
7. Press "backspace".

### ACTUAL BEHAVIOUR
the field will be reverted to the original state

### DESIRED BEHAVIOUR
"backspace" should be recorded as your hotkey for the "up" command

**Comment by caclark** [comment]
The code handling this does not receive the BackSpace keystroke, so I assume GTK is consuming it.
I cannot at the moment find any GTK documentation about it.

You can use `Shift-BackSpace` or `Control-BackSpace`

If you want an immediate solution, close Geeqie and edit file `$HOME/.config/geeqie/accels`
Find the lines
`; (gtk_accel_path "<Actions>/MenuActions/Up" "")`
`; (gtk_accel_path "<Actions>/MenuActions/PrevImage" "BackSpace")`
Make the appropriate changes and remove the semi-colons;
