### ISSUE TITLE
Freezing solid after change from ext4 to btrfs upgrade

### ISSUE THREAD

**Issue by connectionlink** [BestImageViewer/geeqie#869]
Possible incompatibility with the new file system Fedora is now going forward with.

**Comment by caclark** [comment]
I installed a spare drive and formatted it to btrfs.
I compiled Geeqie on it (although the executable will take /usr and so on from an ext4 drive), and put a few images onto the drive.
There is no problem detected.

What is the output of:
`geeqie --version`
`geeqie --debug=4`

**Comment by connectionlink** [comment]
Hey, thanks for taking the time!
The result of --version is:

Gtk-Message: 19:33:17.926: Failed to load module "pk-gtk-module"
Geeqie 1.5.1

The --debug didn't show much the program just froze.

But then a system upgrade solved the problem. It's now working again.

This is indeed the best image viewer. Couldn't live without it. :+1:
