### ISSUE TITLE
Geometry of Icon pane not being saved

### ISSUE THREAD

**Issue by jefferysmall** [BestImageViewer/geeqie#872]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

Geeqie 1.6+git20210208-5901ff85 GTK3

### OS / DISTRIBUTION

Ubuntu 20.04.2 LTS  (focal)

### SUMMARY
Geeqie 1.5.1 properly remembers the window pane geometry, but the 1.6 development build does not.  See attached image.  When you start Geeqie it begins with a fixed-width icon pane as shown in shot #1.  You modify the pane as shown in shot #2 and then exit.  When you restart Geeqie, it has the original pane width as seen in shot #3.  The modified geometry should be preserved as is done in 1.5.1.

I just puled the most recent code and recompiled it using install-debian.sh

![geeqie](https://user-images.githubusercontent.com/36275594/108262266-900fae80-7119-11eb-9b57-814636ace932.jpg)

**Comment by caclark** [comment]
I believe this is something to do with the differing way in which `gtk_widget_get_allocation()` works in GTK2 and GTK3.
The width value is initially too small, and cannot be changed.

An immediate workaround is to close Geeqie and edit `$HOME/.config/geeqie/geeqierc.xml`
Find the line:
` main_window.hdivider_pos=`
and set the value to maybe 300 or so.
Once fixed it should stay fixed.
You will also find that you cannot now set the width of that pane to a small value.

**Comment by jefferysmall** [comment]
In my geeqierc.xml file for the 1.6 beta I have the two lines:

main_window.hdivider_pos = "350"
main_window.vdivider_pos = "250"

I looked in my geeqierc.xml for 1.5.1 and copied in the two values of 446 and 396.  However, when I start up 1.6 again it has the same geometry and before and when I exit, it writes the 350/250 values back into the xml file.

If I adjust the pane width and then exit, the larger adjusted width value **is**  written to the xml file, but just like adjusting the value manually manually, the value is ignored when starting up.  Its as if these values were hardcoded and the config file values are being ignored.

I start Geeqie 1.6 with a geometry specification as follows: and use the .config_alt directory to keep 1.6 from interfering with 1.5.1.

 XDG_DATA_HOME=/u/jeff/.config_alt XDG_CONFIG_HOME=/u/jeff/.config_alt XDG_CACHE_HOME=/u/jeff/.config_alt /usr/lbin/geeqie --geometry=1862x2039+984+87  . >/dev/null 2>&1 &

I tried eliminating the --geometry component altogether to see f that made a difference.  Geeqie starts as a very small window, but the icon pane is still the same width and upon exit it still writes the 350 value back to the xml file.

**Comment by jefferysmall** [comment]
Also, When firing up 1.6 with the above geometry specification (I have a script that does this by calling **gq -a**), the overall window is displayed with the correct geometry.  But here is the kicker!  I have a bunch of xfce4 terminal windows opened.  If I launch another session calling **gq -a** from some terminals, the subsequent windows open with the proper geometry, while from other terminals the geometry is half ignored.  The window is positioned where expected, but the overall width and height are ignored as seen in the attached image.  This is completely consistent depending upon the terminal window used to launch Geeqie!  The first instance is correct and the subsequent instances are either all correct or not correct.  And this is on a dual-screen setup with terminals that exhibit both behaviors on either screen and it makes no difference if the window position is on one screen or the other.

Now, that's some weird stuff.  And none of this happens with 1.5.1.


![geeqie2](https://user-images.githubusercontent.com/36275594/108365519-2a203700-71ac-11eb-8aac-e0dde4f88e35.jpg)

**Comment by caclark** [comment]
`main_window.hdivider_pos = "350"`
`main_window.vdivider_pos = "250"`

These are the default values. The only place in the code I can find where they are set is if `Edit/Preferences/Remember window positions` is not set.

Which setting do you have for this?

**Comment by jefferysmall** [comment]
I have **Remember window positions** unchecked.  We had an earlier discussion about positioning and I remember that this was causing me problems when I wanted to use the --geometry option.  I also don't want a bunch of Geeqie windows saved and automatically restarting.  I just want to open one, on demand, in the current directory and on the current desktop.  But I want to be able to have multiple sessions concurrently running on different desktops as necessary.

I do have **Remember tool state** and **Remember dialog window positions** both checked.

I can see the problems here as so many people want to use Geeqie in different ways.  I think the only solution is to try and isolate each operation down to it's smallest unit (save, positioning, size, etc.) and provide a separate preference switch for each, leaving it up to the user to turn on the appropriate set for the desired operation.  Ha!  Easy to say; more difficult to implement successfully.  :-/ 

I do really appreciate the effort in trying to nail all of this down.

**Comment by jefferysmall** [comment]
BTW, unless there were any recent changes, I'm still not seeing the icon pane width being preserved between sessions on the 1.6 beta build.  I set it for two columns of thumbnails and yet it always starts up narrower, showing only one.
