### ISSUE TITLE
Can't get Geeqie to display proportionally on 4k/HiDPI screen w/Xubuntu 20.04

### ISSUE THREAD

**Issue by Nick-Deubert-Bose** [BestImageViewer/geeqie#873]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION
```
Geeqie 1.5.1
```

```
$ apt-cache show libgtk-3-0                                                                                         
Package: libgtk-3-0                                                                                                               
Architecture: amd64                                                                                                               
Version: 3.24.20-0ubuntu1  
$ apt-cache show libgtk2.0-0 
Package: libgtk2.0-0
Architecture: amd64
Version: 2.24.32-4ubuntu4
```

### OS / DISTRIBUTION
Ubuntu 20.04.2 LTS

### SUMMARY
I have been unable to get Geeqie to display correctly (proportionally to other gtk apps) on my 4k/HiDPI screen (with "Window Scaling" in Xfce set to 2x). I have tried:
 gsettings set org.gnome.desktop.interface scaling-factor 2
```
GDK_SCALE=2 geeqie
```
Most apps seem to work fine (using some of the tips from here https://wiki.archlinux.org/index.php/HiDPI), I had a similar issue with Gimp but have the theme tweaked to look right now, but have not found any way to confugure Geeqie so.

### STEPS TO REPRODUCE
- Install Xubuntu 20.04 (I am suspect it is not specific to Xfce, but just to be clear).
- Set Settings -> Appearance -> Settings -> Window Scaling = 2x
- Install and launch Geeqie (preface it with GDK_SCALE=2)

![Screenshot_2021-02-22_11-41-22](https://user-images.githubusercontent.com/22311617/108742509-c37d7f00-7505-11eb-9958-394eb298a8c7.png)

I assume there is some solution to this I just don't know about, but after days of googling I haven't found anything that works, so I wanted to ask here. BTW I saw the other HiDPI bug in your github, but what they used (GDK_SCALE) did not work for me. Thank you for your time.

**Comment by caclark** [comment]
I think that Geeqie v1.6 has a fix for this.

**Comment by Nick-Deubert-Bose** [comment]
Yes, it does, and looks like it requires Gtk3 as well (I only had libgtk2.0-dev installed at first I built it and it didn't scale). Thank you.
