### ISSUE TITLE
Support for webp images?

### ISSUE THREAD

**Issue by adrnde** [BestImageViewer/geeqie#881]
* Feature Request
"Geeqie 1.5.1"
Linux Mint 20 Ulyana

Add support for webp, please?
Webp images are beginning to show up, and it is annoying to have to fire up a somewhat lesser image viewer.  "iv" from openimageio tools package, seems to be the nicest viewer that handles webp at moment, but feh and pqiv support webp as well.

### STEPS TO REPRODUCE
Here's a current example of a webp showing up on a fairly mainstream site:
http://cicadasafari.org/images/brood-x-2020-cs-map-457-1.webp

**Comment by tomaszg7** [comment]
Geeqie 1.6 already supports WEBP.

**Comment by caclark** [comment]
If you cannot get v1.6 from whichever package manager Mint uses, the flatpak version is v1.6 (although the flatpak website text still shows it as v1.5).
