### ISSUE TITLE
Display APNG files in the thumbnails area.

### ISSUE THREAD

**Issue by bserem** [BestImageViewer/geeqie#884]
### ISSUE TYPE

* Feature Request

### GEEQIE VERSION
```
Geeqie 1.6
```

### OS / DISTRIBUTION
Debian Bullseye (testing)

### SUMMARY
APNG files are not visible in the thumbnails area, even though Geeqie can render display them (without the animation).

### STEPS TO REPRODUCE
- Create or get an APNG file (or download attached file and rename to .apng).
- Open containing folder with Geeqie.
- File is not visible in the thumbnails area.

![Animated_PNG_example_bouncing_beach_ball](https://user-images.githubusercontent.com/520237/116064025-4a79df80-a68e-11eb-9f3b-7011752e2379.png)

**Comment by caclark** [comment]
If I include an entry for `.anpg` in `Edit/Preferences/Files` I get both an image and a thumbnail.

Is this a request to display .anpg files with animation?

**Comment by bserem** [comment]
The request is to have this entry available by default, so that the files can be viewed.

Animated PNGs is a much bigger issue.

**Comment by caclark** [comment]
> Animated PNGs is a much bigger issue.

There is a gdk_pixbuf_loader for apng files on GitHub:
https://github.com/berenm/gdk-pixbuf-loader-apng

It has not been updated for 3 years, and does not work for me.
However it looks like the author has created enough code to significantly reduce the effort needed to implement this in C within Geeqie.

But there have been no other requests for this file type - and I have no idea how common these files are.

**Comment by bserem** [comment]
I suppose they are not that common, but it would be nice to be able to view them in the thumbnails area and as normal pngs.

In any case, it's your call. Like you said a default geeqie installation needs just one line to be able to display them.

Thanks
