### ISSUE TITLE
fixed and updated Russian translation

### ISSUE THREAD

**Issue by ashed** [BestImageViewer/geeqie#888]
**ISSUE TYPE**

    Bug Report
[ru-fix.zip](https://github.com/BestImageViewer/geeqie/files/6407856/ru-fix.zip)

**GEEQIE VERSION**

Geeqie 1.6 and below

**SUMMARY**

Partially incorrect and non-full Russian translatiaion

I fixed and updated Russian translation, add it please to upstream.

Almost perfect, exclude missing srings in `en_GB.po`
from `prefences.c`
"Star character:"
"Rejected character:"

Maybe need start regen_potfiles.sh

**Comment by caclark** [comment]
All .po files updated in commit d79f9b2974
