### ISSUE TITLE
Option to NOT use a single process for all windows

### ISSUE THREAD

**Issue by ssokolow** [BestImageViewer/geeqie#889]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
```
Geeqie 1.5.1
```

```
GTK: 3.24.18-1ubuntu1
```

### OS / DISTRIBUTION
Kubuntu 20.04.2 LTS

### SUMMARY
For two reasons, I want clicking Geeqie in my launcher to open up a new process:

1. I tend to find ways to crash or otherwise incapacitate Geeqie and don't want what happens to one Geeqie window to affect the others. (I haven't reported them in the past because I'm on an LTS distro and haven't had time to make builds of more recent versions but, now that I'm starting to use more and more apps via Flatpak, I have another option to consider.)
2. I don't like how, when I upgraded to Kubuntu 20.04 LTS, Geeqie started only opening on `$PWD` if there were no existing windows.

Launching multiple instances worked fine for me when I was on Kubuntu 16.04 LTS but something about upgrading to Geeqie 1.5.1 broke that and, now, the only fix I could find was to `chmod 0000 ~/.config/geeqie/.command`.

(Well, that or the even more heavy-handed option of using `firejail --blacklist=$HOME/.config/geeqie/.command geeqie`.)

### STEPS TO REPRODUCE

Please add either a checkbox in the Preferences or a command-line flag equivalent to Firefox's `--no-remote`.

(If you're only doing one, the latter would be more versatile, since users could still edit the `.desktop` file to make it default, but it would allow a user to use a single instance normally, but spawn extra instances on demand.)

**Comment by caclark** [comment]
Geeqie v1.6 has a command line option `--new-instance`

But there remains the problem that Geeqie has only one geeqierc.xml file (not one per instance).

**Comment by ssokolow** [comment]
> But there remains the problem that Geeqie has only one geeqierc.xml file (not one per instance).

Not a huge problem for my use-case. If I could be certain it wouldn't risk causing crashes, I'd have `chmod`ded `geeqierc.xml` read-only years ago to ensure that things like Geeqie's remembered window position would reset to what I prefer every time I close it.

**Comment by caclark** [comment]
>  I wonder how long it'll be before Flathub starts offering v1.6 

Quoting from my fallible memory, I recall that the text for Geeqie on Flathub quotes v1.5, but the download is actually v1.6.

**Comment by ssokolow** [comment]
Huh. You're right... but it's also a GTK+ 2.x build and there's no GTK+ 2.x equivalent to `org.gtk.Gtk3theme.Breeze`, which makes it so ugly that it's not worth trading up from my hacky workarounds unless I can find time to make an `org.gtk.Gtk2theme.Breeze`.
