### ISSUE TITLE
Option to not save last_path

### ISSUE THREAD

**Issue by ssokolow** [BestImageViewer/geeqie#890]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
```
Geeqie 1.5.1
```

```
GTK: 3.24.18-1ubuntu1
```

### OS / DISTRIBUTION
Kubuntu 20.04.2 LTS

### SUMMARY
I use Geeqie for both worksafe and non-worksafe things, and I also keep my `geeqierc.xml` in my `git`-based roaming profile, so I'd prefer that `last_path` remain at a fixed path so there's no chance of accidentally committing a sensitive path through that avenue and so I don't have that one line that's perpetually listed as changed in my `git diff`.

Currently, my workaround is adding this line to my [`incrontab`](https://linux.die.net/man/5/incrontab):

```
/home/ssokolow/.config/geeqie/geeqierc.xml	IN_CLOSE_WRITE	sed -i 's@^\s*last_path\s*=\s*.*$$@\tlast_path = "/home/ssokolow"@' $@
```

### STEPS TO REPRODUCE
Please include a checkbox to either leave `last_path` at whatever it currently is or remove it when updating `geeqierc.xml`.

**Comment by caclark** [comment]
It seems to me that the last line of the `[path_list]` section of the `$HOME/.config/geeqie/history` file duplicates the data in the `last_path` parameter in geeqierc.xml.
If this is so, that part of geeqierc.xml can be removed.
