### ISSUE TITLE
Request for v1.6.1 release

### ISSUE THREAD

**Issue by ehaupt** [BestImageViewer/geeqie#893]
For a while now I observed a weird bug of geeqie v1.6 on FreeBSD 13.0-RELEASE. At random intervals running geeqie at the shell would spawn the window for a short moment then it would disappear. The process is still running (no crash). I tried various things:

* Start out fresh purging old config files `rm -rf ~/.config/geeqie ~/.local/share/geeqie`
* Running `geeqie --debug=999999999`. I found nothing in particular that would explain the window disappearing

I figured I built the latest version from the `master` branch and sure enough I don't observe the problem anymore. I am not sure which of these changes fixed it:

https://github.com/BestImageViewer/geeqie/compare/v1.6...master

Any chance you could tag a `v1.6.1` bugfix release from master?

Thanks for your consideration.

**Comment by AMDmi3** [comment]
Could it be related to a window manager you are running? FWIW, I've had no such problems with i3.

**Comment by ehaupt** [comment]
It's possible but I wouldn't know for sure. I'm using Xfce 4.16.

**Comment by gusnan** [comment]
Whats your setting under "Windows" tab, "Remember window workspace" - if that is checked, that could give a behaviour similar to this - it doesn't remove the window, but moves it to the last workspace that it was on when you last closed the geeqie window.

**Comment by ehaupt** [comment]
Hello @gusnan,

Thank you for your response. I suppose you mean 'Remember window **positions**':

![image](https://user-images.githubusercontent.com/7777244/121478090-eb1b2900-c9c8-11eb-983f-bac75bd52971.png)

That was exactly it. This should probably not be default as I have never seen such a behavior with other applications but now that I know about it I can disable it.

Please feel free to close this issue.
