### ISSUE TITLE
Menu items remain greyed

### ISSUE THREAD

**Issue by covex** [BestImageViewer/geeqie#894]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.5.1
```
```
```

### OS / DISTRIBUTION
Fedora 32, 33...

### SUMMARY
After starting the geeqie and right clicking on a folder, the menu items like "New folder" are greyed out and can not be used. I have to reclick to a different directory then go back and menu is usable again. The same happens then again while browsing and organizing pictures, but I am not sure what triggers this.

### STEPS TO REPRODUCE
Open geeqie, try to right click on highlighted folder with right mouse button.

**Comment by covex** [comment]
![qeeqie_menu](https://user-images.githubusercontent.com/5057744/118101669-5cb28800-b3c7-11eb-8e2b-8f6a8134ade8.jpg)

**Comment by caclark** [comment]
I do not see this exact symptom, but there was a bug (now fixed) which was similar.
The workaround was:

1. move mouse cursor over object
2. press and hold left mouse button
3. click right mouse button
4. drag down to required action

Maybe you could try this arcane solution.

**Comment by covex** [comment]
Yes, this helps too.. I found out this only happens in "Toggle folder view" mode (Ctrl+T).
