### ISSUE TITLE
Change default keybinding for faster/slower slideshow

### ISSUE THREAD

**Issue by mzagrabe** [BestImageViewer/geeqie#904]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
```
Geeqie 1.6
```

### SUMMARY
Please change the default keybinding for Slideshow Faster/Slower. The current keybindings are:

Ctrl Keypad +/-

Many laptop keyboards do not have a keypad, or the keypad is many key strokes away from being available.

I would wager that laptop usage for Geeqie is greater than desktop usage - changing the keybinding to:

Ctrl +/-

would be an (easy?) win for laptop users.

**Comment by caclark** [comment]
Fixed in commit  aaf1420aa54
