### ISSUE TITLE
Install script times out at "getting new sources from server"

### ISSUE THREAD

**Issue by SimonDedman** [BestImageViewer/geeqie#907]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
Latest from wget on today's date

### OS / DISTRIBUTION
Xubuntu 21.04 Hirsute

### SUMMARY
Per title really. Ran script acquired with wget, ticked all options, times out on "getting new sources from server". Tried again, only 2 options available to tick this time, times out again. On university T1 wired connection.

Cheers. Also - COOL NEW WEBSITE! Nice work! :)

edit: dialogue box text:

> Git error:
> www.geeqie.org[0: 185.199.109.153]: errno=Connection timed out
> www.geeqie.org[1: 185.199.110.153]: errno=Connection timed out
> www.geeqie.org[2: 185.199.111.153]: errno=Connection timed out
> www.geeqie.org[3: 185.199.108.153]: errno=Connection timed out

**Comment by caclark** [comment]
There were changes made over the weekend to get the new website working. They might have had an untoward effect.
The simple way to reset everything is to delete the geeqie folder and then:
`git clone git://git.geeqie.org/geeqie.git`

Unless you need to compile from sources, an easier way is to use an AppImage - no compiling necessary:
https://www.geeqie.org/AppImage/index.html

**Comment by SimonDedman** [comment]
Nice one, cheers, got the appimage going.

**Comment by tjjjwxzq** [comment]
It does seem like the install script provided in the README is still using `www.geeqie.org/geeqie.git` and I still get the same error with git clone timing out as above.
