### ISSUE TITLE
"Configure Editors" actually deletes desktop files!

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#91]
Select the Edit-&gt;Preferences-&gt;Configure Editors menu item.

If you hit "Delete" on any of the entries, it actually tries to delete the .desktop file! This is bad. You should never screw with other program's config files.

It should simply delete it from the list.

Reported by: gcash

**Comment by caclark** [comment]
Commit 4bbf6df484 fixes this
