### ISSUE TITLE
Option to stay on the current image when moving with the mouse

### ISSUE THREAD

**Issue by olcc** [BestImageViewer/geeqie#910]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
```Geeqie 1.6 (Geeqie 1:1.6-9 on Debian Linux)```

### OS / DISTRIBUTION
Debian Linux 

### SUMMARY
Is there **an option for Geeqie to stay on the current image when moving with the mouse** ?

I often zoom into an image and move through it by sliding the image with the mouse. When I come to a border of the image, Geeqie jumps on the next or the previous image... I find this behavior annoying because it is hard to stop moving just before reaching the border of the image(*).

What I request is **an option to disable jumping on next or previous image when the image border is reached**.

Thank you, 

Olivier

(*) This is particularly difficult because Geeqie is generaly slow at displaying images, and particularly slow for zoomed images.

**Comment by caclark** [comment]
> When I come to a border of the image, Geeqie jumps on the next or the previous image.

You can move to the next/previous image using the mouse wheel or mouse buttons, but Geeqie does not have the ability to move to the next image simply by using the mouse to slide around a zoomed image.
I think there must be another factor involved here. Is there perhaps some other utility involved?


> Geeqie is generaly slow at displaying images, and particularly slow for zoomed images.

Can you give an indication of how slow? Which file types are you using, how large are they and what is the approximate delay?
I find that zoomed or un-zoomed, switching between images is near instantaneous (although svgz files are slow).

**Comment by olcc** [comment]
"Geeqie does not have the ability to move to the next image simply by using the mouse to slide around a zoomed image."

OK, thank you. I am starting to understand. See below.

"Can you give an indication of how slow?"

When I click on "+" in order to zoom in, or when I "slide" the zoomed image, the image reconstruction by Geeqie often takes about 1 s (which is very long).
In comparison, the same actions with the "feh" software is very much faster on the same image (acceptable lag).
The image for example is a 372K PNG.

I think what happens is the following: When I do an "image slide" gesture (i.e. click left mouse button and slide), Geeqie is lagging behind so much that the gesture is interpreted as a simple "image click" instead of a "slide" (the system is so much overwhelmed that the "slide" movement is not understood). Indeed, if I do the "image slide" gesture very slowly, i.e. keep the finger a long time on the left mouse button, Geeqie does not jump to the next image.

Understanding this, I disabled "Preferences > Behavior > Navigation by left or middle click on image", and this solves my problem, or at least works around Geeqie's slowness.
