### ISSUE TITLE
can't rename or create directories, while file name outside the window

### ISSUE THREAD

**Issue by s8huth** [BestImageViewer/geeqie#911]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.5.1
```
```
deb-package
```

### OS / DISTRIBUTION
Linux Mint 20.2

### SUMMARY
while renaming a directory, i can't read the full directory name, because the rename line moved outside the window.
![2021-07-25 10 53 40](https://user-images.githubusercontent.com/55435982/126893587-a28f85ec-da7f-4043-8cad-e11b56bd8946.png)

### STEPS TO REPRODUCE
click in the file list on a directory (right mouse) and rename it.

**Comment by caclark** [comment]
This problem still exists in the latest version of Geeqie. I suspect the fault lies deep inside GTK.

A (kind of) workaround is to move the scroll bar of the folders pane to either fully left or fully right.
The full path name can then be seen.
On two computers I use the problem shows in a different way. On the first I have to move the scroll bar fully left, and on the second to move it to fully right - I have  no idea why.

**Comment by caclark** [comment]
If you would like to try an AppImage, the Downloads section of geeqie.org contains a link to an AppImage that contains this latest fix.
