### ISSUE TITLE
Zoom-to-fit is no longer the default and cannot be selected from preferences

### ISSUE THREAD

**Issue by clarified** [BestImageViewer/geeqie#914]
This refers to version in debian testing: debian version 1:1.6-9.

All images were displayed as zoom 1-1 and I could not find any way to modify this in the preferences dialogue. I could however edit  ~/.config/geeqie/geeqierc.xml  image.zoom_mode from "0" to "1".

**Comment by caclark** [comment]
The zoom setting is now on the status bar, which makes it easier to access.
On the status bar, click on the box displaying the current zoom setting.
The value set is stored in the config. file.

**Comment by clarified** [comment]
On Tue, Jul 27, 2021 at 05:41:02PM +0000, Colin Clark wrote:
> The zoom setting is now on the status bar, which makes it easier to access.
> On the status bar, click on the box displaying the current zoom setting.
> The value set is stored in the config. file.

OK. Found it. But I doubt that I would have discovered that on my own
:-( Easier to access only if you know it is there...

I did skim the changelogs and the man page.

ael

**Comment by caclark** [comment]
There is an on-line help search function too. But the usefulness depends on the search engine used and the search parameter.
It also works best if you already know the answer :-(

[There is no index to the user manual because it turned into a nightmare trying to create one]
