### ISSUE TITLE
Remember zoom between images

### ISSUE THREAD

**Issue by sakkamade** [BestImageViewer/geeqie#916]
### ISSUE TYPE

* Feature Request

### GEEQIE VERSION

```
Geeqie 1.6
```

(from official repository)

### OS / DISTRIBUTION

Arch Linux

### SUMMARY

Good day. 
The option I would like to suggest is for Geeqie to keep the zoom from image to image. 
And, perhaps, additional option to keep zoom only if images are having the same size.

The settings are so extensive, however I cannot seem to find such feature. Neither can I find such feature request.
Hmm...

**Comment by caclark** [comment]
If you click on the zoom box on the status line, you are presented with the options you are looking for.

[Neither the zoom or sort boxes on the status line have any visual indication (other than the tooltip) that they contain selectable items. That will be fixed in the next few days.]

> And, perhaps, additional option to keep zoom only if images are having the same size.

It is unlikely that will be implemented, but you may open another feature request for that if you wish.

**Comment by sakkamade** [comment]
> If you click on the zoom box on the status line, you are presented with the options you are looking for.

I knew it! it was already somewhere there! Thank you kindly.

> > And, perhaps, additional option to keep zoom only if images are having the same size.
>
> It is unlikely that will be implemented,

I can see why, the way it is implemented here is quite different from other image viewers, such as nomacs, 
and in order to have it, the whole feature should be revised;
but I like the way it is here: upon calling "Zoom to fit" function, it is also applied to all the images, and 
even saved between the sessions.

> but you may open another feature request for that if you wish.

I wonder if I need it with the way things are (the reason is above).
Thank you :heart:

**Comment by caclark** [comment]
>  No, it is just the default method on startup.

The setting should be saved. After closing Geeqie execute:
`grep zoom_mode $HOME/.config/geeqie/geeqierc.xml`
and you should see that the setting has changed.

[The option `Edit/Preferences/Image/Allow Enlargement Of Image` can be useful if there are smaller images in the sequence you are viewing.]

**Comment by sakkamade** [comment]
> The setting should be saved. After closing Geeqie execute:
grep zoom_mode $HOME/.config/geeqie/geeqierc.xml
and you should see that the setting has changed.

Yes, sorry, that is not what I meant.

The setting is saved, indeed. What I tried to say is that zoom ratio is not, i.e. I zoom the image to 1:1, and I have this same zoom until I change it, **or** until the program restart. 
After another startup, zoom setting is _not_ being set to "Fit image to window", however it _does_ work this way.

**Comment by sakkamade** [comment]
But, please, don't change it.
