### ISSUE TITLE
Release a new version so macOS can use this app

### ISSUE THREAD

**Issue by mkozjak** [BestImageViewer/geeqie#924]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION
```
1.6
```

### OS / DISTRIBUTION

macOS 11.6

### SUMMARY

All images render white.

### STEPS TO REPRODUCE

Just install from brew and run. #644 fixes the issue.

**Comment by caclark** [comment]
@mowgli @gusnan et al

Does anyone have an opinion of whether or not there should be a specified release schedule for Geeqie - e.g. fixed, rolling or simply whenever feels like a good time? If so does it need to tie in with e.g. Debian/Ubuntu releases etc.?

**Comment by caclark** [comment]
v1.7.1
