### ISSUE TITLE
Request to add image bookmarking/tagging within a folder

### ISSUE THREAD

**Issue by ScriptJunky** [BestImageViewer/geeqie#934]
### ISSUE TYPE

* Feature Request

### GEEQIE VERSION

```
{22:10}~ ➭ geeqie --version
Geeqie 1.6
{22:27}~ ➭ 

```

### OS / DISTRIBUTION
EndeavourOS

### SUMMARY
This is a request to add an image bookmarking/tagging feature. 
When viewing images inside of a folder that has a large amount of images, it can become difficult to remember the last image viewed when one has to exit out and continue later. 
It would be wonderful if we could place a note, or tag, within Geeqie that would mark which image we last viewed within a folder, and which we could elect to resume from when we open images in the same folder again.
This functionality could be further expanded to support tagging multiple files within a folder, and then having Geeqie support "bulk moving by tag".

**Comment by caclark** [comment]
Geeqie has an option to "Restore last path" when starting Geeqie. This could easily be extended to also move the focus to the last image viewed.

Keeping track of the last image viewed in every folder that has been entered would probably be excessive.

You can use Marks to temporarily tag images - so you could e.g. use Mark 10 to indicate an image you would like to return to.
Using Marks you can also select groups of files for copying/moving etc.

The disadvantage of using Marks is that it makes Geeqie slow down noticeably.

[I guess it would be worth expending effort to find a way to reduce the speed impact of using Marks]

**Comment by ScriptJunky** [comment]
@caclark 

> Keeping track of the last image viewed in every folder that has been entered would probably be excessive.

I was thinking the preferred route would be allowing someone to have Geeqie track folders by choice (right click dialogue?), and upon opening any image within that same folder, the user could be presented with a dialog w/ 4 choices (I am 100% sure this could be said in a manner that makes much more sense than what I am providing here) -- 

**This folder has a positional mark in place, would you like to.....**

* Continue from marked image, keep existing mark
* Continue from marked image, remove mark
* Continue at current position, remove current mark 
* Continue at current position, keep existing mark

> You can use Marks to temporarily tag images - so you could e.g. use Mark 10 to indicate an image you would like to return to.
Using Marks you can also select groups of files for copying/moving etc.

I actually had no idea this was a feature. I need to look into that, as it might serve the same purpose and work beautifully.
