### ISSUE TITLE
Delete / Trash using keyboard keys in duplicate finder does not remove the selected file.

### ISSUE THREAD

**Issue by bdkramer** [BestImageViewer/geeqie#935]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
Geeqie 1.6

### OS / DISTRIBUTION
Pop!_OS 21.04, Gnome 3.38.5

### SUMMARY
When using the "Find Duplicates" feature, selecting a file and using the Delete key or Shift+Delete key combination removes the duplicates form the interface, but does not remove the actual file. Log window with Debug level at 3.0 gives the following output when using the Delete key, and little else.:
"filedata.c:file_data_unref_debug:793:file_data_unref fd=0x55d8b926d4c0 (5:0): '/home/user/Pictures/temp/0hLU3ZA.jpg' @ dupe.c:315"
Same behavior has been observed on a separate system, with a similar OS and Geeqie version.

### STEPS TO REPRODUCE
Load files into the Find Duplicates dialog window
Select a file
press the Delete key on the keyboard
Observe the duplicates are removed from the Find Duplicates interface
Observe the selected file was not actually deleted from the path in the file browser.

**Comment by caclark** [comment]
In the Duplicates window the "Delete" key is linked to the "Remove from list" function.
The "Control-D" key is linked to the "Delete file" function.
 
You can find information on key shortcuts on Help/Keyboard Shortcuts, or maybe Help/Online Help Search (depending which search engine you use).

The keyboard shortcuts documentation is incomplete and not easy to navigate. The Help/Keyboard Map maybe should be extended to include maps for each of the windows (Search, Dupes, Collections etc.)

Or perhaps the keyboards shortcuts page could be rearranged in some way.

I will leave this open until I fined a way to improve the documentation.

**Comment by bdkramer** [comment]
Ctrl+D confirmed as working in the Duplicates list. Thank you for the rapid response.

My initial searching for the right shortcut was limited to the Keyboard Shortcuts section in the Preferences, so I had not seen the documentation for the Find Duplicates under the Help options. When the first of the keys bound to "delete" or "move to trash" didn't work, I did not try the "<Primary>D" shortcut.

Having the Keyboard Map available is a nice addition I don't think I've ever seen in this sort of software, and the effort is appreciated. I believe the shortcuts documentation is pretty sensible, and had I seen it, would have found the answer. 

I would recommend updating the shortcut preferences dialog with either a per-dialog section, or an additional column listing the applicable dialog for each action.

One final option for consideration would be to list the associated shortcut keys next to right-click menu items, as is already done with top-menu items.
