### ISSUE TITLE
configure fails due to auxdir links pointing to nonexistant files

### ISSUE THREAD

**Issue by Apteryks** [BestImageViewer/geeqie#936]
I tried to update this package to 1.6 on GNU Guix, en encountered the following:

```
starting phase `configure'
source directory: "/tmp/guix-build-geeqie-1.6.drv-0/source" (relative from build: ".")
build directory: "/tmp/guix-build-geeqie-1.6.drv-0/source"
configure flags: ("CONFIG_SHELL=/gnu/store/vx6vfbmmazvfi7vp8xyjn2mcyylvw9gn-bash-minimal-5.1.8/bin/bash" "SHELL=/gnu/store/vx6vfbmmazvfi7vp8xyjn2mcyylvw9gn-bash-minimal-5.1.8/bin/bash" "--prefix=/gnu/store/abf9iqasy5qd8qq34n94qrww549zmn5g-geeqie-1.6" "--enable-fast-install" "--build=x86_64-unknown-linux-gnu" "CFLAGS=-fcommon" "--enable-map" "--enable-gtk3")
configure: WARNING: unrecognized options: --enable-fast-install
configure: error: cannot find install-sh, install.sh, or shtool in auxdir "."/auxdir
error: in phase 'configure': uncaught exception:
%exception #<&invoke-error program: "/gnu/store/vx6vfbmmazvfi7vp8xyjn2mcyylvw9gn-bash-minimal-5.1.8/bin/bash" arguments: ("./configure" "CONFIG_SHELL=/gnu/store/vx6vfbmmazvfi7vp8xyjn2mcyylvw9gn-bash-minimal-5.1.8/bin/bash" "SHELL=/gnu/store/vx6vfbmmazvfi7vp8xyjn2mcyylvw9gn-bash-minimal-5.1.8/bin/bash" "--prefix=/gnu/store/abf9iqasy5qd8qq34n94qrww549zmn5g-geeqie-1.6" "--enable-fast-install" "--build=x86_64-unknown-linux-gnu" "CFLAGS=-fcommon" "--enable-map" "--enable-gtk3") exit-status: 1 term-signal: #f stop-signal: #f> 
phase `configure' failed after 0.4 seconds
```

This is because on GNU Guix, the assumption that the files
```
depcomp -> /usr/share/automake-1.16/depcomp      
install-sh -> /usr/share/automake-1.16/install-sh
```
exist isn't true.

### ISSUE TYPE
* Bug report

### GEEQIE VERSION
1.6

**Comment by caclark** [comment]
I have no knowledge of Guix, but are these two links relevant?:

https://guix.gnu.org/en/packages/geeqie-1.6/
https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/image-viewers.scm#n305

**Comment by Apteryks** [comment]
Hi!  Yes; the 2nd link shows how it was worked around in Guix.   The problem is that the build system assumes hard coded locations for the automake provided scripts.  Aren't these typically copied to the project by invoking `autoreconf --install` anyway?  The Automake manual suggest so (`info '(automake) Creating amhello'`):

> Once you have these five files, it is time to run the Autotools to
> instantiate the build system.  Do this using the ‘autoreconf’ command as
> follows:
> 
>      ~/amhello % autoreconf --install
>      configure.ac: installing './install-sh'
>      configure.ac: installing './missing'
>      configure.ac: installing './compile'
>      src/Makefile.am: installing './depcomp'
> 
>    At this point the build system is complete.

**Comment by Apteryks** [comment]
Not valid anymore with Meson.
