### ISSUE TITLE
Scrollbar actions inconsistent with standard operation

### ISSUE THREAD

**Issue by jefferysmall** [BestImageViewer/geeqie#946]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
Geeqie 1.5.1
and
Geeqie 1.6+git20210625-aaf1420a GTK2

Both versions appear to be linked to libgtk-x11-2.0.so.0

### OS / DISTRIBUTION

Xubuntu 20.04.3 LTS
1.5.1 is from the standard repository
1.6 is custom built from git repository using ./autogen.sh --disable-gtk3

### SUMMARY
I cannot remember if this was discussed in the forum, but there appears to be a scrollbar problem with GTK.  I'm seeing the same thing with GIMP and have submitted a corresponding bug report for that package.  In most Linux tools, when clicking in the scrollbar gutter you get:

```
  B1: Scroll a page worth in the specified direction
  B2: Jump to specified location
  B3: N/A
```
However, in geeqie the operation is:

```
 B1: Jump to specified location
 B2: N/A
 B3: Scroll a page worth in the specified direction

```
I'm fairly sure that this is a byproduct of the GTK.  Is there a way to override the toolkit and specify the expected type of default behavior? Could this be added to the preferences? If not, could a request be passed up the line to GTK to make such a feature available?

**Comment by jefferysmall** [comment]
I asked this [question](https://gitlab.gnome.org/GNOME/gtk/-/issues/4591#note_1344769) of the GTK developers and the response is that the method for determining the mouse-scrollbar operation is dependent upon the setting for: [gtk-primary-button-warps-slider](https://docs.gtk.org/gtk4/property.Settings.gtk-primary-button-warps-slider.html)

I hope this can be investigated and either flipped as the default for Linux builds (and others) or add a settings option that lets the user choose their preferred operational mode.

**Comment by caclark** [comment]
The default setting in GTK2 for this property is FALSE, and for GTK3 it is TRUE.
Oh well. Looks like yet another user option....

**Comment by jefferysmall** [comment]
Well that explains why I saw this change of behavior.  I really don't understand why GTK changed the default, but there you have i!.  Thanks for the confirmation.  I hope this also changes the B2 behavior as a side effect.  I didn't see another function specifically aimed at that button.

**Comment by caclark** [comment]
I have had a change of mind...

This link shows how to set this parameter for all programs (there are other links describing this):
`https://forums.gentoo.org/viewtopic-t-948904-start-0.html`

This is the text from dev-help about this parameter:

> If the value of this setting is TRUE, clicking the primary button in a GtkRange trough will move the slider, and hence set the range’s value, to the point that you clicked. If it is FALSE, a primary click will cause the slider/value to move by the range’s page-size towards the point clicked.

> Whichever action you choose for the primary button, the other action will be available by holding Shift and primary-clicking, or (since GTK+ 3.22.25) clicking the middle mouse button.

**Comment by jefferysmall** [comment]
It would be nice if it was true, but it ain't, at least for me on Xubuntu.  I ran across this "solution" a long time ago in my research on this problem and have had this entry (**gtk-primary-button-warps-slider = false**) in both my personal settings.ini file as well as the global one in /etc for years now and it makes no difference in the operation of Geeqie or GIMP.  Has anyone else actually tried this with different results?

If anyone has additional ideas I'll be happy to test them out.  Let's please wrestle this one to the mat!  :-)

**Comment by jefferysmall** [comment]
In a further attempt for clarification on this issue, I posted a question at the following link.  Follow this if you want to see any replies.

[](https://discourse.gnome.org/t/problem-with-scrollbar-operation/8589)
