### ISSUE TITLE
gtk2 broken

### ISSUE THREAD

**Issue by installgentoo** [BestImageViewer/geeqie#947]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
geeqie-1.6_p20211016
```

```
gtk2
```

### OS / DISTRIBUTION

gentoo

### SUMMARY

see screenshot. this here is the move/rename/copy dialogue as it is right now. as you can see there's nothing there. and that's not surprising, since 

(geeqie:15416): Gtk-WARNING **: 23:43:22.368: /tmp/portage/x11-libs/gtk+-2.24.33/work/gtk+-2.24.33/gtk/gtkwidget.c:5709: widget not within a GtkWindow

(geeqie:15416): Gtk-WARNING **: 23:43:22.368: /tmp/portage/x11-libs/gtk+-2.24.33/work/gtk+-2.24.33/gtk/gtkwidget.c:5709: widget not within a GtkWindow

(geeqie:15416): Gtk-WARNING **: 23:43:22.368: /tmp/portage/x11-libs/gtk+-2.24.33/work/gtk+-2.24.33/gtk/gtkwidget.c:5709: widget not within a GtkWindow

I believe some pointer is being passed incorrectly. Note that with gtk3 everything works, but gtk3 is bloody awful.

### STEPS TO REPRODUCE

checkout geeqie-1.6_p20211016, build with gtk2, try to move a file.
![huh](https://user-images.githubusercontent.com/2088917/147229291-0c6e61e7-51f5-417f-89e6-193a7eeaed5e.png)

**Comment by caclark** [comment]
Fixed in commit: f6bc1d2ead
