### ISSUE TITLE
pdf previewer doesn't work in gtk2

### ISSUE THREAD

**Issue by installgentoo** [BestImageViewer/geeqie#948]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
2021-10-16
```

```
gtk2
```

### OS / DISTRIBUTION

gentoo

### SUMMARY

pdf previewer doesn't work in gtk2

### STEPS TO REPRODUCE
build with gtk2, add *.pdf as document, view any folder with pdf files. thumbnails aren't generated.
works perfectly when built with gkt3, but gtk3 is simply revolting to use.

**Comment by caclark** [comment]
This is not exactly a bug - the pdf section will not compile under GTK2

I am not sure if `libpoppler` compiles with GTK2, but Geeqie uses `gdk_pixbuf_get_from_surface()` which is GTK3 only.

**Comment by installgentoo** [comment]
I see.
I exported GDK_CORE_DEVICE_EVENTS=1 switched to gtk3, that apparently disabled the awful scroll behaviour, in case anyone else is cringing from gtk3 and has this problem in the future.
