### ISSUE TITLE
Refresh flashes when entering/exiting geeqie window

### ISSUE THREAD

**Issue by JohnCC330** [BestImageViewer/geeqie#949]
* Bug Report

```
Geeqie 1.6
Linux Slackware64-current
gtk+3-3.24.29
gdk-pixbuf2-2.42.6
```

### SUMMARY
Each time the cursor enters/leaves the Geeqie window, the image refreshes very visibly. Also, movements
of the cursor in the (bottom) status line causes refreshes when changing 'status areas' (like 'Sort by name',
'image size', 'scale' etc.). These artifacts where not present in geeqie 1.3.

### STEPS TO REPRODUCE
Just start geeqie, and move the cursor around:
  - entering and leaving the geeqie window
  - moving between status areas

This issue is most visible with a 'light' image showing.

**Comment by caclark** [comment]
I think the problem you describe is fixed in the latest version.
You may make a quick check by running an AppImage from here:
https://www.geeqie.org/AppImage/index.html

**Comment by JohnCC330** [comment]
Sorry for the delay. I compiled git master and indeed, the issue disappeared.
Cheers!
