### ISSUE TITLE
Very slow rendering of large (tiff) files, sometimes, when opened for the first time after restart.

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [BestImageViewer/geeqie#952]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
Compiled from source, pulled from git repo: git clone http://git.geeqie.org/git/geeqie.git
git describe: v1.2-1021-ga974a3ad
./geeqie --version: Geeqie 1.6+git20220101-f692950a GTK3
```

```
I have used GTK3
./autogen.sh --enable-gpu-accel --prefix=/home/magnus/usr 
make -j8
make install

output below from configure step:

Localization:
  NLS support:   yes
  LINGUAS:        ar be bg ca cs da de el en_GB eo es et eu fi fr hu id it ja ko nb nl pl pt_BR ro ru sk sl sr@latin sr sv th tlh tr uk vi zh_CN zh_TW

Settings:
  Developer:     no
  Debug flags:   no
  Debug log:     yes
  Deprecated:    no

Support:
  LCMS:          yes
  Exiv2:	 yes
  Lirc:          no
  Clutter:       yes
  Libchamplain:		no
  Libchamplain-gtk:	disabled
  Lua:	         no
  FFmpegthumbnailer:	no
  Pdf:	         yes
  HEIF:	         yes
  WebP:	         yes
  DjVu:	         no
  J2K:	         no
  LibRaw:        yes
  Libjxl:        no
  Libarchive:    yes

Documentation:
  Doxygen:       
  doc-tool:      
```

OS / DISTRIBUTION

Debian 11.2 Bullseye.
uname -a : Linux debian 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux

### SUMMARY

If I restart computer to clear all memory and caches and then run:
./geeqie --debug=4, I sometimes get VERY slow rendering (minutes) of large TIFF files (700 Mbytes-1 Gbyte). The console then displays a long repetitive, almost periodic output pattern, similar to this:

<snip>
renderer-tiles.c:rt_queue_schedule_next_draw:1698:redraw priority: no change 2.12 %
renderer-tiles.c:rt_queue_schedule_next_draw:1698:redraw priority: no change 1.85 %
renderer-tiles.c:rt_queue_schedule_next_draw:1698:redraw priority: no change 1.59 %
renderer-tiles.c:rt_queue_schedule_next_draw:1698:redraw priority: no change 1.32 %
renderer-tiles.c:rt_queue_schedule_next_draw:1698:redraw priority: no change 1.06 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.79 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.53 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.26 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1698:redraw priority: no change 2.12 %
renderer-tiles.c:rt_queue_schedule_next_draw:1698:redraw priority: no change 1.85 %
renderer-tiles.c:rt_queue_schedule_next_draw:1698:redraw priority: no change 1.59 %
renderer-tiles.c:rt_queue_schedule_next_draw:1698:redraw priority: no change 1.32 %
renderer-tiles.c:rt_queue_schedule_next_draw:1698:redraw priority: no change 1.06 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.79 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.53 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.26 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1692:redraw priority: wait 0.00 %
renderer-tiles.c:rt_queue_schedule_next_draw:1698:redraw priority: no change 2.12 %
renderer-tiles.c:rt_queue_schedule_next_draw:1698:redraw priority: no change 1.85 %
renderer-tiles.c:rt_queue_schedule_next_draw:1698:redraw priority: no change 1.59 %
renderer-tiles.c:rt_queue_schedule_next_draw:1698:redraw priority: no change 1.32 %
renderer-tiles.c:rt_queue_schedule_next_draw:1698:redraw priority: no change 1.06 %
<snip>

I can see the file being rendered line by line, rather slowly (60-90 seconds). Once the picture file is loaded into memory and rendered the Geeqie will redraw quickly if I revisit the file.

### STEPS TO REPRODUCE

1: Restart computer to clear memory and caches.
2: Start Geeqie ./geeqie --debug=4
3: Use the file browser and pick a few large (TIFF) files 700 Mbytes-1 Gbyte. Naturally such a large 16 bit uncompressed TIFF file takes time to load and render, but normally Geeqie will render within 10 seconds or so.
4: Keep repeating step  3, for a few new big TIFF files 700 Mbytes to 1 Gbytes. Suddenly the console debug info will show wait 0.00 %, wait 0.00 %, ..., wait 0.00 %, no change, no change, wait 0.00 %, wait 0.00 %, ..., wait 0.00 % and a rendering which used to take 10 seconds on my system will no take 90 seconds (approx).
5: Once a file has been (sometimes very slowly rendered for the first time) it well re-render very quickly if revisited.

Feh viewer takes 10 seconds to display these big files. I understand it takes 10 seconds or similar, to load from my (2013) spinning hard disk. Geeqie is usually as fast, 10 seconds of a 700 Mbytes TIFF file, but then after a few large file openings Geeqie rendering stalls with ...wait 0.00 %, wait 0.00 %, ..., wait 0.00 %, no change, no change, wait 0.00 %, wait 0.00 %, ..., wait 0.00 %... pattern. NOTE: The next large TIFF file might render in 10 seconds, again. I can not repeat this in a deterministic way. The sudden stalls seem almost random. 

I have Intel® Core™ i7-3770K CPU @ 3.50GHz × 8 , 16 Gbytes RAM, 32 Gbytes Swap

In Geeqie preferences I have:
Decoded Image Cache size 200, 2000, 8000, no difference in behavior.
Preload next: OFF
Refresh on file change: OFF
File Browser : Show Star Rating ; OFF

I have a wide gamut monitor and my system is calibrated and color managed. I use 16 bit tiff to transfer between processing applications (RawTherapee to Hugin, to GIMP etc). Some panoramas become large TIFF files. 

I am uncertain if this is particular to large TIFF files or other large files as well (JPG,...), but I have not tested. An 8-bit JPG will naturally be much smaller anyway.

**Comment by caclark** [comment]
Can you post a link to one of these files?

**Comment by KarlMagnusLarsson** [comment]
@caclark and all,

Please try these 3 different tiff files.
https://drive.google.com/drive/folders/16_2JLjY9YdRAn9E9D5t-mOeRA6IhXV89?usp=sharing

I suppose copying one and the same file to different new file names can set up a longer list of files. The issue does not necessarily show up first or second time a file is rendered, but maybe the third or fourth opening of a new file (or sometimes the first time as well, it seems to have a stochastic nature on my system).

**Comment by caclark** [comment]
Could you go to `Edit/Preferences/Image` and if `GPU acceleration` is set,  unset it and restart Geeqie.

**Comment by KarlMagnusLarsson** [comment]
@caclark 

Edit/Preferences/Image | GPU acceleration is not set. GPU acceleration is off from the start. 

This is another issue, but I have clutter, NVIDIA Quadro RTX 4000 GPU with NVIDIA drivers, however GPU acceleration does not work for me, with Geeqie. It is slower with GPU acceleration than without and the pictures are not rendered correctly. I get artifacts in the frame.

**Comment by KarlMagnusLarsson** [comment]
I noticed I had inconsistent commit numbers in git describe and  geeqie --version. This is fixed now with an extra 'make uninstall', as per readme. I am at latest commit, same issue.

./geeqie --version : Geeqie 1.6+git20220106-7a15c24a GTK3
git describe : v1.2-1022-g7a15c24a

**Comment by KarlMagnusLarsson** [comment]
@caclark , Thank you for checking the issue. The tile size does not affect the characteristics of rendering the large tiff files. I see the same issue regardless.

I checked the 'tiles.c:rt_queue_schedule_next_draw:' code segment and played with the percentages and wait times coded there, but that is not the root cause. Somehow the rt_queue_schedule_next_draw is not feed with new data to render.

I will try and read the files from SSD instead of HDD and see what happens. One workaround is perhaps to get a new system with higher disk i/o speed? 

I know my system is a bit dated (2013), but there is an additional reduction of data speed to the render system in Geeqie (on my system), for large files, that I can not figure out. GIMP, and Feh (not color managed) and Rawtherapee open all files fine (faster than Geeqie, when Geeqie enters stuck state). EOG can not open some of the largest files at all, so I have not compared.

I greatly appreciate the fact that Geeqie is color managed, since I need that on my wide gamut monitor.

**Comment by caclark** [comment]
It would be good if you would try that, just to check. But I also loaded the files onto an old 3.5 inch drive, but found no difference in behavior.

**Comment by caclark** [comment]
I cannot replicate this fault on any computer I have.
If this fault can be reproduced in some other way, please re-open this issue.
