### ISSUE TITLE
Opening preferences resets dialog size

### ISSUE THREAD

**Issue by installgentoo** [BestImageViewer/geeqie#964]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
1.7.2
```

```
gtk3
```

### OS / DISTRIBUTION

gentoo
### SUMMARY

Resize move/copy/rename dialogue with gtk3. Their new sizes are properly saved. Open preferences, press ok. Dialogues are reset to default size. Incredibly annoying, happens since at least 1.6, didn't happen on gtk2.

![2022-02-01-231434_467x445_scrot](https://user-images.githubusercontent.com/2088917/151950520-96ea4286-9623-463a-a7b2-2986a058cb21.png)
### STEPS TO REPRODUCE

relevant settings attached

**Comment by installgentoo** [comment]
Oh and it also resets delete key behaviour.
I don't have system trash bin, so maybe that bugs it out.

**Comment by caclark** [comment]
> t also resets delete key behaviour.

I do not see this effect. Which of the delete options are you referring to?

**Comment by installgentoo** [comment]
For me "use no trash bin at all" gets reset to system trash bin, unless i explicitly reset it after each preferences open.

**Comment by caclark** [comment]
>  it also resets delete key behaviour.

 Fixed in commit aef9faa
