### ISSUE TITLE
flatpak: can't rotate JPEG images (exiftran not found)

### ISSUE THREAD

**Issue by maxwood-forester** [BestImageViewer/geeqie#968]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
$ flatpak run org.geeqie.Geeqie --version
Geeqie 1.7.2 GTK2
```

```
GTK2
```

### OS / DISTRIBUTION
Debian 11 (bullseye)

### SUMMARY
Image rotation (Edit > Orientation > Apply the orientation to image content) fails on JPEG files in Flatpak Geeqie on Debian 11 with exiftran installed.

Log says `/app/lib/geeqie/geeqie-rotate: line 30: exiftran: command not found`

and yet:

```
$ dpkg -l | grep exiftran
ii  exiftran                             2.10-4                           amd64        digital camera JPEG image transformer

$ which exiftran
/usr/bin/exiftran
```
### STEPS TO REPRODUCE
1. Install latest Geeqie in flatpak form via `flatpak install flathub org.geeqie.Geeqie` on Debian 11, and ensure the `exiftran` system package is installed.
2. Apply some rotation to a JPEG image using the `[` or `]` keys
3. Click Edit > Orientation > Apply the orientation to image content
4. Command will fail.

**Comment by maxwood-forester** [comment]
Built Geeqie with the Debian build script mentioned in the README and this works fine, no errors.

```
$ geeqie --version
Geeqie 1.7+git20220214-aa5efef1 GTK2
```

Perhaps `exiftran` needs to be part of the Flatpak? Or alternatively, the feature needs to work differently with the Flatpak security model?

**Comment by maxwood-forester** [comment]
For what it's worth, I rotated + applied the transformation with a test image with the version of Geeqie I built, and it appears to be working properly (losslessly) as the image size on disk barely changed and there was no visible degradation of image quality.

So the feature appears to be fully working, and presumably using `exiftran` properly (since the applied rotation is lossless), on the native built version.

**Comment by caclark** [comment]
If this is a Geeqie Flatpak problem, I think this is the place to register the problem:
https://github.com/flathub/org.geeqie.Geeqie
