### ISSUE TITLE
Faulty Control + Click Multiple Selection Behaviour. 

### ISSUE THREAD

**Issue by Martyn575** [BestImageViewer/geeqie#969]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.6
```

```
Standard geeqie version installed from debian 11.2
```

### OS / DISTRIBUTION
Debian 11.2 (x86_64)

### SUMMARY
When using control click to select multiple images, deselecting any image that wasn't the last image you selected causes all the images selected to be deselected again. This is 100% reproducible. 

Correct behaviour should be that when you deselect any image, only that image is deselected. This is the behaviour in the old geeqie application, and that was great. 

### STEPS TO REPRODUCE
0) Get 3 images in a directory. 
1) hold down Ctrl and select the 1st one - it is highlighted. 
2) hold down ctrl and select the 2nd one- it is highlighted.
3) hold down ctrl and select the 3rd one - it is highlighted. 
4) hold down ctrl and deselect the 1st or 2nd one - all of the images are deselected again, and the deselected image is still selected for some reason?!

**Comment by gusnan** [comment]
This is probably #939.

**Comment by gusnan** [comment]
@Martyn575 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008161

**Comment by gusnan** [comment]
This fix is now in Debians "proposed updates", meaning that the fix will come in the next Debian 11 point release 11.4.

**Comment by gusnan** [comment]
And now Debian 11.4 with the geeqie fix has also been released.
