### ISSUE TITLE
color management: the screen profile generates a square pattern

### ISSUE THREAD

**Issue by wsyxbcl** [BestImageViewer/geeqie#971]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION
```
Geeqie 1.7.2 GTK3
```

### SUMMARY
The color profile is not fully applied to the image, which shows a square patterned alignment.
![Screenshot from 2022-03-03 21-17-17](https://user-images.githubusercontent.com/13074950/156572230-c36d38dd-1320-4514-a6e0-166afcd9173e.png)

### STEPS TO REPRODUCE
It can be reproduced just by applying screen profile (have nothing to do with image profile), and the same icc profile works fine in both Gimp and Rawtherapee.

**Comment by caclark** [comment]
Issue #603 shows the same pattern

**Comment by wsyxbcl** [comment]
> Issue #603 shows the same pattern

Thank you, it looks like the same.

I checked the issues but missed that one, I'll close this issue since it's duplicated.

**Comment by caclark** [comment]
I am still unable to replicate this. I only use Nvidia cards, but at some time I will try with an AMD card.
In the meantime could you go to Edit/Preferences/Image and set the Alpha 1/2 colours to something distinctive, and check if the square pattern shows these colours?

**Comment by wsyxbcl** [comment]
> I only use Nvidia cards, but at some time I will try with an AMD card.

FYI., I'm also using a Nvidia card.

>  set the Alpha 1/2 colors to something distinctive, and check if the square pattern shows these colours?

No, it doesn't. The alpha channel colors does not effect the pattern colors.  

BTW., here's a more detailed description of the issue:  
Assuming there is a single-color image. The image has a single color when the color management is turned off, let's call it `color_1`. The grid pattern appears as the color management being turned on, where there are `color_1` and `color_2`. When switching to another screen profile, the colors turn into `color_1` and `color_3`. None of `color_1` and `color_2` is identical with those in Rawtherapee and GIMP (all using the first screen profile).
