### ISSUE TITLE
Fullscreen alwasys loads on the wrong screen in a dual-monitor setup

### ISSUE THREAD

**Issue by speachy** [BestImageViewer/geeqie#985]
### ISSUE TYPE
* Bug Report
### GEEQIE VERSION
```
Geeqie 1.7.3 GTK3
```
```
gtk3-3.24.31-2.fc36.x86_64
```
### OS / DISTRIBUTION
Fedora 36 beta (x86_64, fully up-to-date)
GNOME 42 desktop.
Also occurred on Fedora 35, can't confirm prior to that.
Running in Wayland mode using F/OSS AMD GPU drivers.

### SUMMARY
I have two identical 4K monitors connected via displayport; one oriented vertically, the other horizontally.

The short version is that going fullscreen always pops up onto the left monitor, no matter what the "Fullscreen Location" is set to.

The options are:

 * Window Manager
 * Active Screen
 * Active Monitor
 * Screen wayland-0 Full Size
 * Screen wayland-0 DP-1
 * Screen wayland-0 DP-2

All result in loading onto the left, vertically-oriented monitor in my setup, even when it is not the "active" monitor.

### STEPS TO REPRODUCE
 * launch geeqie on a dual-monitor setup
 * Specify the desired screen in the settings
 * hit "f" to go into full screen
 * Cry because computer says "no" and coughs on you

**Comment by vithom** [comment]
Hello,
Same problem on my side on Arch linux. Full screen window always opens onto the left monitor.

GNOME 42 desktop.
Running Wayland with radeon driver
Geeqie 1.7.3 GTK3
GTK 3.24.34

**Comment by caclark** [comment]
This is a problem involving Wayland in some way or other.
Compiling from sources on Ubuntu/Wayland does not give a problem.
The AppImage does not give a problem (and they are compiled on an X system).
I will look at this further.

**Comment by caclark** [comment]
Start geeqie by:
`GDK_BACKEND=X11 <somewhere>/geeqie`

**Comment by speachy** [comment]
I'm sorry, but this is still a bug that deserves fixing, even in the presence of a workaround -- and that's all that this is, a temporary workaround, as there's no guarantee that the X11 backend will be available forevermore.

Granted, this might not be a bug in geeqie (as opposed to, say, gdk) but some more analysis of this does seem warranted.
