### ISSUE TITLE
Edit->Orientation not visible

### ISSUE THREAD

**Issue by Massimo-B** [BestImageViewer/geeqie#987]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
1.7.3
Built on Gentoo with
USE="exif ffmpegthumbnailer gpu-accel jpeg lcms map nls pdf tiff -debug -doc -lirc -lua -xmp LUA_SINGLE_TARGET="lua5-1 -lua5-3""

### OS / DISTRIBUTION
Gentoo

### SUMMARY
Usually I did Edit->Orientation->Rotate clockwise
That already showed the rotated picture.
After that I usually did Edit->Orientation->Apply the orientation to image content
in order to apply the new orientation by exiftran.
This is the expected behavior but it has changed since 1.6. IIRC it was as expected in 1.5, but 1.6 and 1.7.3 show this behavior:
On Rotate clockwise, no rotation is visible. But after "Apply the orientation to image content" it's somehow applied and a 180° rotation is visible, which means it was 2 times rotated clockwise.

**Comment by caclark** [comment]
I do not see this effect.
There are some settings which may be applicable.

On the status bar is an icon with the tool-tip "`Toggle exif rotate`". This is the same setting as `Edit/Orientation/Exif Rotate`.

The setting: `Edit/Preferences/Metadata/Write Altered Image Orientation To The Metadata`.

 There is also some description in `Help/Frequently Asked Questions/Exif Auto Rotation`.

**Comment by Massimo-B** [comment]
> On the status bar is an icon with the tool-tip "`Toggle exif rotate`".

That solved it, thanks.
