### ISSUE TITLE
Display full-resolution embedded jpg from CR3 files

### ISSUE THREAD

**Issue by markscheel** [BestImageViewer/geeqie#990]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION

```
Geeqie 1.7+git20220401-71504c01 GTK3
```

```
libgtk-3-dev on ubuntu 22.04
compiled geeqie with https://raw.githubusercontent.com/pixlsus/Scripts/master/build-geeqie script.
```

### OS / DISTRIBUTION
ubuntu 22.04 (but problem likely independent of OS)

### SUMMARY
When displaying a CR3 file (in my case from a Canon R5), geeqie displays only the 1620x1080 jpg embedded in the CR3 file.  It should display the full-resolution (8192x5464) jpg that is also embedded in the CR3 file.   Or at least there should be a config option that allows the user of geeqie to choose which embedded jpg is displayed.

For CR2 files (from an earlier camera), geeqie displays the full-resolution jpg embedded in the CR2.   Thanks to the hard work of the developers, geeqie's speed makes it my tool of choice for sorting through CR2 files quickly, zooming in/out, deleting bad photos, and using the geeqie plugin to open the keepers in RawTherapee or darktable (I have used both) for raw conversion.  However, this workflow doesn't work well for CR3 files because the displayed resolution is often too low to evaluate photos for things like focus accuracy (except for grossly bad photos).

Note that using the tool at https://github.com/lclevy/canon_cr3 , I am able to extract three embedded jpgs from my CR3 files: a thumbnail (160x120), a preview (1620x1080), and a full-size jpg (8192x5464).  So I know that the full-size jpg is present in the CR3 file.

### STEPS TO REPRODUCE
Use geeqie to display a CR3 file (with no corresponding jpg in the same folder).  It displays only 1620x1080 resolution.

**Comment by caclark** [comment]
Can you give a link to an image that exhibits this problem?

**Comment by caclark** [comment]
It looks like you are compiling from sources.
Go to line 1041 of `src/image-load.c` and comment it out:
`		//~ if (!il->mapped_file)`

It seems that exiv2 does not find the largest embedded image but libraw does.
I will have to think a bit about this.

**Comment by markscheel** [comment]
Thank you! Commenting out that line works for me.

**Comment by norru** [comment]
I'm currently experiencing the issue and trying the workaround.
Looking at the code, at first glance it looks problematic.

1) this practically disables fast previews for *all* RAW formats (not just CR3)
2) Won't this workaround leak a file descriptor?
