### ISSUE TITLE
image_loader_setup_source: don't use PROT_WRITE mmap flag for files opened O_RDONLY

### ISSUE THREAD

**Issue by Safari77** [BestImageViewer/geeqie#991]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION

```
Geeqie 1.7.3 GTK3
```

```
GTK 3.24.34
```

### SUMMARY
Geeqie fails to read images (with my configuration) from zfs filesystem when files are `chattr +i`.
This does not happen with XFS filesystem.
I traced the bug to image_loader_setup_source, where file is opened with O_RDONLY and later `mmap`'ed
with flags `PROT_READ|PROT_WRITE`.
Removing `PROT_WRITE` allows geeqie to work with zfs + `chattr +i` combination with no other ill effects also on other filesystems.

### STEPS TO REPRODUCE
* Disable usage of EXIF thumbnails
* Copy an image to zfs filesystem and make it `chattr +i`
* Start geeqie in this directory

**Comment by qarkai** [comment]
@caclark Looks like fixed in #1492.

**Comment by Safari77** [comment]
fixed
