### ISSUE TITLE
Unable to Open some JPEG XL Containers

### ISSUE THREAD

**Issue by samueljohnson** [BestImageViewer/geeqie#994]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.7.3 GTK3
```

### What GTK toolkit is used to compile Geeqie? 
```
Binary from standard Arch repo
```

### OS / DISTRIBUTION
Arch Linux

### SUMMARY
Some of the JPEG XL Container files aren't getting opened in Geeqie. Whereas djxl, sxiv, feh, etc. are able to open the same file without any issue.

### STEPS TO REPRODUCE
Sample:
[DSC00941.jxl.gz](https://github.com/BestImageViewer/geeqie/files/8767335/DSC00941.jxl.gz)

**Comment by caclark** [comment]
I think that is because libjxl is not included in the dependency list for archlinux.
Perhaps you could contact the package maintainer.

**Comment by samueljohnson** [comment]
1. I have libjxl installed.
2. Geeqie is able to open some jxl files, but not all. Whereas all jxl files are getting opened in other viewers.

Are you able to open the attached sample in your Geeqie version?

**Comment by caclark** [comment]
> Are you able to open the attached sample in your Geeqie version?
Yes, it displays ok.

If you are using the packaged version which was compiled without libjxl support, you will  not see jxl images.
You might compile Geeqie from sources, and then you will get libjxl linked in.

This subject was also in #900 which describes a hack which could be used to view the images.

**Comment by samueljohnson** [comment]
> you will not see jxl images

As I said, Geeqie was unable to open only few JXL files. 

e.g. my instance of Geeqie can open this JXL file just fine:
[sample](https://github.com/BestImageViewer/geeqie/files/8790389/2021-04-28.GannetsSaltee_EN-US1285648780_1920x1080.jxl.gz)


 > You might compile Geeqie from sources

I just tried the AUR version (geeqie-git) and it seems to be working fine.

Thanks for your support.
