### ISSUE TITLE
freezes when trying to display a specific JPEG image

### ISSUE THREAD

**Issue by calestyo** [BestImageViewer/geeqie#997]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.7.3 GTK3
```

### OS / DISTRIBUTION
Debian unstable

### SUMMARY
When displaying the attached jpeg image, geequie freezes. Interestingly the same image works with e.g. `eog` or imagemagick’s `display`. Other jpegs work just fine.

[20220301_052218.jpg.zip](https://github.com/BestImageViewer/geeqie/files/9040484/20220301_052218.jpg.zip)

(Compressed it to make sure that github doesn’t mess around with it.)

Any ideas?

Thanks,
Chris.

**Comment by caclark** [comment]
The problem is when executing:
`return new _ExifDataProcessed(path, sidecar_path, modified_xmp);`
It never returns from this function call.

`_ExifDataProcessed` is an exiv2 function. Perhaps you could ask on their GitHub project.
