### ISSUE TITLE
OM-1 raw file support ?

### ISSUE THREAD

**Issue by GillesSanMartin** [BestImageViewer/geeqie#998]
Hello

Would it be possible to get support for OM systems OM-1 raw files please ?
Tested with the latest appimage [Geeqie-v1.7+20220614.AppImage](https://cclark.uk/Geeqie/Geeqie-v1.7+20220614.AppImage).
The exifs are read but no preview of the image.

And by the way : thank you for maintaining/developing such a great software (I've been using it with delight for more than 10 years...)

**Comment by caclark** [comment]
The latest LibRaw library supports OM-1, but at the moment I cannot get it to work. The following is a hack to display OM-1 files, but it is a pain to install and the decode time is several seconds per image - but it works.
[OM-1-instructions.txt.gz](https://github.com/BestImageViewer/geeqie/files/9402797/OM-1-instructions.txt.gz)

**Comment by caclark** [comment]
In some circumstances the image load delay can be reduced by going to `Edit/Preferences/General` and setting `Decoded Image Cache Size` to a large value and also selecting `Preload Next  Image`. Set `Cache Thumbnails` of course.

**Comment by caclark** [comment]
To use the latest LibRaw library, use the following as an example:
`cd $HOME/bin/`
`git clone https://github.com/LibRaw/LibRaw.git`
`cd LibRaw`
`autoreconf --install`
`./configure`
`make`
`sudo make install`
`cd <geeqie clone folder>`
`git pull`
`rm -r build;meson setup build`
Either:
`ninja -C build`
`./build/src/geeqie`
Or:
`ninja -C build install`
`geeqie`

If you have configured the Advanced Option External Preview, disable it and restart Geeqie.
Using this method the speed of image display is the same as for other images.

I will maybe create an AppImage in the next few days.

**Comment by GillesSanMartin** [comment]
@caclark : thanks a lot for your work on this. An appimage would be absolutely great as i'm not totally at ease with compiling LibRaw ...

**Comment by caclark** [comment]
There is an AppImage which displays OM-1 files. The download section on geeqie.org gives the link.

If an OM-1 user does not wish to compile from sources or use an AppImage, it will be necessary to wait until the latest version of LibRaw makes it into the distributions.

**Comment by GillesSanMartin** [comment]
The appimage is working perfectly !
Thank you very very much for your work on this...
The speed of geeqie is really impressive (I'm back now from Digikam)
