### ISSUE TITLE
Adding a widget to the info sidebar resizes the sidebar to something around 70% of window width.

### ISSUE THREAD

**Issue by caclark** [BestImageViewer/geeqie#999]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
Geeqie 1.7+git20220630-756f29e8 GTK3

```

```

```

### SUMMARY

As in the title
### STEPS TO REPRODUCE

As in the title

**Comment by gdt** [comment]
Not sure if same bug, but while struggling with #996 before disabling GPU, the info pane became almost zero and I thought it was gone, but no, just the separator was full right.
